### ISSUE TITLE
Searching multiple indices/types (equivalent to "Tire.search")

### ISSUE THREAD

**Issue by viperdezigns** [elastic/elasticsearch-rails#10]
Unfortunately, I've spent possibly too much time looking through this new gem looking for  a top level search method. Is there a way to search without using a specific model? (Like Tire.search used to do)

For the most part, I'm using the base client methods to do my searching, however, I think I'd like to handle most of the response parts through this gem. (Such as Kaminari)

Possibly, is there a way to search via Elasticsearch::Model.client.search(search_hash) and use this gem's result formatting?

I'm partially new to this lower level of ES (coming from Tire) so hopefully you know what I'm looking for. Any help is much appreciated!!

Other than having somewhat of a learning curve, LOVING these new gems for ES

**Comment by daino3** [comment]
Hello,

Just a quick thought (and I might be missing something here). If you need this functionality, rather than monkey patching Elasticsearch::Model, since Karmi's implementation above inevitably hits elasticsearch-api#actions/search. Why not simply initialize a client w/ 
```
c = Elasticsearch::Client.new
c.search q: 'frisky kittens', body: {highlight: {fields: {...} } }
```
If no indexes are passed, it searches all indexes. Then you can create your own helper methods to convert them into AR objects, etc. Would eliminate the need the ES-model altogether and maintaining monkey-patched code?

**Comment by rossdakin** [comment]
:+1: @daino3 

I just implemented multi-model search this way (shared index, different types).

I referenced the client through `Elasticsearch::Model` just for grins (assuming default values for logging, etc. are easier to keep consistent that way):

```Ruby
index = 'my-index'
body = {
  query: { ... },
  highlight: { ... },
  suggest: { ... }
}

@response = Elasticsearch::Model.client.search(index: index, body: body)
```

**Comment by micahlmartin** [comment]
@rossdakin That works perfectly for me too. I don't need the direct models integration. I think this should be documented in a more prominent place.

**Comment by karmi** [comment]
Hi all, thanks for the discussion and the examples! I'll be travelling in the coming days, but I'll keep the issue in mind and will return to it as soon as possible (mainly finishing the work in the `dsl` branch of elasticsearch-ruby)

**Comment by webattitude** [comment]
Hi, what about single model, but multiple time-based indices ?

**Comment by webattitude** [comment]
is wildcard index_name allowed ?

**Comment by solaleye** [comment]
Late to this convo, but really informative!!! Thanks everyone. 👍
