### ISSUE TITLE
Import with parameters in ruby 3

### ISSUE THREAD

**Issue by jonnynux** [elastic/elasticsearch-rails#1014]
When trying to import with parameters i get _ArgumentError: wrong number of arguments (given 1, expected 0)_

```ruby
data.import(**import_options) do |response|
    ...
end
```

import_options is a hash obviously. Same error when calling import like `data.import(batch_size:500) do |response|`

**Comment by crondaemon** [comment]
Same happens on ruby2.7, except it is a warning there not an error. Still annoying, though.

**Comment by crondaemon** [comment]
I guess this would fixed by #1016. However the CI doesn't pass, nor the author signed the requested agreement. Any chance those issues get addressed?

**Comment by tiendo1011** [comment]
seems to be fixed by [this](https://github.com/elastic/elasticsearch-rails/pull/992), but it is not included in the latest release (since it's merged after that).

**Comment by jonnynux** [comment]
@tiendo1011 thanks, I didn't note that, so this can be closed
