### ISSUE TITLE
8.x support

### ISSUE THREAD

**Issue by leifcr** [elastic/elasticsearch-rails#1035]
Any plans for 8.x support? I see there is PR #1025, which should solve it?

**Comment by AlexanderPankiv** [comment]
Any update on this one?

**Comment by tsrivishnu** [comment]
Also waiting for an update on this.

**Comment by picandocodigo** [comment]
We'll eventually update the gem and publish a new release for `8.x`, but we can't commit to a date at the moment.

**Comment by emptyflask** [comment]
So then is there currently any way to use `elasticsearch-rails` on an app that also has `faraday '~> 2.0'`? It looks like only `elasticsearch-transport '>= 8.1'` supports a modern Faraday version, but it's incompatible with the latest `elasticsearch-rails`. 

Frustrating, since ES 8.0 has been out for > 8 months, and this is commercial software...

**Comment by technige** [comment]
Hi @emptyflask. I'm sorry that we're not able to provide a timescale for an 8.x release at this time, and I do appreciate how frustrating this must be for you. Unlike the clients, which are our primary focus, we're only able to keep this project updated on a best-effort basis right now.

If you wish to discuss this in more detail for your specific case, please contact your support channel.

**Comment by jaredbeck** [comment]
This is the last blocker in my app preventing our upgrade to Faraday 2.

`elasticsearch-persistence -> elasticsearch 7 -> elasticsearch-transport 7 -> faraday 1`

Looking forward to a release, thanks for your work.

**Comment by xjunior** [comment]
It looks like the latest elasticsearch-model 7.x library (7.12.1 right now), along with the rest of the 7 suite (elasticsearch-rails, elasticsearch-ruby) work well with elasticsearch 8 (on my limited test scope). Are there concerns for this setup?

**Comment by dani-sc** [comment]
Hi @technige ,

even if there is no date when we can expect 8.x support - is it planned after all, or is it advised to stop relying on this gem altogether? It is currently blocking our update to 8.*, as we rely heavily on it.

**Comment by siba2893** [comment]
Hey I'm also having issues with faraday as the WhatsApp ruby ask ten uses faraday 2.3 and this one is stuck with faraday 1.7. How can we resolve this issue?

**Comment by emptyflask** [comment]
It's not ideal if you already have things built around this gem, but [searchkick](https://github.com/ankane/searchkick) doesn't have this issue, and provides some nice features out of the box like reindexing without downtime. I've migrated some of our projects from elasticsearch-rails to searchkick and it's worked well so far.

**Comment by gael-ian** [comment]
Is there a list of what have to be done before any elasticsearch 8.x compatible release? If we know what's expected, maybe some of us can help.

**Comment by bbenno** [comment]
Probably off-topic, but also due to this issue being still open, I decided to turn my back on ES and migrated to [Meilisearch][2], whose [Rails gem][1] also offers a nicer interface, IMHO.

[1]: https://github.com/meilisearch/meilisearch-rails
[2]: https://meilisearch.com/

**Comment by jeffkirk1** [comment]
FYI, the elasticsearch-ruby gem IS compatible with 8.6, but the elasticsearch-rails gem is not.

https://github.com/elastic/elasticsearch-ruby

That said, I agree, a ten-month delay in getting elasticsearch-rails up to snuff is not acceptable. Either Elastic should light this candle or decide to stop supporting Rails. Which would be a terrible mistake.

**Comment by xjunior** [comment]
@jeffkirk1 yep, you're right. Also, this gem DOES work with an ES 8.6 backend, but it's awkward to do so. Also, by using `elasticsearch-rails` v7, we cannot update `elasticsearch-ruby` to 8.

Please, Elastic, let's get this done. All the people above are also willing to help if we're told what it takes.

**Comment by 23tux** [comment]
We have the same issue here, the missing v8 support is blocking us from upgrading.

**Comment by dbourget** [comment]
One more vote for an upgrade to support faraday 2.x.

**Comment by arjan0307** [comment]
Will this at least be done before ES 7 is EOL?

**Comment by zaru** [comment]
A branch supporting v8 has been created.
https://github.com/elastic/elasticsearch-rails/commits/8.x

**Comment by arjan0307** [comment]
> A branch supporting v8 has been created. https://github.com/elastic/elasticsearch-rails/commits/8.x

Is this branch already usable, or is it still in alpha / beta?

**Comment by picandocodigo** [comment]
The [8.x branch](https://github.com/elastic/elasticsearch-rails/commits/8.x) is work in progress. There are still [some failing tests](https://github.com/elastic/elasticsearch-rails/actions/runs/6184445323/job/16788120811) in `elasticsearch-model` that need to be fixed and some further testing and updates before I can publish an official release. But feel free to test it and report any issues. Just be aware that this is code in development and not an official release yet.

**Comment by jaredbeck** [comment]
My team can't wait any longer for this issue, and will no longer be able to use this gem. Fortunately, our app only uses `Elasticsearch::Persistence::Repository`, and we were able to write a limited replacement (`search`, `save`, and `delete` only) using only the lower-level `elasticsearch` gem. If it would be help someone else, I'd be happy to share a redacted gist of some of that work.

**Comment by neoxader** [comment]
Seems last commits on [8.x update](https://github.com/elastic/elasticsearch-rails/commits/8.x) are from September 2023. 

When can we expect release

**Comment by jashkothari** [comment]
Any updates on when [8.x update](https://github.com/elastic/elasticsearch-rails/commits/8.x) will be released?

**Comment by pbourdet** [comment]
Hello, any news of this ? When can we expect the release ?

**Comment by picandocodigo** [comment]
I appreciate this is frustrating, but I can't provide a timeframe just now. This is still a project on a best-effort basis. It would really help if folks interested tested the `8.x` branch and reported any issues or opened Pull Requests for fixes to that branch to get it closer to a release.

**Comment by picandocodigo** [comment]
Elasticsearch Rails 8.0.0.pre [is now available](https://github.com/elastic/elasticsearch-rails/releases/tag/v8.0.0.pre). Please let us know of any issues. Thanks to everyone who's contributed to `8.x`.
