### ISSUE TITLE
Not able to update single record too please help me to here

### ISSUE THREAD

**Issue by venky-ror** [elastic/elasticsearch-rails#1052]
Elasticsearch::Transport::Transport::Errors::ServiceUnavailable ([503] {"error":"UnavailableShardsException[[businesses][4] Primary shard is not active or isn't assigned to a known node. Timeout: [1m], request: index {[businesses][doc][573602], source[{\"id\":573602,\"name\":\"Balaji organics\",\"verified\":false,\"active\":false,\"business_category_id\":2,\"created_at\":\"2023-02-16T16:31:56.591+05:30\",\"updated_at\":\"2023-02-17T14:51:27.891+05:30\",\"star_invested\":\"\",\"business_type\":\"onlinegrocery\",\"socket_id\":\"72fc4f91-c046-4d9f-9922-2e93de022a89\",\"outlet_id\":null,\"alias_name\":\"Balaji organics\",\"enterprise_id\":null,\"promoter_id\":null,\"account_details\":{\"account_type\":\"Savings\",\"account_name\":\" FINMARK EXPORTERS\",\"account_number\":\"\",\"ifsc_code\":\"\"},\"reviewer_id\":null,\"onboarded_at\":\"2023-02-16T16:31:56.584+05:30\",\"star_rating\":5.0,\"preferences\":{},\"is_custom_delivery\":false,\"verified_at\":null,\"vpa\":\"\",\"qr_file_url\":\"\",\"amazon_store_id\":\"23\",\"amazon_token\":\"\",\"amazon_pay_url\":\"\",\"is_tt_listed\":false,\"paynext_tid\":\"\",\"paynext_mid\":null,\"paynext_app_id\":null,\"amazon_smart_store_id\":\"\",\"is_dmo_registered\":true,\"dmo_vpa\":\"@icici\",\"partner_type\":\"oyeti\",\"paynext_serial_numbers\":[],\"amazon_store_url\":\"\",\"partner_category_code\":null,\"digio_kyc_response\":{},\"digio_bank_response\":{},\"lsq_vpa\":\"\",\"is_lsq_added\":false,\"tt_business_hub_id\":null,\"is_sodexo\":false,\"sodexo_aid\":null,\"sodexo_mid\":null,\"sodexo_tid\":null}]}]","status":503})

**Comment by picandocodigo** [comment]
This doesn't seem to be an `elasticsearch-rails` issue, rather an Elasticsearch issue. Check out [this discussion](https://discuss.elastic.co/t/primary-shard-is-not-active-or-isnt-assigned-to-a-known-node/105145) on the forums, or open a new topic over there to ask for help.
