### ISSUE TITLE
rake elasticsearch:import:model  - ArgumentError: unknown keyword: :type (ArgumentError)

### ISSUE THREAD

**Issue by beatjoerg** [elastic/elasticsearch-rails#1082]
With the commit "Removing type related code b71d5a9dfb1a5212cbad8b6f9321a1e0a6726579" the type related code was removed, but it is still an option in the rake task, which will fail because the now unknown option "type" is passed down to find_in_batches (instead to be removed in the index function). I will post a pull request to fix that issue.

**Comment by azbcww** [comment]
Thank you for the commit and merge. We truly appreciate your ongoing contributions.

@picandocodigo 
We have always benefited from this library, but unfortunately, we have encountered this import task issue in our environment as well. I believe this commit will help many people, so we sincerely hope that a release including this change can be made as soon as possible.
Thank you in advance for your consideration.
