### ISSUE TITLE
elasticsearch-ruby repository missing

### ISSUE THREAD

**Issue by ascoppa** [elastic/elasticsearch-rails#1087]
I know this isn’t the right repo to bring this up, but I just noticed that the Elasticsearch Ruby client repo at https://github.com/elastic/elasticsearch-ruby is missing.

Is it possible it was made private by accident, or has it been intentionally deprecated? I’d really appreciate any info on what’s going on and if there are any alternatives for us to use.

**Comment by technige** [comment]
Hi @ascoppa. We have a known issue with some of our GitHub repositories, and are working to resolve it. Please watch https://status.elastic.co/ for updates.

**Comment by ascoppa** [comment]
Closing as there's another channel to track this.

**Comment by ezimuel** [comment]
The repository https://github.com/elastic/elasticsearch-ruby is public again.
