### ISSUE TITLE
unable to create geo-point 

### ISSUE THREAD

**Issue by suras** [elastic/elasticsearch-rails#127]
i am getting not a geopoint error. also tried with string instead of array, deleting index and recreating 

{
    "error_code": "103",
    "error_message": "[400] {\"error\":\"SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[nja_gc2ERMud-T3_GoRCNw][barter_li_application_development][3]: SearchParseException[[barter_li_application_development][3]: query[title:bb_],from[-1],size[-1]: Parse Failure [Failed to parse source [{\\"query\\":{\\"prefix\\":{\\"title\\":\\"bb\\"}},\\"filter\\":{\\"geo_distance\\":{\\"distance\\":\\"50km\\",\\"lon_lat\\":{\\"lon\\":77.5667,\\"lat\\":12.9667}}}}]]]; nested: QueryParsingException[[barter_li_application_development] field [lon_lat] is not a geo_point field]; }{[nja_gc2ERMud-T3_GoRCNw][barter_li_application_development][4]: SearchParseException[[barter_li_application_development][4]: query[title:bb_],from[-1],size[-1]: Parse Failure [Failed to parse source [{\\"query\\":{\\"prefix\\":{\\"title\\":\\"bb\\"}},\\"filter\\":{\\"geo_distance\\":{\\"distance\\":\\"50km\\",\\"lon_lat\\":{\\"lon\\":77.5667,\\"lat\\":12.9667}}}}]]]; nested: QueryParsingException[[barter_li_application_development] field [lon_lat] is not a geo_point field]; }{[nja_gc2ERMud-T3_GoRCNw][barter_li_application_development][1]: SearchParseException[[barter_li_application_development][1]: query[title:bb_],from[-1],size[-1]: Parse Failure [Failed to parse source [{\\"query\\":{\\"prefix\\":{\\"title\\":\\"bb\\"}},\\"filter\\":{\\"geo_distance\\":{\\"distance\\":\\"50km\\",\\"lon_lat\\":{\\"lon\\":77.5667,\\"lat\\":12.9667}}}}]]]; nested: QueryParsingException[[barter_li_application_development] field [lon_lat] is not a geo_point field]; }{[nja_gc2ERMud-T3_GoRCNw][barter_li_application_development][2]: SearchParseException[[barter_li_application_development][2]: query[title:bb_],from[-1],size[-1]: Parse Failure [Failed to parse source [{\\"query\\":{\\"prefix\\":{\\"title\\":\\"bb\\"}},\\"filter\\":{\\"geo_distance\\":{\\"distance\\":\\"50km\\",\\"lon_lat\\":{\\"lon\\":77.5667,\\"lat\\":12.9667}}}}]]]; nested: QueryParsingException[[barter_li_application_development] field [lon_lat] is not a geo_point field]; }{[nja_gc2ERMud-T3_GoRCNw][barter_li_application_development][0]: SearchParseException[[barter_li_application_development][0]: query[title:bb*],from[-1],size[-1]: Parse Failure [Failed to parse source [{\\"query\\":{\\"prefix\\":{\\"title\\":\\"bb\\"}},\\"filter\\":{\\"geo_distance\\":{\\"distance\\":\\"50km\\",\\"lon_lat\\":{\\"lon\\":77.5667,\\"lat\\":12.9667}}}}]]]; nested: QueryParsingException[[barter_li_application_development] field [lon_lat] is not a geo_point field]; }]\",\"status\":400}"
}

module Searchable
      extend ActiveSupport::Concern

```
  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks


    # Customize the index name
    #
    index_name [Rails.application.engine_name, Rails.env].join('_')

    # Set up index configuration and mapping
    #
    settings index: { number_of_shards: 1, number_of_replicas: 0 } do
      mapping do
          indexes :title,     analyzer: 'not_analyzed'
           indexes :lon_lat, type: 'geo_point'
      end
    end

    def as_indexed_json(options={})
      {
        title: self.title,
        lon_lat: lon_lat
      }
    end

  def lon_lat
       [self.location.longitude.to_f, self.location.latitude.to_f]
   end


  def self.search(query)
    __elasticsearch__.search(
      {
        query: { prefix:  { title: query[:title] } },
        filter: {
            geo_distance: {
                distance: query[:radius],
                lon_lat: {
                  lon: query[:longitude],
                  lat: query[:latitude]

                }
            }
          }
      }
    )
  end
 end
end
```

**Comment by vbrazo** [comment]
I also get an issue while implementing this:

```
    include Elasticsearch::Persistence::Repository
    include Elasticsearch::Persistence::Repository::DSL

    index_name "merchant_#{Rails.env}"

    settings index: { number_of_shards: 1 } do
      mappings do
        indexes :coordinates, type: 'geo_point'
      end
    end
```

The error message is:

```
Elasticsearch::Transport::Transport::Errors::BadRequest:
[400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [coordinates : {type=geo_point}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [properties]: Root mapping definition has unsupported parameters:  [coordinates : {type=geo_point}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [coordinates : {type=geo_point}]"}},"status":400}
```

```
2.5.1 :001 > PersistenceLayer::MerchantDetailsRepository.settings
 => #<Elasticsearch::Model::Indexing::Settings:0x00007fae3f6d2be0 @settings={:index=>{:number_of_shards=>1}}> 
```

I'm using elasticsearch 7.0.0. @karmi thoughts?
