### ISSUE TITLE
Model.import causes stack level too deep error

### ISSUE THREAD

**Issue by tomciopp** [elastic/elasticsearch-rails#144]
Currently when I try to use the import class method provided by elasticsearch-model, I run into `SystemStackError: stack level too deep`. It looks like it runs into an error in irb and pry when they try to run `eval` on the code. This causes errors to occur in the rake tasks as well. I am running version 3.2.16 of ActiveRecord.

**Comment by StepanKuzmin** [comment]
I've the same issue as @arfl described

**Comment by salmanzameer** [comment]
@karmi @arfl @StepanKuzmin any updates on this problem with STI ? 

Did any of you get any chance to resolve it. Also if you can share some gist for STI search would be great. I am have very hard time with it.

Previously, I was working with tire and it was working like a charm.

**Comment by karmi** [comment]
I'll try to look into that later in the month, focused on something else right now, sorry!

**Comment by jimboslic3d** [comment]
I'm also hitting the same issue that @arfl called out. Look forward to seeing what you come up with @karmi . Thanks for the help!

**Comment by jlaw90** [comment]
Hi guys,

I had this same issue in an abstract base class, by instead doing instance_eval on the subclass fixed it.

I added the following method:

```ruby
  def self.inherited(child)
    super
    
    child.instance_eval do
      # Elastic search functionality!
      include Elasticsearch::Model

      # Automatically update the index on change
      include Elasticsearch::Model::Callbacks
    end
  end
```

**Comment by StepanKuzmin** [comment]
Thanks @jlaw90, your code solved this issue for me.

**Comment by karmi** [comment]
Thanks for the code eample, @jlaw90! Do you have an idea how we could address this in the gem, either in code or the documentation?

There are too many mishaps happening with STI, see eg. #333, I need to solve it soon.

**Comment by jlaw90** [comment]
@karmi I haven't looked at the source for this gem, but I guess the issue must be that when the module is included it's using the class name to then cache the index, type and other parameters.
The fix would be to change any of these cached variables to be dynamically calculated when they're used.

This is all conjecture though, I don't know if there's anything else funky going on

**Comment by karmi** [comment]
@jlaw90 Thanks!, I'll have a look at that when I'm back onlilne properly.

**Comment by karmi** [comment]
The underlying problem is with the proxied methods. The "practical" solution seems to be include the `Elasticsearch::Model` module in the child class as well, as outlined in https://github.com/elastic/elasticsearch-rails/issues/333#issuecomment-103940296
