### ISSUE TITLE
Support "wrapper" option

### ISSUE THREAD

**Issue by benjaminbarbe** [elastic/elasticsearch-rails#161]
Wrapping with Hashie::Mash can be slow (~ 4s)
![with-hashie](https://cloud.githubusercontent.com/assets/630365/3496217/e38a0c24-05df-11e4-96f8-6ffb5d098b5e.png)

Versus [extend method](https://gist.github.com/benjaminbarbe/99be9a4391de1a1284b0) (but it won't allow deeper hierarchies ~ 0.26s)
![without-hashie](https://cloud.githubusercontent.com/assets/630365/3496218/e38af788-05df-11e4-928b-f1015fee9bb0.png)

One option would be to support "wrapper" option, which could be Hash, Hashie::Mash, custom object...
`Elasticsearch::Model.wrapper = Hash`

**Comment by fbernier** [comment]
This would indeed be a useful feature. Would you still accept a PR for this?

**Comment by Animeye** [comment]
Has there been any further information on this?

**Comment by karmi** [comment]
@Animeye No new information, this felt off the radar... If anybody would like to pick it up (@fbernier), I'm up for assistance and review!

**Comment by martinemde** [comment]
@karmi I submitted a partial fix for this in #755. Hopefully it can address some of the concerns in this thread.

**Comment by bkazez** [comment]
I'm still seeing large performance issues due to `Hashie::Mash` - see below. What is the recommended workaround?

<img width="800" alt="screen shot 2017-12-20 at 01 06 49" src="https://user-images.githubusercontent.com/64005/34199285-262c9cca-e522-11e7-98d5-1669712f02e9.png">

**Comment by martinemde** [comment]
@bkazez I monkeypatched the gem for now to remove the wrapping in a Hashie::Mash. It has made a big difference for me. I also submitted #755 to attempt to deal with it without breaking anything.

btw, here's the monkeypatch we are using in our production app:

```ruby
MonkeyPatch.for('elasticsearch-persistence', '<your gem version here>') do
  module Elasticsearch
    module Persistence
      module Repository
        module Response # :nodoc:
          class Results
            # This patch removes the usage of Hashie::Mash which is very very slow
            # and provides us no value. As of 2017-11-15, the newest version of
            # elasticsearch-persistence gem still has a compatible initialize
            # method that won't be broken by this patch.
            #
            # https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/lib/elasticsearch/persistence/repository/response/results.rb
            #
            def initialize(repository, response, options={})
              @repository = repository
              # This is the only change:
              #@response   = Hashie::Mash.new(response) # Comment this line
              @response   = response # Add this line.
              @options    = options
            end
          end
        end
      end
    end
  end
end
```

**Comment by bkazez** [comment]
Thanks so much, this shaved 25% off my search! It's still creating some Hashie::Mashes somehow but this much better. Going to try dropping down to the lower-level ES APIs to see how much that saves.

**Comment by estolfo** [comment]
Hi @bkazez @benjaminbarbe @martinemde I opened [a pull request](https://github.com/elastic/elasticsearch-rails/pull/825) that provides a `#raw_response` accessor on the response objects and that only wraps the response when it's accessed. Does that help with this issue?

**Comment by estolfo** [comment]
Closing this as I've merged in the pull request https://github.com/elastic/elasticsearch-rails/pull/825. Please comment on this issue if it's not resolved and I'll reopen it and investigate further.

**Comment by bkazez** [comment]
@estolfo Great solution - thanks so much and sorry for the late reply!
