### ISSUE TITLE
Model's settings and mappings are ignored when the index is created through Model.import

### ISSUE THREAD

**Issue by dimroc** [elastic/elasticsearch-rails#173]
Hi all,
I'm trying to use mappings defined in an AR model backed by postgres (rails 4.0.4) to create an index and its corresponding mappings. My model has the following:

```ruby
    mappings dynamic: false do
      indexes :text
      indexes :neighborhood, index: 'not_analyzed'
    end
```

Unfortunately, when I run `curl -XGET 'http://localhost:9200/my_index/_mapping?pretty=true'`

```json
{
  "my_index" : {
    "mappings" : {
      "my_type" : {
        "properties" : {
          "index" : {
            "properties" : {
              "_id" : {
                "type" : "long"
              },
              "_score" : {
                "type" : "long"
              },
              "neighborhood" : {
                "type" : "string"
              },
              "text" : {
                "type" : "string"
              }
            }
          }
        }
      }
    }
  }
}
```

Notice the lack of `"index": "not_analyzed"`. Using the curl commands against ES directly, I was able to create the index needed.

This is all invoked using `ModelName.import`.

**Comment by denispeplin** [comment]
This can be VERY confusing. Spent few hours trying to figure out what's going on on production after removing and re-creating wrongly mapped index. Filters stopped working.
Warning will not help when `import` will start to put tons of logs into console.

**Comment by karmi** [comment]
@denispeplin I understand the frustration, and feel for you -- but read the discussion, there are no easy ways out of this situation..

When re-reading the discussion with @dimroc, I think it's maybe reasonable for `Model.import` to raise an exception when the index doesn't exist -- sorry, Dimitri, for not seeing that clearly the first time. That's something we actually should do -- I'll reopen the issue.

**Comment by karmi** [comment]
@denispeplin @dimroc I'm more confused than should be possible :) The raising of an exception when an index exists was added in 55af45b3 by Ben Woosley. It just hasn't been released to Rubygems, I'll fix that...

**Comment by karmi** [comment]
Released as part of https://rubygems.org/gems/elasticsearch-model/versions/0.1.8

**Comment by denispeplin** [comment]
Thank you!

I checked all ways of creating index I know:

```ruby
Model.__elasticsearch__.create_index!
Model.__elasticsearch__.create_index! force: true
Model.import force: true
```

Every time the index has been created with properly set mappings. The exeption was raised for `Model.import` without `force: true` as expected.

So #214 probably may be closed too.

**Comment by dimroc** [comment]
Great news! :beers:

**Comment by whokilledtheelectricmonk** [comment]
To be clear, if a custom mapping is not specified, elasticsearch-rails will still generate a mapping with `Model.import force:true`, correct? I found out that Bonsai (Heroku add-on for ES) requires an index to exist before you can import data into it, so the force option was needed in order to autogenerate the mapping and populate it.

**Comment by karmi** [comment]
@whokilledtheelectricmonk Yes, it will. But it makes sense to create the index in a separate code, and in advance, for mor complex applications.

@denispeplin @dimroc Thanks for understanding and the verification! Closing the issue for now..
