### ISSUE TITLE
Update does not work for custom properties.

### ISSUE THREAD

**Issue by dwkoogt** [elastic/elasticsearch-rails#178]
Hi.

I have models that have custom index properties defined in the mapping. The values for these properties are computed when as_indexed_json is called. However, update_index call in Elasticsearch::Model::Indexing checks for changed attributes and only selects those values from as_indexed_json missing all the custom index properties.

see the :custom_prop in below class.

class M
  field :id
  field :name, type: String

  mappings do
    indexes :id,        index: :not_analyzed
    indexes :name,  analyzer: 'standard'
    indexes :custom_prop
  end

  def as_indexed_json(options={})
    _hash = as_json(only: [name])
    _hash['custom_prop'] = "some computed value"
  end
end

**Comment by Meekohi** [comment]
I'm having this issue as well -- in my case just have a small derived field to put geo-coordinates in the right format

```
class Hotel < ActiveRecord::Base
  [...]
  def geo
    [longitude,latitude]
  end
end
```
, but even when lat/lon are updated correctly `geo` is not being updated. Seems like this is what #182 is trying to address. In the meantime, trying to understand how to force this at the right times. Any suggestions?
