### ISSUE TITLE
Handling errors application-wide

### ISSUE THREAD

**Issue by jbwl** [elastic/elasticsearch-rails#181]
Hi,

I am looking for a way / best practice to handle ES errors in my Rails app, such as:

```
Elasticsearch::Transport::Transport::Errors::NotFound
```

I sometimes experience unrelated issues with my ES node, i.e. indexes are missing because of other processes, or the whole ES server has gone away. In production, I would like to be able to handle such errors gracefully, and have my application inform the user about the problem.

In case of a missing index, doing a search like 

```
Elasticsearch::Model.client.search index: "MyExampleIndex",
                                             body: {
                                                 size: 10,
                                                 query: query,
                                                 aggs: aggs
                                             }
```

results in an error

```
Elasticsearch::Transport::Transport::Errors::NotFound
```

Would it be advisable to simply use a begin..rescue block or is there a better way to get error information, etc.?

Thanks.

**Comment by apraditya** [comment]
How about rescuing inside the `spec_helper` or `test_helper`? I have the following on my RSpec setup:

```ruby
  config.after :each do
    ActiveRecord::Base.descendants.each do |model|
      next unless model.respond_to?(:__elasticsearch__)
      begin
        model.__elasticsearch__.delete_index!
      rescue Elasticsearch::Transport::Transport::Error => e
        STDERR.puts "There was an error removing the elasticsearch index for #{model.name}: #{e.inspect}"
      end
    end
  end
```

Based on the Exception Handling section, `Elasticsearch::Transport::Transport::Error` is the highest exception level. However, I still get `Elasticsearch::Transport::Transport::Errors::NotFound` when running specs. It's not even get rescued if I use `StandardError`. Any idea? Thanks!
