### ISSUE TITLE
filling an attr_accessor attribute does not work with retrieved records

### ISSUE THREAD

**Issue by jvenezia** [elastic/elasticsearch-rails#187]
I have a an attribute in my model witch is not meant to be in the database, so i declare it with attr_accessor.

When I try to fill it after querying with elasticsearch-rails and retrieving records, it seems to have no effect.

```
class Article < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  attr_accessor :my_attribute
end
```

```
articles = Article.search('query').records
articles.each { |article| article.my_attribute = 'something' }
articles.first.my_attribute #=> nil
```

**Comment by toddcesere** [comment]
For the sake of anyone else coming here with this issue and experiencing the side effect of wondering how to best explain any issue: It's hard for me to imagine a clearer example than what @jvenezia posted in the first comment, or a more confusing way to express the problem than the fully working, standalone example from https://github.com/elastic/elasticsearch-rails/issues/187#issuecomment-54963699.

**Comment by jvenezia** [comment]
As you like, never used this gem because of this issue 🙂

**Comment by estolfo** [comment]
thanks @jvenezia
