### ISSUE TITLE
update_document doesn't work on derived fields

### ISSUE THREAD

**Issue by irsalmashhor** [elastic/elasticsearch-rails#195]
Hi,

This is similar to issue #140

If I have the following model defined 

```
 class Article < ActiveRecord::Base
  include Elasticsearch::Model

  def as_indexed_json(options = {})
    { description: self.description }
    { short_description: self.description[0...100] }
  end
end
```

Calling update_document will not update the short_description field because in the update_document method here:

```
self.as_indexed_json.select { |k,v| changed_attributes.keys.map(&:to_s).include? k.to_s }
```

 It will only select attributes that are defined in the model

**Comment by Meekohi** [comment]
For anyone else searching -- As @wielinde points out, I don't think this issue is actually resolved by #166.

#182 looks like the new place to track the issue.
