### ISSUE TITLE
Delete By Query implementation

### ISSUE THREAD

**Issue by ghost** [elastic/elasticsearch-rails#204]
I was looking for something more like a Delete By Query API
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/docs-delete-by-query.html

I thought that something like this

```
Sales.search query: { filtered: { filter: { bool: { must: [{ term: { month: 2014 } }, { term: { year: 5 } } ] } } } }
```

I could delete just like this:

```
Sales.delete query: { filtered: { filter: { bool: { must: [{ term: { month: 2014 } }, { term: { year: 5 } } ] } } } }
```

Is this possible any other way or are you planning on implement this?

**Comment by Startouf** [comment]
Because I was looking for a more detailed example, the following helps me clear my indexes of models implementing `Elacticsearch::Model` in RSpec when I don't want to delete/create the index and mappings each time

```
models_implementing_es_model.each do |collec|
  collec.__elasticsearch__.client.delete_by_query(
    index: collec.__elasticsearch__.index_name,
    body: { query: { match_all: {}} }
  )
end
```

**Comment by karmi** [comment]
Thanks for the snippet, @Startouf!
