### ISSUE TITLE
Pagination + records + additional scopes broken

### ISSUE THREAD

**Issue by bdmac** [elastic/elasticsearch-rails#208]
The pagination support breaks down if you chain additional scopes on after calling `records` (e.g. to eager load relations and avoid N+1 queries).  You end up getting `NoMethodError: undefined method`total_count' for [MODEL NAME]`.  Calling`.page(params[:page]).per(x)` adds back in the appropriate pagination methods but because we end up doing an explicit fetch of just the IDs in the Elasticsearch result page we get a total_count that is equal to the original per_page instead of the actual total_count in Elasticsearch's result set.

```
Model.search('foo').page(1).per(10).records.total_count => a big number
Model.search('foo').page(1).per(10).records.includes(:relationship).total_count => Undefined method error
Model.search('foo').page(1).per(10).records.page(1).per(10).total_count => 10
```

**Comment by lorenso** [comment]
Actual problem, my solution:
```
@results_ = Model.search('query').page(params[:page]).records
@results  = @results_.includes(:profile)
```

```
= will_paginate @results_
```

**Comment by deependersingla** [comment]
I end up doing this, 
users_ = User.search_with_elasticsearch(query: query).page(params[:page]).records
users  = users_.includes(:credentials).includes(:linked_accounts)
render status: 200,
          json: users, each_serializer: Api::V1::UdacityDirectoryUserProfileSerializer, meta: meta_data(users_)

## see in serializer gave "users" and in meta_data "users_" the result of search

def meta_data(object)
  {
    current_page: object.current_page,
    next_page: object.next_page,
    prev_page: object.prev_page,
    total_pages: object.total_pages,
    total_count: object.total_count
   }

**Comment by carterdea** [comment]
I'm trying to do this, but with a more complex join

        def search
        if params[:q].present?
          @families_ = Family.approved.visible.page(params[:page]).per(30).search(params[:q]).records
          @families = @families_.include_total_raised
          render :index
        else
          redirect_to families_path
        end
      end

Here is the scope: 
    scope :include_total_raised, -> { joins('LEFT OUTER JOIN donations ON families.id = donations.recipient_id').select('families.*, COALESCE(SUM(donations.amount), 0) AS total_raised').group('families.id') }

The `approved` & `visible` scopes work fine, but the `includes_total_raised` scope doesn't work. It just gives me an obscure error:

    PG::SyntaxError: ERROR:  syntax error at or near "AS"
    LINE 1: ...NT(families.*, COALESCE(SUM(donations.amount), 0) AS total_r...
                                                             ^
     : SELECT COUNT(families.*, COALESCE(SUM(donations.amount), 0) AS total_raised) AS count_families_all_coalesce_sum_donations_amount_0_as_total_rai, families.id AS families_id FROM "families" LEFT OUTER JOIN donations ON families.id = donations.recipient_id WHERE "families"."id" = 56 GROUP BY families.id

**Comment by serodriguez68** [comment]
@bdmac I'm also not able to eager load and paginate using something like

 ```ruby
@products_ = Product.search('foo').page(params[:page]).records.includes(:category, :brand)
```
Did you find a solution for this?
