### ISSUE TITLE
each_with_hit doesn't support includes to eager load associations

### ISSUE THREAD

**Issue by sr3d** [elastic/elasticsearch-rails#221]
collection.records.includes(:some_association).each_with_hit will error out: undefined method `each_with_hit' for #School::ActiveRecord_Relation:0x007fb13c51fe88

I looked around the source code and couldn't see it at all 
(https://sourcegraph.com/github.com/elasticsearch/elasticsearch-rails@b500bf03d18f0852b9ee6ebc1aa15fe684f9a9f2/.tree/elasticsearch-model/lib/elasticsearch/model/response/records.rb).  With Tire gem it's possible but somehow in the ES-Rails it's not.

**Comment by alepore** [comment]
ref: #472

**Comment by nerfologist** [comment]
Hello, I might be missing something here but the following continues to fail due to `includes` returning a plain `ActiveRecord::Relation`:

```
users = User.search(params)
  .records            # custom ES-rails relation
  .includes(:address) # standard relation! No more custom methods
  .map_with_hit { |user, hit| user._score = hit._score } # NoMethodError

# ...
undefined method `map_with_hit' for #<User::ActiveRecord_Relation:0x007fb5a6107260>
```
