### ISSUE TITLE
Rails instrumentation does not work with persistence model

### ISSUE THREAD

**Issue by trungpham** [elastic/elasticsearch-rails#238]
```
class MyModel
  include Elasticsearch::Persistence::Model
end
```

I can't seem to get rails timing to work the standalone persistence model. Is it because I'm not using ActiveModel?

**Comment by Mathiou04** [comment]
Hi,
I am using ```elasticsearch-persistence (5.0.1)``` but cannot find a way to instrument it in my development environment.  I tried to ```require 'elasticsearch/rails/instrumentation'``` in my application.rb file but this does not seem to work as I do not see any more log in my rails console.
I suppose I could make it work by overloading the ```client``` using option ```log: true``` in my model (actually I see the instrumentation logs when I instantiate a client ```Elasticsearch::Client.new(log: true).cluster.health```), but is there a better way to turn it on once for all models ?
