### ISSUE TITLE
undefined method `page' - will_paginate

### ISSUE THREAD

**Issue by mmahalwy** [elastic/elasticsearch-rails#239]
Keep getting this error: 

```
NoMethodError: undefined method 'page' for #<Elasticsearch::Model::Response::Response:0x007fe3107f2c90>
```

With will_paginate 3.0.6

My query: 

```
Quran::Ayah.search("allah").page(2)
```

This works:

```
Quran::Ayah.page(2)
```

---

Also, for some reason ES is not exposing `Elasticsearch::Model::Response::Results`

```
2.1.2 :049 > ap Content::Translation.search("allah").results.current_page
NoMethodError: undefined method `current_page' for #<Elasticsearch::Model::Response::Response:0x007f915c656888>
2.1.2 :050 > ap Content::Translation.search("allah").current_page.results
NoMethodError: undefined method `current_page' for #<Elasticsearch::Model::Response::Response:0x007f915d7a39d8>
```

**Comment by hlxwell** [comment]
@mmahalwy In my project, I found this issue also, but if in your gemfile

Include kaminari before elasticsearch libs will be ok.

```
gem 'kaminari'
gem 'elasticsearch-model', git: 'git://github.com/elasticsearch/elasticsearch-rails.git'
gem 'elasticsearch-rails', git: 'git://github.com/elasticsearch/elasticsearch-rails.git'
```

**Comment by coolprobn** [comment]
> @mmahalwy In my project, I found this issue also, but if in your gemfile
> 
> Include kaminari before elasticsearch libs will be ok.
> 
> ```
> gem 'kaminari'
> gem 'elasticsearch-model', git: 'git://github.com/elasticsearch/elasticsearch-rails.git'
> gem 'elasticsearch-rails', git: 'git://github.com/elasticsearch/elasticsearch-rails.git'
> ```

This worked, does anyone know the reason behind this? 🤔

**Comment by sled** [comment]
> > @mmahalwy In my project, I found this issue also, but if in your gemfile
> > Include kaminari before elasticsearch libs will be ok.
> > ```
> > gem 'kaminari'
> > gem 'elasticsearch-model', git: 'git://github.com/elasticsearch/elasticsearch-rails.git'
> > gem 'elasticsearch-rails', git: 'git://github.com/elasticsearch/elasticsearch-rails.git'
> > ```
> 
> This worked, does anyone know the reason behind this? 🤔

The reason is that `Kaminari` won't be defined if it's included after Elasticsearch:

https://github.com/elastic/elasticsearch-rails/blob/8fe0a555083d16d9d64dea7b0ae8a8695c1d4211/elasticsearch-model/lib/elasticsearch/model.rb#L59
