### ISSUE TITLE
Combined filter bool and range return 400 error

### ISSUE THREAD

**Issue by allam-matsubara** [elastic/elasticsearch-rails#241]
Sorry to ask here the same thing I did on stackoverflow, but since I have no clue on what I'm doing wrong, neither anyone helped me there, I decided to post my doubt here. I'll just copy and paste what I asked there. Thanks in advance for any help.

---

I'm having trouble with elasticsearch again(again because i already asked a question about it 2 days ago). So, now my problem is that I have a filtered query that works pretty well until I combine a range filter with my bool filter. I'll explain, I use a bool filter with a must and a should and it always works fine. When I search using only the range filter without the bool, the query works fine again, but, when I mix bool and range, I receive this error:

Elasticsearch::Transport::Transport::Errors::BadRequest ([400] 
{"error":"SearchPhaseExecutionException[Failed to execute phase [query], all shards 
 failed; shardFailures {[SqKdBq3xRdKkXRIf-cp9vg][blogs][0]: SearchParseException[[blogs]
 [0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":
 {\"filtered\":{\"filter\":{\"bool\":{\"must\":[{\"range\":
 {\"created_at\":null}}],\"should\":[]}}}}}]]]; nested: QueryParsingException[[blogs] 
 [range] filter no field specified for range filter]; }{[SqKdBq3xRdKkXRIf-cp9vg][blogs]
 [1]: SearchParseException[[blogs][1]: from[-1],size[-1]: Parse Failure [Failed to parse 
 source [{\"query\":{\"filtered\":{\"filter\":{\"bool\":{\"must\":[{\"range\":
 {\"created_at\":null}}],\"should\":[]}}}}}]]]; nested: QueryParsingException[[blogs] 
 [range] filter no field specified for range filter]; }{[SqKdBq3xRdKkXRIf-cp9vg][blogs]
 [2]: SearchParseException[[blogs][2]: from[-1],size[-1]: Parse Failure [Failed to parse 
 source [{\"query\":{\"filtered\":{\"filter\":{\"bool\":{\"must\":[{\"range\":
 {\"created_at\":null}}],\"should\":[]}}}}}]]]; nested: QueryParsingException[[blogs] 
 [range] filter no field specified for range filter]; }{[SqKdBq3xRdKkXRIf-cp9vg][blogs]
 [3]: SearchParseException[[blogs][3]: from[-1],size[-1]: Parse Failure [Failed to parse 
 source [{\"query\":{\"filtered\":{\"filter\":{\"bool\":{\"must\":[{\"range\":
 {\"created_at\":null}}],\"should\":[]}}}}}]]]; nested: QueryParsingException[[blogs] 
 [range] filter no field specified for range filter]; }{[SqKdBq3xRdKkXRIf-cp9vg][blogs]  
 [4]: SearchParseException[[blogs][4]: from[-1],size[-1]: Parse Failure [Failed to parse 
 source [{\"query\":{\"filtered\":{\"filter\":{\"bool\":{\"must\":[{\"range\":
 {\"created_at\":null}}],\"should\":[]}}}}}]]]; nested: QueryParsingException[[blogs] 
 [range] filter no field specified for range filter]; }]","status":400}):
Here's a query that does return me a valid result:

{
  :query=>{
    :filtered=>{
      :filter=>{
        :range=>{
          :created_at=>{:gte=>"2014-08-10T07:56:59Z"}
        }
      }
    }
  }
}
Another one that works fine(this is a query with a bool filter):

{
  query: {
    filtered: {
      query: {
        multi_match: {
          query:"billy", 
          fields:["name^3", "author^2", "description", "lyrics", 
            "custom_genres.name", "location_display"]
        }
      }, 
      filter: {
        terms: {
          genre: ["alternative"]
        }
      }
    }
  }
}
The last one that works:

{
  :query=>{
    :filtered=>{
      :query=>{
        :multi_match=>{
          :query=>"<some query>", 
          :fields=>["title^3", "author_name^2", "excerpt", "body",
            slideshows.slide_title", "slideshows.slide_detail"]
        }
      }, 
      :filter=>{
        :range=>{
          :created_at=>{:gte=>"2014-08-10T08:39:35Z"}
        }
      }
    }
  }
}
And finally, the one that gives me the error:

{
  :query=>{
    :filtered=>{
      :filter=>{
        :bool=>{
          :must=>[{
            :terms=>{"genre_name"=>["Rock"]}
          }]
        }, 
        :range=>{
          :created_at=>{
            :gte=>"2014-08-10T08:55:16Z", :lte=>"now"
          }
        }
      }
    }
  }
}
I must say that I'm running those queries inside rails using .elasticsearch.search(), I'm using rails 3.2.19, ruby 1.9.3, elasticsearch-ruby 0.0.4, elasticsearch-rails and elasticsearch-model 0.1.4 and elasticsearch 1.3.2. I'm running it only on development environment on my local machine, which is running on a debian 7.

Thanks in advance for any clue.

**Comment by tbhockey** [comment]
Thanks for clearing this up @karmi ! Fixed my problem. Sometimes I find the documentation for this incredibly difficult to follow. :disappointed:
