### ISSUE TITLE
Don't know how to build task 'elasticsearch:import:model'

### ISSUE THREAD

**Issue by renatojf** [elastic/elasticsearch-rails#248]
> > Comment.**elasticsearch**.refresh_index!
> > 2014-09-16 16:53:16 -0300: POST http://localhost:9200/comments/_refresh [status:404, request:0.003s, query:N/A]
> > 2014-09-16 16:53:16 -0300: < {"error":"IndexMissingException[[comments] missing]","status":404}
> > 2014-09-16 16:53:16 -0300: [404] {"error":"IndexMissingException[[comments] missing]","status":404}
> > [!!!] Error when refreshing the index: Elasticsearch::Transport::Transport::Errors::NotFound
> > [404] {"error":"IndexMissingException[[comments] missing]","status":404}
> > => nil

This is my actual error. Everywhere I search, people say I need to import my model into elasticsearch. So I run bundle exec rake environment elasticsearch:import:model CLASS='Comment'

This returns me the task error. I can't find anything about it. Is there something wrong beside me not knowing how to configure it properly?

Elasticsearch is running fine.

**Comment by JDshi** [comment]
@renatojf  I also encountered the same problem, when I run "bundle exec rake environment elasticsearch:import:model CLASS='Modelname'", Can you give me some suggestions?
