### ISSUE TITLE
Setting Elasticsearch for production

### ISSUE THREAD

**Issue by tarebyte** [elastic/elasticsearch-rails#25]
Hi there I'm trying to deploy a toy app with this gem to heroku, and I didn't see any documentation how how to set the production environment url.

I'm sorry if I overlooked something, but any help would be much appreciated.

**Comment by atcoco** [comment]
Hello!

I have some issues with AWS. I have installed and configured perfectly about apache2 and passenger.  But this times out to the deployment app on AWS. So I tried to deploy sample project. As a result it worked. Only My real project doesn't work.  I need your help! :)
