### ISSUE TITLE
Question about defining models

### ISSUE THREAD

**Issue by twigbranch** [elastic/elasticsearch-rails#263]
Trying to setup Elasticsearch with a Rails app.

Basing the app around a XML dataset which I will convert to JSON.

It is already structured by Book, with Chapters, and Pages, as successive children.   Was thinking it would make sense to use Elasticsearch for persistence, but have a question about defining the models.

Ultimately, I'd want to be able to search for certain books by title, for example, but also show all books and respective chapters that have pages with certain text.

In the example music app, Artist has a method albums which performs a search for albums.  In my case, is that the right approach, or do I instead define an attribute for the children in each parent?

**Comment by estolfo** [comment]
Closing as this question is out of date.
