### ISSUE TITLE
Mongoid: use scope or where to limit imports?

### ISSUE THREAD

**Issue by netwire88** [elastic/elasticsearch-rails#267]
Hi,
Is there a way to use `scope` or `where` clause for Mongoid imports? I see it was made available for ActiveRecord via this update https://github.com/nono/elasticsearch-rails/commit/4a44bc750d22fa4972d2161e75fa43a200c5b818, but I wasn't able to do so via Mongoid, none of the following code works:

```
MongoidArticle.import(query: -> { where('status = active') })

MongoidArticle.where(status: 'active').import
```

**Comment by karmi** [comment]
@netwire88 Closing this in favor of @295 if that's OK!
