### ISSUE TITLE
mapping not honoring document_type

### ISSUE THREAD

**Issue by andrejj** [elastic/elasticsearch-rails#270]
I set a document_type directive.
Then use Influencer13.create_index!
But the mapping does not contain my document type.
Instead it contains a type derived from class name.

```ruby
class Influencer13
  include Elasticsearch::Persistence::Model
  index_name "influencers"
  document_type 'influencer'
  mapping do
    puts @type
    @type = 'influencer'
  end
end
```

=> "influencer13"

**Comment by tomeara** [comment]
@karmi I'd like to consider contributing to this project. Would this bug be something that you need help with, or are you already looking into it?

**Comment by karmi** [comment]
@andrejj Should be fixed by @miguelff.

@tomeara Terribly sorry to miss your message! Please do ping me *again* if I don't respond in time...
