### ISSUE TITLE
Performance: find_many needs hook to map docs before deserialize

### ISSUE THREAD

**Issue by aceofspades** [elastic/elasticsearch-rails#272]
This is per elasticsearch-persistence.

Imagine you are grabbing ID's from search results, and using those ID's to do a (costly) fetch the full record set from the main store (i.e. SQL, remote, etc.). The fetch should be done in one query with a list of ID's, then those results mapped via deserialize. 

I'm thinking either an overridable method or option for find that would map result document set into another array that would then be mapped via deserialize in `__find_many`.

Thoughts?

**Comment by karmi** [comment]
@aceofspades Sorry for missing your question for so long -- if it's still relevant, can you please be more concrete, preferably with a code example or sketch?

**Comment by aceofspades** [comment]
Basically I'm suggesting the `__find_many` should have the mapping from results into documents extracted, so it can be overridden, i.e. (no functional changes here)

```
def __find_many(ids, options={})
  type     = document_type || (klass ? __get_type_from_class(klass) : '_all')
  documents = client.mget( { index: index_name, type: type, body: { ids: ids } }.merge(options) )
  deserialize_many(documents['docs'])
end

def deserialize_many(documents)
  documents.map { |document| document['found'] ? deserialize(document) : nil }
end
```

Imagine you have a search index that maps terms into ids for ActiveRecord objects. Now it's possible to override `deserialize_many` to load the resulting ActiveRecord objects in one query with something like:

```
def deserialize_many(documents)
  ids = documents.compact.map { |d| d['_source']['_id'] }
  MyModel.find(ids)
end
```

**Comment by karmi** [comment]
@aceofspades I'd like to revive this discussion. I'm a fan of extracting features to allow overloading, but I'm a bit confused how ActiveRecord comes here to the mix, when the dicussed feature is about `elasticsearch-persistence` gem?

**Comment by aceofspades** [comment]
@karmi ActiveRecord is my use-case. I'd just like to extract the mapping of result documents into their deserialized form into its own method. In my case the result documents are just record ID's, which I would then extend/override `deserialize_many` to do a fetch from my SQL data store.

**Comment by karmi** [comment]
@aceofspades But how are you using `elasticsearch-persistence` with ActiveRecord? Why not the `elasticsearch-model` which is for ActiveModel/ActiveRecord integration?

**Comment by aceofspades** [comment]
@karmi I'm using a domain driven architecture that is based on ActiveRecord, but at a higher level. So I need to hook in to map search results into DB fetches to handle custom logic.

Any reason you'd hesitate extracting the mapping?

**Comment by estolfo** [comment]
Closing this issue as it is out-of-date.
