### ISSUE TITLE
Must manually include kaminari modules for paging

### ISSUE THREAD

**Issue by dimroc** [elastic/elasticsearch-rails#274]
I had the gems included and loaded but still needed to create an initializer to include the paging functionality. The documentation led me to believe otherwise:
https://github.com/elasticsearch/elasticsearch-rails/tree/master/elasticsearch-model#pagination

**initializers/elasticsearch.rb**

``` ruby
Elasticsearch::Model::Response::Response.__send__ :include, Elasticsearch::Model::Response::Pagination::Kaminari
```

**Comment by estolfo** [comment]
I don't think this is still an issue. @dimroc and @rahilsondhi can I close this?

**Comment by rahilsondhi** [comment]
Definitely close, thanks @estolfo

**Comment by estolfo** [comment]
thanks @rahilsondhi = )
