### ISSUE TITLE
Multiple types per index

### ISSUE THREAD

**Issue by pctj101** [elastic/elasticsearch-rails#279]
What's the best way of defining multiple document_types per model, and directing the various __elasticsearch__ API calls to each.

I may need to have say....

/index_name/type_version1/...
/index_name/type_version2/...
/index_name/type_version3/...

And of course insert/update/query on each of the types separately depending on my need.  

I totally get how to do "one type".  Is there are "good" way of managing more document types?

**Comment by karmi** [comment]
Just set the same index_name for the models. Closing, please reopen if you need more help. And please definitely have a look at the example applications.
