### ISSUE TITLE
Duplicate items in elasticsearch but not in PG

### ISSUE THREAD

**Issue by phawk** [elastic/elasticsearch-rails#281]
Hey, I’m using Elasticsearch::Model and Elasticsearch::Model::Callbacks with Rails 4.1.6. on https://niice.co/.
We’ve been having some issues lately with duplicates finding their way into elasticsearch but they are not present in the PostgreSQL database. I’m wondering if I need to include the ID param in the `as_indexed_json` response.

``` ruby
# It currently looks like this
def as_indexed_json(options={})
  as_json(only: [:title, :tags, :description, :provider, :provider_full, :image, :url, :created_at], ).merge({
    colours: MultiJson.dump(colours)
  })
end
```

When I do a resync to ES, i.e. teardown the index, create it from scratch and batch sync everything up, I don’t get any duplicates. 

I think the data in ES is being corrupted because the `update_document` callback for some reason isn’t finding the record and is just updating it again. I’m not 100% sure where this is going wrong, and from reading the source code for `update_document` I’m still not sure if I need to pass my models ID into the as_indexed_json or not, this is just a suspicion at this stage as to how the dupes are creeping in.

Any help on this would be much appreciated and I can provide more info if you need!

**Comment by estolfo** [comment]
@phawk Is this still an issue for you? Please let me know if I can close this, thanks!

**Comment by phawk** [comment]
@estolfo I’m not 100% sure, I think it's still an issue, although the version of elasticsearch-rails could well be out of date by now. Worth checking with @colinyoung87 and @chrisarmstrong

**Comment by estolfo** [comment]
Hey @colinyoung87 and @chrisarmstrong, is this issue still relevant? Let me know, thanks!

**Comment by colinyoung87** [comment]
@estolfo it was so long ago, i'm honestly not sure. Feel free to close it 👍thanks.

**Comment by estolfo** [comment]
thanks @colinyoung87 for getting back to me.
