### ISSUE TITLE
Dynamic index name should provide access to current record

### ISSUE THREAD

**Issue by fabn** [elastic/elasticsearch-rails#286]
I've already seen [source code for index_name](https://github.com/elasticsearch/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model/naming.rb) and also related issue #271 but in my opinion there is a missing option here. One should be able to define `index_name` according to the indexed record, for instance

```ruby
class Article
  include Elasticsearch::Model
  # calling block with the indexed record
  index_name { |a| "articles_#{a.locale}" } # return article_{en|es|fr|it}
  # or with instance_eval
  index_name { "articles_#{self.locale}" } # return article_{en|es|fr|it}
end
```
I noticed that there is [an instance method](https://github.com/elasticsearch/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model/naming.rb#L83) but also using it there is no way to do that.

This should be pretty easy to implement for record operations and it's also compatible with current behavior.

What do you think?

**Comment by karmi** [comment]
@fabn What do you think about the reservations I've mentioned?

**Comment by fabn** [comment]
Hi @karmi, I think that the primary use case for most of us is to manage different indices per language. It's been a while since I've developed the aforementioned app so I don't remember all the details.

The main point against this is your note in regard to `MyModel.create_index!` (or in general where an instance is not available), so in any case even with my suggestion one needs to write custom code to create indices (and mappings).

On the other side this could be combined with some code to automatically create index on first usage and in that case we have an instance to deal with.

Thus if you think this is not useful at all feel free to close, otherwise I'll try to think to it more generally and see where an instance is needed and how to solve that kind of issues.

As last option, since almost all methods take an optional `:index` param, one can do something like this in methods that don't have access to instances:

```ruby
# Calling code is now something like this
 target_index = options.delete(:index) || self.index_name
# In class methods where instance is not available
def index_name name=nil, &block
  raise "Cannot use instance based index name because instance is not present" if name.nil? && block.arity == 1
end
```

In this way the user is forced to wrap method calls and/or pass `:index` param explicitely when he's using this feature

**Comment by karmi** [comment]
@fabn It's mostly a matter of experience, in this case an experience with [_Tire_](https://github.com/karmi/retire). Whenever the library tries to be "too clever", you hit many edge cases, and more importantly, communicate a false assumption that any behaviour or requirement is matter of "just using it".

I see the Ruby/Rails libraries for Elasticsearch a bit differently: they should provide a robust and flexible framework for basing custom code on, while solving the most obvious or frequent use cases (hence e.g. the support for `import` etc). While having an index for each language is obviously a very frequent pattern, I do consider it something which the _application code_ should handle, for many reasons: ultimate flexibility, lack of reliance on the library features, better transparency across the team, ...

In the light of this, I'm leaning towards closing this, in favour of opening a pull request with some code (even a sketch), if that's OK?

**Comment by fabn** [comment]
Yes, that's ok. Thanks.

**Comment by karmi** [comment]
@fabn Closing this if it's OK. Please reopen or open a new PR if you wanna talk about it more!
