### ISSUE TITLE
Only in test environment (RSpec): callbacks are not syncing the index

### ISSUE THREAD

**Issue by volontarian** [elastic/elasticsearch-rails#298]
Only in test environment: callbacks are not syncing the index. In a development console it works.
I'm refreshing the index after trying to index data through callbacks and also tried to sleep 30 seconds before search but no solution.

I'm using elasticsearch gem 1.0.6 and elasticsearch server 1.0.3. I also tried it with 0.2.x and 0.9.x of elasticsearch server respectively elasticsearch gem 0.4.11.

I have this test code:

```
# rails_helper.rb
config.before(:all)do
  ActiveRecord::Base.connection.tables.each do |table|
    klass = table.capitalize.singularize.camelize.constantize rescue nil

    if klass.respond_to? :__elasticsearch__
      klass.__elasticsearch__.delete_index!
      klass.__elasticsearch__.create_index! force: true
    end
  end
end

# spec example
movie = Movie.create(title: 'Dummy')
Movie.__elasticsearch__.refresh_index!
expect(Movie.search('Dummy').records.to_a.map(&:id)).to eq([movie.id])
```

You can reproduce it in [this example application](https://github.com/gawlista/elasticsearch-callback-sync-fail):

```
bundle install
bundle exec rake db:create
bundle exec rake db:migrate
bundle exec rspec spec/models/movie_spec.rb
```

There is [1 commit with customization of the Rails generator code](https://github.com/gawlista/elasticsearch-callback-sync-fail/commit/2524ccaf62cc4384eaecc6b67dfa74e66ec26270).

The code for the movie model is located [here](https://github.com/gawlista/elasticsearch-callback-sync-fail/blob/master/app/models/movie.rb).

**Comment by inkstak** [comment]
I had the same problem.
After several tries, I discovered the gem [test_after_commit](https://github.com/grosser/test_after_commit) recommended by the [rails doc](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html#method-i-after_commit)

It solved the problem while keep using transactional fixtures or DatabaseCleaner transaction strategy.
