### ISSUE TITLE
How can I use facets 

### ISSUE THREAD

**Issue by magieSky** [elastic/elasticsearch-rails#304]
When I use elasticsearch-model, I find there has nothing to do with the facets search ,then I edit the source to achieve my function,will it be better to add the facets to the response?

Elasticsearch::Model::Response::Response  
        def facets
          response['facets']
        end

        def terms name=nil
          facets[name]['terms']
        end

**Comment by karmi** [comment]
@magieSky Can I help somehow? Or should we close this?
