### ISSUE TITLE
will paginate is not working after set param_name

### ISSUE THREAD

**Issue by warmwind** [elastic/elasticsearch-rails#307]
In ```pagination.rb```, it is hard coded to get page from ```options[:page]``` as below, 
```ruby```
module Elasticsearch
  module Model
    module Response
      module Pagination
       module WillPaginate

         def paginate(options)
            page = [options[:page].to_i, 1].max
            per_page = (options[:per_page] || klass.per_page).to_i

            search.definition.update size: per_page,
                                     from: (page - 1) * per_page
            self
          end

       end
     end
   end
end
```
But will_paginate supports customizing page param using param_name
https://github.com/mislav/will_paginate/blob/master/lib/will_paginate/view_helpers/link_renderer.rb

So when I had two pagination in one page and set param_name, it will not work.

**Comment by karmi** [comment]
Hey, I'll look into that, but with a slightly low priority, unless it's a blocker for you?

**Comment by warmwind** [comment]
Thanks. I've monkey patch this method in our codebase. It is not a blocker to us for now.

**Comment by karmi** [comment]
@warmwind Finally found some time to fix this -- see the attached commit, it should work! Thanks for your patience and thank you for reporting it!

**Comment by warmwind** [comment]
@karmi That's great! Thanks!~~
