### ISSUE TITLE
Scope with arguments for indexing?

### ISSUE THREAD

**Issue by mogox** [elastic/elasticsearch-rails#311]
I was wondering if you would be interesting in supporting parameters for scopes in the rake task for indexing documents.  It would be very useful to limit the index.

Assuming you have a ```Post``` class:
```ruby
class Post < ActiveRecord::Base
   scope :published ->(since_when){
      where(published_at: since_when..Time.current)
   }
end
````
What I really want is something like this:

```ruby
rake environment elasticsearch:import:model CLASS='Post' SCOPE="published(#{1.week.ago})" FORCE=y
```

what I think would be easier to implement is something like this:
```ruby
rake environment elasticsearch:import:model CLASS='Post' SCOPE="published" SCOPE_ARGS="#{1.week.ago}" FORCE=y
```

What do you think?  I'd be happy to help with the implementation but I'd like to have a sense of what would be the preferred public API.

Thanks!

**Comment by karmi** [comment]
@mogox The `import` method [supports passing the scope](https://github.com/elasticsearch/elasticsearch-rails/blob/master/elasticsearch-model/test/integration/active_record_import_test.rb#L56-L63) and that's where we should start -- the Rake task is basically just a wrapper around it.

Can you model your example as an integration test in the file `active_record_import_test.rb` linked above? That feels like the best way to discuss the API, and move to unit tests and the Rake task later.

**Comment by mogox** [comment]
Hey @karmi, thanks for getting back, I was thinking in something like this:

```ruby
          class ::ImportArticle < ActiveRecord::Base
            include Elasticsearch::Model

            scope :popular, -> { where('views >= 50') }
            scope :by_views, ->(min_views) { where('views >= ?', min_views) }
            mapping do
              indexes :title,      type: 'string'
              indexes :views,      type: 'integer'
              indexes :numeric,    type: 'integer'
              indexes :created_at, type: 'date'
            end
          end
....
        should "import only documents from a specific scope with parameters" do
          assert_equal 100, ImportArticle.count

          assert_equal 0, ImportArticle.import(scope: 'by_views', scope_args: 90)

          ImportArticle.__elasticsearch__.refresh_index!
          assert_equal 10, ImportArticle.search('*').results.total
        end

        should "import only documents from a specific scope with parameters" do
          assert_equal 100, ImportArticle.count

          assert_equal 0, ImportArticle.import(scope: 'by_views', scope_args: 30)

          ImportArticle.__elasticsearch__.refresh_index!
          assert_equal 70, ImportArticle.search('*').results.total
        end
````

What do you think? I'll be happy to give it a try and make a PR with the code changes needed for this test to pass.  Let me know if you think it should look different.

**Comment by karmi** [comment]
@mogox Sorry for replying so late -- it got lost during hectic times... It does make sense, but I wonder if we can support all possible arguments for the import method like this... But it's a valid point! If you're still up to implementing that, please open a PR and keep pinging me until I respond :)

**Comment by mogox** [comment]
will do! I actually figure out how to use ```ImportArticle.import(query: {...})```` for what I needed but I still think I'd be useful to have something like that because I'll have to do the same for other models in the short term.  I'll give it a try and ping you.  Thanks @karmi

**Comment by karmi** [comment]
@mogox Great! Closing this issue then, and let's open a PR when the time comes.
