### ISSUE TITLE
`require': cannot load such file -- elasticsearch/model (LoadError)

### ISSUE THREAD

**Issue by bcackerman** [elastic/elasticsearch-rails#32]
I'm receiving this error: `'require': cannot load such file -- elasticsearch/model (LoadError)`

I have `gem "elasticsearch-rails"` bundled in my `Gemfile` and have this at the top of my `Orders` model.

```
require 'elasticsearch/model'

class Order < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
```

**Comment by birchlore** [comment]
Yeah I was confused about this because the [Heroku guide](https://docs.bonsai.io/docs/ruby-on-rails) doesn't mention anything about a second gem.

**Comment by karmi** [comment]
@birchlore, I'm still torn on the issue. The `elasticsearch-rails` gem is rather small, it's just couple of convenience helpers, I _want_ people to be aware of `elasticsearch-model` (and maybe `elasticsearch-persistence`)... The Bonsai guide for Heroku needs to be fixed -- it not only misses the gem from Gemfile, but also have that strange `require` in the model, which is wrong.

**Comment by birchlore** [comment]
Yeah I hear what you're saying. I'll let the Bonsai people know to update it. Thanks @karmi
