### ISSUE TITLE
Is there a way to support multi-tenant? 

### ISSUE THREAD

**Issue by mingc** [elastic/elasticsearch-rails#321]
Is there a way to support multi-tenant?  We're using the apartment https://github.com/influitive/apartment gem do multi-tenant.

**Comment by kizashi1122** [comment]
I am using elasticserach with multitenant app (rails)

In my app, elasticsearch indexes are created by tenant.
When a tenant is created, its index (name is "#{Rails.env}-#{tenant.schema_name}") is automatically created at the same time.

I hope this will help.

**Comment by karmi** [comment]
Yeah, @kizashi1122 is right, this is something you have to set up in your application code, preferably using the `index_name` method.

The index doesn't have to be the real Elasticsearch index, it can an alias as well. Just note that you cannot index documents into an alias which points to multiple indices.

**Comment by karmi** [comment]
@mingc Closing this issue.
