### ISSUE TITLE
Elasticsearch::Persistence::Repository.search does not handle type _all properly

### ISSUE THREAD

**Issue by alolis** [elastic/elasticsearch-rails#324]
I have set the `type` for my repository class to be `_all` but when i make the following call the wrong `GET` request is being produced:

`my_repository.search(query: {match_all: {}})`

The above should make a `GET` request to `http://localhost:9200/my_index/_search` when `_all` type is set and not in `http://localhost:9200/my_index/_all/_search`

**Comment by karmi** [comment]
@alolis So, I managed to dig deep enough to find your question, apologies :) 

But `http://localhost:9200/my_index/_all/_search` is still valid in Elasticsearch, no? What is the issue with that?

**Comment by alolis** [comment]
@karmi , it does look valid but it returns 0 hits. I guess it does not understand '_all' as 'search in all types' but as a type.

In order to search in all types, you need to use `/my_index/_search` endpoint, at least in 1.5 from what I see.

**Comment by karmi** [comment]
Hmm,  `/my_index/_all/_search` should definitely be valid... Will check...

**Comment by alolis** [comment]
@karmi, I was going through the elastic docs and found this:

```https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-get.html
The get API allows for _type to be optional. Set it to _all in order to fetch the first document matching the id across all types.
```

So it seams that `_all` is valid when you use the `GET` API, not the `Search` API (which I was using and noticed the issue.

**Comment by karmi** [comment]
@alolis Yeah, I suspect something like that -- still haven't found time to properly verify/evaluate it against current ES, will need to add tests etc for that.

**Comment by estolfo** [comment]
@alolis Is this still an issue for you? Please let me know if I can close this, thanks!

**Comment by alolis** [comment]
@estolfo heh, it's been two years since then; we have moved to other platforms/libraries since then but thank you for asking :)

**Comment by estolfo** [comment]
thanks for letting me know @alolis !
