### ISSUE TITLE
Import from a JSON in bulk

### ISSUE THREAD

**Issue by uchoaaa** [elastic/elasticsearch-rails#329]
Hi, I have a huge NoSQL database (~4MM docs and counting) to migrate to ElasticSearch.
The first strategy is split this in batches, fetch it and put on ES. Simple enough.
Is not necessary save in database and I didn't want to manipulate each batch to make it compatible with special Bulk API format ([here](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/docs-bulk.html#docs-bulk))
Just import from a array of json data or even from a json file.

Is it possible with `Model#import`?
Other thoughts?

Cheers

**Comment by karmi** [comment]
@uchoaaa Sorry for a late reply -- basically, you should look at https://github.com/elastic/elasticsearch-ruby instead of _this_ gem -- but in any case you'd have to somehow transform the JSONs to proper format I think.

**Comment by karmi** [comment]
Anything more I can help with?

**Comment by uchoaaa** [comment]
@karmi my turn to say sorry for a late reply :)
I accomplished this using no gems, fetching the data and putting in the ES in bulk with the native APIs.
Thanks for the answer.

Cheers

**Comment by kkirsche** [comment]
Is anything else needed here or can this be closed?

**Comment by uchoaaa** [comment]
Can be closed, thanks.
