### ISSUE TITLE
failing at has_child query (No mapping for for type [xxx] error)

### ISSUE THREAD

**Issue by xxx** [elastic/elasticsearch-rails#330]
I have a couple of models set up in a `has_many`/`belongs_to` relationship. I'd like to set up parent/child indexing so I can find parents that have children that match the query, but I seem to be doing something wrong. I've seen the example in the elasticsearch-persistence repo, but replicating it is not working for me.

I feel like I'm missing something very small.

I'm using Elasticsearch 1.4.2 with the latest version of the gems (as of today).

I have a gist with some sample code and the error I'm receiving up at https://gist.github.com/xxx/bcc0fd84ec1629b7aced

**Comment by karmi** [comment]
Hey, sorry for missing this for so long. There's an example of relationships in models here: https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/examples/activerecord_associations.rb, can you check it? Please also check the full example Rails applications, they also have quite a lot of relationships-related stuff.

**Comment by karmi** [comment]
Any news? Closing?

**Comment by johnstoecker** [comment]
A year later, was having the same issue -- this is failing because the parent and child are on different indices. This is not possible in elasticsearch, the parent + child must be on the same index. I believe you can close this issue.

**Comment by jplethier** [comment]
I follow the example code on music folder here on this repository, but I am falling into this error. The two objects are being stores in same index, but the album object is not being created with has_parent attribute correct set up with type for artist.

**Comment by estolfo** [comment]
I'm going to close this issue. Please open a new one if the problem persists.
