### ISSUE TITLE
Request: Documentation on Testing

### ISSUE THREAD

**Issue by Ch4s3** [elastic/elasticsearch-rails#331]
Does anyone have experience testing features that use Elasticsearch-Rails using webmock (or similar)? If so, could some tips make it into the docs?

**Comment by karmi** [comment]
@Ch4s3 have a look in the `examples` folder, and more importantly try out the example Rails applications.

**Comment by karmi** [comment]
@Ch4s3 As for Webmock, Fakeweb, etc, it should be the same as handling any other web API.

**Comment by Ch4s3** [comment]
Thanks, that helps.

**Comment by karmi** [comment]
@Ch4s3 Safe to close this issue?

**Comment by Ch4s3** [comment]
Oh sorry. We're good here. We actually ended up using VCR. Wasn't too bad.

**Comment by karmi** [comment]
Glad to hear that!
