### ISSUE TITLE
SystemStackError: stack level too deep error while executing import on child class using Single Table Inheritance

### ISSUE THREAD

**Issue by rbaghele** [elastic/elasticsearch-rails#333]
require 'mongoid'
    Mongoid.connect_to 'articles'

    class Article
      include Mongoid::Document

      field :id,    type: String
      field :title, type: String
      field :first_name, type: String
      field :last_name, type: String
      attr_accessible :id, :title, :published_at
      include Elasticsearch::Model

       settings index: { number_of_shards: 1 } do
        mappings dynamic: 'false' do
          indexes :title, analyzer: 'english', index_options: 'offsets'
          indexes :first_name, type: "string"
          indexes :display_name, type: "string", as: "full_name"
        end
      end

      def full_name
  	    "#{first_name} #{last_name}"
      end

      def as_indexed_json(options={})
        as_json(
    	    except: [:id, :_id],
    	    methods: [:full_name]
    	    )
      end
    end

    class ChildArticle < Article
    end  
    ChildArticle.create id: '0', title: 'title for test 0', first_name: 'jhon', last_name: 'carter'
    ChildArticle.create id: '1', title: 'title for test 1', first_name: 'smith ', last_name: 'jones'

    
    ChildArticle.import    # giving error for child class import
    SystemStackError: stack level too deep
    from /home/user/.rvm/gems/ruby-2.1.5/gems/pry-0.10.1/lib/pry/pry_instance.rb:355

**Comment by fonji** [comment]
I have the same problem here and found some stuff... I think it needs to be investigated, support and documentation for child classes with single table are unclear or lacking.

Anyway, if you don't want everything in the same index re-```include Elasticsearch::Model``` in the child classes (ChildArticle in your example) seems to resolve the problem.

Now, if you want to index everything in the parent class (Article here), and want to use ```Elasticsearch::Model::Callbacks```, it seems more complicated:
```Article.import``` will import ChildArticles into the index, but it seems that the callbacks won't maintain the index, so you might need to re-write those. Also, you might want to add the "method" ```_type``` in ```as_indexed_json``` to use it as a filter.

**Comment by karmi** [comment]
Hey guys, I'm starting a two week vacation today, so I won't be able to investigate this properly. I agree that STI support is lacking, on the other hand, I don't personally believe in STI too much, so we must find some balance :)

With regards to:

> Now, if you want to index everything in the parent class (Article here), and want to use Elasticsearch::Model::Callbacks (...)

Let me just say again that the bundled callbacks module is merely a convenience thing -- you can see even in the README how easy it is to implement indexing by yourself. And of course, any serious application should do that in the background with Sidekiq, Resque, etc.

**Comment by fonji** [comment]
Thanks for your answer, and enjoy your vacations!

**Comment by karmi** [comment]
See #144 for a workaround from @jlaw90 -- we need to address it in the gem somehow.

**Comment by TomHoss** [comment]
+1 to request support for this feature... @karmi Even if you don't believe in it personally, it's a widely used feature of Mongoid, and this gem supports Mongoid right :)

I'll look at the workaround for now... @karmi Thanks for all your work on this

**Comment by karmi** [comment]
@rbaghele @TomHoss Keeping this open, and I'll look into it, I think some work has/is being done about inheritance lately.

**Comment by karmi** [comment]
I was playing with this for almost an hour. The problem is cleary coming from proxying the methods in `proxy.rb`, but I cannot solve it properly.

There seems to be a practical solution though -- include the module "once again" in the child class. Then the "stack level too deep" problem goes away:

```
class ChildArticle < Article
  include Elasticsearch::Model
end
``

For whatever reason, though, the documents are not created in Mongo for me:

```
[1] pry(main)> ChildArticle.create! id: '0', title: 'title for test 0', first_name: 'jhon', last_name: 'carter'
=> #<ChildArticle _id: 0, id: nil, title: "title for test 0", first_name: nil, last_name: nil, _type: "ChildArticle">
[2] pry(main)> ChildArticle.all.to_a
=> []
```
Can you veryify this somehow?

**Comment by Johaned** [comment]
(sorry for my english) Hi, I had the same problem (i'm working with Postgres/Rails 4), I just solved it by including Elasticsearch::Model (once again) in my child class, as @karmi suggested, now I can search using my STI approach and with many level of nesting. Many thanks!

**Comment by karmi** [comment]
@Johaned Cool, thanks for the verification! It's of course not a fix, but only a practical solution. I guess we'll have to live with it for a while until a proper solution for the proxying methods is found ( I cannot invest significant time into it right now).
