### ISSUE TITLE
Mapping

### ISSUE THREAD

**Issue by guilhermemello** [elastic/elasticsearch-rails#336]
I really don't know how to define a mapping.
The documentation doesn't explain details.

I want to know how to make a mapping to query documents with accents.
Somebody can help me ?

Thanks.

**Comment by karmi** [comment]
@guilhermemello Have a look at the application templates: https://github.com/elasticsearch/elasticsearch-rails/tree/master/elasticsearch-rails#rails-application-templates

These have fairly complex examples of mappings in the models, and show different ways how to create an index with the specific mapping(s).

**Comment by guilhermemello** [comment]
Hi Karmi.
Thanks for the reply.

These templates are very good but I need to know how to configure the settings section.
I think that in this section I can configure filters and so on. Am I right ?

I need to search records that have accents and I have to know how to configure asciifolding filter.

Thanks again.

**Comment by karmi** [comment]
The "expert" template has both the settings and mappings section, have you seen it? https://github.com/elasticsearch/elasticsearch-rails/blob/master/elasticsearch-rails/lib/rails/templates/searchable.rb#L13

The asciifolding analyzer will have to be set in the mappings section.

**Comment by guilhermemello** [comment]
Yes.

My code:

module Searchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model

    settings index: { number_of_shards: 1, number_of_replicas: 0 } do
      mapping do
        indexes :nome, analyzer: 'asciifolding'
      end
    end
  end
end

I run: Model.import

When I search for 'português' nothing is returned by elasticsearch.

**Comment by davedash** [comment]
Is there a way to update the existing mapping?

**Comment by fonji** [comment]
@guilhermemello I had a similar problem, here's my code if it's of any help
```ruby
  settings analysis: {
    analyzer: {
      default: {
        type: 'custom',
        tokenizer: 'standard',
        filter: ['standard', 'lowercase', 'asciifolding', 'word_delimiter', 'french_stemmer']
      }
    },
    filter:{
      french_stemmer: {
        type: 'stemmer',
        name: 'light_french'
      }
    }
  }
  mapping do
    indexes :medical_file_id, index: 'not_analyzed'
  end
```
As you can see, the mapping configuration is in an other method than the settings call.

@davedash destroy and recreate index is the easiest.
```ruby
Article.__elasticsearch__.create_index! force: true
Article.__elasticsearch__.refresh_index!
```
You may need to re-import your data.
As this can be slow, you can also try to use elasticsearch's API directly, but this may not re-parse existing documents.

**Comment by karmi** [comment]
Thanks for the helpful answer, @fonji!

@guilhermemello Does it work for you when you force recreate the index?

**Comment by karmi** [comment]
Anything more I can help with here?

**Comment by l4u** [comment]
Adding asciifolding to the default analyzer works. But If I use a custom analyzer like @guilhermemello's code, asciifolding no longer works.
