### ISSUE TITLE
Using Kaminari with Elasticsearch::Persistence::Model

### ISSUE THREAD

**Issue by infiniteiteration** [elastic/elasticsearch-rails#338]
Hi, I tried to use Kaminari with Elasticsearch::Persistence::Model, but it does not work yet it seems. Is there a way to paginate a Elasticsearch::Persistence::Model? Or is it somewhere on the roadmap?

Thank you!

**Comment by twigbranch** [comment]
We have a similar issue with will_paginate... 
undefined method `paginate' for #<Elasticsearch::Persistence::Repository::Response::Results:

**Comment by karmi** [comment]
There is no automatic support for Kaminari/WillPaginate yet, but it's of course planned.

**Comment by xpepermint** [comment]
+1

**Comment by andreacfm** [comment]
+1

**Comment by amal007** [comment]
+1

**Comment by jogaco** [comment]
+1

**Comment by amal007** [comment]
I was able to paginate the elasticsearch results with the below example.

```
# User Controller
def index
  @records = User.match_all_query(params[:page])
  total_count = @records.response.hits.total
  @records = Kaminari.paginate_array(@records, total_count: total_count)
                                    .page(params[:page])
                                    .per(100)
end


# User Model
def match_all_query(page = 1, per_page = 100)
  page ||= 1
  search({
    query: {
      match_all: {}
     },
     size: per_page,
     from: (page.to_i - 1) * per_page
   })
end


```
We can then use @records in the view page as  ```  <%= paginate @records %> ```

**Comment by jogaco** [comment]
Thanks for the tip!

**Comment by xpepermint** [comment]
+1

**Comment by nflorentin** [comment]
+1

**Comment by nflorentin** [comment]
I'd be interested to help with this feature. I'd appreciate any advice on how to implement it without making breaking changes. As far as I understood when calling method `search` on a repository or a model, the request is done right away and isn't waiting until method `results` is called. We'd have to change that behaviour right ? 

@karmi if you could put me in the right path, that would be great

thanks and sorry for my poor english

**Comment by fbarriosCL** [comment]
+1 Hi, I have the same problem(elasticsearch-persistence + kaminari), I will try with the solution of @amal007 🤞

**Comment by estolfo** [comment]
I'm going to close this as there is currently support for Kaminari and WillPaginate (and Pagy in progress).
