### ISSUE TITLE
Rails - ES and nested resources...

### ISSUE THREAD

**Issue by benoit5699** [elastic/elasticsearch-rails#343]
Hi, 
It has been now a few days and night I am stuck with this problem so I dare to ask my question...
I have a Post Model with its mapping and an Item Model : 
```
class Post < ActiveRecord::Base
   validates :title, length: {maximum: 140 }, presence: true
   has_one :initial_item, -> { where is_initial: true }, class_name: "Item"
   accepts_nested_attributes_for :initial_item

   mappings dynamic: 'false' do
        indexes :title, analyzer: 'custom_post_index_analyzer'
        indexes :initial_item, :type => "nested" do 
             indexes :content, analyzer: 'custom_post_index_analyzer'
        end
   end 
end

class Item < ActiveRecord::Base
  belongs_to :post
  validates :content, presence: true
end
```

I want to search with ES on post.title AND on post.initial_item.content

Here is my query:
```
	         query: 
				{
			    bool: 
			    	{
			      	should: 
			      		[
			        	{ 
			        	match: 
			        		{ 
			        		'title' =>
			        			{
								query: query,
					            analyzer: "custom_post_search_analyzer"
			        			} 
			        		}
			        	},
		        		{
			      		nested: 
			      			{
		        			path: "initial_item",
					        query: 
					        	{
					            bool: 
					            	{
					                should: 
					                	[
					                    {
					                    match: 
					                    	{
					                    	'initial_item.content' =>
					                    		{ 
					                    		query: query,
					                    		analyzer: "custom_post_search_analyzer"
					                    		}
					                    	}
					                    }
					                	]
					            	}
					        	}
					    	}
					    }
					    ]
					}			
	      		}

```

But only the title is accessible. I can't access the "initial_item.content in my search...

Any idea ?? Thk U veeeerrrrryyyy much for your attention.

**Comment by karmi** [comment]
Hi @benoit5699, this all looks OK, which is bad since I can't spot any error. Are you 100% you've recreated the index with `import force: true` or something like that when changing the mapping?

(The third example application has exactly this setup and it works: https://github.com/elasticsearch/elasticsearch-rails/blob/master/elasticsearch-rails/lib/rails/templates/searchable.rb#L36)

**Comment by benoit5699** [comment]
Hi Karmi,

Thk U VERY much your answer ! In fact, I am really a newbee...I had forgotten to add the 


	def as_indexed_json(options={})
	  	self.as_json(
	    	include: { initial_item: { only: :content}}
	    )
	end

which messed up the indexation...

Thk U for everything. I am discovering ES and all its wonderful power. It is a beautiful moment :-)

Rgds
