### ISSUE TITLE
How to configure mappings?

### ISSUE THREAD

**Issue by Aetherus** [elastic/elasticsearch-rails#350]
I have an ActiveRecord model named `Tag` like this:

``` ruby
create_table :tags do |t|
    t.string :name, null: false, limit: 20
    t.timestamps null: false
end
```

I want to index it in Elasticsearch in the following way:
1. index name is the name of my Rails project
2. type name is `tags`
3. field `name` should be indexed in 2 ways: `snowball (french)` and `ngram`
4. field `id` should be stored in Elasticsearch, but not indexed
5. any other fields are not stored in Elasticsearch
6. field `_all` is disabled

How and where should I code to achieve these?

**Comment by karmi** [comment]
@Aetherus have you actually checked the readmes and the example applications? https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-rails#rails-application-templates

**Comment by estolfo** [comment]
@Aetherus Is this still an issue for you? Please let me know if I can close this, thanks!

**Comment by estolfo** [comment]
I'm going to close this. Please open a new issue if you have further questions.
