### ISSUE TITLE
Multi Field not working

### ISSUE THREAD

**Issue by jalberto** [elastic/elasticsearch-rails#355]
rails 4.2 + elk 1.5

I have a model like this:

```
class My
  include Elasticsearch::Persistence::Model

  attribute :foo, Array,    mapping: {type: 'array'}
  attribute :title, String,   mapping: {type: 'string'}
  attribute :name, String,   mapping: { fields: {
                                                                name: { type: 'string', analyzer: 'snowball' },
                                                                raw:  { type: 'string', analyzer: 'not_analyzed' }
                                                               } }
```

in My.mapping.inspect I can see the correct mapping:

```
:name=>{:type=>"string", :fields=>{:name=>{:type=>"string", :analyzer=>"snowball"}, :raw=>{:type=>"string", :analyzer=>"not_analyzed"}}}
```

If I create a bunch of document I have this problem:

```
res_raw = My.search aggregations: {  names: { terms: { field: 'name.raw' } } }
res_raw.response.aggregations.tests.buckets.count  #=> 0

res_raw = My.search aggregations: {  names: { terms: { field: 'name' } } }
res_raw.response.aggregations.tests.buckets.count  #=> 10
```

I tried different approach like, change field type to 'multi_field' but I got same result. I created the docs using:

```
my = My.new {title: 'foo', name: 'bar'}
my.save
my.name #=> bar
```

Am I doing something wrong?

**Comment by pacuna** [comment]
+1, multi field isn't working for me either in Rails 4.2

**Comment by karmi** [comment]
> in My.mapping.inspect I can see the correct mapping

And when you look directly at `localhost:9200/my/_mapping`? Are you recreating the index when you changed the mappings?

**Comment by jalberto** [comment]
@karmi I'm deleting the index and creating it again

Only workaround I found is to do the mapping "directly" before ES:Persistence do it

**Comment by karmi** [comment]
@jalberto Hm, this is weird, I really don't see why this wouldn't work. There's quite complicated mapping configs being used here: https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/examples/music/artist.rb#L12, and that works. Would you be able to use that example and try the multi field with that? So we can have something I can run & debug on my end?

**Comment by jalberto** [comment]
@karmi it's quite weird :)

the only way it works for me is creating the index and mapping in a different step and then feed the data

Trying to go deeper in the problem

**Comment by karmi** [comment]
@jalberto But yeah, you _have_ to create the index first and _then_ start indexing the data, otherwise the dynamic (default) mapping will kick in and ignore your configuration

**Comment by karmi** [comment]
@jalberto Can I help more?

**Comment by delwaterman** [comment]
@jalberto Double check the version of Elasticsearch you are running. I ran into numerous issues on our servers because of some old Elasticsearch packages, and it won't warn you if you try to create an index with options that it doesn't understand.

**Comment by jalberto** [comment]
@delwaterman you are right, updating to last ELK fixed it. Now I can see multifield resuls :)

In other hand, how I access the secondary field:

    res = My.search query: { match: {'foo.raw': 'bar'} }
    res.first.foo #=> bar
    res.first.foo.raw #=> NoMethod (as expected)
    res.response.hits.hits.first._source[:foo] #=> bar
    res.response.hits.hits.first._source['foo.raw'] #=> empty

So How can I access foo.raw?

**Comment by stjhimy** [comment]
Any fix for this? Still having the issue to create multi_fields, they appear on the Model.mapping but it seems to not be created with create_index! force: true

**Comment by tamersalama** [comment]
When relying on `Model.import` for index creation - the index gets created through the default mappings and any defined/custom mappings are ignored as @karmi pointed out.

The work around is to create the index before the import.
```
Model.__elasticsearch__.create_index! force: true
Model.import
```

**Comment by michelson** [comment]
Hi I've the same issue , 
@tamersalama , I've tried forcing the index creation , and then run the import but it does not work

**Comment by karmi** [comment]
@jalberto The "artificial" field, like `foo.raw` *value* isn't accessible from the `_source` -- that is purely a Lucene index level thing, so you can use it in queries, aggregations, sorting, and so on.

**Comment by karmi** [comment]
@tamersalama What "does not work" mean specifically?

**Comment by michelson** [comment]
@karmi , Sorry , "does not work" means that when the index is creates and then the import is made then in the search the use of `not_analyzed` index fields are not filtering results at all

**Comment by michelson** [comment]
the search hash used for this is somethink like the following

```ruby
q = {
  query: {
    multi_match: 
      {
        query: "oli", 
        fields: ['first_name', "last_name", "type"], 
        operator: "or" ,
        type: "phrase_prefix", 
        slop: 10
      } 
  },
  filter: {
    and: {
      filters: [
        { term: { type: "sometype" } },
        { term: { color: "red" } }
      ]  
    }
  }
}
```

**Comment by karmi** [comment]
@michelson So, are you 100% sure you're using the `force: true` option? Can you attach here the (snippet) of mapping definition, and the resulting mapping?

**Comment by michelson** [comment]
Hi @karmi , thanks for your reply

and yes I've reindexed many times, with force true and with delete index

the mapping is something like this:

```json
vagrant@miguel:/vagrant$ curl  http://localhost:9200/people/person/_mapping?pretty=true
{
  "people" : {
    "mappings" : {
      "device" : {
        "dynamic" : "false",
        "properties" : {
          "type" : {
            "type" : "string",
            "fields" : {
              "raw" : {
                "type" : "string",
                "index" : "not_analyzed"
              }
            }
          },
          "color" : {
            "type" : "string",
            "fields" : {
              "raw" : {
                "type" : "string",
                "index" : "not_analyzed"
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by jalberto** [comment]
@michelson what versions are you using?

**Comment by estolfo** [comment]
Closing as this is out of date.
