### ISSUE TITLE
Search not querying fields included in index as part of associations

### ISSUE THREAD

**Issue by jraczak** [elastic/elasticsearch-rails#356]
My primary search needs to query against content that is derived from multiple associations in addition to values provided by a given record's database values. Checking the index configuration via `object.as_indexed_json` validates the data I'm looking for is being properly indexed. Below is the configuration for the indexing.

```
def as_indexed_json(options={})
  self.as_json({ 
    only: [:name, :properties],
    include: {
      venue_subcategory: { only: :name },
      tips: { only: :text }
    }
  })
end
```

Checking a record with `object.as_indexed_json` returns the following.

```
 => {"name"=>"Spring", "properties"=>"--- {}\n", :venue_subcategory=>{"name"=>"Restaurant"}, :tips=>[{"text"=>"Try the 1000 island sauce. It's better then cheese."}, {"text"=>"Best spicy onion rings in all of New York. They are extra deep fried."}]}
```

Note that all expected values are present in the JSON representation of the entry. To this point I assume I have everything configured correctly. However, a query for `'1000 island sauce'` returns several entries with partial matches but does not return the entry for Spring, which has '1000 island sauce' present in the text value for one of the indexed tips. Here is my query configuration.

```
def self.search(query)
  __elasticsearch__.search(
    {
        query: {
            multi_match: {
                query: query,
                fields: ['name^5', 'properties^3', 'tips["text"]', 'venue_subcategory'],
            }
        }
    }
  )
end
```

Within the `fields` configuration I've also defined tips as `'tips'` and `'tips.text'` with no success. I'm not sure how to point the query at fields/values that are provided as part of indexing associated objects. 

Thanks in advance for any help and insight.

**Comment by jraczak** [comment]
I should add, this doesn't work for searching against the `venue_subcategory` name from the index, either.

**Comment by jraczak** [comment]
Just took note of two things from the logs. First,

    Parse Failure [Failed to parse source [{"query":{"multi_match":{"query":{"include":["venue_category","venue_subcategory"]},"fields":["name^5","properties^3","tips[\"text\"]","venue_subcategory"]}}}]]

Then I noticed this:

    Caused by: org.elasticsearch.index.query.QueryParsingException: [venues] [match] query does not support [include]

Does this mean it is not at all possible to search against these values provided by content from associated objects?

**Comment by jraczak** [comment]
@karmi Any idea how to address this? I've thought of some workarounds like pushing content into text fields on the searched object but that seems really hacky...

**Comment by karmi** [comment]
@jraczak Sorry for missing this for so long! I don't see how this would fail with the example you provide, it's weird. Do you have any new info in the mean time? (Again, apologies for the late reply!)

**Comment by karmi** [comment]
Any news?

**Comment by estolfo** [comment]
@jraczak Is this still an issue for you? Please let me know if I can close this, thanks!

**Comment by estolfo** [comment]
I'm going to close this, feel free to open a new issue if you still have questions.
