### ISSUE TITLE
Multitenant scenario

### ISSUE THREAD

**Issue by jimmybaker** [elastic/elasticsearch-rails#359]
Greetings. I have a multi-tenant application where each tenant has it's own database and I would like for them to share a single ES instance. I'm having trouble using this gem since all since it relies on the record id to set the document id. When I import documents from two different tenants, the docs from the second tenant overwrite the docs from the first tenant where they have the same record ids but they're in different databases.

I thought there might be configuration option that would allow me to set a document id somehow. Let me know if anyone sees a way for this to work for me. Thanks a bunch!

Jimmy

**Comment by kizashi1122** [comment]
See https://github.com/elastic/elasticsearch-rails/issues/321

I hope this will help you.

**Comment by jimmybaker** [comment]
Hey. Thanks for the response. Question though. Isn't index_name a class method? Once it's set, isn't it set for all later instances of the class?

I just set mine like so and all the documents are being put in customers-1

```
index_name "customers-#{ActiveRecord::Base.connection.schema_search_path.split(',')[0].gsub('tenant', '')}"
```

**Comment by kizashi1122** [comment]
In my case, 

```rb
index_name = "#{Rails.env}-#{tenant.schema_name}"
Article.import({:index => index_name})
```

Searching as well.

```rb
index_name = "#{Rails.env}-#{tenant.schema_name}"
Article.search(query, {:index => index_name})
```

**Comment by jimmybaker** [comment]
Thanks again. I actually found that you can pass a Proc to the index_name method now which solves this problem. I created a mixin for my searchable models that will point them to the right index based on the current tenant like this:

```
index_name Proc.new { "#{name.underscore.pluralize}_#{tenant_id}" }
```

Name in this case would be the class name (Customer, SalesOrder, etc).
Thanks again for your help.

**Comment by kizashi1122** [comment]
Proc is better way :)

**Comment by karmi** [comment]
@jimmybaker Yeah, Proc is the way to go I think :) Sorry for missing the question. Thanks @kizashi1122 for the pointer to the issue!

**Comment by vanboom** [comment]
I would like to add our experiences with an Apartment/multi tenant app to this scenario.  Consider a scenario with thousands of tenants each with small amounts of data.  The Elasticsearch node will quickly reach sharding limits and require more nodes for very little data. 

So an index per tenant works well for small tenants, but does not scale efficiently on the Elasticsearch side. 

Attempting to keep multiple tenants' data in the same Elasticsearch index presents a different issue with how `elasticsearch-model` relates the records using the `id` field.  

So possibly an alternative method would deal with the ID mapping issue while allowing data from multiple tenants in the same index.
