### ISSUE TITLE
Re-index documents in batch

### ISSUE THREAD

**Issue by igorbelo** [elastic/elasticsearch-rails#363]
Is there a way to re-index a bunch of documents in batch?

My situation is:
I have a model called Sku, which belongs to a Product
When i update a Product, i want to re-index associated skus

I have looked into docs, api...but `index_document` method seems to be very simple, maybe there's another method to perform that

**Comment by karmi** [comment]
You can call the `import` method with a specific scope, see https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model/importing.rb#L29-L102

(Sorry for missing your question for so long)

**Comment by igorbelo** [comment]
Hello @karmi, no problem...

I think the `import` with scope does not work for me, as it deletes the records out of scope

Like...ids 1, 2, 3, 4, 5 are already indexed, and i want to reindex only ids 1, 2, 3, 4, using import with scope, it deletes my id 5...i mean, if i understood correctly the behaviour of `import`

**Comment by karmi** [comment]
It doesn't actually delete record with ID 5 -- it will just reindex 1, 2, 3, 4 (when they included in records found by the the scope of course). Closing this then?

**Comment by igorbelo** [comment]
Very nice! Didn't know that...
Thanks!
