### ISSUE TITLE
Faraday::ConnectionFailed: Connection reset by peer

### ISSUE THREAD

**Issue by krim** [elastic/elasticsearch-rails#365]
I have 700k articles. When i do Article.import i get an error "Faraday::ConnectionFailed: Connection reset by peer" after import some of articles.

**Comment by karmi** [comment]
Try using a client with support for persistent connections -- see README for elasticsearch-transport.

**Comment by karmi** [comment]
@krim Have you tried another HTTP library?

**Comment by twigbranch** [comment]
Using Faraday with Patron and gott the same thing.  
```
Faraday::ConnectionFailed: Recv failure: Connection reset by peer
```
Appears to have been due to a 100+ MB file which exceeds the limit (configurable).

**Comment by chappejw** [comment]
I'm seeing the same issue. I have reinstalled ruby using brew, rvm, with openssl from scratch... all to no avail. I've uninstalled / resinstalled all my gems, checked that my path is set correctly in my shell environment, but I have not gotten past this issue. 

If someone was able to resolve this can you please take a minute to explain how you resolved it and what specifically was the problem? Thanks.!

**Comment by ervinb** [comment]
@chappejw This is a long shot, but I've managed to fix the issue by updating VirtualBox (`5.1.8` -> `5.1.30`).


The bug causes SSL connections to be incorrectly reset ([ticket](https://www.virtualbox.org/ticket/16084)). My error rate before this was around 43% and zero after the update. I've got the hint from [@dploger](https://github.com/puppetlabs/r10k/issues/670) 🍻.

**Comment by estolfo** [comment]
Hi @krim @chappejw, Is this still an issue for you or can I close this? Let me know, thanks!

**Comment by chappejw** [comment]
I am no longer experiencing this issue. I set everything up on a new machine and no problem. I believe my openSSL was replaced by a networking tool and this was the core issue. Go ahead and close.

**Comment by estolfo** [comment]
Thanks @chappejw for letting me know!
