### ISSUE TITLE
Structured search queries

### ISSUE THREAD

**Issue by infiniteiteration** [elastic/elasticsearch-rails#368]
Is there parser for the queries for the usually used search query enhancements like: name:Tom year:2012, which would search for matching Tom in the name attribute in year 2013. Also "..." is often used and demanded by the users, which searches for exact match inside the apostrophes.

Is there a way to such strings translated to a proper query?

**Comment by karmi** [comment]
Hey, I'm not following the question? What kind of "parser"? You can either use the `query_string` query syntax, or the Query DSL. Have a look at the [`elasticsearch-dsl`](https://github.com/elastic/elasticsearch-ruby/tree/master/elasticsearch-dsl) gem for building the search definitions programatically in Ruby.

**Comment by infiniteiteration** [comment]
Hi, sorry for the late response. I was looking for this http://www.elastic.co/guide/en/elasticsearch/reference/1.x/query-dsl-query-string-query.html. I think it should be simple to formulate using elasticsearch-dsl.

**Comment by karmi** [comment]
@infiniteiteration That is opaque to the DSL builder -- the query syntax is a "freeform text", and in general, there shouldn't be _any_ reason whatsoever to use it from code. There are use cases where _people_ provide these queries. Machines should generate corresponding JSON structures.

**Comment by karmi** [comment]
@infiniteiteration Anything more I can can help with?

**Comment by karmi** [comment]
A

**Comment by infiniteiteration** [comment]
Sorry for responding bit late. It's clear now, I need string-query (https://www.elastic.co/guide/en/elasticsearch/reference/1.x/query-dsl-query-string-query.html), and will provide it people, no intention to use it from the code. That's an advanced option which some users might want to take.
