### ISSUE TITLE
Question: add attachments to child objects with mapper plugin?

### ISSUE THREAD

**Issue by twigbranch** [elastic/elasticsearch-rails#371]
Question explained here:

http://stackoverflow.com/questions/29622437/add-an-attachment-to-a-child-array-with-attachment-plugin-and-elasticsearch-rail

I'm using Elasticsearch::Persistence::Model.

In short, data comprises nested array of objects to which I wish to add an attachment.  I'm importing the data - not including the attachment - via bulk data api. The mapping appears to be determined automatically. Subsequently I wish to add an attachment to the objects in the nested array. I'm wondering how to do this - particularly how to setup the mapping, add, and index the attachments.

---
Using Elasticsearch::Persistence::Model with rails...

I have an index where one of the properties is an array of objects. I'd like to add an attachment via the mapper plugin to each object in that array.

Here's some example json,
```
"books" : [
  { 
    "title" : "book one", 
    "editor" : "me",
    "chapters" : [
      {
        "number" : "one",
        "author" : "first author",
        "full_text : ATTACHMENT
      },
      {
        "number" : "two",
        "author" : "second author",
        "full_text : ATTACHMENT
      }
    ]
  },
 ...
]
```
Currently, I've been importing data (not including any attachments) via the bulk api - in the example above, everything but the 'full_text'. I haven't explicitly defined mapping. I'm able to perform searches on various fields, without issue. Now I want to add the attachments.

How do I make this work?

Specifically, as to the mapping, continuing with the example above, I've tried adding the following to class Book:
```
  mapping do 
    indexes :chapters do
      indexes :full_text, type: 'attachment' 
    end 
  end
```
But, when I check the mapping, before actually indexing the full_text, I don't see a full_text field. Book.mapping returns,
```
 {:book=>{:properties=>{
   :title=>{:type=>"string"}, 
   :editor=>{:type=>"string"}, 
   :chapters=>{:type=>"string"}
 }}}
```
curl -XGET 'http://localhost:9200/my_app/_mapping/book' returns,
```
{"my_app-development":{"mappings":{"book":{"properties":{
  "title":{"type":"string"},
  "editor":{"type":"string"},
  "chapters":{"properties":{
    "number":{"type":"string"},
    "author":{"type":"string"}
  }}
}}}}}
```

**Comment by karmi** [comment]
> But, when I check the mapping, before actually indexing the full_text, I don't see a full_text field. 

This is weird, are you sure you're recreating the index? (see `create_index! force: true`)

**Comment by twigbranch** [comment]
I think the reason there was no 'full_text' field in the mappings result was that I was calling 'attribute :chapters, Array[Chaper]' _after_ 'mappings do indexes :chapters do indexes :full_text, type: 'attachment' end end.  This caused the type of chapters to be set to 'string.'

**Comment by twigbranch** [comment]
_And_ I was under the impression that dynamic mapping was still enabled, and I could explicitly map just the 'full_text' field.  Both wrong.

**Comment by karmi** [comment]
Yeah, see my answer in https://github.com/elastic/elasticsearch-rails/issues/391#issuecomment-101573351

**Comment by karmi** [comment]
Closing this?

**Comment by twigbranch** [comment]
OK (though #391 still appears to be a quirk)

**Comment by karmi** [comment]
I don't see the issue in #391 I'm afraid. Will reply as well there.
