### ISSUE TITLE
after_initialize missing?

### ISSUE THREAD

**Issue by julien51** [elastic/elasticsearch-rails#373]
We're using `Elasticsearch::Persistence::Model` to mimick ActiveRecord.
We are trying to setup "default" values in Ruby (can't do it at the ES level), when objects are instantiated... but for some reason the after_initialize hook is missing.

Looks like it's not part of  `ActiveRecord::Callbacks` module, so it's not included :(

```ruby
          extend  ActiveModel::Callbacks
          define_model_callbacks :create, :save, :update, :destroy # Why not add define_model_callbacks :initializer, only: :after 
          define_model_callbacks :find, :touch, only: :after
```

Any idea on how to add it?

**Comment by karmi** [comment]
Hi, depends on how these default values should behave -- I would maybe rather do it in "plain Ruby", even if `after_initialize` would be supported. What are these default values, can you be more specific, provide an example? (Note that default values for `attribute` _are_ [supported](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/examples/music/artist.rb#L22))

**Comment by julien51** [comment]
Karmi, thanks for responding. What do you call "plain Ruby" way?
Basically, there are 2 things we're trying to achieve: set default values (on for this, yes, we can use `attribute`, yay!) and we else want to reflect that a new object has been "instantiated" in *another* object to keep track of the "latest" instance of it.

**Comment by karmi** [comment]
So, any default values can indeed be set with the `attribute` method. I don't quite understand this part, though:

> we else want to reflect that a new object has been "instantiated" in another object to keep track of the "latest" instance of it.

If you give me some example, ideally in (pseudo)code, we can iterate on that further :)

**Comment by julien51** [comment]
Karmi, I think I found a solution about the linked object (we have an association between users and notes and wanted to keep track of all of a user's instantiated notes).

Another question: does `default` on attribute accept lambdas? For example we want to generated a "key" for each user and it can't be static.

**Comment by karmi** [comment]
It's basically a wrapper around Virtus' `attribute` method, so should be possible: https://github.com/solnic/virtus#default-values

**Comment by julien51** [comment]
Perfect! Thanks!
