### ISSUE TITLE
Elasticsearch persistence mapping example - set mapping for attribute twice?

### ISSUE THREAD

**Issue by twigbranch** [elastic/elasticsearch-rails#374]
Why is the example setting the mapping for suggest_title twice?
Here:
https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/examples/music/album.rb#L16

and here:
https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/examples/music/album.rb#L25

**Comment by karmi** [comment]
I think it's merely an oversight, one of these is not needed...
