### ISSUE TITLE
after unicorn restart, some zombie processes stay

### ISSUE THREAD

**Issue by Sen** [elastic/elasticsearch-rails#381]
so many processes like:

![2015-04-30 1 30 58](https://cloud.githubusercontent.com/assets/3863/7397080/9bfc7dfa-eed8-11e4-9ae7-b5e316345ae2.png)

what is it?
Seems i need to write a script to detect and kill these processes.

**Comment by karmi** [comment]
So what was it?

**Comment by Sen** [comment]
@karmi sorry, my bad, it's [spring] (https://github.com/rails/spring)

**Comment by karmi** [comment]
@Sen Cool.
