### ISSUE TITLE
Problems with pagination in MultiModel Search

### ISSUE THREAD

**Issue by miguelespada** [elastic/elasticsearch-rails#382]
I try to use pagination with Kaminari in a MultiModel Search.
    
This is my call:
    Elasticsearch::Model.search(query, [AAA, BBB]).page(1).results

This is the error:
     Failure/Error: response = MultiModelSearch.search('xxx')
     NoMethodError:
       undefined method `default_per_page' for #<Elasticsearch::Model::Multimodel:0x007ff9dbe4f520>

Is pagination supported for multimodel?

**Comment by xpepermint** [comment]
+1

**Comment by miguelespada** [comment]
It works with will_paginate

Elasticsearch::Model.search(query, [AAA, BBB]).per_page(25).page(1).results

**Comment by karmi** [comment]
@miguelespada Don't know from top of my head, we'll look into that.

@miguelff, would you spare some time to look at the issue, please?

**Comment by miguelff** [comment]
Sure, I will look into as soon as I got some time.

**Comment by miguelff** [comment]
One question @miguelespada, does the Gemfile of your application declare `gem 'kaminari' ` **before** elasticsearch-rails?

**Comment by xpepermint** [comment]
Btw... I have `kaminari` before `elasticsearch-rails`.

**Comment by miguelespada** [comment]
Hi @miguelff,
I do have kaminari before ES

# gem "will_paginate_mongoid"
gem "kaminari"
gem 'elasticsearch-model', git: 'git://github.com/elasticsearch/elasticsearch-rails.git'
gem 'elasticsearch-rails', git: 'git://github.com/elasticsearch/elasticsearch-rails.git'

**Comment by kikyous** [comment]
+1

**Comment by kikyous** [comment]
@miguelespada , @miguelff 
add `default_per_page` method simply works for me

```ruby
module Elasticsearch
  module Model
    class Multimodel
      def default_per_page
        10
      end
    end
  end
end
```

**Comment by miguelff** [comment]
Thanks for the feedback, I will tackle the issue as soon as I got some time. Before the end of the week.

**Comment by miguelff** [comment]
Working on this.

**Comment by xpepermint** [comment]
thx!

**Comment by miguelff** [comment]
Waiting for @karmi's review

**Comment by karmi** [comment]
Should be solved by @miguelff patch in #408 now!

**Comment by miguelespada** [comment]
Thanks! @miguelff  and @karmi

**Comment by rkrdo** [comment]
Are you guys planning on releasing a version on rubygems with this patch?
Also, what would be safer to use in the meantime, reference the gem to master or to the specific commit?

**Comment by karmi** [comment]
@rkrdo Absolutely, I'm processing issues on the `elasticsearch-ruby` repository this week, I hope I'll get to the Rails one first. If it would be a blocker for you, there's no trouble in releasing a version, but I'd like to accumulate more patches in that first.

In the Gemfile, I'd rather go with a specific commit -- master _should_ be always safe in terms of not suddenly breaking compatibility or having bugs, but of course it _might_ happen...

**Comment by rkrdo** [comment]
@karmi Makes sense, I'll reference a specific commit until you guys have enough patches to release a new version for now, thanks!
