### ISSUE TITLE
ActiveRecord::Enum causes Elasticsearch to throw an NumberFormatException exception.

### ISSUE THREAD

**Issue by 1nput0utput** [elastic/elasticsearch-rails#384]
I have a model with enum type 'state' and the  Elasticsearch::Model::Callbacks is included. Whenever I try to update the 'state' field, I get the following exception thrown at me: 

Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":"MapperParsingException[failed to parse [state]]; nested: NumberFormatException[For input string: \"submitted\"]; ","status":400}

Now, this seems obvious that the state should not be a string but an integer instead. I have no clue to how this possibly be converted to an integer in the elasticsearch's query.

**Comment by karmi** [comment]
So, post the index mappings. It might be that you indexed numbers first for that attribute. See the `create_index! force: true` method to re-create the index with up to date mappings and the `import` method.

**Comment by karmi** [comment]
Any news?

**Comment by 1nput0utput** [comment]
I was able to resolve my issue by forcing reindex as suggested by @karmi, I used the import rake task with FORCE=y
