### ISSUE TITLE
Elasticsearch::Persistence index is overwritten by newly instantiated classes

### ISSUE THREAD

**Issue by JonathanKolnik** [elastic/elasticsearch-rails#385]
split_test_repository.rb

```
class SplitTestRepository
  include Elasticsearch::Persistence::Repository

  def initialize(test_name, options={})
    index test_name
  end
end
```

rails console

```
[15] pry(main)> repo_1 = SplitTestRepository.new('repo_1');
[16] pry(main)> repo_1.index
=> "repo_1"
[17] pry(main)> repo_2 = SplitTestRepository.new('repo_2');
[18] pry(main)> repo_2.index
=> "repo_2"
[19] pry(main)> repo_1.index
=> "repo_2"
```

Is index a class variable? That seems weird. I don't understand why by instantiating repo_2, repo_1.index now points to repo_2's index

I followed this example https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/README.md#a-custom-class

**Comment by karmi** [comment]
@JonathanKolnik Hey, I see you've closed the issue -- how did you solve it? It looks like incorrect instructions or a bug in the library indeed.

**Comment by JonathanKolnik** [comment]
@karmi I chickened out and thought I hadn't explored it enough.

**Comment by karmi** [comment]
@JonathanKolnik Yeah, I tried it briefly and I think it's a bug, labelling appropriately...

**Comment by dimroc** [comment]
:+1:

**Comment by MMartyn** [comment]
@karmi I started to look into this and I am not quite sure how you would want to proceed with this bug. The problem seems to stem from the gateway being made a class method: 
https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/lib/elasticsearch/persistence/repository.rb#L46
 I started to change it, but then quickly realized that there are tests specifically looking for that behavior.

**Comment by estolfo** [comment]
same issue as this one: https://github.com/elastic/elasticsearch-rails/issues/811

**Comment by estolfo** [comment]
@MMartyn @JonathanKolnik @dimroc 
6.0.0.pre versions are available of elasticsearch-rails, elasticsearch-model, and elasticsearch-persistence. They include a refactor so that this problem should be resolved. Feel free to try it out in your testing environment.

**Comment by estolfo** [comment]
I'm closing this as 6.0.0 is released and it includes a fix for this.
