### ISSUE TITLE
How to nest attributes that are on the same model?

### ISSUE THREAD

**Issue by npearson72** [elastic/elasticsearch-rails#386]
I have a Feature model that `belongs_to` FeatureKey and FeatureValue.
````
FeatureKey#name => 'color'
FeatureValue#name => 'red'
````
I would like to generate a nested aggregations structure to build a shopping cart filter (facet) navigation.

Ideally, the structure would like something like

````
{ features: {
  { key: color, values: [ red, blue, yellow ] },
  { key: size, values: [ large, medium, small ]}
}}
````

Can anyone anyone suggest how I can do this?

**Comment by karmi** [comment]
This all depends on how your models are being indexed in Elasticsearch (eg. call `Feature.__elasticsearch__.as_indexed_json`). Technically, what you're looking for is the `terms` aggregation.

The third, "expert" template (see https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-rails#rails-application-templates) has a really comprehensive, code based example for a faceted navigation.

**Comment by karmi** [comment]
Any news?

**Comment by npearson72** [comment]
Oh sorry, I forgot I opened this.

Yes, here's how I got it to work (after studying the templates):

````
    settings index: { number_of_shards: 1, number_of_replicas: 0 } do
      mapping do
        indexes :features, type: :object, index: :not_analyzed
      end
    end

    def as_indexed_json(options={})
      {
        features: {
          pair: features.map do |f|
            { f.feature_key.name => f.feature_value.name }
          end
        }
      }
    end

````

Then I could just build my aggs with my own method like so:

````
    def build_aggregations
      search_params[:aggs] = feature_keys.map do |key|
        { key => { terms: { field: "features.pair.#{key}" } } }
      end.reduce(:merge)
    end
````

I think the trick was mapping it as an object, so I can access nested attributes with the dot notation. It works great.
