### ISSUE TITLE
 Elasticsearch::Model broke find_in_batches, first and last methods

### ISSUE THREAD

**Issue by fuCtor** [elastic/elasticsearch-rails#390]
Methods find_in_batches, first, last and maybe some thing else are broken after including Elasticsearch::Model.

For example:
with Elasticsearch::Model

``` ruby
Contact.first
Contact Load (0.7ms)  SELECT "current_contacts".* FROM "current_contacts" ORDER BY "current_contacts"."contact_id" ASC LIMIT 1
PG::UndefinedColumn: ERROR:  column current_contacts.contact_id does not exist
```

without

``` ruby
Contact.first
Contact Load (0.5ms)  SELECT "current_contacts".* FROM "current_contacts" ORDER BY "current_contacts"."id" ASC LIMIT 1
```

As you can see SQL are changed. I can't find place where reorder called.
If i call like this:

``` ruby
Contact.reorder(:id).last
```

All is OK.

**Comment by karmi** [comment]
Would you be able to provide me with a fully executable example, so I don't have to reconstruct it from the snippet? I would be surprised to see the gem interfering with ActiveRecord. (The only place I know from the top of my head where we interact with `primary_key` is here, https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model/adapters/active_record.rb#L16)

**Comment by karmi** [comment]
For example, I used this executable example when sketching the support for different primary keys, maybe it's easy to adapt it for PostgreSQL?

```ruby
$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)

require 'pry'
Pry.config.history.file = File.expand_path('../elasticsearch_development.pry', __FILE__)

require 'logger'
require 'ansi/core'
require 'active_record'
require 'active_support/core_ext/numeric'
require 'active_support/core_ext/hash'
require 'uuid'

require 'elasticsearch/model'

ActiveRecord::Base.logger = ActiveSupport::Logger.new(STDOUT)
ActiveRecord::Base.establish_connection( adapter: 'sqlite3', database: ":memory:" )

ActiveRecord::Schema.define(version: 1) do
  create_table :articles, id: false, primary_key: :uuid do |t|
    t.string       :uuid, primary_key: true
    t.string       :title
    t.date         :published_at
    t.boolean      :published
    t.timestamps
  end
  add_index :articles, :uuid
end

Elasticsearch::Model.client= Elasticsearch::Client.new log: true

class Article < ActiveRecord::Base
  include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks

  before_create { self.uuid = UUID.new.generate }

  def attribute_names; ["uuid", "title", "published_at", "published", "created_at", "updated_at"]; end

  def self.primary_key; 'uuid'; end
end

Article.delete_all
# Article.create! title: 'Foo',     created_at: 1.day.ago,  published: true
# Article.create! title: 'Bar',     created_at: 2.days.ago, published: true
# Article.create! title: 'Foo Foo', created_at: 3.days.ago, published: false

Article.__elasticsearch__.create_index! force: true

puts '', '-'*Pry::Terminal.width!

Pry.start(binding, prompt: lambda { |obj, nest_level, _| '> ' },
                   input: StringIO.new(''),
                   quiet: true)
```

**Comment by fuCtor** [comment]
OK, I try make minimal app with for reproduce this situation.

I'm surorised to. I was finding places where order or reorder called. I don't find any places, but wrong field placed in this part of SQL query.

**Comment by karmi** [comment]
It doesn't have to be a full app, that muddies the waters usually. See eg. https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/examples/activerecord_article.rb

**Comment by fuCtor** [comment]
Rewrite this example for PG, all work good.
In code I make test:
- model without elastic, all right, in console include Elastic model, all right to.
- model with elastic, wrong and primary_key changed.

I will be search where this attribute changed. Mystic.

**Comment by lorenjohnson** [comment]
This is causing failures for me due to our use of UUIDs which by definition are incompatible with find_in_batches

Ref docs for #find_in_batches:

"NOTE: It's not possible to set the order. That is automatically set to ascending on the primary key (“id ASC”) to make the batch ordering work. This also means that this method only works with integer-based primary keys."
