### ISSUE TITLE
elasticsearch-model datamapper example is broken

### ISSUE THREAD

**Issue by postmodern** [elastic/elasticsearch-rails#392]
I copied the example into my project. While registering the custom adapter, I get this error:

<pre>
ERROR -  NameError - uninitialized constant Elasticsearch::Adapters::DataMapper::Importing:
/home/hal/.gem/ruby/2.1.4/gems/elasticsearch-model-0.1.7/lib/elasticsearch/model/adapter.rb:128:in `const_get'
/home/hal/.gem/ruby/2.1.4/gems/elasticsearch-model-0.1.7/lib/elasticsearch/model/adapter.rb:128:in `const_get': uninitialized constant Elasticsearch::Adapters::DataMapper::Importing (NameError)
</pre>

**Comment by karmi** [comment]
That's because that's just an example, without all the extra modules -- see the https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model/adapters/active_record.rb.

I don't want to provide a _fully working_ example for DataMapper, but it would be better to provide a clear documentation in the example.

**Comment by karmi** [comment]
@postmodern Closing this, if it's fine? Please reopen if you'd like to discuss it more!

**Comment by postmodern** [comment]
I looked over the activerecord adapter, but I need more in-depth documentation on the various methods I would need to define. I may try writing my own adapter and publishing that as a gem.

**Comment by karmi** [comment]
So, the regular contract of an adapter is defined in the default one: https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model/adapters/default.rb (regular pattern, raises `NotImplemented` for contract methods, etc). 

For the importing module, you basically have to implement the `__find_in_batches` and `__transform ` methods; it should be quite straightforward.
