### ISSUE TITLE
elasticsearch-model chain for method where

### ISSUE THREAD

**Issue by vfa-dunghn** [elastic/elasticsearch-rails#394]
Hi friends
I am new to elasticsearch-model
I have a options field: keyword, city
I want to do something like
``` ruby
Club.search(opt[:keyword]).records.where(city: opt[:keyword] || '*')
```
to check if city is not in option => search all
But it does not work.
Thanks !

**Comment by dabit** [comment]
Wouldn't a mixed approach work better in this case?

    if opt[:keyword]
      Club.search(opt[:keyword]).records
    else
      Club.all
    end

**Comment by karmi** [comment]
++ @dabit

**Comment by vfa-dunghn** [comment]
@dabit  thanks !

**Comment by vfa-dunghn** [comment]
@
