### ISSUE TITLE
[404] {"error":"IndexMissingException[[Index_Key] missing]","status":404}

### ISSUE THREAD

**Issue by vfa-dunghn** [elastic/elasticsearch-rails#396]
Hi friends.
I have a model

``` ruby
require 'elasticsearch/model'

class Club
  include Mongoid::Document
  include Mongoid::Timestamps
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  include Mongoid::Attributes::Dynamic

  index_name "club-ygo"

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :id, index: :not_analyzed
      indexes :name, index: :not_analyzed
    end
  end

  def as_indexed_json(options={})
    as_json(
      only: [:id, :name,  :address, :display, :loc, :country, :city, :updated_at],
      methods: [:search_keys]
    )
  end
```
- When I try to do a search by calling

``` ruby
Club.search('aero')
```
- this error shows `[404] {"error":"IndexMissingException[[Index_Key] missing]","status":404}`
- Did I miss some configuration ? Thanks !

**Comment by karmi** [comment]
Can you model your question with an executable example like this one: https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/examples/mongoid_article.rb so I can just run it and see?

**Comment by anuj-verma** [comment]
Hi @vfa-dunghn ,
Have you created an index for your model Club. If not, this can be a reason for your error. Before searching, you must index your documents by running the following command for each document in your Club model. 
`Club.each { |club| club.__elasticsearch__.index_document! }`
Or you can index all documents of your model by executing these two commands:
1. `Club.__elasticsearch__.create_index!`
2. ` Club.import`
After indexing your documents you can search them by executing:
`Club.search('aero')`

**Comment by estolfo** [comment]
Hi @vfa-dunghn can I close this?

**Comment by estolfo** [comment]
Closing issue as there hasn't been activity on it since 2016.
