### ISSUE TITLE
Scores are not equal when searching a model vs. multiple models

### ISSUE THREAD

**Issue by zackseuberling** [elastic/elasticsearch-rails#397]
Perhaps I'm missing something, but I'm trying to search across multiple models and show the most relevant records based on score (this seems obvious), but I'm having an issue with the multiple models Elasticsearch method. Here's an example:

```
2.0.0-p643 :162 > Elasticsearch::Model.search('Hans', [Article]).results.first._score
 => 0.17990226
2.0.0-p643 :163 > Article.search('Hans').results.first._score 
=> 2.7795632
```

Perhaps related, but these two records aren't even the same record. Is there a reason for this? Am I missing something? 

Using `Elasticsearch::Model.search('Hans', [Article, Collection])`, I am only getting Articles, but when using the `Collection.search` method I've implemented, I find the Collection. 

I must be doing something wrong.

**Comment by karmi** [comment]
Scores won't ever be equal if you search eg. across multiple indices -- that's just how the Lucene scoring works... So all potential solutions depend on what you want to achieve.

**Comment by zackseuberling** [comment]
after many more hours of research, I believe the root of my issue is how to properly set up indices in the first place, so perhaps my misunderstand something fundamental

**Comment by karmi** [comment]
@zackseuberling I understand these issues are frustrating. If you'd be able to come up with an example I can run and debug on my end, I can try to help...

**Comment by karmi** [comment]
Any news?

**Comment by miguelff** [comment]
@zackseuberling Did you dig deeper on this issue? Was it an improper setup of the indices in the end?

**Comment by zackseuberling** [comment]
I can't say for sure (still trying to understand the complexities of Elasticsearch), but I do believe my issue was a fundamental misunderstanding of Lucene and setting up my indices

**Comment by karmi** [comment]
@zackseuberling Post any isolated code fragments if you'd have them... I can look over the next days.
