### ISSUE TITLE
Faraday Timeout error

### ISSUE THREAD

**Issue by vickyonit** [elastic/elasticsearch-rails#398]
I am getting the faraday timeout error when i try searching but it works fine while indexing. I am behind the corporate proxy.

So i used the proxy setting while creating the elasticsearch client and below is the setting

```
Elasticsearch::Model.client = Elasticsearch::Client.new hosts: [
      { host: 'localhost',
        port: '9200',
        user: 'username',
        password: '***********'        
      },
      { host: 'localhost',
        port: '9201',
        user: 'username',
        password: '***********'        
      } ], log: true
```

Below is the log on request to load the page

```
Started GET "/search/index" for 127.0.0.1 at 2015-05-15 12:05:33 +0530
  ActiveRecord::SchemaMigration Load (0.2ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by SearchController#index as HTML
2015-05-15 12:06:34 +0530: [Faraday::TimeoutError] Timeout::Error {:host=>"localhost", :port=>"9200", :user=>"username", :password=>"***********", :protocol=>"http"}
  Rendered search/index.html.erb within layouts/application (60192.9ms)
Completed 500 Internal Server Error in 60386ms

Faraday::TimeoutError - Timeout::Error:
  /usr/lib/ruby/1.9.1/net/protocol.rb:146:in `rescue in rbuf_fill'
  ...
```

Please help. I am onto this for like 3 days not able to resolve it.

**Comment by karmi** [comment]
Have a look at https://github.com/elastic/elasticsearch-ruby/tree/master/elasticsearch-transport#transport-implementations, which shows an example how to configure timeouts for the client.

Depending on which particular HTTP library you use (you should always use one with support for persistence connections, as the README makes clear), you might need to set it differently.

**Comment by karmi** [comment]
Any news?

**Comment by vickyonit** [comment]
@karmi i am not able to do it, when it does the http request it is getting blocked in the http_request module. I have provided the proxy setting at the curl level and also at the application level. No help but needed to implement the search feature for application so changed to sunspot rails and is working fine but flexibility is less compared to elastic.

**Comment by vickyonit** [comment]
Wrongly clicked the button which closed the issue. So reopened it. Sorry.

**Comment by karmi** [comment]
I understand that this is frustrating, but passing timeout options to Faraday generally should work fine (see https://github.com/elastic/elasticsearch-ruby/tree/master/elasticsearch-transport#transport-implementations). 

Does [`http_request`](https://github.com/xianhuazhou/http_request.rb) actually support persistent connections, like Curb, Patron, Typhoeus? Are you able to perform the search request for example with Curb, and pass the [necessary options](http://curb.rubyforge.org/classes/Curl/Easy.html#M000059)?

I'm afraid I can't help you much unless I model the same situation with the particular HTTP library you're using, and debug if and how it takes the timeout options. Is there any way I can help you?

**Comment by estolfo** [comment]
Closing as this is out of date.
