### ISSUE TITLE
Why the index name is the class name?

### ISSUE THREAD

**Issue by matreyes** [elastic/elasticsearch-rails#401]
I understood that the index is the equivalent to a database, and mappings are ≈ to tables (in sql world)
So I tried with a common index_name for each of my models (mappings).. and it got problems when aggregating nested documents (it said that mapping wasn't deffined for the nested document).

So i finished with the default configuration (index name = class name pluralized) and (document name = class name) and it works great... but i'm still with the doubt why it uses different indexes for each model. 

Someone could explain?
Thanks !

**Comment by karmi** [comment]
Different index names for different models are just the default. It's perfectly fine to have models in the same index (see eg. example for persistence gem [here](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/examples/music/index_manager.rb#L4)).

> it got problems when aggregating nested documents

I'm afraid I need some real code to be able to efficiently review that. Can you work with an example similar to this one: https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/examples/activerecord_associations.rb, so we can share a code base?

(Of course, a failing test is also a great example, even better.)

**Comment by karmi** [comment]
@matreyes Any news?

**Comment by ElamT** [comment]
Hey i got the same problem
