### ISSUE TITLE
Anyone have an example of setting up stemming, stopwords, etc?

### ISSUE THREAD

**Issue by npearson72** [elastic/elasticsearch-rails#403]
I'm new to ES and this gem, and would really appreciate if someone could give me an example of how to setup stemming and stopwords.

Thanks

**Comment by khcr** [comment]
You have to use elasticsearch language analyzers or declare your own analyzer in the settings.
Have a look here: https://www.elastic.co/guide/en/elasticsearch/reference/1.5/analysis-lang-analyzer.html

To use custom settings, do the following in your model:

```ruby
settings index: { analysis: { filter: { ... }, analyzer { my_custom_analyzer: { ... }}}} do
    mapping do
        indexes :name, analyzer: :custom_analyzer
    end
end
```

**Comment by npearson72** [comment]
Thanks @khcr 

I must be doing something wrong. Neither the stemming nor the stopwords are working. Here is what I have:

````
    settings index: {
      number_of_shards: 1, number_of_replicas: 0, analysis: {
        analyzer: {
          keyword: {
            tokenizer: "standard",
            filter: ["lowercase", "asciifolding", "english_stopwords", "english_stemmer"]
          }
        },
        filter: {
          english_stopwords: {
            type: "stop",
            stopwords: "_english_"
          },
          english_stemmer: {
            type: "stemmer",
            language: "light_english"
          }
        }
      }
    } do
      mapping do
        indexes :name, type: "multi_field" do
          indexes :name, analyzer: "keyword"
        end
        indexes :categories, type: "multi_field" do
          indexes :categories, analyzer: "keyword"
        end
        indexes :feature_values, type: "multi_field" do
          indexes :feature_values, analyzer: "keyword"
        end
        indexes :description, type: "multi_field" do
          indexes :description, analyzer: "keyword"
        end
      end
    end
````

Also, here is my query.. does this look right to you?

````
        search_params[:query][:filtered][:query] = {
          bool: {
            should: [
              {
                multi_match: {
                  query: query,
                  type: "cross_fields",
                  fields: ["name^10", "feature_values^5", "categories^2", "description"],
                  operator: "and"
                }
              }
            ]
          }
        }
````

**Comment by khcr** [comment]
The setting seems right.
1. In your mapping, you use a `multi_field` type. This is only useful if you want to have two indexes on the same field. Simply do `indexes :name, type: :string, analyzer: :keyword`
See there: https://www.elastic.co/guide/en/elasticsearch/reference/0.90/mapping-multi-field-type.html
2. If you're including associations (maybe `categories` ?), be sure to do customize the `as_indexed_json` method.

**Comment by npearson72** [comment]
Ok, thanks. It seems my problem was that I didn't properly create my index. I was just importing my products without first creating the index each time I made changes.

I'm now using:

`Product.__elasticsearch__.create_index! force: true`

Is that right? Do I need to use `force: true` each time?

**Comment by karmi** [comment]
@npearson72 For a general question like this one, you might get answers sooner at https://discuss.elastic.co.

Regarding your last comment, yes, the best/simplest way how to update the index mapping is just to re-create it and re-import the data (if the amount allows for that).

I think you should check the example Rails application, so you study the techniques and patterns a little bit, in real code. See https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-rails#rails-application-templates

**Comment by npearson72** [comment]
@karmi Thanks for the resource. I'm new to ES and this really helps. Sorry for adding noise to the issues. Great gem!

**Comment by karmi** [comment]
@npearson72 No worries. It's fine to use Github issues for questions, but a really generic ES ones are better handled by the discussion board / mailing list or IRC.
