### ISSUE TITLE
#__elasticsearch__.index_document changes sort position of resource

### ISSUE THREAD

**Issue by npearson72** [elastic/elasticsearch-rails#404]
I am using custom callbacks in my models like so:

```
  def update_product_index
    self.product.__elasticsearch__.index_document
  end
```

But when a product gets updated, it drops to the bottom of the "list" -- in other words the it becomes the last item in the collection even if it was the first item prior to the update.

Is there a way to change this behavior?

**Comment by karmi** [comment]
Sorry, I don't understand what you mean by "it becomes the last item in the collection". Can you provide a more full and illustrative example?

**Comment by npearson72** [comment]
Ok, imagine... that you have a catalog view of products in an ecommerce site. The first product in the list is product A.

You update product A.

Now product A becomes the last item in the list.

Does that help explain what I mean?

**Comment by totallymike** [comment]
It sounds like you're using the default ordering of search results?  Try specifying a sort parameter on your search.

**Comment by npearson72** [comment]
Would that effect search results being ordered by relevancy?

**Comment by karmi** [comment]
> Does that help explain what I mean?

No, sorry. I am totally lost what you might mean here. I'm afraid you have to provide some code examples, the search definition, etc. Updating a record/document doesn't affect its score, and hence the ordering -- unless you sort on the `updated_at` field, of course.

**Comment by totallymike** [comment]
I am able to reproduce the behavior raised in this issue.

```ruby
MyModel.first.__elasticsearch__.index_document
MyModel.last.__elasticsearch__.index_document
MyModel.search('*').results.map(&:id) #=> [1, 99]
MyModel.first.__elasticsearch__.index_document
MyModel.search('*').results.map(&:id) #=> [99, 1]
```

**Comment by karmi** [comment]
@totallymike Yeah, but you search with an asterisk, so the order here is totally random...

**Comment by totallymike** [comment]
Correct.  Which calls back to my original question, where I suspect @npearson72 is using a query which is susceptible to the same behavior.

**Comment by totallymike** [comment]
Though @npearson72 is correct where relevancy should come into play.  I think you are right, @karmi, that we need to see a search body

**Comment by npearson72** [comment]
@totallymike Yes, that's exactly what's happening.

Here's the code for my search:

This is in the products controller:

```
  def index
    @products = Product.search(**search_params)
  end

  def search_params
    params.slice(:query, :features, :category_id).deep_symbolize_keys
  end
````

This is my query:

````
    def search(query: nil, features: nil, category_id: nil)
      @query       = query
      @features    = features
      @category_id = category_id

      build_search_query

      .... (omitted irrelevant methods)

      search_results = __elasticsearch__.search(search_params) and reset_search
      search_results
    end

    def search_params
      @search_params ||= {
        query: { filtered: { query: { match_all: {} }, filter: { and: [] } } },
        filter: { range: { quantity: { gt: 0 } } },
        size: 100
      }
    end

    def build_search_query
      if query
        search_params[:query][:filtered][:query] = {
          bool: {
            should: [
              {
                multi_match: {
                  query: query,
                  type: :cross_fields,
                  fields: [:name, :categories, :feature_values, :description],
                  operator: :and
                }
              }
            ]
          }
        }
      end
    end

````

Does this help?

**Comment by totallymike** [comment]
I think so.  Have you looked at the scores of the documents yielded by the search?

**Comment by karmi** [comment]
@npearson72 So you appear to be using the multi_match query on certain fields. The score shouldn't take into account any "updated" information from the documents. You have to check the scores, and to dig deeper you can use the `explain` parameter for the search definition.

**Comment by npearson72** [comment]
I haven't looked into the scores -- not sure yet what I'd be looking at there as I'm new to ES -- but will check tonight when I get in from work.

What would I want to look for exactly?

**Comment by totallymike** [comment]
My strongest suspicion is that the scores are equal for all the results you can see.

**Comment by npearson72** [comment]
And would the scored change if I added a sort param?

**Comment by karmi** [comment]
@npearson72 When you sort, the score is ignored... I think you should first read the introduction chapters of [Elasticsearch: The Definitive Guide](https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html) so you understand the general concepts and techniques, before you dive into the Ruby part of things...

**Comment by npearson72** [comment]
@karmi Thanks for the resource. I've been grokking through bits and pieces of the documentation along with the template apps (which are great btw). Fortunately I've been able to get things where I need them, and am really pleased with the results, but you're right... I do need to set some time aside to learn some of the basic concepts in a formal way.

Anyway, thanks all for the help. Great gem!

**Comment by npearson72** [comment]
Oh, btw, you guys were right, I just needed to add a default sort param. I set it up so that it's only used when I do match_all query. But if a user actually submits a query value, then I let ES sort by relevancy.

**Comment by karmi** [comment]
@npearson72 That's a fine solution -- I think the one used in the "expert" variant of the example application.
