### ISSUE TITLE
Objects not deleting 

### ISSUE THREAD

**Issue by bcackerman** [elastic/elasticsearch-rails#406]
I'm using Rails 3.2 with elasticsearch-rails and elasticsearch-model 0.1.7

Delete not working locally using include `Elasticsearch::Model::Callbacks`

Any idea why / what's going on?

**Comment by bcackerman** [comment]
Correction, delete not working locally using `include Elasticsearch::Model::Callbacks`

**Comment by karmi** [comment]
I'm afraid a question like that cannot be answered without seeing what's going on in code.

I suggest you try to model the problem you see with the [`activerecord_article.rb`](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/examples/activerecord_article.rb) so we can share a common codebase.

**Comment by bcackerman** [comment]
Ended up adding `after_destroy { |r| __elasticsearch__.delete_document  }` to my model and now the delete function is working

**Comment by karmi** [comment]
@bcackerman Yeah, that's correct, the weird thing is that it basically just does what the automatic `Callbacks` modules is doing, and there's an integration test for that: https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/test/integration/active_record_basic_test.rb#L105-L117

Closing this one if it's OK, let's reopen please if/when we have more info!
