### ISSUE TITLE
Upsert in Elasticsearch::Persistence::Model

### ISSUE THREAD

**Issue by ben-av** [elastic/elasticsearch-rails#409]
Hi,

I'm trying to do an upsert via the persistence model, is it possible or I have to first find a record then increment the values? 

Thanks,
Ben

**Comment by karmi** [comment]
> is it possible or I have to first find a record

A bit confused -- normally you need to find the model instance to be able to use the persistence methods like `update_attributes`, `increment`, etc? See docs at http://www.rubydoc.info/gems/elasticsearch-persistence#Persistence

**Comment by ben-av** [comment]
Hi Karmi,

I'm referring to this capability of elasticsearch(https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#upserts).
Basically what I need is to update counters and create a record if it doesn't exist yet, upsert does all of that in one request to ES.
If I want to do it from the model, I need to find the record by id(and catch an exception if it doesn't exist), then increment the values?

**Comment by karmi** [comment]
Right, understood. So, if you wanna use the `ActiveRecord` pattern, then in accordance with that pattern, you need to find the record, and execute methods on it.

Of course, you can always "drop down a level", and use the "raw" Ruby API to perform the [`update`](http://www.rubydoc.info/gems/elasticsearch-api/Elasticsearch/API/Actions#update-instance_method) action, using scripts, upserts, etc.

Lastly, the `Repository` pattern of `elasticsearch-persistence` allows you to use the [`update`](http://www.rubydoc.info/gems/elasticsearch-persistence#Storage) method, which is performed on the repository...

So, everything depends on what is best in the context of the application. If you enjoy the `ActiveRecord` pattern and everything which comes with it (Rails views integration and so on), it might make sense to implement something like `MyModel.increment(id)` method, which would wrap either the Repository method or the low level client method -- you can always access the client as `MyModel.__elasticsearch__.client` -- the README for `elasticsearch-persistence` has all the details.

**Comment by ben-av** [comment]
Great, thanks @karmi .
MyModel.__elasticsearch__.client doesn't work for me, however MyModel.gateway.update works great.

**Comment by karmi** [comment]
...that's because I'm too confused by context switching :), it's `Elasticsearch::Persistence.client` in the "elasticsearch-persistence" gem of course. But using the gateway is actually even better. Closing the ticket if it's OK.

**Comment by ben-av** [comment]
Great, thanks for the help!
