### ISSUE TITLE
Elasticsearch::Model::Response::Result: Problem while accessing association key

### ISSUE THREAD

**Issue by nitinstp23** [elastic/elasticsearch-rails#410]
Hi,

I have a `Product` model which belongs to a `Store`.
Below is the `as_indexed_json`  method -

``` ruby
  def as_indexed_json(options = {})
    as_json(
      only: [:title, :store_id, :base_price, :discount],
      include: {
        store: { only: [:name] }
      }
    )
  end
```

Now when i do `Product.search({}).results.first.store`

I get this error - 

``` ruby
ArgumentError: wrong number of arguments (0 for 2)
    from /home/nitin/.rvm/gems/ruby-2.2.2@mobmerry --create/gems/elasticsearch-model-0.1.7/lib/elasticsearch/model/response/result.rb:39:in `store'
    from /home/nitin/.rvm/gems/ruby-2.2.2@mobmerry --create/gems/elasticsearch-model-0.1.7/lib/elasticsearch/model/response/result.rb:39:in `method_missing'
```

But this works - `Product.search({}).results.first._source[:store]`

The reason this is happening because `Elasticsearch::Model::Response::Result` class stores search results in `@result` variable which is an instance of `Hashie::Mash` which inherits from ruby `Hash` class and ruby `Hash` implements a `:store` method, which is what getting called on the result object and not the `store` association which i have defined in my `Product` model.

**I know that renaming my association name will resolve this issue, 
but i am asking if there is a better way to address this.**

Thanks

**Comment by jaymanklu** [comment]
:+1:

**Comment by estolfo** [comment]
@nitinstp23 Is this still an issue for you or can we close this? I would recommend not using an attribute `store` on your Product model.

**Comment by nitinstp23** [comment]
@estolfo It was a long back when I reported this. 😄 

_I'm not working with ruby and have no context whether the issue still persists._

You can close this if its not relevant anymore. 👍

**Comment by estolfo** [comment]
ok, thanks for letting me know @nitinstp23
