### ISSUE TITLE
How to eager load associations before importing ?

### ISSUE THREAD

**Issue by Uelb** [elastic/elasticsearch-rails#418]
Hi,

My import tasks can take a really long time and I was wondering if I could eager load the associated models in order to increase the speed.

**Comment by karmi** [comment]
I think you should be able to do that via a query passed to the import method, please see the documentation, https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model/importing.rb#L73
