### ISSUE TITLE
search changes after reload

### ISSUE THREAD

**Issue by mustmodify** [elastic/elasticsearch-rails#419]
Very strange behavior that I'm having a difficult time nailing it down. After the app starts up, search works one way and then, mysteriously, adds an index that, as far as I know, isn't set anywhere. I'm wondering if you guys have any thoughts as to why this might be happening.

Stack: Rails 4.2, puma, rbx
gems:
elasticsearch 1.0.9
elasticsearch-api 1.0.9
elasticsearch-transport 1.0.9
elasticsearch-model 0.1.7
elasticsearch-rails 0.1.7

I hit the searches#show controller via AJAX (or ... actually ... AJAJ but whatever.)

When I restart the server and search for 'auc' I get the expected result for a Person with name "Kevin Aucain". From the log entry.

```
Started GET "/search.json?search[term]=auc" for 127.0.0.1 at 2015-06-08 13
Processing by SearchesController#show as JSON
  Parameters: {"search"=>{"term"=>"auc"}}
  ... snip ...
  #<Elasticsearch::Model::Multimodel:0x42388> Search (11.1ms) {index: [], type: [], body: {"query"=>{"filtered"=>{"query"=>{"bool"=>{"should"=>[{"match_phrase_prefix"=>{"_all"=>"auc"}}, {"query_string"=>{"query"=>"auc"}}, {"fuzzy_like_this"=>{"like_text"=>"auc", "fuzziness"=>"AUTO", "boost"=>0.5}}]}}}}}}
Completed 200 OK in 23ms (Views: 1.1ms | ActiveRecord: 3.7ms | Elasticsearch: 11.1ms)
```

When I reload the page ( which has what effect? Should have none on the search model or controller... ) I stop getting that result. New log entry:

```
Started GET "/search.json?search[term]=auc" for 127.0.0.1 at 2015-06-08
Processing by SearchesController#show as JSON
  Parameters: {"search"=>{"term"=>"auc"}}
  ...snip...
  #<Elasticsearch::Model::Multimodel:0x49cf4> Search (4.4ms) {index: ["organizations"], type: ["organization"], body: {"query"=>{"filtered"=>{"query"=>{"bool"=>{"should"=>[{"match_phrase_prefix"=>{"_all"=>"auc"}}, {"query_string"=>{"query"=>"auc"}}, {"fuzzy_like_this"=>{"like_text"=>"auc", "fuzziness"=>"AUTO", "boost"=>0.5}}]}}}}}}
Completed 200 OK in 13ms (Views: 0.2ms | ActiveRecord: 3.1ms | Elasticsearch: 4.4ms)
```

Notice that the 'index' parameter changed. I have no idea why. I have searched my codebase and can't find any reason for it to have switched.

Search model:

```
class Search < Valuable
  has_value :term

  def results(options = {page: 1})
    complex_search_a.results
  end

  def complex_search_a
    query = Elasticsearch::Model.search(
            {
              "query"=> {
                "filtered"=> {
                  "query"=> {
                    "bool"=> {
                      "should"=> [
                            {
                                "match_phrase_prefix"=> {
                                    "_all"=> term
                                }
                            },
                            {
                                "query_string"=> {
                                    "query"=> term
                                }
                            },
                            {
                                "fuzzy_like_this"=> {
                                    "like_text"=> term,
                                    "fuzziness"=> "AUTO",
                                    "boost"=> 0.5
                                 }
                            }
                      ]
                    }
                  }
                }
              }
            }
    )
  end
end
```

controller:

```
class SearchesController < ApplicationController
  def new
    @search = Search.new
  end

  def show
    @search = Search.new( local_params )
    @results = @search.results

    respond_to do |format|
      format.html { render :action => 'show' }
      format.json { render :json => {results: @results} }
    end
  end
```

and the models:

```
class Organization < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  def as_indexed_json(stuff= nil)
    {
      name: self.name,
      dba: self.dba,
      uri: "/organizations/#{self.id}",
      description: '',
    }
  end
end
```

```
class Person < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  def as_indexed_json(stuff= nil)
    {
      name: self.name,
      uri: "/people/#{self.id}",
      description: self.organization.try(&:name),
    }
  end
```

**Comment by karmi** [comment]
Hi, so the important thing is that this is a multimodel search (`Elasticsearch::Model.search`) in your model method. Another important thing is that you're using Puma, which uses threads, and you might have hit some kind of issue with thread safety in the multi-model search implementation.

I'd start isolating the problem with these approaches:

1. Turn on the logging or tracing in the client (see `elasticsearch-transport` documentation), so we can see what exact HTTP request is sent to Elasticsearch. Please paste the relevant parts of the output here.

2. Try the exact thing in a non-thread-based server, such as Thin (probably locally, since I assume this is Heroku?).

3. Try a single-model search (`MyModel.search`), to see if the issue stays.

Can you try that and get back? Please ping me if I don't respond in timely manner :)

**Comment by miguelff** [comment]
One thing that can be happening is that model classes are not being eagerly loaded in your environment (check `config.eager_load_paths`) 

As you are doing the multimodel seach without explicitly specifying in which models to search., `Elasticsearch::Multimodel` [is inferring the models to search](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model/multimodel.rb#L55) based on the [current classes that are loaded which include `ElasticSearch::Model`](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model.rb#L127)

This will explain that among restarts, if there are any operations that cause the load of app/models, at different points in time, the results of doing a search can be different, as at those times, there are different models loaded.

I would suggest:
1) to [not forget to define eager_load_paths](http://blog.arkency.com/2014/11/dont-forget-about-eager-load-when-extending-autoload/).
2) [to explicitly specify in which models to do the multimodel search](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model.rb#L127), if we cannot be sure that the models we want to search into, are always loaded.

Can you please check my hypothesis?

**Comment by karmi** [comment]
++ for what @miguelff says

**Comment by inska** [comment]
Hi @karmi,

I am using Puma too, and trying to stress test rails app with Elasticsearch and got a lot of 500 errors, and it turns out thread safety problem. when setting puma threads count as 1, any problem occurs but when threads count is over then 1, rails app returns 500 error. 

In this case, how can I approach to fix this problem? should I drop Puma for ES?

Best,
Inska

**Comment by estolfo** [comment]
[This section](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-and-sti) in the Rails documentation describes exactly this scenario. Please follow the advice in the Rails documentation and above for suggestions for how to get around this gotcha.
