### ISSUE TITLE
Getting {"error":"IndexMissingException[[default] missing]","status":404} for elastic search laravel

### ISSUE THREAD

**Issue by chandravanshialok** [elastic/elasticsearch-rails#425]
Hi, I need to integrate elastic search with laravel and mongodb to search at various places.
please suggest the best solution or any working example.
Do i need to use https://github.com/shift31/laravel-elasticsearch

While practicing with laravel elasticsearch I am getting above when installing https://github.com/tonysm/laravel-elasticsearch-test on my local on ubuntu. I were getting error ' Failed connect to localhost:9200; Connection refused' , then I followed
'Install Elasticsearch' section of http://www.atfelt.com/technology/ubuntu-enviroment-useful-commands link, now I am getting {"error":"IndexMissingException[[default] missing]","status":404}

@jarib @ph  
@andrew 
@colinsurprena
@rsutphin 

Thanks.

**Comment by jeteon** [comment]
This is not a PHP repo and its not the base Elasticsearch repo either. This repo is specifically about a Ruby on Rails integration for Elasticsearch. Perhaps the repo you linked to since it mentions both Laravel and Elasticsearch which is closest to what you seem to be looking for.
