### ISSUE TITLE
Elasticsearch Transport Error

### ISSUE THREAD

**Issue by moonmalinowska** [elastic/elasticsearch-rails#431]
Hi! I have a problem with configuration of elasticsearch-transport. 
I am trying to upload my rails application on the server but somehow it doesn't work...
First I had problems with faraday connection error, so created the file elasticsearch.rb in config/initializers and placed: Elasticsearch::Model.client = Elasticsearch::Client.new host: 'host name'.
Now, I am still getting error, but this time: Elasticsearch::Transport::Transport::Errors::NotFound.

It's my first rails application I am trying to upload on server, I searched over about this issue but couldnt find any ways of solving the problem that would work for my app. If possible please explain me step-by-step what I should do.

Thanks in advance!

**Comment by estolfo** [comment]
I'm going to close this as I doubt it's still relevant, looking at the timestamp. Please comment if it's still an issue.
