### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass when trying to get only some fields

### ISSUE THREAD

**Issue by Coren** [elastic/elasticsearch-rails#433]
Hi,

Let's say we have a model MyModel 

``` ruby
class MyModel
  include Elasticsearch::Persistence::Model
end
```

and a filter f:

``` ruby
   f = { filter: { term: { XXX: YYYY } } }
```

Search "classic"  works fine. 

``` ruby
   query = {
      query: { filtered: f }
    }
    MyModel.search query
```

Search on generic fields works fine:

``` ruby
   f = { filter: { term: { XXX: YYYY } } }
   query = {
      query: { filtered: f },
      fields: [ 'id', 'content' ]
    }
    MyModel.search query
```

Search on specific fields:

``` ruby
   f = { filter: { term: { XXX: YYYY } } }
   query = {
      query: { filtered: f },
      fields: [ 'id' ]
    }
    MyModel.search query
```

You get this error when you try to iterate over them:

``` ruby
NoMethodError: undefined method `[]' for nil:NilClass
    from /var/lib/gems/2.1.0/bundler/gems/elasticsearch-rails-ded203569208/elasticsearch-persistence/lib/elasticsearch/persistence/model/base.rb:12:in `initialize'
    from /var/lib/gems/2.1.0/bundler/gems/elasticsearch-rails-ded203569208/elasticsearch-persistence/lib/elasticsearch/persistence/model.rb:103:in `new'
    from /var/lib/gems/2.1.0/bundler/gems/elasticsearch-rails-ded203569208/elasticsearch-persistence/lib/elasticsearch/persistence/model.rb:103:in `deserialize'
    from /var/lib/gems/2.1.0/bundler/gems/elasticsearch-rails-ded203569208/elasticsearch-persistence/lib/elasticsearch/persistence/repository/response/results.rb:68:in `block in results'
    from /var/lib/gems/2.1.0/bundler/gems/elasticsearch-rails-ded203569208/elasticsearch-persistence/lib/elasticsearch/persistence/repository/response/results.rb:67:in `map'
    from /var/lib/gems/2.1.0/bundler/gems/elasticsearch-rails-ded203569208/elasticsearch-persistence/lib/elasticsearch/persistence/repository/response/results.rb:67:in `results'
    from /var/lib/gems/2.1.0/bundler/gems/elasticsearch-rails-ded203569208/elasticsearch-persistence/lib/elasticsearch/persistence/repository/response/results.rb:26:in `method_missing'
    from (irb):3
    from /var/lib/gems/2.1.0/gems/railties-4.2.1/lib/rails/commands/console.rb:110:in `start'
    from /var/lib/gems/2.1.0/gems/railties-4.2.1/lib/rails/commands/console.rb:9:in `start'
    from /var/lib/gems/2.1.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:68:in `console'
    from /var/lib/gems/2.1.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /var/lib/gems/2.1.0/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
    from ./bin/rails:4:in `require'
    from ./bin/rails:4:in `<main>
```

It seems to come from _lib/elasticsearch/persistence/model.rb_, where object is built from '_source' field, which can be nil for some kind of search

``` ruby
   def deserialize(document)
       object = klass.new document['_source']
   [...]
```

**Comment by Coren** [comment]
For the record, one can workaround this by using directly raw results. For instance, this call
```ruby
MyModel.search(query).response['hits']['hits'] 
```
gives an array of results, using [Hashie](http://www.rubydoc.info/github/intridea/hashie/Hashie/Mash) class.

**Comment by makarchuk** [comment]
I thing this line not needed

**Comment by makarchuk** [comment]
Found you workaround very useful, since I faced same problem. 

Can't we just edit initialize method here(https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/lib/elasticsearch/persistence/model/base.rb#L11) like this? 
```
def initialize(attributes={})
  attributes ||= {}
  @_id = attributes[:id] || attributes['id']
  super
end
```

I think it will solve problem without any consequences

**Comment by Coren** [comment]
Probably, yes.

Keep in my mind that this workaround is far quicker than "normal" model association. 

When I (sadly) needed to get 1k items within a single request, this workaround helped me to go from 1s to 0.2s.

**Comment by makarchuk** [comment]
Actually find out that it will not work since if fields specified response contain "fields" field  instead of "_source"
And if you use it elastic puts values in array like this 
``` 
        "fields": {
          "src_ip": [
            "127.0.0.1"
          ]
```
So I create a fix https://github.com/makarchuk/elasticsearch-rails/commit/ba458f42962c0e3bb26d614c45ded71bea122611

But later I find trouble since if field I have no way to know if field is supposed to be array. 

The best I can think of is check length, but if value supposed to be an array with single element -- it will fail and I can't do anything about it

**Comment by jogaco** [comment]
Same problem here. If there is a very long description field that its only needed to see the item details, it should be possible to query for only id and title fields to get a list of items.

The access to raw results are a real pain:
```
res.response.hits.hits[0].fields.format[0]
res.response.hits.hits[0].fields.title[0]
```
assuming that format is just an Integer field and title is just a String.

**Comment by jogaco** [comment]
@makarchuk : haven't checked but wouldn't be possible in your fix to check the model metadata to see if a field is an array?

**Comment by makarchuk** [comment]
yeah Actually it's possible through 
```
ModelName.attribute_set['timestamp'].type
```

It returns (yeah in my model timestamp IS array, I know it's weird)
```
Axiom::Types::Array (Array)
```
In case of array.
I probably will fix it in a  weekend and update my pull request

**Comment by jogaco** [comment]
Great!

**Comment by makarchuk** [comment]
Okay, guys, sorry for being suck a lazy person. Finally submited pull request https://github.com/elastic/elasticsearch-rails/pull/461

In addition to problem we talked about solve one more minor 

When you calling for nested fields json in response not nested hashes, but dot-sparated fields 
``` 
        "fields": {
          "src_geoip.country_code2": [
            "RU"
          ]
        }
```

So I split field name and hope that user used mapping from example (https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/examples/music/album.rb#L1)

**Comment by jogaco** [comment]
@makarchuk : I have tried your fork https://github.com/elastic/elasticsearch-rails/pull/461 and it seems to work well.

**Comment by jogaco** [comment]
@makarchuk : I have hit a couple of problems with your fix:
 
- does not work for Float

- does not work for an object with fields

I'm trying to figure out what the problem is.

**Comment by jogaco** [comment]
@makarchuk I was mistaken: only affects to arrays of objects with fields. Will try to investigate further.
