### ISSUE TITLE
How to configure analyser/tokeniser to search for terms with space?

### ISSUE THREAD

**Issue by mingc** [elastic/elasticsearch-rails#434]
How to configure analyser/tokeniser to search for terms with space?

For example, a filter search like ("b b"):
{"query":{"filtered":{"query":{"match_all":{}},"filter":{"and":[{"term":{"external_shipping_status":"b b"}}]}}}}

Above search could not find the document because the string has a space in it.

Any advice on how to set the right analyser would be helpful. Thanks in advance.

**Comment by mingc** [comment]
It seems one way is to not analyze it

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :external_shipping_status, index: :not_analyzed
    end
  end

**Comment by Coren** [comment]
I can confirm that

**Comment by karmi** [comment]
With `filter`, no analysis will be performed. So either use a query, or set the field to not analyzed eg. with `analyzer: "keyword"`. The examples in this repository give plenty of concrete cases for this.

**Comment by mingc** [comment]
Thanks Karmi. 

>The examples in this repository give plenty of concrete cases for this.
Can you please paste the links related to this area? Thanks.
