### ISSUE TITLE
namespacing indexes per environment?

### ISSUE THREAD

**Issue by mustmodify** [elastic/elasticsearch-rails#439]
I have two versions of the same application running on a server: staging and production. It seems that results are colliding. Is there a way I can have Elasticsearch namespace these based on the environment so they won't collide? Or do I need to run two different elasticsearch servers? [ I ask because it's already using up 14% of my 2gb server so... :) ]

**Comment by gmartsenkov** [comment]
You probably can, I have only seen it in a Rails project but that shouldn't really matter.
this is the code -> index_name [Rails.env, 'questions'].join('_')

**Comment by mustmodify** [comment]
@gmartsenkov so does this go in the model?

```
class Person < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  index_name [Rails.env, 'people']

  def as_indexed_json(stuff= nil)
    {
      name: self.name,
      uri: "/people/#{self.id}",
      description: self.organization.try(&:name),
    }
  end
```

And then is this the correct way to include those index names in my query?

```
    query = Elasticsearch::Model.search(
            {
              "indices" : [
                     [Rails.env, 'people'].join('_'),
                     [Rails.env, 'places'].join('_'),
                     [Rails.env, 'things'].join('_'),
              ],
              "query"=> {
                "filtered"=> {
                  "query"=> {
                    "bool"=> {
                      "should"=> [
                            {
                                "match_phrase_prefix"=> {
                                    "_all"=> term
                                }
                            },
                            {
                                "query_string"=> {
                                    "query"=> term
                                }
                            },
                            {
                                "fuzzy_like_this"=> {
                                    "like_text"=> term,
                                    "fuzziness"=> "AUTO",
                                    "boost"=> 0.5
                                }
                            }
                        ]
                          }
                      }
                  }
              }
            }
    )

```

**Comment by gmartsenkov** [comment]
I have currently a lot less configuration.Hope this gives you an idea of how it should work.On whatever model you include Elasticsearch:Model/Callbacks you can call #search(query).

This is my model:
```ruby
include Elasticsearch::Model
include Elasticsearch::Model::Callbacks
index_name [Rails.env, 'questions'].join('_')
```
And the controller:
```ruby
def search(query)
    @questions = Question.search(query).records
  end
```

Hope that helps

**Comment by mustmodify** [comment]
@gmartsenkov Ah, I hate having that much configuration. I'm doing a multi-model search, which seems to be why it is necessary.

**Comment by gmartsenkov** [comment]
@mustmodify i've just noticed that you are not calling #split("_") when you're indexing in the model as i do.

**Comment by lostapathy** [comment]
One thing I've done to simplify this is to use an ActiveSupport::Concern, such as:

```ruby
module Searchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model
    index_name [Rails.env, model_name.collection].join('_')
  end
end
```
and then inside each indexed model

```ruby
  include Searchable
```

That at least centralizes the naming logic and reduces how much it leaks into your models.

Did you have any other questions or can this be closed?
