### ISSUE TITLE
Checklist for New Features

### ISSUE THREAD

**Issue by dskvr** [elastic/elasticsearch-rails#442]
(1) When adding or modifying functionality that affects other developers, _always update the readme_
(2) If you've included functionality that requires that a new process is ran, the app should be _configured for development, staging and production_ environments, and should run that process without any extra work on the developer's behalf; vagrant and capistrano, for example. _This lower's the bar for other developers to merge and work on your feature! and eliminates confusion, saving time overall!_

**Comment by estolfo** [comment]
Closing this as the mentioned best practices are taken into account. Thanks!
