### ISSUE TITLE
Elasticsearch::Transport::Transport::Errors::NotFound when destroying a model instance, but data *is* being removed from the index.

### ISSUE THREAD

**Issue by xxx** [elastic/elasticsearch-rails#447]
Hi,

I'm running into this issue when I destroy an ActiveRecord model instance. I've inspected the data in the ES index before, and after the destroy, and it *is* being removed as expected from the media-development index, so I'm not sure why I'm getting this exception. I'm completely baffled right now.

I've put up a full stack track at https://gist.github.com/xxx/9254a4a806a875858a7a

**Comment by sumitngupta** [comment]
+1

**Comment by xxx** [comment]
This is resolved. `Elasticsearch::Model::Callbacks` was included in both the parent and child class, leading to duplicate callback registrations
