### ISSUE TITLE
Article model missing at '03-expert.rb'

### ISSUE THREAD

**Issue by briandiaz** [elastic/elasticsearch-rails#449]
Hi,

Trying to create a new rails app with the template '03-expert.rb' it fails because 'models/article.rb' file is missing.

I know we have to follow a sequence of templates but why dont just add a file where the expert perks are just in one file.

Greetings

**Comment by Agowan** [comment]
Hi, I had the same problem, is there any solutions to this problem at all? Such as a workaround?

Regards

**Comment by sk187** [comment]
I initially had the same problem.

If you clone 1 and then 2 and then 3 it works kinda. I am getting a 
[404] {"error":"IndexMissingException[[searchapp_application_development] missing]","status":404}

**Comment by karmi** [comment]
Hi, I've added checks for the template run order in eab4058.

> (...) but why dont just add a file where the expert perks are just in one file.

Because that would mean somehow duplicating all the commands in the previous two. I don't think running the templates one after another is that much of an inconvenience?
