### ISSUE TITLE
`update` does not use setters before persisting to ES

### ISSUE THREAD

**Issue by natematykiewicz** [elastic/elasticsearch-rails#450]
A `create` will coerce values using Virtus because `initialize` will coerce, and `save` will use `self.attributes`.

`update` does not read from `self.attributes`, but instead just sets the values in ES, and then updates the object's `self.attributes` after the save successfully occurs. This means that any custom coercion done with Virtus doesn't take effect when using `update`.

(reference: https://github.com/elastic/elasticsearch-rails/blob/v0.1.7/elasticsearch-persistence/lib/elasticsearch/persistence/model/store.rb#L115)

**Comment by natematykiewicz** [comment]
This problem is a lot worse than I originally realized because it doesn't take ANY setters into account. It just blindly sets the values in ES to what the user passed in, regardless of whether there's an attribute defined for it or not.

This is a real problem, especially when using has_secure_password.
Calling `member.update(:password => 'foo')` will store, the unencrypted password field and value in ES, when it should be storing password_digest.

The update method should only allow you to change defined attributes, and be smart enough to realize that after updating attributes, the password_digest attribute is now dirty.

**Comment by knshiro** [comment]
+1
Due to the same thing it does not check any validation either.

**Comment by k-rudy** [comment]
+1 guys, the issue seems to be there for a long time already and is pretty important, could you please update us if anyone is working on that and what's the ETA for the fix.

**Comment by estolfo** [comment]
Please see my comment [here](https://github.com/elastic/elasticsearch-rails/pull/658#issuecomment-419400259). We have deprecated and removed the `ActiveRecord` pattern in the elasticsearch-persistence gem.
