### ISSUE TITLE
Unicode issue?

### ISSUE THREAD

**Issue by cbetta** [elastic/elasticsearch-rails#454]
I am running elasticsearch within a Rails app. I have a bit of text that includes some Greek words (ΜΕΝΤΟΡΣ) but when I search for it I can't find the entry. I can find the entry by search for other words in the same piece of text, just not by these greek words.

**Comment by whokilledtheelectricmonk** [comment]
This issue is old, but for future reference it sounds more like an issue with the Elasticsearch setup. See: https://www.elastic.co/guide/en/elasticsearch/guide/current/unicode-normalization.html

**Comment by karmi** [comment]
@cbetta This is really weird -- I can index and search for Greek words just fine:

```ruby
client.index index: 'greek', type: 'doc', body: { text: 'ΜΕΝΤΟΡΣ' }
# => {"_index"=>"greek", "_type"=>"doc", "_id"=>"AVDSbiCpHGnZLq92Quvy", "_version"=>1, "created"=>true}

# client.search index: 'greek', body: { query: { match: { text: 'ΜΕΝΤΟΡΣ' }  } }
# => {"took"=>30,
#  "timed_out"=>false,
#  "_shards"=>{"total"=>5, "successful"=>5, "failed"=>0},
#  "hits"=>
#   {"total"=>1,
#    "max_score"=>0.30685282,
#    "hits"=>[{"_index"=>"greek", "_type"=>"doc", "_id"=>"AVDSbiCpHGnZLq92Quvy", "_score"=>0.30685282, "_source"=>{"text"=>"ΜΕΝΤΟΡΣ"}}]}}

client.search index: 'greek', body: { query: { match: { text: 'ΜΕΝΤΟΡΑΣ' }  } }
# => {"took"=>2, "timed_out"=>false, "_shards"=>{"total"=>5, "successful"=>5, "failed"=>0}, "hits"=>{"total"=>0, "max_score"=>nil, "hits"=>[]}}
```

I apologize for such a silly delay, many issues accumulated over summer when I was out. Is this still an issue for you?

**Comment by cbetta** [comment]
Honestly this ticket is so old I dont remember the issue anymore. I think I resolved it already. Apologies for the open issue.

**Comment by karmi** [comment]
@cbetta, my apologies for the delay!, and please ping via the issue in -ruby or -rails repo in case of questions -- it is the right channel.

**Comment by cbetta** [comment]
Cool no worries
