### ISSUE TITLE
How to set null_value in mapping?

### ISSUE THREAD

**Issue by Draqun** [elastic/elasticsearch-rails#458]
Hi.

When I read documentation I found parameter null_value

https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-core-types.html

```
When there is a (JSON) null value for the field, use the null_value as the field value. Defaults to not adding the field at all.
```

I want use it because sort option always put records with null on the end of list. I tried do it in this way, but it didn't work.

```
  settings do
    mapping _all: {} do
      indexes :source_server, type: :string, null_value: ""
      indexes :source_server_agent_number, type: :integer, null_value: 0
    end
  end
```

Any help would be appreciated.
Best regards.

**Comment by zaziemo** [comment]
@karmi I have the same problem. How can we deal with null_values using this gem?

**Comment by Draqun** [comment]
Sorry but I don't remember, and cannot check it in source code. Is possible I never found solution. Cannot help so again sorry and good luck.

**Comment by BriocheBerlin** [comment]
Hi @karmi, do you think passing null_value will be implemented any time soon? Thanks!

**Comment by karmi** [comment]
Hi, I did some experimenting with it, and this _does_ work:

```ruby
mapping do
    indexes :title, type: 'keyword', null_value: 'NOTHING'
  end
```

But it doesn't work for the `text` type (an _analyzed_ type in Elasticsearch), which is the default for the `indexes` method.

So, @zaziemo and @BriocheBerlin, it _would_ work, if you'd explicitely set the field to be the `keyword` type, like in that example.

But the larger question is, in what case do you actually need this? Isn't it better to supply "null" values in the property, and then use the ["missing"](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-exists-query.html#_literal_missing_literal_query) query/filter to get those documents?

@Draqun, many apologies for completely missing your question :(, I can see you've sent it in August, when I was offline, and it got lost in the fray of dozens of questions opened over the month... I hope you have solved it somehow. Sorry again!

**Comment by Draqun** [comment]
@karmi

No problem. I finished with RoR. I hate languages with single inheritance. I prefer Python and C++ :)

Best regards.

**Comment by zaziemo** [comment]
Hi @karmi,

thanks for your quick response.
We are still working with v 2.4 and are using the type: ‚completion’ because we use it in the context of a suggest field. Probably it doesn’t work with this type?

To explain the larger context: we have a database of speakers who can list their profile details in different languages, e.g. their main topic of expertise. Most of them only have one language so some fields remain empty. On indexing things break:  not only does the empty field not get indexed, instead the whole profile it belongs to doesn’t get indexed and  I still get the error
`MapperParsingException[completion field [main_topic_en.suggest] does not support null values]`
So probably, `null_values` might not be the way to go but the "missing" query/filter is only a solution in the process of querying. But we already have to fix our problem during indexing. Do we miss something? Thanks for your help!

**Comment by karmi** [comment]
> We are still working with v 2.4 and are using the type: ‚completion’ because we use it in the context of a suggest field. Probably it doesn’t work with this type?

Yes, @zaziemo, that is what I see as well now on `2.4.0` when I try it.

Thanks for the details — I understand now how the `null_value` would be attractive there. I was playing with the [bundle `activerecord_mapping_completion.rb` example](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/examples/activerecord_mapping_completion.rb), and when the `title` attribute of the model is empty, I'm getting the `completion field [title.suggest] does not support null values` error.

I think the only solution is to put the "protective" logic inside the indexing layer, and remove the empty property in the `MyModel#as_indexed_json` method, even something simple like should work:

```ruby
mapping do
  indexes :title_suggest, type: 'completion'
end

# ...

def as_indexed_json(options={})
    output = as_json
    output.delete 'suggest' unless self.suggest.present?
    output.merge 'url' => "/articles/#{id}"
  end
```

(If the project is open source, don't hesitate to ping me there!)

**Comment by zaziemo** [comment]
@karmi thanks a lot. With your hint and a little help of @svenfuchs I got it working using the select method `output.select{ |key, value| value.present? }`

**Comment by estolfo** [comment]
Closing as the issue seems to have been resolved.
