### ISSUE TITLE
Update api support is missing params

### ISSUE THREAD

**Issue by eric-pigeon** [elastic/elasticsearch-rails#459]
You can't pass doc_as_upsert or scripted_upsert in the body of update.

**Comment by estolfo** [comment]
I'm going to close this because you can pass those options as the body field:
```ruby
client.update(index:'name', id: 1, body: { doc_as_upsert: true } )
```

or as an option to the method on a repository object:
```ruby
repository.update(id, doc: { text: 'testing_2' }, doc_as_upsert: true)
```
