### ISSUE TITLE
Custom type name with analyzer in the mapping

### ISSUE THREAD

**Issue by lowski** [elastic/elasticsearch-rails#462]
Hi,
I have a question about `document_type` method. If I specify analyzer for attribute mapping and I also modify `document_type` the analyzer is not set.

``` ruby
class MyModel
  include ElasticSearch::Persistence::Model

  index_name "my_model_index"

  document_type "type"
  attribute :name, String, mapping: { analyzer: "my_custom_analyzer" }
end
```

When I create a item `MyModel.create({ name: "Sample name" })` and I send request to ES `GET /my_model_index/type/_mapping` then I receive:

``` json
{
   "my_model_index": {
      "mappings": {
         "type": {
            "properties": {
               "created_at": {
                  "type": "date",
                  "format": "dateOptionalTime"
               },
               "name": {
                  "type": "string"
               },
               "updated_at": {
                  "type": "date",
                  "format": "dateOptionalTime"
               }
            }
         }
      }
   }
}
```

Without modifying `document_type` it works correctly and mapping is set as it should be.

Is there any other way to specify type name?

**Comment by rafaltrojanowski** [comment]
Ihmo it should works.

What returns:

```
YourModel.mapping.to_hash
```

Did you try?

YourModel.gateway.delete_index!
YourModel.gateway.create_index!
YourModel.gateway.refresh_index!

before create object?
