### ISSUE TITLE
Rename public API `__elasticsearch__`

### ISSUE THREAD

**Issue by SergXIIIth** [elastic/elasticsearch-rails#471]
From my view it not best code `@acticle.__elasticsearch__.index_document`. 
I think make sense to rename `__elasticsearch__` to something more readable.

**Comment by rosswilson** [comment]
+1

**Comment by karmi** [comment]
In my opinion the need to use the `__elasticsearch__` proxy is quite limited -- most methods are exposed via the regular namespace. 

The main motivation to use a name like that was to be 100% sure we don't interfere with any `.elasticsearch` (or `.es` or whatever else) method defined by the user in the model. I'd rather pay the price with a slight discomfort in the method name, than force users to change their namespace.

Moreover, if you'd prefer to call the method as `elasticsearch`, it's one line of code in your model:

```ruby
alias elasticsearch __elasticsearch__
```

What do you think?

**Comment by whokilledtheelectricmonk** [comment]
IMO since most of the other available methods on a Model---there over over 1000 when you tab-complete in a rails console---aren't namespaced, it makes sense to have the `__elasticsearch__` clearly delimited to protect against conflicts and ambiguity (import and search are the main source of this).

**Comment by karmi** [comment]
@SergXIIIth @rosswilson Any news here?

**Comment by SergXIIIth** [comment]
@karmi well, I agree with you re `alias elasticsearch __elasticsearch__`. But still think if method is mention in documentation it should be named properly - http://www.rubydoc.info/gems/elasticsearch-model/#The___elasticsearch___Proxy.

What about `Article.elastic_proxy.client = Elasticsearch::Client.new host: 'api.server.org'`?

**Comment by karmi** [comment]
I like `__elasticsearch__` :)

**Comment by rosswilson** [comment]
```
In my opinion the need to use the __elasticsearch__ proxy is quite limited -- most methods are exposed via the regular namespace.
```

If the above statement is true, then my motivation to get the proxy renamed to something "more ruby like" is lessened. I do like the propsal for `elastic_proxy`.

**Comment by karmi** [comment]
I like `__elasticsearch__` since there's almost 0% probability of it clashing with something else (vs. e.g. simply `elasticsearch`). I don't like `elastic_proxy`, since that's just describes the technical implementation, not the "thing". For example, `Article.elastic_proxy.client` feels really, really weird to me.

**Comment by estolfo** [comment]
Closing as this discussion is quite old.
