### ISSUE TITLE
Kaminari Pagination with MultiModel Search

### ISSUE THREAD

**Issue by rkrdo** [elastic/elasticsearch-rails#476]
This is related to #382 
Using the code from master, I'm trying to make a MultiModel Search:
(`Elasticsearch::Model.search('search term', [User, Admin]).page(params[:page]).records`)

And that works fine, however, when trying to use Kaminari's `paginate` helper with the **records** collection, I'm getting the following error:

```
NameError - undefined local variable or method `max_pages' for #<Elasticsearch::Model::Response::Records:0x007f99cd59b258>:
   () .../bundler/gems/elasticsearch-rails-ded203569208/elasticsearch-model/lib/elasticsearch/model/response/records.rb:58:in `method_missing'
  kaminari (0.16.3) lib/kaminari/models/page_scope_methods.rb:27:in `total_pages'
  kaminari (0.16.3) lib/kaminari/helpers/action_view_extension.rb:18:in `paginate'
```

I noticed that the Kaminari configuration methods are getting included in `Elasticsearch::Model::Response::Results` but not on `Elasticsearch::Model::Response::Records` (see [model/response/pagination.rb](https://github.com/miguelff/elasticsearch-rails/blob/v0.1.6/elasticsearch-model/lib/elasticsearch/model/response/pagination.rb#L19-L21)), so including the Kaminari methods in `Elasticsearch::Model::Response::Records` fixes my issue.

Is there a reason why those methods don't get included in  `Elasticsearch::Model::Records` ?

**Comment by jonfer** [comment]
I have same problem

**Comment by miguelff** [comment]
@rkrdo , @jonfer, is `kaminari` included in the Gemfile, before `elasticsearch-*`? (some context: https://github.com/elastic/elasticsearch-rails/issues/489, https://github.com/elastic/elasticsearch-rails/issues/487#issue-115380728)

**Comment by jonfer** [comment]
@miguelff Yes

**Comment by jonfer** [comment]
Ok, this commit in Master fixes the problem: https://github.com/elastic/elasticsearch-rails/commit/5f32e484a6d0458f26dc9acfa9dd5fed4e5d6453

**Comment by rkrdo** [comment]
@miguelff yeah, `'kaminari` is included before `elasticsearch-model` and `elasticsearch-rails` in the Gemfile.

I'm using version `0.1.7` BTW, I noticed that `0.1.8` hasn't included the fix for this issue.
Also I'm still wondering why `Elasticsearch::Model::Response::Records` doesn't include `Kaminari::ConfigurationMethods::ClassMethods` (like in [Elasticsearch::Model::Response::Results](https://github.com/miguelff/elasticsearch-rails/blob/v0.1.6/elasticsearch-model/lib/elasticsearch/model/response/pagination.rb#L19) ), that would fix this specific issue.

**Comment by miguelff** [comment]
@rkrdo Yep, actually, `Kaminari::ConfigurationMethods::ClassMethods` is not needed in `Response::Results` either. For that reason, I removed it as part of #524

**Comment by rkrdo** [comment]
@miguelff Ah alright that sounds good, thanks for the reply!

Should I close this issue now or should I wait until the gem's version is bumped?

**Comment by karmi** [comment]
@rkrdo The patch has not been merged yet, I'll amend the commit during merge, so it should appear here, and close the issue.

**Comment by mindtonic** [comment]
Curious as to the status on this patch?

**Comment by miguelff** [comment]
cc @karmi ☝️
