### ISSUE TITLE
query-string TransportError when importing to AWS Elasticsearch

### ISSUE THREAD

**Issue by benwalsh** [elastic/elasticsearch-rails#477]
I'm trying to populate an Elasticsearch instance. Running:

```
RAILS_ENV=some_env_name bin/rake environment elasticsearch:import:model CLASS='SomeModel' SCOPE='my_scope'
```

yields:

```
Elasticsearch::Transport::Transport::Errors::Forbidden: [403] {"message":"When Content-Type:application/x-www-form-urlencoded, URL cannot include query-string parameters (after '?'): '/links/link/_bulk?type=link'"}
```

I found [this document about AES limits](http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-limits.html) and wonder if that's related:

```
The service ignores parameters passed in URLs for HTTP POST requests signed with Signature Version 4.
```

Is there a way around this, if so?

**Comment by benwalsh** [comment]
Seems to be something to do with AWS Version 4 signing. I'm seeing variations of this problem happening for folks on various different AWS services.

**Comment by benmkramer** [comment]
I'm experiencing this issue as well when trying to use AWS Elasticsearch Service.

**Comment by nidalaa** [comment]
@benwalsh  @benmkramer in case it can help you https://github.com/elastic/elasticsearch-ruby/issues/226 (but can be unrelated as well).

**Comment by benwalsh** [comment]
:+1: that looks like the exact issue. Will check it out, thanks!

**Comment by karmi** [comment]
@benwalsh Yes, that's probably the issue, can you please verify if the master version works for you? I'll cut a release soon with accummulated patches.

**Comment by benwalsh** [comment]
@karmi @nidalaa yes, verified with the latest commit from master. Works perfectly! Thanks.

**Comment by nidalaa** [comment]
:+1:

**Comment by cyrill62** [comment]
It work for a public or IP whitelisted AWS elasticsearch endpoint, but not with IAM user credentials.

Somebody know how include AWS signature in headers ?

**Comment by key88sf** [comment]
@cyrill62 @karmi Any ideas on support for AWS-hosted ElasticSearch that has IAM access security? Many of us can't use IP-based restriction or open clusters, so will be forced to signing requests with the AWS signatures.  Would be great if this could be natively supported in the gem.

**Comment by karmi** [comment]
@key88sf It is supported, see the README for `elasticsearch-ruby/elasticsearch-support`, link to commit: https://github.com/elastic/elasticsearch-ruby/commit/30265ee953c86c5ea092f323802e7c90253463bc

**Comment by key88sf** [comment]
@karmi Wow, awesome. Thanks!  :+1:
