### ISSUE TITLE
Elasticsearch 2.0?

### ISSUE THREAD

**Issue by whokilledtheelectricmonk** [elastic/elasticsearch-rails#478]
Elasticsearch v2.0 is out, and there are a number of [breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking-changes-2.0.html) to the API and the [Query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/_query_dsl_changes.html). 

Is there a roadmap for supporting/migrating to the new version with this gem?

**Comment by karmi** [comment]
Any changes shouldn't break functionality in these gems and Elasticsearch 2.0 should be fully supported.
