### ISSUE TITLE
mixed-language fields index config

### ISSUE THREAD

**Issue by xofred** [elastic/elasticsearch-rails#479]
Hi all, I'm newbie in rails and elasticsearch.

I have a attribute "title", and I hope it can be analyzed by two different analyzers, which covers both english and chinese. How should I do?

I check it on [elasticsearch docs](https://www.elastic.co/guide/en/elasticsearch/guide/current/mixed-lang-fields.html). Analyze multiple times should work this out. And I found a example settings. 

```
PUT /movies
{
  "mappings": {
    "title": {
      "properties": {
        "title": { 
          "type": "string",
          "fields": {
            "de": { 
              "type":     "string",
              "analyzer": "german"
            },
            "en": { 
              "type":     "string",
              "analyzer": "english"
            },
            "fr": { 
              "type":     "string",
              "analyzer": "french"
            },
            "es": { 
              "type":     "string",
              "analyzer": "spanish"
            }
          }
        }
      }
    }
  }
}
```

Question is, how to apply it into rails? Through index config maybe?

Forgive my poor english ...

**Comment by karmi** [comment]
Have you had a look at the example Rails apps in https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-rails first?

What you describe above is a proper way how to set your model app -- see the examples and documentation how to do that in Ruby code inside your model. Don't forget to forcefully re-create the index when you change mappings in code.

**Comment by xofred** [comment]
@karmi Thanks for the quick response! I checked the [docs](https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-model) and [index settings template](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-rails/lib/rails/templates/searchable.rb), but could't find a mixed-language fields scenario...

**Comment by karmi** [comment]
Can we close this?

**Comment by xofred** [comment]
@karmi Ok. Actually I stopped digging for a while, maybe I will figure out how to turn that es mappings into Ruby code later. Thanks again!

**Comment by Geesu** [comment]
@xofred did you ever figure this out for rails?

**Comment by ianmurrays** [comment]
I did it like this, seems to work:

```ruby
mapping do
  indexes title, fields: { en: { analyzer: :english, type: :string }, da: { analyzer: :danish, type: :string } }
end
```

**Comment by henrikholm89** [comment]
@ianmurrays Nice one. How do you then control which analyzer should be used at query time?

**Comment by ianmurrays** [comment]
@henrikholm89 I don't, actually, it seems to pick any of them and use the best? Not sure, I'm no elastic expert 😄

**Comment by henrikholm89** [comment]
@ianmurrays Hehe fair enough :) Awesome if that is the case. @karmi Can you confirm or help here?

**Comment by henrikholm89** [comment]
@ianmurrays I just missed this actually [mix language elastic search docs](https://www.elastic.co/guide/en/elasticsearch/guide/current/mixed-lang-fields.html).

Here you can specific with fields you want to use, like in the example below. Maybe it by default searches in the all the fields as you mentioned.

```
"query": {
        "multi_match": {
            "query":    "club de la lucha",
            "fields": [ "title.da", "title.en" ], 
            "type":     "most_fields",
            "minimum_should_match": "75%" 
        }
    }
```

**Comment by ianmurrays** [comment]
@henrikholm89 yeah I just remembered I use something like that in my queries.
