### ISSUE TITLE
PR #138 breaks nested type

### ISSUE THREAD

**Issue by inkstak** [elastic/elasticsearch-rails#480]
Hi,

The #138 breaks my app specs.
Why adding nested to TYPES_WITH_EMBEDDED_PROPERTIES ?

I use nested properties like this :

    indexes :users, type: :nested do
      indexes :name_badge: 
    end

to expect the following mapping :

    "user": {
      "type": "nested",
      "properties": {
        "name": {
          "type": "string"
        }
      }
    }

So now, `properties` becomes `fields`

According to https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-nested-type.html and https://www.elastic.co/guide/en/elasticsearch/reference/current/_multi_fields.html :

> the field type multi_field has been removed. Instead, any of the core field types (excluding object and nested) now accept a fields parameter.

So, when recreating mapping, ES ignore the fields parameter, and the final mapping is now :

    "user": {
      "type": "nested"
    }

**Comment by xxxpigeonxxx** [comment]
change nested to be a string instead of a symbol

```ruby
indexes :users, type: "nested" do
  indexes :name_badge: 
end
```

**Comment by inkstak** [comment]
Thanks @xxxpigeonxxx

**Comment by karmi** [comment]
@xxxpigeonxxx, thanks for the hint!

@inkstak Sorry for the delay. We should do `.to_s` on the type then.

**Comment by inkstak** [comment]
But why adding nested to TYPES_WITH_EMBEDDED_PROPERTIES ?
Doesn't it go against the ES doc ?

**Comment by karmi** [comment]
@inkstak In what sense? Do you have a complete example which would demonstrate your point? Thanks!

**Comment by mmahalwy** [comment]
@karmi my example is I cannot get this:

```
mappings _all: { enabled: false } do
        indexes :text, {
          type: 'string',
          similarity: 'my_bm25',
          term_vector: 'with_positions_offsets_payloads',
          fields: {
            stemmed: {
              type: 'string',
              similarity: 'my_bm25',
              term_vector: 'with_positions_offsets_payloads',
              analyzer: 'standard'
            },
            # phonetic: {
            #   type: 'string',
            #   analyzer: 'dbl_metaphone'
            # }
          }
        }
      end
```

With this:
```
mappings _all: { enabled: false } do
        indexes :text, type: 'multi_field', similarity: 'my_bm25', term_vector: 'with_positions_offsets_payloads' do
          indexes :stemmed, type: 'string', similarity: 'my_bm25', term_vector: 'with_positions_offsets_payloads', analyzer: 'standard'
          indexes :phonetic, type: 'string', analyzer: 'dbl_metaphone'
        end
      end
```

Instead, in ES it becomes: 
```
"text": {
"index": "no",
"type": "string",
"fields": {
"stemmed": {
"analyzer": "standard",
"similarity": "my_bm25",
"term_vector": "with_positions_offsets_payloads",
"type": "string"
},
"phonetic": {
"analyzer": "dbl_metaphone",
"type": "string"
}
}
```

**Comment by karmi** [comment]
@mmahalwy, sorry, don't get what you expect as the output?

**Comment by mmahalwy** [comment]
@karmi sorry, should explain further. According to the ES docs, multi_field is deprecated. Therefore, in the code of doing
```
mappings _all: { enabled: false } do
        indexes :text, type: 'multi_field', similarity: 'my_bm25', term_vector: 'with_positions_offsets_payloads' do
          indexes :stemmed, type: 'string', similarity: 'my_bm25', term_vector: 'with_positions_offsets_payloads', analyzer: 'standard'
...
```

You'd expect to index:
```
text: {
          type: 'string',
          similarity: 'my_bm25',
          term_vector: 'with_positions_offsets_payloads',
          fields: {
            stemmed: {
              type: 'string',
              similarity: 'my_bm25',
              term_vector: 'with_positions_offsets_payloads',
              analyzer: 'standard'
            },
...
```

But what I get:
{
  "text": {
    "index": "no",
    "type": "string",
    "fields": {
      "stemmed": {
        "analyzer": "standard",
        "similarity": "my_bm25",
        "term_vector": "with_positions_offsets_payloads",
        "type": "string"
      },
      "phonetic": {
        "analyzer": "dbl_metaphone",
        "type": "string"
      }
    }
  }
}
```

when it should be:
```
{
  "text": {
    "analyzer": "standard",
    "similarity": "my_bm25",
    "term_vector": "with_positions_offsets_payloads",
    "type": "string",
    "fields": {
      "stemmed": {
        "analyzer": "standard",
        "similarity": "my_bm25",
        "term_vector": "with_positions_offsets_payloads",
        "type": "string"
      },
      "phonetic": {
        "analyzer": "dbl_metaphone",
        "type": "string"
      }
    }
  }
}
```

It made sense that multi_field previously did not have the `text` property to have any options such as analyzer, etc. because you'd have to explicitly set a field with the same name and those options, but with multi_field gone, one would expect it'd just set them on that and have different fields if developer wishes to include

**Comment by inkstak** [comment]
@karmi your commit should fix the issue.
I didn't read well the #138 changes and didn't think that the problem was about the symbol/string equality. Thanks.

@mmahalwy you issue is different. You should open a new one so I can close this one.
