### ISSUE TITLE
Cequel Adapter

### ISSUE THREAD

**Issue by bobbrez** [elastic/elasticsearch-rails#482]
I'm currently using [Cequel-backed](https://github.com/cequel/cequel) models in my application with Cassandra as a backend store. I'm interested in putting together a pull-request to add a Cequel adapter, has this come up before? Is there any considerations that I should be aware of?

**Comment by karmi** [comment]
Hi, it hasn't come up yet, it would be great to add it. I think you can take inspiration from the existing adapters. Please ping me (repeatedly, if needed :) if you'd like to have some assistance, or hear an opinion. Thanks!

**Comment by pranny** [comment]
Is there been any update on this? I am using Cequel too and find it odd that the adapter is not there. I am ready to pick it up now.

**Comment by bobbrez** [comment]
I have some work that I started on this, let me see if I can put together a PR this weekend.

**Comment by pranny** [comment]
Here's an attempt at the Cequel adapter. https://github.com/elastic/elasticsearch-rails/compare/master...pranny:master  It does the importing, callbacks and pretty much major things it is expected to. However, when the `Cequel::RecordSet` instance from `rec.records` is sent a `:where` call,  I hit the following exception

```ruby
response = Article.search 'bar'
rec = response.records
rec.to_a  # [#<Article id: 2, published_at: nil, title: "Bar">]
rec.records.where(id: 3)
/Users/pranav/.rvm/gems/ruby-2.1.5/gems/cequel-1.10.0/lib/cequel/record/record_set.rb:849:in `next_unscoped_key_name': undefined method `name' for nil:NilClass (NoMethodError)
	from /Users/pranav/.rvm/gems/ruby-2.1.5/gems/cequel-1.10.0/lib/cequel/record/record_set.rb:778:in `filter_columns'
	from /Users/pranav/.rvm/gems/ruby-2.1.5/gems/cequel-1.10.0/lib/cequel/record/record_set.rb:216:in `where'
	from examples/cequel_article.rb:98:in `<main>'
```

**Comment by onesupercoder** [comment]
Hey @pranny any luck with this?  It looks like you are real close.  It looks like the target class isn't returning any key columns here: https://github.com/cequel/cequel/blob/master/lib/cequel/record/record_set.rb#L826

I don't know anything about this but just thought I would chime in to see if you thought this was still possible, if so i would love to help.

**Comment by pranny** [comment]
Hi @onesupercoder . I got this far and then the project got stuck and we kind of changed our priorities so this thing could never be resolved. I am still very interested in getting this issue fixed, but do not have the required time to work on it.

**Comment by rapheki** [comment]
Hi, I'm working on a project where I need to connect elasticsearch & cassandra, so I'm very much interested in this cequel adapter.
It seems to works with tables where the primary key column name is `:id`, but fails the primary key column is named differently (I get the following error when the primary key column is `:id_str`)

```
NoMethodError: undefined method `id' for #<Elasticsearch::Model::Proxy::InstanceMethodsProxy:0x00562a478718c0>
/usr/local/bundle/gems/elasticsearch-model-0.1.9/lib/elasticsearch/model/proxy.rb:90:in `method_missing'
/usr/local/bundle/gems/elasticsearch-model-0.1.9/lib/elasticsearch/model/indexing.rb:339:in `index_document'
```
