### ISSUE TITLE
Elasticsearch::Transport::Transport::Errors::BadRequest in example

### ISSUE THREAD

**Issue by yurko** [elastic/elasticsearch-rails#484]
After running the last template `03-expert.rb` application throw an error:

Elasticsearch::Transport::Transport::Errors::BadRequest at / [400] {"error":{"root_cause":[{"type":"search_parse_exception","reason":"failed to parse search source. unknown search element [facets]","line":1,"col":239}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query_fetch","grouped":true,"failed_shards":[{"shard":0,"index":"searchapp_application_development","node":"Ba5Nr4l6TGi5DXDlDrVJeg","reason":{"type":"search_parse_exception","reason":"failed to parse search source. unknown search element [facets]","line":1,"col":239}}]},"status":400}

**Comment by karmi** [comment]
This is because facets have been deprecated in Elasticsearch 2.0 -- I'll fix the template shortly.

**Comment by mohsinali** [comment]
Any progress?

**Comment by karmi** [comment]
@mohsinali Not yet -- too much stuff going on. In general, replace `facets` with `aggregations` and fix errors along the way, the structures are almost the same.
