### ISSUE TITLE
response.results and response.records return different results in Rspec

### ISSUE THREAD

**Issue by wizardone** [elastic/elasticsearch-rails#485]
Hi there, i have the following problem:

When i run some search query in `development` it works just as it is supposed to. In my controller i have:
```ruby
MyModel.search('some_name').records.page(params[:page]).per(params[:per_page])
```
is working like a charm. However i can't get my specs to pass.

So in my `spec_helper.rb` file i have a pretty regular setup:
```ruby
config.around(:each, elasticsearch: true) do |example|
    MyModel.__elasticsearch__.create_index!(force: true)
    MyModel.import
    MyModel.__elasticsearch__.refresh_index!
    example.run
    MyModel.__elasticsearch__.client.indices.delete index: MyModel.index_name
  end
```
This seems to do the trick, the index is being created and the entries from `MyModel` (created with `FactoryGirl`) are imported into elasticsearch.

I have a request spec like this:
```ruby
it 'gets my search results', :elasticsearch do
    get(request_path + search_params)
    # binding.pry for debugging
    # Some expectations about the results here....
  end
```
Now this spec never returns the expected results. I'm creating one record with my factory and i expect 1 result. So I put a debugger in the spec and did:

```ruby
MyModel.search(params[:search]).results.total
GET http://localhost:9200/..../_search [status:200, request:0.004s, query:0.001s]
>  {"query": # Information about the query}
< {"hits":{"total":1,"max_score":1.8491668}}
=> 1
```
Elasticsearch is being queried and the proper result is returned. However if i do:
```ruby
MyModel.search(params[:search]).records
GET http://localhost:9200/..../_search [status:200, request:0.004s, query:0.001s]
>  {"query": # Information about the query}
< {"hits":{"total":1,"max_score":1.8491668}}
=> []
MyModel.search(params[:search]).records.count
GET http://localhost:9200/..../_search [status:200, request:0.004s, query:0.001s]
>  {"query": # Information about the query}
< {"hits":{"total":1,"max_score":1.8491668}}
=> 0
```
So i receive the same result from Elasticsearch, which is cool, but why is it missing from the `records` collection?
Like i said this is happening only within the Rspec contex, not in development. I'm using MongoID.
Am i missing something small here?

**Comment by wizardone** [comment]
Issue was fixed! In the end the "problem" was in the index create/refresh. At the time of the index creation the objects from `MyModel` were not yet created and this somehow let to the above problem.

**Comment by karmi** [comment]
@wizardone Glad it was something so simple! Sorry for not getting to you sooner, it's a known issue that in tests you have to call refresh.
