### ISSUE TITLE
Partial indexing possible?

### ISSUE THREAD

**Issue by larskluge** [elastic/elasticsearch-rails#486]
I'd like to index only particular documents of an entire collection, e.g. based on a boolean `published` attribute in the database, the document should be indexed or (if indexed before) deleted from the elastic search index. 

How can this achieved in a good way? Thank you!

**Comment by larskluge** [comment]
Just noticed the section [Custom Callbacks](https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-model#custom-callbacks) which seems to enable the custom logic I'm looking for. If there is a better way, please let me know. Perhaps a method that you can overwrite a la `#include_in_index?`..?

**Comment by karmi** [comment]
@larskluge There is luckily no method like `include_in_index` :) I prefer the library to be a set of reusable building blocks, not ready mades. The approach in the "Custom Callbacks" section is the right one, and for a more sophisticated application, the indexing should be generally done in the background.

**Comment by larskluge** [comment]
Thanks for the reply @karmi. Generally agreed. Perhaps I'm the only person trying to approach it this way :) And yes, building it via custom callbacks works just fine.

**Comment by karmi** [comment]
The problem with the approach a la `include_in_index` is that you have then a gazillion of weird method names to memorize and look up to configure any nook and cranny of the application, as opposed to "just doing it with Ruby"...

**Comment by larskluge** [comment]
True. Perhaps if you could return `nil` or `false` from `#as_indexed_json` to not include a document, this might already give you all the flexibility required.

**Comment by karmi** [comment]
> (...) if you could return nil or false from #as_indexed_json (...)

Argh, that's the most dangerous idea I've heard today :)

**Comment by larskluge** [comment]
Hah, why?

**Comment by karmi** [comment]
Well, because the responsibility of `as_indexed_json` is to serialize the document for indexation -- and returning nil or false is not a valid "serialization" of the document, in my eyes. The proper approach is some logic "index this if something is true", e.g. `published` property, within the application.

**Comment by larskluge** [comment]
Fair point, thanks for the clarification @karmi !
