### ISSUE TITLE
Multi Model search with pagination.

### ISSUE THREAD

**Issue by zwarburg** [elastic/elasticsearch-rails#487]
I am performing a multi model elasticsearch in my controller and have not managed to get the results to paginate with the `will_paginate` gem. 

In my controller I have:
```ruby
    def index
       @people = Elasticsearch::Model.search('*', [Authors, Editors])
    end
```
Then in my view I have:
```html
    <table>
      <thead>
        <tr>
          <th>Name</th>
        </tr>
      </thead>
      <tbody>
        <% @people.each do |person| %>
          <tr>
            <td><%= person.name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @people, renderer: BootstrapPagination::Rails %>
```
The main error that keep getting is `undefined method 'total_pages' for #<Array:0x007fd8b0e32660>`.

**Comment by miguelff** [comment]
Can you please detail, what are the versions of `will_paginate` and `elasticsearch-model` in your `Gemfile.lock` and whether in the `Gemfile`,  `will_paginate` is declared **before** `elasticsearch-*` gems?

Additionally, are you manage to do pagination with a single model?

One thing that can happen, is that at the moment when `elasticsearch-model` is loading, `will_paginate` hasn't been loaded yet.

**Comment by zwarburg** [comment]
@miguelff that was the issue. I'm using engines which added to my confusion. Once it was put in the proper order things worked. Thanks!

**Comment by miguelff** [comment]
Cool, thank you.
