### ISSUE TITLE
[MODEL] Decouple from order on which pagination libraries are required.

### ISSUE THREAD

**Issue by miguelff** [elastic/elasticsearch-rails#489]
When using elasticsearch-model with a pagination library (i.e. Kaminari, or will-paginate) it's necessary to load those libraries before elasticsearch-model.

This leads to situations like [the one described in #487](https://github.com/elastic/elasticsearch-rails/issues/487#issue-115380728) in which the system would not behave as expected just because of not placing dependencies in the correct order.

This issue is aimed at discussing alternatives to remove the aforementioned coupling, and make elasticsearch-rails better at integrating with pagination libraries.

**Comment by karmi** [comment]
@miguelff Nice try :), but I don't yet see a nice solution for this -- we rely on the fact that some pagination module is [defined](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model.rb#L38). Of course there could be some imperative way of including the pagination modules in the response, but I wonder how that would help -- the fact that you must load pagination libraries before the -model gem is quite clearly in the [README](https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-model#pagination). Of course, we can make it **bold** :)

**Comment by miguelff** [comment]
Couldn't we delay the inclusion of the pagination module? The thing is that we include the pagination at the precise point when we load elasticsearch-model. Wouldn't it make a difference if we include it later, maybe lazily?

**Comment by karmi** [comment]
But what would be the event to hook into?

**Comment by miguelff** [comment]
I don't know yet. For me this is the main concern of this issue: To find another point in time in which to include the pagination module. I will try to come up with something.

**Comment by miguelff** [comment]
What about delaying the load of the libs until the actual `Response::Response` constant is resolved?

https://github.com/elastic/elasticsearch-rails/compare/master...miguelff:master

Is there any reason (a-priori) to discard something like this?

**Comment by miguelff** [comment]
Sorry, I was wrong about this. I will do more tests and come back to you again.

**Comment by karmi** [comment]
The tricky thing with this is that it can introduce delays in parts of code. I'd rather stay away from this, since what we're trying to solve here is solved when people read the documentation. It's no surprise that in Ruby, the order in which you include files/libraries matters. I was only half-joking when I suggested we make the instruction bold .)

**Comment by miguelff** [comment]
@karmi, I understand your concern, and I agree we should make documentation clearer, and also agree about the importance of reading documentation.

But even in that case, there's something I don't feel we are doing right: We are assuming that gem load order is the orden of declaration, which is an assumption based on Bundler internals. In addition we are including the module in a place different then when it's actually used, so when you open `Response` source, you don't know that is actually paginable.

With regards of delays in the code, I can do a benchmark of #489 vs master because actually the code only executes once during the whole application execution in the first request, so my perception is that it will not introduce a big delay, neither will make performance significantly worse. (But I need to confirm that with numbers)

Are you open to that?

**Comment by karmi** [comment]
> We are assuming that gem load order is the orden of declaration, which is an assumption based on Bundler internals.

I don't know if I agree -- `gem "foobar"` is functionally equivalent to `require "foobar"`, and that has natural consequences in a Ruby code.

I think the problem we're trying to solve is not a major one -- as a bit of evidence, notice that over the years, only two or three issues about it have been submitted... for couple of hundreds of thousands downloads...
