### ISSUE TITLE
explicitly set _id in as_indexed_json

### ISSUE THREAD

**Issue by mmahalwy** [elastic/elasticsearch-rails#490]
Is there a way to explicitly set the `_id` for my index in `def as_indexed_json`?

The reason I ask is because my id is a composite key of two primary keys, which fails when importing into elasticsearch

**Comment by karmi** [comment]
Just pass the ID when you create/save?

**Comment by karmi** [comment]
Hi, any news?

**Comment by mmahalwy** [comment]
hey, I had to do a work around, as I am seeding the index, and not on create/save. see:
https://github.com/quran/quran.com-api/blob/dev/app/models/content/transliteration.rb#L27

Closing for now.

**Comment by neyp** [comment]
So, is it possible to define `_id` in the `indexable_json` block? I can't access the url above.
