### ISSUE TITLE
Multiple Hosts --Creating a doc happens on only one host

### ISSUE THREAD

**Issue by alexphys** [elastic/elasticsearch-rails#491]
When setting up a new client with multiple hosts like so;

 ` client = Elasticsearch::Persistence.client Elasticsearch::Client.new(hosts: ['sample-ip-1', 'sample-ip-2'])`

and then trying to persist something like the following;

`client.create  index: 'my-index', type: 'my-type', body: {attr1: 'test', attr2: 999}`

creates the document on only one of the two hosts. (for example I can find the doc on sample-ip-1 but not on sample-ip-2).
Anyone has any idea how to change it so it saves on both hosts?

**Comment by karmi** [comment]
@alexphys This isn't something to solve in the client: the changes should be propagated in the Elasticsearch cluster -- it doesn't matter which host you save to and which you query. Make sure the refresh interval or a very long network latency doesn't bite you.

**Comment by karmi** [comment]
Hi, any news?

**Comment by alexphys** [comment]
@karmi Hi, sorry for the late answer.
You are right about the cluster solution. What I was thinking is to be able to save in independent servers out of a cluster on the same time but I can see several problems with that approach. 
I'm closing the issue. Thank you.
