### ISSUE TITLE
nested mapping fails

### ISSUE THREAD

**Issue by rrphotosoft** [elastic/elasticsearch-rails#495]
Hi,
I am using elasticsearch as a <b>standalone persistence layer</b> in my app.
I have an issue with a basic indexing requirment. 

    GemFIle:
    gem 'elasticsearch-persistence'
    gem 'virtus'

I have two models : tree and leaf.

    class Tree
        include Elasticsearch::Persistence::Model

          attribute :title,  String
          attribute :leaves, Array[Leaf],mapping: {
              type: 'nested',
                  properties: {
                  color: { type: 'string' },
                  shape: { type: 'string'}
             }
         }
    end

       class Leaf
              include Virtus.model
              attribute :color, String
              attribute :shape, String
       end

Then in my controller i do the following:
               
                tree = Tree.new(:title => "cucumber")
		tree.leaves << Leaf.new(:color => "yellow")
		tree.leaves << Leaf.new(:shape => "round")
		
            
		puts Tree.mappings.to_hash

                ##=> {:tree=>{:properties=>{:title=>{:type=>"string"}, :leaves=>{:type=>"nested",       :properties=>{:color=>{:type=>"string"}, :shape=>{:type=>"string"}}}}}}
              
                tree.save

In Sense, I query the mapping and get the following:
   

     "trees": {
      "mappings": {
         "tree": {
            "properties": {
               "leaves": {
                  "properties": {
                     "color": {
                        "type": "string"
                     },
                     "shape": {
                        "type": "string"
                     }
                  }
               },
               "title": {
                  "type": "string"
               }
            }
         }
      }
   } 

The <b>nested</b> is missing, The es log shows :
    

    [2015-11-18 23:18:02,608][INFO ][cluster.metadata         ] [Bombshell] [trees] creating index, cause  [auto(index api)], shards [5]/[1], mappings [tree]
    [2015-11-18 23:18:03,403][INFO ][cluster.metadata         ] [Bombshell] [trees] update_mapping [tree] (dynamic)

It creates the index initially, and then the index is overridden by a new definition, 

Things I tried:
including elasticsearch-persistence-model in the leaf class instead of Virtus.model.
This didn't make any difference.

I've seen a couple of other ways to create the mapping, but this is the one in the docs.
Finally I've looked into the gem source but couldnt find where the call to create the index is made.(mappings, types etc.)
I'd be grateful if someone could point it out.

Regards,
bux

**Comment by karmi** [comment]
You have to call `Tree.create_index!` before you start indexing data (see [README](https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-persistence)), or, if you want to create the index with mappings for multiple types, adapt something like this: https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/examples/music/index_manager.rb

See the "auto(index api)"? This means the index is created automatically based on the data.

**Comment by rrphotosoft** [comment]
Hi,
Thanks for your input.
I was a bit confused since the create_index! call is mentioned in the docs, but in the "repository" pattern. I didn't know whether we were supposed to use it for the standalone persistence layer.
I will implement the index_manager.rb approach.
As an aside,I am about to begin using elasticsearch::persistence::model with devise. Is there any documentation or an example app that uses devise with elasticsearch persistence:standalone? I couldn't find anything when I looked.
Thanks,
 Bux
