### ISSUE TITLE
MapperParsingException[Field [_id] is a metadata field and cannot be added inside a document.

### ISSUE THREAD

**Issue by charlescui** [elastic/elasticsearch-rails#505]
I use Rails4 + Mongoid + elasticsearch-rails + elasticsearch-model.

My Model is : 

```
class Epg::Schedule
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :starttime, type: DateTime
  field :endtime, type: DateTime

  belongs_to :channel, :class_name => "Epg::Channel"

  index({channel_id: 1, starttime: -1, endtime: 1}, {background: 1, unique: true})
  index({channel_id: 1, starttime: -1}, {background: 1, unique: true})

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
end
```

When create a model, and save will report an error as below:

```
[2015-12-06 11:20:16,555][DEBUG][action.index             ] [Bedlam] [epg-schedules][1], node[6-NFKFHTThSkZlY7Rt6G_A], [P], v[2], s[STARTED], a[id=ZuqP6q8dQcqJ2-vwVElEGQ]: Failed to execute [index {[epg-schedules][schedule][5663a96f7202c77553000000], source[{"_id":{"$oid":"5663a96f7202c77553000000"},"channel_id":{"$oid":"56049fd3de70143f1f0006fa"},"created_at":"2015-12-06T11:20:15.865+08:00","endtime":"1970-01-01T08:00:00.000+08:00","name":"动物世界","starttime":"2015-12-06T00:42:00.000+08:00","updated_at":"2015-12-06T11:20:15.865+08:00"}]}]
```

**Comment by karmi** [comment]
You should implement the `as_indexed_json` method in your model, to properly format the ID, have you seen this chapter of the Readme? https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-model#other-activemodel-frameworks

**Comment by charlescui** [comment]
Thanks! I have read this chapter, but I haven't got understand why except id in as_indexed_json method. if the id filed doesn't pass to elasticsearch, how does elasticsearch keep the relation between indexed document in elasticsearch and the Mongodb data.

**Comment by karmi** [comment]
The ID doesn't belong to the **serialized** document -- the document is referenced by `index/type/id` and that is what makes a relationship between your database and your Elasticsearch.

Have a look here: https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/examples/mongoid_article.rb as well.

**Comment by estolfo** [comment]
Hi @charlescui is this issue still relevant or can I close it?

**Comment by estolfo** [comment]
I'm going to close this issue, please open a new one if you have further questions. Thanks!
