### ISSUE TITLE
Instrumentation details not printed for persistence model

### ISSUE THREAD

**Issue by Animeye** [elastic/elasticsearch-rails#507]
According to the documentation, adding `require 'elasticsearch/rails/instrumentation'` to the `config/application.rb` should add two bits of instrumentation details: A line detailing what query was run, and a bit in the controller response saying how much of the time was doing the elasticsearch query.

```
Started GET "/traces" for ::1 at 2015-12-08 15:55:21 -0600
Processing by TracesController#index as HTML
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."uid" = $1 LIMIT 1  [["uid", "user@example.com"]]
  Rendered helpers/_fielded_object.json.jbuilder (0.3ms)
  Rendered helpers/_fielded_object.json.jbuilder (0.2ms)
  Rendered helpers/_fielded_object.json.jbuilder (0.2ms)
  Rendered helpers/_fielded_object.json.jbuilder (0.2ms)
  Rendered helpers/_fielded_object.json.jbuilder (0.0ms)
  Rendered helpers/_fielded_object.json.jbuilder (0.2ms)
  Rendered helpers/_fielded_object.json.jbuilder (0.2ms)
  Rendered helpers/_fielded_object.json.jbuilder (0.2ms)
  Rendered helpers/_fielded_object.json.jbuilder (0.2ms)
  Rendered helpers/_fielded_object.json.jbuilder (0.2ms)
  Rendered helpers/_fielded_object.json.jbuilder (0.2ms)
  Rendered helpers/_fielded_object.json.jbuilder (0.2ms)
  Rendered helpers/_fielded_object.json.jbuilder (0.2ms)
  Rendered helpers/_fielded_object.json.jbuilder (0.2ms)
  Rendered helpers/_paginated_results.json.jbuilder (7.2ms)
  Rendered traces/index.json.jbuilder (8.4ms)
Completed 200 OK in 111ms (Views: 9.8ms | ActiveRecord: 0.7ms | Elasticsearch: 0.0ms)
```

In practice, it looks like the bit that prints the query being run isn't getting output, and the time in the final statement seems to always be 0.0ms.  Not sure if I have something configured wrong or if this is a bug

**Comment by toao** [comment]
@Animeye Please have a look at https://github.com/elastic/elasticsearch-rails/issues/305#issuecomment-68552192, you need to add a small wrapper snippet to get the instrumentation to work.

**Comment by wflanagan** [comment]
@toao As I understand #305, that is for the repository model. i'm not sure if he's using the AR style or the repository style. Either way, I have the same problem in the AR style I'm trying to troubleshoot.

**Comment by Animeye** [comment]
As I understand it, there is the same underlying issue for both the AR and repository style.
I was able to get some instrumentation hooked up by entering into the gateway, as shown here https://github.com/elastic/elasticsearch-rails/issues/269#issuecomment-69755606, but as noted in that issue, things don't work "out of the box" or as documented in the README

**Comment by tombeynon** [comment]
In case it can help anyone, I was able to resolve this in an AR style model (Persistence::Model) as below.

```
class Article
    include Elasticsearch::Persistence::Model

    gateway do
      def search(query, options = {})
        ActiveSupport::Notifications.instrument "search.elasticsearch", name:
          'Search', klass: host, search: query do 
          super 
        end 
      end
    end

end
```

**Comment by Animeye** [comment]
It may be worth mentioning that that will only instrument the "search" method, while activerecord users may prefer/expect that other common methods (find, save, destroy) to also contribute to the logged timing.  These methods can get instrumented in a similar fashion (entering into the gateway and overloading each method).

**Comment by Animeye** [comment]
Also worth noting that there doesnt seem to be a consistent way of doing this.  Overloading the methods in gateway works for some methods, but not for others (such as find_in_batches)
Overloading self.find_in_batches at the class level works, but does wind up including time spent in the block as time spent in elasticsearch.  Looking at the source, it looks like a more "correct" solution would require overloading the search and scroll methods of the client object?
