### ISSUE TITLE
Elasticsearch Persistence missing settings

### ISSUE THREAD

**Issue by wizardone** [elastic/elasticsearch-rails#510]
Hola, i have a fully working `elasticsearch-model` implementation for one of my projects. Now i wanted to test something with `elasticsearch-persistence` and found that i'm not able to set custom analyzers( or at least when i query ES they do not show up).

```ruby
let(:repository) do
    Elasticsearch::Persistence::Repository.new do
      client Elasticsearch::Client.new url: 'http://localhost:9200', log: true
      index SecureRandom.uuid
      type 'document'
      klass Document

      settings index: {
        analysis: {
          filter: {
            substring: {
              type: 'edge_ngram',
              min_gram: 1,
              max_gram: 10
            }
          },
          analyzer: {
            autocomplete: {
              type: 'custom',
              tokenizer: 'standard',
              filter: %w(lowercase substring)
            }
          }
        }
      } do
        mapping do
          indexes :values, analyzer: 'autocomplete', search_analyzer: 'standard'
        end
      end
    end
  end
```
Now when i do check the index i get:
```
{"d324f0a7-2189-421e-9dca-d9e982290f69":{"aliases":{},"mappings":{"document":{"properties":{"id":{"type":"string"},"values":{"type":"string"}}}},"settings":{"index":{"creation_date":"1449845831807","uuid":"RhLp5p2ISPWA371H7ydRlQ","number_of_replicas":"1","number_of_shards":"5","version":{"created":"2000099"}}},"warmers":{}}}
```

And when i try to check the analyzer itself:
```
_analyze?analyzer=autocomplete

{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: text is missing;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: text is missing;"},"status":400}
```
All of the above works fine with `elasticsearch-model`...
I know that this is probably something easy, but i cannot find the solution for this. How is this different then indexing in `elasticsearch-model`?

**Comment by karmi** [comment]
First thing, are you sure you've recreated the index to pick up the new mapping? (Eg. `create_index force: true`)

**Comment by wizardone** [comment]
Nope, i didn't do that. Added the `force: true` option and now the settings are there. Of all the things i checked and double checked that is literally the only thing that i didn't do. Sorry for bothering you.

**Comment by karmi** [comment]
No worries! This can be tricky to figure out, I guess it could be emphasized a little bit in the documentation...
