### ISSUE TITLE
Module Namespace Clash (ElasticSearch::Model::Client)

### ISSUE THREAD

**Issue by kcore** [elastic/elasticsearch-rails#511]
Observing a strange behaviour if we have STI enabled with the child model name being "Client".
Assume the following scenario:
class Parent
include ElasticSearch::Model
end

class Client < Parent
include ElasticSearch::Model
end

Now if we do just '''Parent::Client''' in the console it returns the class "ElasticSearch::Model::Client" instead of "Parent::Client" class - which is very strange since both of them have a distinct namespace

**Comment by karmi** [comment]
I can verify the behaviour, it happens also for the `Client` class, and by extension for any other class:

```
Client::Client
# => Elasticsearch::Model::Client
```

It is indeed weird, I'll have a look at why this happens...
