### ISSUE TITLE
Stack level too deep error after upgrading to elasticsearch-model 0.1.8

### ISSUE THREAD

**Issue by kidlab** [elastic/elasticsearch-rails#512]
After upgrading to elasticsearch-model 0.1.8, the error `stack level too deep` will occur if I use `records.records` when searching multiple models:

``` ruby
Elasticsearch::Model.search("hello", [User, Post]).records.records
```

```
SystemStackError:
  stack level too deep
# ~/.rvm/gems/ruby-2.0.0-p643/gems/elasticsearch-model-0.1.8/lib/elasticsearch/model/adapters/multiple.rb:40
```

It's okay if I downgrade to elasticsearch-model 0.1.7.

**Comment by estolfo** [comment]
I'm going to close this, especially as it references gem version 0.1.7. Please open a new issue if you have further questions.
