### ISSUE TITLE
mapper attachment type support in elastic rails

### ISSUE THREAD

**Issue by channainfo** [elastic/elasticsearch-rails#515]
I am using elasticsearch mapper attachment type to search inside html and pdf file. I could not figure out how to map a field to attachment type ?

**Comment by karmi** [comment]
Just translate the [mapping](https://github.com/elastic/elasticsearch-mapper-attachments#hello-world) into a Ruby hash:

```ruby
class MyModel
  # ...
  mapping cv: { type: "attachment" }
end
```
