### ISSUE TITLE
How to  delete multiple documents that match a query condition with elasticsearch persistence

### ISSUE THREAD

**Issue by channainfo** [elastic/elasticsearch-rails#516]
is there any way to delete multiple documents with just a query similar to this: 

   curl -XDELETE 'http://localhost:9200/twitter/tweet/_query' -d '{
      "query" : {
        "term" : { "user" : "kimchy" }
      }
  } '

 I know elasticsearch persistence can destroy as an object method but I might have up to hundreds of record to be deleted by a criteria. Deleting one by one might send too many requests to elastic search server.

**Comment by karmi** [comment]
Preferably use the [`bulk`](http://www.rubydoc.info/gems/elasticsearch-api/Elasticsearch/API/Actions#bulk-instance_method) method of the Ruby client, optionally using the `scan/scroll` feature to find matching documents before; see the Elasticsearch [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/1.6/docs-delete-by-query.html).
