### ISSUE TITLE
Repository as a model

### ISSUE THREAD

**Issue by kot-begemot** [elastic/elasticsearch-rails#529]
We are developing a service where we need to create indexes in remote ES clusters.

Our use case is like that

``` ruby
class RemoteRepository
  include Elasticsearch::Persistence::Repository

  attr_reader :index_model, :remote_client

  def initialize(index_model)
    @index_model = index_model
    @remote_client = Elasticsearch::Client.new client_options

    define_settings
  end

  protected

  def client_options
    { host: index_model.cluster.host }
  end

  def define_settings
    index  index_model.name
    document_type index_model.type

    ...
  end
```

Problem raised when we were testing that approach with rspec. It seems like  mapping get cached.

Say we have following test setup

``` ruby
repo1 = RemoteRepository.new(model_1)
repo2 = RemoteRepository.new(model_2)

repo1.mapping 
# => {:index=>"index_1", :body=>{:settings=>{:number_of_shards=>2}, :mappings=>{:"type_1"=>{:properties=>{...}}}}}
repo2.mapping 
# => {:index=>"index_2", :body=>{:settings=>{:number_of_shards=>2}, :mappings=>{:"type_1"=>{:properties=>{...}}}}}
```

Since mapping is cached, it gets complicated  if you have to deal many repo instances at once.

**Comment by kot-begemot** [comment]
Here is some technical insight.

* Gateway is defined when repository class gets [included into model](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/lib/elasticsearch/persistence/repository.rb#L37)
* It includes [class methods for model indexing](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/lib/elasticsearch/persistence/repository/class.rb#L48) 
* Here is how [mapping gets cached](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model/indexing.rb#L135)

I wonder if that would be a good idea to initialize a new geteway instance for every `RemoteRepository` instance?

**Comment by karmi** [comment]
Hi, if I understand correctly, you're passing a model class as the `index_model` argument, and the access the mappings. This is what makes it a bit tricky, because the repository itself doesn't care about the mappings, but the model does.

I don't think we can throw out the caching _in the model_ "just like that", because currently we support calling `mapping` repeatedly, and accessing the same object... and I think it makes sense to support it.

What's weird though, is that the mapping would be shared across the repository objects...

**Comment by kot-begemot** [comment]
I solved my case by initializing new gateway for every repository instance

```ruby
  def initialize(index_model)
    ...
    @gateway = Elasticsearch::Persistence::Repository::Class.new host: self.class
    ...
  end
```

I am not sure how efficient it will be in terms of memory, that I will have to figure out later, but it solves an obstacle atm.

IMHO this thing can be addressed by introducing a setter method for a gateway and covering that case in Readme.

**Comment by kot-begemot** [comment]
I got this impression that `Elasticsearch::Model` should be included into Activerecord class and then it provided ES functionality to deal with records of this data.

Our case is a bit different. We use db to stare information about geographically distributed clusters and indexes that they contain and provide functionality to create and manage those indexes via web UI. In this context `index_model` contains an information about ES index it self (like name, host, fields) and is not for indexing or searching.

**Comment by estolfo** [comment]
This is resolved with the release of elasticsearch-persistence 6.0.

Please see the documentation [here](https://github.com/elastic/elasticsearch-rails/tree/6.x/elasticsearch-persistence#the-repository-pattern).
