### ISSUE TITLE
Could not find elasticsearch-api-1.0.15 in any of the sources

### ISSUE THREAD

**Issue by NateGreat8** [elastic/elasticsearch-rails#533]
I tried resetting the gems since I use RVM. I still am receiving this error.

**Comment by nathantechie9** [comment]
The template app works.

**Comment by karmi** [comment]
So are you still getting the error?

> Where is the documentation for connecting to a 3rd party elastic server like amazon?

See https://github.com/elastic/elasticsearch-ruby/tree/master/elasticsearch-transport#setting-hosts, the easiest way is to set the `ELASTICSEARCH_URL` environment variable, the client will pick it up.

**Comment by nathantechie9** [comment]
I used the generator sample app. It works now. That example app was a life saver.

**Comment by karmi** [comment]
Glad to hear that!, a lot of time & energy went into those :) Closing the issue then?

**Comment by nathantechie9** [comment]
Ya. Closed.
