### ISSUE TITLE
[Model] is there any way to get rid of pagination?

### ISSUE THREAD

**Issue by cursorzz** [elastic/elasticsearch-rails#534]
I am currently us elasticsearch-rails in my project and for most pages they are working good with pagination info included, but for some pages, requires the search return all the result instead of paginated result, is there any options(or way) to temporarily disable the pagination for that search?

the pagination gem I am using is gem 'kaminari' btw

**Comment by karmi** [comment]
I'm afraid I'm a bit confused about what do you want to achieve. Do you want to return _all results_ for a particular query? (That's different then "getting rid of pagination" in my understanding.)

For a small dataset, you can just use a really big `size`, but obviously that's quite heavy both for Elasticsearch and Ruby. For a big amount of data, you'll need to use the ["scan and scroll"](http://www.rubydoc.info/gems/elasticsearch-api/Elasticsearch%2FAPI%2FActions%3Ascroll) API.

**Comment by cursorzz** [comment]
in list showing page result is paginated by 50, which is expected; but in one page I need to show all "Activities" within a week, some times this result will be hundreds; since I am just reuse the same endpoint from list showing page (with extra page=unlimit option). then the result is always paginated and the maximum result is limited to 50;

and I got an walk around to achieve my expectation.  I add extra size option to handle this problem
something like this
     ` model_name.__elasticsearch__.search(query, size: 1000)`

so the `response.records` can actually get a bigger result

**Comment by karmi** [comment]
Yeah, that's on my suggested solutions. Be aware though, that big result sets will stress both Elasticsearch and the Ruby application, and a proper solution is the scan/scroll I've mentioned.

Closing the issue then?

**Comment by cursorzz** [comment]
sure, thank you very much

**Comment by shivdeepnv** [comment]
> in list showing page result is paginated by 50, which is expected; but in one page I need to show all "Activities" within a week, some times this result will be hundreds; since I am just reuse the same endpoint from list showing page (with extra page=unlimit option). then the result is always paginated and the maximum result is limited to 50;
> 
> and I got an walk around to achieve my expectation. I add extra size option to handle this problem
> something like this
> `model_name.__elasticsearch__.search(query, size: 1000)`
> 
> so the `response.records` can actually get a bigger result

@cursorzz - How and where do I add this option?
