### ISSUE TITLE
[MODEL] Struggling with as_indexed_json and attachments

### ISSUE THREAD

**Issue by redsquirrel** [elastic/elasticsearch-rails#535]
I am trying to use ElasticSearch with Rails to search PDF documents. I have installed the [attachments plugin](https://github.com/elastic/elasticsearch-mapper-attachments) on my laptop. I tried following [this tutorial](http://rny.io/rails/elasticsearch/2013/08/05/full-text-search-for-attachments-with-rails-and-elasticsearch.html). After trying to get things to play nice with all the latest gems, I ended up with this:

``` ruby
class ReferenceDocument < ActiveRecord::Base
  include Elasticsearch::Model

  settings do
    mapping do
      indexes :name
      indexes :attachment, type: 'attachment'
    end
  end

  def attachment
    require 'open-uri'
    encoded_url = URI.encode(upload.url)
    file_contents = open(encoded_url) { |file| file.read }
    Base64.encode64(file_contents)
  end

  def as_indexed_json(*ignored)
    to_json(methods: [:attachment])
  end
end
```

I seem to be doing many things wrong, but I can't find documentation to help me. If I remove all the attachment stuff, `ReferenceDocument.search("foo")` will match on the `name` field as you'd expect it to. If I remove the `as_indexed_json` method, the `ReferenceDocument.import` method finishes immediately, obviously _not_ grabbing all the attachments. And the above code simply never returns any records for words in the `name` field, or for words in the PDF attachments. So I imagine I'm just configuring things incorrectly?

This isn't an issue with your code. More of a cry for help from a user. :confused:

**Comment by ricn** [comment]
I just followed my own instructions in the blog post and I got everything working with the latest version of ElasticSearch, the attachment type plugin and the latest version of Rails. So those components should not be part of the problem. However, I saw that the tire gem has be deprecated in favor of the elasticsearch-rails and by looking at your code above it seems like you're using that gem instead. I will try to see if I can get it to work with that gem instead.

**Comment by redsquirrel** [comment]
Thanks @ricn!

**Comment by ricn** [comment]
Nah couldn't get it to work using elasticsearch-rails :( Must be some kind of configuration/mapping magic that needs to be added. The attachment & as_indexed_json method is never called when I tried your code.

**Comment by redsquirrel** [comment]
Well, that makes me feel better (at least my ego). So you were able to get it to work with the latest Rails and [Tire](https://github.com/karmi/retire)? What version of elasticsearch?

**Comment by ricn** [comment]
Yep, I got it to work using es 2.2.0 and the Mapper attachments plugin. I just saw that the plugin will become deprecated: https://www.elastic.co/guide/en/elasticsearch/plugins/master/mapper-attachments.html

A lot have changed since 2013 when I wrote the blog post 😳

**Comment by karmi** [comment]
@redsquirrel When you call your `as_indexed_json` method, does it seem to output the base64 stuff correctly? The mappings look right, did you force recreate the index when you try it?

Aside, if it's not just a tiny application, I'd probably skipped the attachment plugin part, and did my own parsing eg. with Tika (the library the plugin uses). In this way, you can make the parsing asynchronous, and not put additional load on Elasticsearch. Also, you'll decouple the PDF parsing from Elasticsearch versions, and not have to update the plugin together with Elasticsearch. On the other hand of course, the attachment plugin works, so if those are not your problems it should be OK to use it.

**Comment by redsquirrel** [comment]
@karmi I've been doing `ReferenceDocument.import(force: true)`, does that force recreate the index?

FWIW, I'm trying to get this working on Heroku, using [searchbox](https://devcenter.heroku.com/articles/searchbox).

**Comment by redsquirrel** [comment]
@karmi Can you confirm whether you've been able to to get `elasticsearch-model` working with attachments? There aren't any [examples](https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-model/examples) that show how it works. If we can get this working, then I'd be happy to contribute an example.

**Comment by redsquirrel** [comment]
Does't seem like attachments are actually supported in elasticsearch-model :disappointed: ... I'm going to try to get it working anyway. 🐒

**Comment by kirka121** [comment]
http://stackoverflow.com/questions/36500827/elasticsaerch-rails-cant-search-for-mac-extensions

here is an example of semi-working code with elasticsearch-rails, mapper-attachment and rails 4.2.5, i have most data types working, but experiencing issues with mac file extensions specifically.

**Comment by fiedl** [comment]
@redsquirrel : Hi, did you get it working? 

`Document.search("*foo*")` finds documents by title, but does not search the pdf content for me using [elasticsearch-rails](https://github.com/elastic/elasticsearch-rails) and the [Mapper Attachments Plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/current/mapper-attachments.html).

**Comment by redsquirrel** [comment]
@fiedl No, I eventually punted. Never got it working.

**Comment by rakeshsaharan** [comment]
@redsquirrel   I am facing the same issue, Did you get it working ?

**Comment by garyfoster** [comment]
Same here, I can get the attachments search working with Rails 5 and Tire, but once I switch to the elasticsearch-rails gem, it fails. I tried deleting/recreating the search index to no avail. Also, I was not able to get it working with elasticsearch running locally on my mac from homebrew, but it does work when connecting to a bonsai heroku add-on. Hoping to get a solution since the Tire gem was last updated 6 years ago, it's amazing that it actually still runs.

**Comment by guizaols** [comment]
Any news about this issue? I'm facing the sae problem here even in the latest version.
