### ISSUE TITLE
[Question] How could I keep the synchronization within elasticsearch-rails

### ISSUE THREAD

**Issue by poc7667** [elastic/elasticsearch-rails#536]
How could I keep the synchronization within elasticsearch-rails

I have a existing data in mysql. 

I imported all records from mysql into elasticsearch with a rake task

However, I wonder know how could I keep synchronization when I delete, update, insert a record within Rails

How could Rails trigger the modification to elasticsearch? Thanks
# model

```
require 'elasticsearch/model'
class Job < ActiveRecord::Base
  attr_accessor :deadline_asap
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks  

end
```
# Rake test

```
  task :import_all => :environment do
    Job.__elasticsearch__.create_index!
  end
```

**Comment by Ashviniv** [comment]
@poc7667 In the model you have included `include Elasticsearch::Model::Callbacks` which automatically performs callbacks. In case you need more control of the indexing process you can add `custom callbacks` like `after_create`, `after_save`, `after_update` or `after_destroy`. For more details read `elasticsearch-model` readme for callbacks.
