### ISSUE TITLE
Failed to Store Geopoint Type with elasticsearch-persistence

### ISSUE THREAD

**Issue by dsilver829** [elastic/elasticsearch-rails#539]
Hi,

A while back I ran into a problem storing geopoint types using the elasticsearch-persistence gem. 

I was trying to build a Rails app using elasticsearch as my data store.

It looked like the JSON that was getting built was formatting the geopoints as strings and not geopoints. As best I could tell, this might have originated in the `lookup_type()` method within [`Elasticsearch::Persistence::Model::Utils`](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/lib/elasticsearch/persistence/model/base.rb), which does not have a case statement for geopoints.

Unfortunately, I don't have the code at hand right now (I should have written up the issue at the time, not weeks later, sorry), but I could try to re-create it.

Eventually, I switched to the elasticsearch-model gem and used ActiveRecord, and everything worked fine.

A couple questions:
1. Is this expected behavior? I'm new to elasticsearch, so maybe I just did something wrong.
2. Would you like me to try to recreate this issue, fix it, and create a pull request?

Thanks!

**Comment by estolfo** [comment]
Closing as this is out of date.
