### ISSUE TITLE
Import Data Faster

### ISSUE THREAD

**Issue by bcackerman** [elastic/elasticsearch-rails#54]
Is there a way to have this command run faster `bundle exec rake environment elasticsearch:import:model CLASS='model' FORCE=y`by including any table joins?  My model has mapping object on it that includes another table currently.

**Comment by netwire88** [comment]
Hi @karmi, has any user been able to replicate your bulk import example with Mongoid instead of ActiveRecord? I search all over the net but since Mongoid doesn't have `find_in_batches`, I'm not sure how to implement your example above.

**Comment by karmi** [comment]
@netwire88 It should work exactly the same for Mongoid -- there's an adapter for Mongoid shipped.

**Comment by karmi** [comment]
@netwire88 I mean, if you wanna write a custom importing code like that, just use the appropriate Mongoid methods, see eg. this comment, https://github.com/mongoid/mongoid/issues/1334#issuecomment-2419621

**Comment by netwire88** [comment]
Thanks @karmi, does the default `import` method that comes with elasticsearch rails use bulk import?
