### ISSUE TITLE
NGRAM doesn't work in Elasticsearch Rails 

### ISSUE THREAD

**Issue by poc7667** [elastic/elasticsearch-rails#542]
I have a table which has job_title field,

I want to make a fuzzy search let user can still get the result when they mis-spell query keyword.

For example, I have many records have the "Android developer" as its job_title,

When the user issues the incorrect search `Job.es_qsearch("Andoirddd")`, it should work as well by the help of `NGRAM_ANALYZER`

However, I could get any results from the incorrect keyword.

I can only get the result when I type `Job.es_qsearch("Android")`

How could I achieve the search result as I expect.

Thanks 
# job.rb

```
NGRAM_ANALYZER = {analysis: {
       filter: {
          autocomplete_filter: {
             type: "edge_ngram",
             min_gram: 3,
             max_gram: 20
          }
       },
       analyzer: {
          ngram_analyzer: {
             type: :custom,
             tokenizer: :standard,
             filter: [
                :lowercase,
                :autocomplete_filter
             ]
          }
       }
    }}

settings NGRAM_ANALYZER do
    mappings do
      indexes :job_title, include_in_all: 'ngram_analyzer'
      indexes :description, include_in_all: 'ngram_analyzer'
    end
end


def self.es_qsearch(*args, &block)
 q_params = {
        multi_match: {
          query: "*#{args}*",
          fields: ['job_title^5', 'description']
        }
      }

  __elasticsearch__.search(
    {
      query: q_params,
    }
  )
end
```

**Comment by arthuang** [comment]
+1

**Comment by karmi** [comment]
So, does your settings for the index work in plain Ruby or Curl? (There's an Ngram example in the API documentation at http://www.rubydoc.info/gems/elasticsearch-api/Elasticsearch/API/Indices/Actions#create-instance_method)

Second, as I wrote in #543, you have to pass the whole definition to the `search` method, not as a query argument. I suggest to spend some time with the example Rails application https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-rails#rails-application-templates, which offer a lot of useful usage examples and patterns.

**Comment by karmi** [comment]
Hi, any news here?

**Comment by henrikholm89** [comment]
It works fine here with the following settings:
```
module SearchableTeam
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
    index_name [Rails.env, model_name.collection].join("_")

    settings analysis: {
      filter: {
        edge_ngram_filter: {
          type: "edgeNGram",
          min_gram: "2",
          max_gram: "20",
        }
      },
      analyzer: {
        edge_ngram_analyzer: {
          type: "custom",
          tokenizer: "standard",
          filter: ["lowercase", "edge_ngram_filter"]
        }
      }
    } do
      mappings do
        indexes :name, type: "string", analyzer: "edge_ngram_analyzer"
        indexes :club, type: "object" do
          indexes :country_id, type: "integer"
          indexes :name, type: "string"
          indexes :deleted, type: "boolean"
        end
      end
    end

    def as_indexed_json(*)
      as_json(include: { club: { only: [:country_id, :name, :deleted] } })
    end
  end
end

**Comment by strivemag** [comment]
@poc7667 , @henrikholm89 , @karmi 
I will be grateful if you can reply!
Is it possible to integrate `typeahead.js`(or `Jquery Autocomplete`) to Rails App for **auto-complete searching** with `elasticsearch-rails` and `elasticsearch-model`?

**Comment by karmi** [comment]
@strivemag, it is definitely possible. I suggest to first read https://www.elastic.co/blog/you-complete-me, to get familiar with Elasticsearch auto-completers. Then, you can use the "Suggest" API, as in [this example from the repository](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/examples/music/suggester.rb).

**Comment by estolfo** [comment]
Closing as this is out of date.
