### ISSUE TITLE
ESearch + Rspec error

### ISSUE THREAD

**Issue by divyashravanthi** [elastic/elasticsearch-rails#552]
I always end up with the following error, when i try to search imported records through rspec. 

NoMethodError: undefined method `model_name' for [PROXY] Object:Elasticsearch::Model::Proxy::ClassMethodsProxy

method_missing, from proxy.rb 

After some investigation, i found out that i can search through the records normally in development and test environment. But when i debug through one of the request specs (which invokes one of my actions involving elasticsearch methods) it doesn't go through and bamm, the same error.

**Comment by estolfo** [comment]
Is this still an issue, @divyashravanthi ?

**Comment by estolfo** [comment]
I'm going to close this issue. Please reopen if you have further questions.
