### ISSUE TITLE
Custom analyzer not working in indexing or searching ?

### ISSUE THREAD

**Issue by abournier** [elastic/elasticsearch-rails#557]
I created a custom analyzer for my model, but it seems to not be "analyzed".

My code:

```
# elasticsearch
  include Elasticsearch::Model
 # I use custom callbacks

  # mapping
  def as_indexed_json(options={}) 
    as_json(only: [:searchable, :year]) 
  end 
  
  settings analysis: {
    analyzer: {
      custom_analyzer: {
        tokenizer: "standard",
        filter: ["lowercase", "asciifolding", "worddelimiter"]
      }
    },
    filter: {
      worddelimiter: {
        type: "word_delimiter"
      }
    }
  } do
    mappings dynamic: 'false' do
      indexes :searchable, analyzer: :custom_analyzer
      indexes :year
    end
  end
```

My goal is for example that querying "Château" and "chateau" to give the same score. I used this query:

```
@results = Wine.search(query: {match: {searchable: {query:params[:search], fuzziness:2, prefix_length:1}}}, sort: {_score: {order: :desc}, year: {order: :desc, ignore_unmapped: true}}, size:100)
      @records = @results.records.
```

In this example, if I query "Château", I will obtain:

> Château, 2016
> chateau, 2015

and if I query "chateau", I will obtain the reverse:

> chateau, 2015
> Château, 2016

If _chateau_ and _Château_ were returning the same score, the response should be like the first one.

Also, it looks like the custom_analyzer is not working cos' I can't see it in the mapping with curl:

```
curl 'http://localhost:9200/wines/_mapping?pretty=true'
{
  "wines" : {
    "mappings" : {
      "wine" : {
        "properties" : {
          "searchable" : {
            "type" : "string"
          },
          "year" : {
            "type" : "long"
          }
        }
      }
    }
  }
}

```
Well, at the time, I'm confused: 
- It seems the mapping with my custom analyzer is not working correctly (I have removed and recreate the index).
- I don't know if my search is using the custom analyzer
- I'm not sure that asciifolding is working to remove accents

Thanks

**Comment by abournier** [comment]
OK. I forced the index mapping with:

`Wine.__elasticsearch__.create_index! force: true`

and now the mapping works.

Where is the best place to create indexes in the app ? (if we don't want to create them with curl)

**Comment by abournier** [comment]
I put the index creation in an initializer.
Now, all seems to work, the mapping, and my search query using ngrams.
Thanks for this nice gem !

**Comment by karmi** [comment]
Hi, look at the example applications in the repo, they have all the patterns, even for tests and so on.

**Comment by abournier** [comment]
OK, I will have a look. Thanks.
