### ISSUE TITLE
Use one elasticsearch server of rails application in another rails application

### ISSUE THREAD

**Issue by rick17** [elastic/elasticsearch-rails#558]
My rails application is running using four ec2 instances. When user hit rails application using url, rails application will be serve to the user using any one of four ec2 instance using ELB.

Elasticsearch server is installed on one of the rails server. How i can use same elasticsearch server which is installed on one server for rest of three rails servers also for searching?

Example:
I have one server(54.34.22.1) on which ES server installed. I have ssh into it and when i run 'curl 'localhost:9200/?pretty';, it shows me {.....(some text)}. It means ES server is working. I am able to search in my rails application which is running on (54.34.22.1) server. I have other 3 servers of rails application with ips(54.34.22.2,54.34.22.3 and 54.34.22.4). Now what i should do that rest of three server can use ES server of (54.34.22.1) on which ES installed?

**Comment by karmi** [comment]
So first, you should use a dedicated server for Elasticsearch by all means.

Otherwise, it's just a matter of properly configuring the client host, see https://github.com/elastic/elasticsearch-ruby/tree/master/elasticsearch-transport#setting-hosts. You need to make sure that the IP used is accessible from within your AWS environment, ie. you can `ping` or `curl` that server from your application servers.

**Comment by rick17** [comment]
Yes. when i executed curl 'http://0.0.0.0:9200/?pretty' its showing me  {.....(some text)} that means ES server is running. But when i do 'http://54.34.22.1:9200/?pretty', its showing 'curl: (7) couldn't connect to host'. So how i can run it on 54.34.22.1?

**Comment by karmi** [comment]
This is not a good forum for this question, because it's about basic networking aspects of AWS. You should consult the AWS documentation about how to access a server from another one, about the VPC aspect of AWS, and so on. And when all that fails, contact AWS support.
