### ISSUE TITLE
Alias method to search

### ISSUE THREAD

**Issue by yozzz** [elastic/elasticsearch-rails#559]
Is there any way to add alias for `search` method? Because I have already `search` method inside my model, in which i'm including:
```
 include Elasticsearch::Model
 include Elasticsearch::Model::Callbacks
```

**Comment by yozzz** [comment]
It can be done with `__elasticsearch__` proxy, so i'll close it.

**Comment by karmi** [comment]
Thanks! Yes, the proxy was designed specifically for this purpose -- see the example applications!
