### ISSUE TITLE
model.as_json with options returns empty hash

### ISSUE THREAD

**Issue by Animeye** [elastic/elasticsearch-rails#560]
Tested when using elasticsearch-persistence

Providing any options (specifically :only) to the serialization methods (to_json, as_json, serializable_hash) results in an empty hash.  Drilling down into it, I think this is because attributes() is returning a hash using symbols for keys, but the serialization methods convert the option parameters into strings:

```
# For something using Elasticsearch::Persistence::Model
obj.attributes
# {:id => 1}

# For an ActiveRecord model
obj.attributes
# {"id" => 1}
```

Changing attributes to give back a hash_with_indifferent_access seems to resolve the issue, but I haven't done much testing (and there is probably a better place to implement this):

```
# In the class that includes Elasticsearch::Persistence::Model
def attributes
  super.with_indifferent_access
end
```

**Comment by estolfo** [comment]
Closing as `Elasticsearch::Persistence::Model` has been deprecated and removed.
