### ISSUE TITLE
Mapping `_all` field in 2.2 version

### ISSUE THREAD

**Issue by dawidlenkiewicz** [elastic/elasticsearch-rails#563]
Hi

I got a multi model search and my configuration looks like:

```ruby
    settings analysis: {
      ...
    } do
      mappings do
        indexes "_all",
          type: "string",
          analyzer: "ngram_analyzer",
          search_analyzer: "whitespace_analyzer"
      end
    end
```

It all worked great on Elasticsearch 2.1 but breaks on 2.2 with:
```
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Failed to parse mapping [insurer]: Field [_all] is defined twice in [insurer]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [insurer]: Field [_all] is defined twice in [insurer]","caused_by":{"type":"illegal_argument_exception","reason":"Field [_all] is defined twice in [insurer]"}},"status":400}
```

How can fix it to index `all` fields?

**Comment by karmi** [comment]
Hi @dawidlenkiewicz, sorry for not getting to you sooner -- how did you solve it? I'm not aware of any significant breaking change between ES 2.1 and 2.2 which should cause it...

**Comment by dawidlenkiewicz** [comment]
@karmi Hi

I didn't configure it properly, the `_all` field has to be on the same level as `mappings`, not inside it.

So, changing my settings to:

```ruby
    } do
      mappings _all: {
        type: "string", analyzer: "ngram_analyzer", search_analyzer: "whitespace_analyzer"
      }
    end
```
Did the job and it works well.

The 2.2 version has a new validation to assert that mappings could not define the same field twice and it failed with my settings.

**Comment by karmi** [comment]
Yes, that is true! ES started adding these checks in the 2.x series, so that's why you get the error. Glad it has been solved!
