### ISSUE TITLE
rake 11+

### ISSUE THREAD

**Issue by dominicsayers** [elastic/elasticsearch-rails#566]
The test failure caused by rake 11.0 was fixed in rake 11.1 onwards.

Rather than pin rake to < 11 I believe you should pin it it rake ~> 11.1

Because other gems depend on rake 11 onwards, the consequence of what you did is to prevent bundler from upgrading `elasticsearch-model` past 0.1.8. I'm not sure this is what you intended.

More details:

1.  You pinned rake to < 11 in this commit https://github.com/elastic/elasticsearch-rails/commit/599b2952969876dd69777bd70bb40c7112ff3975
1.  The `last_comment` method was restored in rake 11.1 as documented here https://github.com/ruby/rake/blob/v11.1.0/History.rdoc
1.  The test failure was caused by the Yard gem's use of rake's deprecated `last_comment` method. The fix appears to relatively simple if you were inclined to submit a PR to them: https://github.com/lsegal/yard/blob/v0.8.7.6/lib/yard/rake/yardoc_task.rb#L69 (I'll do so myself if I can find time).

**Comment by karmi** [comment]
Hi @dominicsayers, thanks for the detective work! I guess I just hastily tried to "fix" the test failures, let me try with 11.1!

**Comment by karmi** [comment]
Thanks for reporting and all the pointers, @dominicsayers, updated the dependency, all seems well.
