### ISSUE TITLE
Update index for nested fields?

### ISSUE THREAD

**Issue by flyfy1** [elastic/elasticsearch-rails#570]
## What I have:

Product is the root document, and Variant is inside the `variants` of product, as nested array.

## Issue:

When I update the variant, the corresponding product document is not updated.

Any idea how to solve that?

**Comment by flyfy1** [comment]
My Current Solution:

    ## in the nested model:
    after_commit lambda { product.__elasticsearch__.index_document(parent: product_id) if product },  on: :create
    after_commit lambda { product.__elasticsearch__.update_document(parent: product_id) if product },  on: :update
    after_commit lambda { product.__elasticsearch__.delete_document(parent: product_id) if product },  on: :destroy

**Comment by karmi** [comment]
@flyfy1, yeah it makes sense to codify these nested updates like you do.
