### ISSUE TITLE
#create_index! produces error output under correct operation

### ISSUE THREAD

**Issue by dogweather** [elastic/elasticsearch-rails#571]
Given that there's no index, when this is executed:

``` ruby
klass.__elasticsearch__.create_index! force: true
```

then this is sent to stderr:

```
[!!!] Index does not exist (Elasticsearch::Transport::Transport::Errors::NotFound)
```

I believe that nothing should be sent to stderr in this particular case, because we've asked the lib to "create an index, over-writing any potentially existing one". And so there's no error when none exists.

I'm willing to contribute a PR if this issue is approved.

([Relevant code](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model/indexing.rb#L225))

**Comment by andyw8** [comment]
@dogweather any luck with solving this? I'm not super familiar with with ES but this message pollutes my test output.

**Comment by karmi** [comment]
Hi @andyw8, I think we've debated adding some "quiet mode" in some issue, but I don't recall the reference now.

Looking at the code now, it comes from `delete_index!`, where we should use the `ignore` option in the Elasticsearch client, instead of capturing the exception like this.

**Comment by webhive** [comment]
Any progress on it? Very annoying!

**Comment by Kani999** [comment]
Still not solved?

**Comment by shawndeprey** [comment]
Still running into this issue as well.

**Comment by estolfo** [comment]
@shawndeprey @Kani999 @andyw8 @dogweather how does [this solution](https://github.com/elastic/elasticsearch-rails/pull/868) look?
I use the client transport `logger` to log the message. That way, the user has control over whether it's printed via the log level.

**Comment by shawndeprey** [comment]
@estolfo If I understand what `client.transport` is this seems reasonable to me as this will follow the logging set in our application configuration. :+1:

**Comment by estolfo** [comment]
@shawndeprey `client.transport` is the client transport layer, which is where the `logger` would be set if you set one on an `Elasticsearch::Client`. That said, it sounds like we're on the same page = )

**Comment by estolfo** [comment]
Closing as this has been resolved in the linked PR.
