### ISSUE TITLE
How to define the settings of an implicitly-created index

### ISSUE THREAD

**Issue by lbrito1** [elastic/elasticsearch-rails#578]
One can easily define a dynamic `index_name` by passing a callable object to the method, as implemented in [this commit](https://github.com/elastic/elasticsearch-rails/pull/159/files) of `elasticsearch-rails`. A dynamic `index_name` implies indirect creation of indices by Elasticsearch as new data arrives and the `index_name` changes. However, there doesn't seem to be a simple way to call `settings` _right after the creation of a new index_. So we're effectively stuck with the default settings.

All the examples [here](https://github.com/elastic/elasticsearch-rails/blob/92f0148af8849dac154ee41bd1c3dd868b421b86/elasticsearch-model/lib/elasticsearch/model/indexing.rb#L189) presume a asynchronous call to the model, e.g. `Article.settings File.open("config/elasticsearch/articles.yml")`. This is fine when you're using a static `index_name`, but if the name changes then you should be able to define the new index's settings as well, am I right?

My personal motivation is that I have month-based indices being created dynamically: `index_name ->{ "#{base_index_name}_#{date_suffix}" }`. As new data arrives and the new indices are implicitly created by Elasticsearch, I need them to load the default settings in a yaml. I would expect some kind of hook that would be called after the creation of a new index.

**Comment by lbrito1** [comment]
I was unaware of the template API. This solves my issue.

https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html

**Comment by karmi** [comment]
@lbrito1, yeah, that's one of the options you have, and a pretty good one, if it's not convenient to create the indices in advance.

>  This is fine when you're using a static index_name, but if the name changes then you should be able to define the new index's settings as well, am I right?

In that case, you could define the settings/mappings in the model, in a module, constant, whatever like that, and just fetch it.
