### ISSUE TITLE
Sort order results are not sorted properly

### ISSUE THREAD

**Issue by michelson** [elastic/elasticsearch-rails#594]
Hi , I'm trying to sort by name, but I'm not getting the results properly sorted, I would like to know if anyone here got any ideas what is going on. the field I'm trying to sort is not_analyzed ,

the query is:

``` ruby
{:sort=>[{"name.raw"=>{"order"=>"asc"}}, "_doc"],
 :query=>
  {:filtered=>
    {:filter=>
      {:bool=>
        {:must=>
          [{:term=>{:account_id=>1}},
           {:bool=>{:should=>[], :minimum_should_match=>0}}],
         :must_not=>{:term=>{:state=>"deleted"}},
         :should=>[]}}}}}
```

when I get results the order is not right, if I inspect the sort attribute when I search results (not records) with  `Device.__elasticsearch__.search(query).results.map{|o| o["sort"]}` I get something like this:

```
[["Mic233", 1], ["Mich-MacBook-Pro", 0], ["Mich-MacBook-Pro", 10], ["juanito", 4], ["juanito", 5], ["juanito", 6], ["juanito", 8], ["mbair", 17], ["motorola XT1058", 15], ["my XT1058", 11]]
```

I've mapped the field as not_analyzed

``` ruby
      indexes :name, type: 'multi_field' do
        indexes :name, type: :string
        indexes :raw, index: :not_analyzed
      end
```

**Comment by jogaco** [comment]
The results are perfectly fine to me. They are sorted in ASCII then _doc. Uppercase codes go first than lowercase.
