### ISSUE TITLE
Feature request - after ES index Rails hooks

### ISSUE THREAD

**Issue by equivalent** [elastic/elasticsearch-rails#601]
I'm thinking about creating PR to elasticsearch-rails that will introduce triggering of hook methods after indexation to ES was accepted

so similar way how you have in rails `after_create` and `after_update` you would have `after_es_indexed`, `after_es_updated`, `after_es_deleted` (or any other suggested names)

I'm planing to call the hook methods from https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model/indexing.rb
- InstanceMethods#index_document
- InstanceMethods#update_document
- InstanceMethods#delete_document

...if the hook methods are defined on a model (so something like `model.try(:after_es_deleted)` ) 

the reason is that I have a situation that I need to know if something is ES indexed without the need to trigger request to ES  => the `after_es_updated` hook updated an instance attr_accessor attribute I can just rely on the information in memory "it was indexed" 

So before I spend time writing the PR can you give me some feedback if this is worthy to be introduced to the gem or not ? thx.

**Comment by equivalent** [comment]
counterargument for this proposal is that all I need to do is 


```ruby

  def index_document
    super
    update_suggestability_flag
  end

  def update_document
    super
    update_suggestability_flag
  end

  def update_suggestability_flag
     if something
      @suggestable = true
     else
      @suggestable = false
     end
   end
```

but would be cool to have this hooks native in gem so I could do 


```ruby
def after_es_update
   update_suggestability_flag
end
  
def after_es_indexed
  update_suggestability_flag
end
```

**Comment by estolfo** [comment]
Closing this as it's out of date.
