### ISSUE TITLE
Elasticsearch::Persistence ActiveRecord pattern: after_find callback not called

### ISSUE THREAD

**Issue by jogaco** [elastic/elasticsearch-rails#603]
This callback is good to customize behaviour after deserialization. Trouble is it is not called.

**Comment by karmi** [comment]
Hi @jogaco, sorry for the long delay on this one... I'll need some time to wrap my head around it. I'll ping you with questions when I have them.

**Comment by jogaco** [comment]
As reported in the PR, this is actually not a feature, but a non-implemented callback
https://github.com/elastic/elasticsearch-rails/blob/7aa03e87b7fee71007ff7aa1a6fb452de298587e/elasticsearch-persistence/lib/elasticsearch/persistence/model.rb#L38

**Comment by jogaco** [comment]
Any progress with this @karmi please? This is a show stopper.

For elasticsearch-persistence Repository Pattern, there is customizable deserialization:

https://github.com/elastic/elasticsearch-rails/blame/109c155df6c8b8989aa935bc1fe163a1452a2b4e/elasticsearch-persistence/README.md#L144-L148

For elasticsearch-persistence ActiveRecord Pattern, there is a promise for it in the defined Model callbacks. Only trouble is *it is not implemented*. My PR is just one line of code that **fulfils the promised declared callback**.

https://github.com/jogaco/elasticsearch-rails/blob/bce287ed35afb855e93eeebc3c5a7c363523c164/elasticsearch-persistence/lib/elasticsearch/persistence/model.rb#L119-L121

If there is need for additional modifications in code, or anything I can do to facilitate the PR mersing, please let me know and I'll do my best.

**Comment by postmodem** [comment]
Having this fix merged would be very beneficial to me as well. Any word on merging?

**Comment by estolfo** [comment]
Closing as the ActiveRecord persistence pattern has been deprecated.
