### ISSUE TITLE
Highlighter cuts off portion of result

### ISSUE THREAD

**Issue by emplumb** [elastic/elasticsearch-rails#605]
The highlighter function seems to be working properly for me, but depending on what word I search for, it may or may not cut off a portion of the result. As demonstrated in [this link](http://imgur.com/a/euba6), the first screenshot shows that I searched for the word "pass". It highlighted the correct result and returned the entire entry from my database. In the second screenshot, I searched for "andar", but the result is missing the entire first sentence of the last paragraph. 

I also tested my search without the highlighter enabled, but I have not had the same problems. Below is the search method in my model. Please let me know if more code is needed. Thanks

```
  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['name^7', 'definition^6', 'etymology1^5', 'etymology2^4', 'uses^3', 'notes1^2', 'notes2^1'],
            operator: 'and'
          }
        },
        highlight: {
          pre_tags: ['<em>'],
          post_tags: ['</em>'],
          fields: {
            definition: {},
            etymology1: {},
            etymology2: {},
            uses: {},
            notes1: {},
            notes2: {}
          }
        }
      }
    )
  end
```

**Comment by karmi** [comment]
Yeah, highlighter will only return "fragments" of the mathcing content, if you want to return the whole highlighted field, use the `fragment_size: 0` configuration in the highlighter. See the docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html#_highlighted_fragments

Also, the example applications in this repository contain examples how to achieve this with Ruby.

**Comment by emplumb** [comment]
Oh wow, that was really easy. I'm not sure how I missed that documentation, but thank you for your help

**Comment by math-on** [comment]
For those who may face this "problem" in the future: The correct approach seems to be ```number_of_fragments: 0```, as shown in the documentation linked by @karmi.

**Comment by estolfo** [comment]
Closing this as the [comment by karel above](https://github.com/elastic/elasticsearch-rails/issues/605#issuecomment-236436955) shows the solution.
