### ISSUE TITLE
Concurrency probem when running Cucumber test suite with Mongoid

### ISSUE THREAD

**Issue by Startouf** [elastic/elasticsearch-rails#609]
When running my test suite on CircleCI automated builds, I run into problems that seem to be related to concurrency of execution of Elasticsearch processes VS Rails process.

That is, if I run the test suite normally, tests fail because ES returns 0 results. If I wait long enough (1-2 sec) before resuming the execution, it works again.

During the test suite I create models with FactoryGirl that are indexed using the automatic Model::Callbacks, and I expect my search to return some occurences

``` ruby
FactoryGirl.create(:foo)
...
@response = Foo.search(@query).per(100)
puts @response.count # => 0
sleep(3)
puts @response.count # => 2
```

I saw [this similar issue](https://github.com/elastic/elasticsearch-rails/issues/298), but I'm not sure how to deal with Mongoid and a `DatabaseCleaner.strategy = :truncation`. 

Any tip ? Did I miss something in the doc ? Right now my temp fix is to `sleep(2)` after every FactoryGirl creation batch.
- Rails 5
- Mongoid 6
-  elasticsearch (1.0.17)
-  elasticsearch-api (1.0.17)
-  elasticsearch-model (0.1.9)
-  elasticsearch-rails (0.1.9)
-  elasticsearch-transport (1.0.17)

**Comment by jasdeepsingh** [comment]
I'm having the same issue - and I'm using just the `elasticsearch-persistence` part without Rails.

**Comment by jasdeepsingh** [comment]
Okay - I was able to solve this issue as follows, in case others are facing a similar issue:

```ruby
Repository.save(doc)
Repository.refresh_index!
expect(Repository.search('term').total).to be > 0
```

**Comment by estolfo** [comment]
Closing, as the solution is to refresh the index as mentioned in the last comment.
