### ISSUE TITLE
Pass retry_on_conflict parameter to update_document method

### ISSUE THREAD

**Issue by AliceOJJm** [elastic/elasticsearch-rails#613]
I am updating model asynchronously and am getting errors: Elasticsearch::Transport::Transport::Errors::Conflict [409] {"error":"VersionConflictEngineException[[products][4] [product][30201]: version conflict, current [84], provided [83]]","status":409}. 
In elasticsearch docs I've read that it can be fixed by supplying the retry_on_conflict parameter to partial update request, however I can't pass it to the method:
 documented_model.**elasticsearch**.update_document(retry_on_conflict: 1)
and get ArgumentError: URL parameter 'retry_on_conflict' is not supported
error. 
Is there any way to avoid conflicts?

**Comment by karmi** [comment]
Hi, on vacation, so cannot properly handle the issue, but the [`update_document`](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model/indexing.rb#L389) method should just pass the options to the [`update`](https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-api/lib/elasticsearch/api/actions/update.rb) method, can you check your gem and Elasticsearch versions? Also, unless you specify the version, Elasticsearch ignores it.

**Comment by madhurigr** [comment]
@karmi 
I also got the same issue and followed the same process as @AliceOJJm mentioned.
I was using elasticsearch-2.0.0 with elasticsearch-model 0.1.6 and elasticsearch-rails 0.1.6 gems. After reading above comment I have update elasticsearch-model 0.1.9 and elasticsearch-rails 0.1.9. But I am still getting the ArgumentError: URL parameter 'retry_on_conflict' is not supported error.
Any suggestion on this?

**Comment by violetaria** [comment]
@karmi I ran into this issue as well and I think it's due to the `else` part of the code in `update_document`.  If there are no changed_attributes detected, the code calls `index_document` then `index` which rejects the `retry_on_conflict` URL parameter.  

```ruby
       def update_document(options={})
          if changed_attributes = self.instance_variable_get(:@__changed_attributes)
            attributes = if respond_to?(:as_indexed_json)
              self.as_indexed_json.select { |k,v| changed_attributes.keys.map(&:to_s).include? k.to_s }
            else
              changed_attributes
            end

            client.update(
              { index: index_name,
                type:  document_type,
                id:    self.id,
                body:  { doc: attributes } }.merge(options)
            )
          else
            index_document(options)
          end
        end
```

**Comment by karmi** [comment]
@violetaria, err, that might be indeed true. I'm not happy with that part of the code, it's prone to subtle errors. I'll try to look into it.

**Comment by violetaria** [comment]
thanks for responding! Appreciate you looking into it :) Further inspection showed that we are falling into that else due to having additional methods added to the index via `as_indexed_json`.  We update the document through a has_many association `after_commit` callback which doesn't trigger the `update` since technically no attributes on the model have changed.  

Perhaps our implementation is odd, but for now we are working around it by calling `client.update` directly instead of `update_document`.
