### ISSUE TITLE
Elasticsearch::Transport::Transport::Errors::BadRequest with number_format_exception

### ISSUE THREAD

**Issue by dawidlenkiewicz** [elastic/elasticsearch-rails#617]
Hi

I need to index a model related with some dynamic data structure.
So my as_indexed_json method looks like:

``` ruby
def as_indexed_json(options={})
  as_json(include: { user_data: { only: :doc }})
end
```

Where the `doc` is a `jsonb` column.

Now I got an error with one of the fields when indexing data. It looks like:

```
[400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse [user_data.doc.test_field]"}],"type":"mapper_parsing_exception","reason":"failed to parse [user_data.doc.test_field]","caused_by":{"type":"number_format_exception","reason":"For input string: \"25a\""}},"status":400}
```

It looks like it is mapped to number and it's a problem like https://www.elastic.co/guide/en/elasticsearch/hadoop/current/mapping.html#_incorrect_mapping

But how can I solve it? Can I somehow force it to be mapped as string with the jsonb column?

**Comment by dandrews** [comment]
+1 same issue

**Comment by estolfo** [comment]
Closing as this question is out of date. Please reopen if it's still relevant.
