### ISSUE TITLE
undefined method `settings' for Elasticsearch::Model:Module (NoMethodError)

### ISSUE THREAD

**Issue by Startouf** [elastic/elasticsearch-rails#619]
You added a note in https://github.com/elastic/elasticsearch-rails/commit/5251a5201f0b3fa1278e4366e364f9aaded81be6 explaining we could use `Elasticsearch::Model.settings[:inheritance_enabled] = true` to not have to define the index name again in child classes, but it's not working ?

> undefined method `settings' for Elasticsearch::Model:Module (NoMethodError)

elasticsearch-rails (0.1.9)

**Comment by bananastalktome** [comment]
I had this issue too, and the problem is that this new feature is not yet available in the latest version (0.1.9).
