### ISSUE TITLE
Elasticsearch document inheritance search on base class

### ISSUE THREAD

**Issue by Startouf** [elastic/elasticsearch-rails#620]
With noSQL, inheritance can just be seen as adding extra fields to a JSON document (I am using Mongoid)

Given the following taxonomy

``` ruby
class Employee # Meant to be an abstract class : can only create Dev or Admin
  include Searchable::Employee
end
class Dev < Employee
  include Searchable::Employee::Dev
end
class Admin < Employee
  include Searchable::Employee::Admin
end
```

Both `Dev` and `Admin` are very similar in nature, it made sense to regroup them under the same index, but with a different `document_type` (which is also exactly what happens on MongoDB if I'm not mistaken : same collection but a `_type` field added in JSON)

Can I somehow perform a `Employee.search(...)` who would actually search that index, amongst all document_types and whose method `.records.records` would return a mongoid criteria for the `Employee` class ? It doesn't seem to work as the ES request seems to be looking for an 'employee' document_type.

```
Employee Search (247.0ms) {index: "employees-development", type: "employee"
# type: should be nil, or both 'dev,admin'
```

I really want that criteria so the multiclass search like in the readme isn't really an option for me

If I search on the specific class instance `Dev.search(...)`or `Admin.search(...)` it does work nicely, but searching on both via the inherited class no.

I feel like it should be quite easy to achieve what I want, but I'm afraid maybe the gem doesn't support it (nor plan to maybe). Would there be an easy monkeypatch to do in that case ?

Here is how I defined my Searchable modules

``` ruby
module Searchable::Employee
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model
    include SearchConfig

    index_name "employees-#{Rails.env}"
    # document_type 'employee,mentor' or nil ? Tried both, didn't really work
    # The idea would be just to search the employees index without any specific document_type condition, and have `Employees.search(...).records.records` return a Mongoid criteria

    def as_indexed_json
      # common fields for dev/admin
    end
  end

  module Dev # Searchable::Employee::Dev
    extend ActiveSupport::Concern

    included do
      include Searchable::Employee
      include Elasticsearch::Model::Callbacks

      index_name "employees-#{Rails.env}"
      document_type 'employee'

      mapping do
        # Employee mapping
      end

      # Override to add employee-specific fields
      def as_indexed_json(*)
        super.merge({
          # Dev specific fields
        })
      end
    end
  end

  module Admin # Searchable::Employee::Admin
    extend ActiveSupport::Concern

    included do
      include Searchable::Employee
      include Elasticsearch::Model::Callbacks

      index_name "employees-#{Rails.env}" # Has to be written again
      document_type 'mentor'

      mapping do
        # Admin mapping
      end

      def as_indexed_json(*)
        super.merge({
          # Admin specific fields
        })
      end
    end
  end
end
```

**Comment by Startouf** [comment]
Would it be acceptable to exclude the `type` parameter from the output query in case the document_type is set to nil or * ?

The following did the trick for me

https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model/searching.rb#L39

```ruby
base_query = if body
   { index: __index_name, body: body }.update options
else
  { index: __index_name, q: q }
end
base_query[type] = __document_type unless [nil, '', '*'].include?(__document_type)
@definition = base_query.update options
```
I'd be happy to make a PR with that if judged appropriate

**Comment by dgmora** [comment]
@Startouf A bit late, but you might be interested:  I implemented something similar [here](https://github.com/moviepilot/elasticsearch-rails/commit/af34a0287bf477f7b8948057db0c78776a1db975)

. I could not manage to use a different document type, as then when you searched the base class, it could not find the subclasses.

**Comment by estolfo** [comment]
Closing as this question is out of date.
