### ISSUE TITLE
[Feature Request] Return the tokens of a field when do a search

### ISSUE THREAD

**Issue by zw963** [elastic/elasticsearch-rails#623]
How can I have the tokens of a search keyword returned in the search scope result?

Thanks.

**Comment by vikramjadon921995** [comment]
@zw963 One way that you can do it is by feeding it to the [Analyze API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-analyze.html).

For example: `curl -XGET 'localhost:9200/twitter/_analyze?text=trying out Elastic Search'`

You can also use scripting which will give you analyzed data of an elasticsearch query.

For example: 
```
curl 'http://localhost:9200/index_name/_search?pretty=true' -d '{
    "query" : {
        term: {
          _id: 1
        }
    },
    "script_fields": {
        "terms" : {
            "script": "doc[field].values",
            "params": {
                "field": "message"
            }
        }
    }
}'
```
For the above method, you have to enable scripting in elasticsearch.

**Comment by zw963** [comment]
Thanks, I will do a try for `scripting` function.

**Comment by estolfo** [comment]
Closing as the question is resolved.
