### ISSUE TITLE
[PERSISTENCE] Ruby Float should correspond to Elasticsearch double

### ISSUE THREAD

**Issue by Animeye** [elastic/elasticsearch-rails#626]
The Ruby Float class is in fact a double-precision floating point value, not single-precision.  Because of this, when mapping the attribute information for elasticsearch-persistence, the Float class should become 'double', rather than 'float' in order to avoid loss of precision

Ruby Float documentation: https://ruby-doc.org/core-2.2.0/Float.html
Line of code mapping the Ruby Float type to the Elasticsearch float type: https://github.com/elastic/elasticsearch-rails/blob/a714d5931182501531d2ce6b767bcb3c97ce56a7/elasticsearch-persistence/lib/elasticsearch/persistence/model/base.rb#L76

**Comment by estolfo** [comment]
Closing as the `ActiveRecord` persistence pattern has been deprecated and removed.
