### ISSUE TITLE
Unique values in the field of an index

### ISSUE THREAD

**Issue by vikramjadon921995** [elastic/elasticsearch-rails#627]
I have an index of a following type:

`{
  company: {
    watchlist: [ {id: 1}, {id: 2}, {id, 1} ]
  }
}`

In the watchlist array in the indexes, duplicate values are stored. I want the indexes not to store duplicate values as this is increasing the size of my index.

I know that i can get unique values by calling aggregation, but what I want to do here is to store unique values in the index.

I am using elasticsearch rails here, it indexes data according to the json returned from 'as_indexed_json' method. The data for the above index is in sql database, which i cannot change. I can only create indexes from that database, so i need some 'uniqueness' constraint on the field 'watchlist'.

Is there a way to do it?

**Comment by vikramjadon921995** [comment]
Sometimes, elasticsearch is used as primary datastore also. I think, there should be a way to include only the unique values in the fields of indexes.

**Comment by estolfo** [comment]
Closing as this question is out of date.
