### ISSUE TITLE
How do I add synonyms to a model?

### ISSUE THREAD

**Issue by klaut** [elastic/elasticsearch-rails#63]
Hi all,

I am not sure how to do this:
I have an ActiveRecord that has some attributes indexed. I would like to add the synonyms for some of these fields but I am not sure how to do this.. should it be put inside the mappings block? is it even possible to do that with this gem?

Thank you in advance!

**Comment by daino3** [comment]
Hi guys. I'm not sure if this should be a new issue, or remain on this thread, but I'll mention it here and go from there. 

In the example above, multi-word synonyms are being treated as single terms ("web developer" ~> "web", "developer"). How would we incorporate / treat multi-word synonyms? The [docs mention contraction](http://www.elastic.co/guide/en/elasticsearch/guide/current/multi-word-synonyms.html#_use_simple_contraction_for_phrase_queries), but don't give code / json examples of how to incorporate these.
