### ISSUE TITLE
[RAILS] Datetime object not properly hydrated from index, reads as string

### ISSUE THREAD

**Issue by coneybeare** [elastic/elasticsearch-rails#633]
I have an indexed field defined as `:date` that is a method to determine which `DateTime` object to store.

``` ruby
settings index: { number_of_shards: 1 } do
    mapping do
      ...
      indexes :date,            index: :not_analyzed, type: 'date'
      ...
    end
end
```

And in my `as_indexed_json` I have it listed under `:methods` 

``` ruby
def as_indexed_json(options = {})
  self.as_json(
    ...
    methods: [:full_text, :tag_list, :category_list, :date, :month, :year],
    ...
  )
end
```

It properly indexes the desired value as `"date": "2016-05-19T09:43:09-04:00"` but when I read the value after searching, the date comes back as class `String` instead of any of the date classes. 

I have fiddled with some of the [`format`](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html) values on that field, but it appears that that only adjusts the setting and understanding of the value, rather than the reading and class hydration of them. How can I get this `date` value to read back as a `DateTime`? Is this a bug in `elasticsearch-rails`?

**Comment by coneybeare** [comment]
If this is not the correct place for help on determining if this is a bug or not, can the mods please point me in the right direction?

**Comment by karmi** [comment]
Hi, is this a `elasticsearch-persistence` or an `elasticsearch-model` model? In the former case, `attribute` is the right way to set the property, in the latter case, the library doesn't automatically translate date-like formatted strings into Date/Time objects, that's something to be done in the application.

**Comment by coneybeare** [comment]
`elasticsearch-model`. Thanks for confirming that. I use the same rails partials for displaying an ElasticSearch result and a ActiveRecord model, so littering my view code with tons of type checking and conversion formatting would not be beneficial. Is there any sort of callback or hook I can get into on the search results before wrapping in a `Elasticsearch::Model::Response::Response` that I could use for one-time conversions?

**Comment by estolfo** [comment]
I would suggest creating a "virtual attribute" in this case -- a method that conditionally translates the raw data to the desired object type/format.
