### ISSUE TITLE
Multiple mappings is not working for me

### ISSUE THREAD

**Issue by m-nasser** [elastic/elasticsearch-rails#635]
Im trying multiple mappings for the same model but I ain't able to do so.

```
include Elasticsearch::Model
Spree::Product.index_name 'motorcycles'
  mapping retail: {} do
      indexes  :model_id, type: 'string', index: "not_analyzed"
      indexes :mileage, type: "float"
      indexes :price, type: "float"
      indexes :wholesale_price, type: 'float'
      indexes :sku, type: 'string'
      indexes :created_at, type: 'date'
      indexes :family_id, type: 'long'
      indexes :coordinates, type: 'geo_point' 
  end
  mapping wholesale: {} do
      indexes  :model_id, type: 'string', index: "not_analyzed"
      indexes :mileage, type: 'float' 
      indexes :price, type: 'float' 
      indexes :wholesale_price, type: 'float' 
      indexes :sku, type: 'string' 
      indexes :created_at, type: 'date' 
      indexes :family_id, type: 'long'
      indexes :coordinates, type: 'geo_point' 
  end
```

here's my code but when I try creating the index I get this error `Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [wholesale : {}] [retail : {}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [product]: Root mapping definition has unsupported parameters:  [wholesale : {}] [retail : {}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [wholesale : {}] [retail : {}]"}},"status":400}
from /Users/Nasser/.rvm/gems/ruby-1.9.3-p194/gems/elasticsearch-transport-2.0.0/lib/elasticsearch/transport/transport/base.rb:201:in __raise_transport_error'`

**Comment by estolfo** [comment]
Closing as this question is out of date.
