### ISSUE TITLE
Elasticsearch::Model.search multimodel always returns 10 records.

### ISSUE THREAD

**Issue by bhushangahire** [elastic/elasticsearch-rails#645]
How do I override this ?

**Comment by henrikholm89** [comment]
If you use the query DSL, you can do it like this, 

```
{
        size: 20,
        query: {
          bool: {
            must: [
              { match: { name: { query: query } } },
              { match: { country_id: country.id } },
              { match: { crowd_sourced: true } },
              { match: { deleted: false } },
            ],
          }
        }
      }
```

The size parameter determines how many documents elastic search will return for you.

**Comment by lostapathy** [comment]
At @bhushangahire did that take care of the issue for you, and if not can you provide a little larger snippet of an example of how you're using the library?

**Comment by bhushangahire** [comment]
Yes, I used similar DSL but we built custom code to build DSL dynamically.

**Comment by lostapathy** [comment]
Great!  Is there anything else you need or can you close this issue?
