### ISSUE TITLE
Document de-serialization fails when non-attributes are present in "_source"

### ISSUE THREAD

**Issue by agis** [elastic/elasticsearch-rails#646]
Doing the following in a model:

```ruby
# app/models/person.rb
class Person
  # ...
  def as_json(options = {})
    super(options).merge(foo: "bar")
  end
end
```

...where `foo` is *not* an ActiveRecord attribute, will result in the following error when elasticsearch-persistence attempts to deserialize the document:

```ruby
ActiveRecord::UnknownAttributeError: unknown attribute 'foo' for Person.
        from /gems/activerecord-4.2.5.2/lib/active_record/attribute_assignment.rb:59:in `rescue in _assign_attribute'
        from /gems/activerecord-4.2.5.2/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
        from /gems/activerecord-4.2.5.2/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
        from /gems/activerecord-4.2.5.2/lib/active_record/attribute_assignment.rb:35:in `each'
        from /gems/activerecord-4.2.5.2/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
        from /gems/activerecord-4.2.5.2/lib/active_record/core.rb:566:in `init_attributes'
        from /gems/activerecord-4.2.5.2/lib/active_record/core.rb:281:in `initialize'
        from /gems/activerecord-4.2.5.2/lib/active_record/inheritance.rb:61:in `new'
        from /gems/activerecord-4.2.5.2/lib/active_record/inheritance.rb:61:in `new'
        # ...

```

This happens since `#deserialize` attempts to construct an ActiveRecord object using all the attributes from "_source" in [here](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/lib/elasticsearch/persistence/repository/serialize.rb#L25).

We could fix this by only passing the current model's attributes. What do you think? If this sounds good I could prepare a PR.

P.S. I'm on elasticsearch-persistence 0.1.7 but I guess this happens in the latest versions too.

**Comment by estolfo** [comment]
Closing as this is out of date.
