### ISSUE TITLE
String deprecated by ES5.x

### ISSUE THREAD

**Issue by jalberto** [elastic/elasticsearch-rails#648]
Elastisearch 5.x don't use String on mappings anymore but text or keyword but current gem cannot define this attribute types as constants Text or Keyword doesn't exists.

What is the recommended way to do something like:

```
attribute :foo, Text
attribute :bar, Keyword
```

**Comment by jalberto** [comment]
as I see here: http://www.rubydoc.info/gems/elasticsearch-persistence/Elasticsearch/Persistence/Model/Utils#lookup_type-class_method

there is not support for new mapping type in ES5 right now, but gem versoins claims to be 5.x compatible

**Comment by jalberto** [comment]
I guess the workaround for now is to explicitly defien the mapping:

```
attribute name, String, mapping: { type: 'text' }
```

But I wonders if this keeps the defautl ES behaviour of creating a keyword subfield

**Comment by mnoack** [comment]
@jalberto It has been fixed in https://github.com/elastic/elasticsearch-rails/commit/ffc1aa4e0a566d9deeee56e3f636ffc060c9ec07

So alternatively you can fix it by pointing to the master branch, but perhaps @karmi can cut a release or is planning something, after all the last release was May 2016

**Comment by jalberto** [comment]
IMHO the AR pattern casue too many headaches, it's easier to get rid of it and use the repository pattern  as it's closer to ES

**Comment by karmi** [comment]
Hi all, I've recently fixed all the examples, and indeed changed the default type to `text`.

@mnoack, yes, I agree, the releases are really behind, apologies for that, I'll push new releases soon.

And agreed with @jalberto, the ActiveRecord pattern for persistance has been and is a source of so many headaches. I'm now working on rewriting the [example application](https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-persistence/examples/music) from ActiveRecord to the Repository pattern, and seriously considering deprecating the former in favour of the latter.

**Comment by Animeye** [comment]
This change breaks compatibility with ES versions prior to 5.  The gem claims to support "Elasticsearch 1.0 (or higher)", but with the switch to use "text" instead of "string", it now actually only supports 5.x or higher.
