### ISSUE TITLE
Repository count method still uses deprecated search_type=count

### ISSUE THREAD

**Issue by loren** [elastic/elasticsearch-rails#654]
https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/lib/elasticsearch/persistence/repository/search.rb#L78

https://www.elastic.co/guide/en/elasticsearch/reference/5.1/breaking_50_search_changes.html#_literal_search_type_count_literal_removed

**Comment by estolfo** [comment]
This issue is no longer relevant. The repository uses the `#count` api on the client. Please see [this line](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/lib/elasticsearch/persistence/repository/search.rb#L96).
