### ISSUE TITLE
Rake import:model throws an BadRequest error

### ISSUE THREAD

**Issue by gretch** [elastic/elasticsearch-rails#655]
Elasticsearch version **5.1.1**

**Running this command will throw a BadRequest error**
rails new searchapp --skip --skip-bundle --template https://raw.github.com/elasticsearch/elasticsearch-rails/master/elasticsearch-rails/lib/rails/templates/03-expert.rb

rake aborted!
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [multi_field] declared on field [user_location]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [article]: No handler for type [multi_field] declared on field [user_location]","caused_by":{"type":"mapper_parsing_exception","reason":"No handler for type [multi_field] declared on field [user_location]"}},"status":400}
Tasks: TOP => elasticsearch:import:model

**Comment by dandrews** [comment]
+1 same issue

**Comment by clschalkwyk** [comment]
As a test I changed "multi_field" to "text", now I have other issues but with a different module.

**Comment by karmi** [comment]
Correct, the most immediate problem is the `type: 'multi_field'` setting in the mapping. Simply changing it to "text" isn't enough to make the application run, as @clschalkwyk writes.

I'll have a look into the application templates and make them run on Rails 5 & Elasticsearch 5 in the next days.

**Comment by karmi** [comment]
I've spent some time with the templates and Rails 4 & 5 and Elasticsearch 5, and all the templates should be now fixed and work for _both_ Rails and Elasticsearch version 5. Importantly, the _tests_ have been fixed as well, so the application templates are again the main entry point for anybody learning the Rails integration for Elasticsearch.

Can you please try the current `master` and report any issues? Thanks!
