### ISSUE TITLE
Disable Elastic search as whole or Indexing temporarily 

### ISSUE THREAD

**Issue by MuneebSarfraz94** [elastic/elasticsearch-rails#656]
I have integrated Elasticsearch in my ROR project. i want to disable elasticsearch if a specific flag value is 1 and enable if flag value is 0. How can i do that is there any specific method to disable indexing of elasticsearch.

**Comment by Meekohi** [comment]
Seems the same as #643

**Comment by karmi** [comment]
@MuneebSarfraz94 There's an example in the ["Custom Callbacks"](https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-model#custom-callbacks):

```ruby
after_commit on: [:create] do
    __elasticsearch__.index_document if self.published?
end
```
Is this what you're after?
