### ISSUE TITLE
Support suggestion with context

### ISSUE THREAD

**Issue by mchaver** [elastic/elasticsearch-rails#657]
https://www.elastic.co/blog/elasticsearch-1-2-adding-context-suggestions

It looks like elasticsearch supports context to suggestions, but I'm not sure if the elasticseach-rails gem supports this or not. I don't think there are any examples in this project either. If it is possible to add context to a suggestion, could you add an example? Otherwise, what is the possibility of supporting context in suggestions?

```
User.__elasticsearch__.client.suggest(
  index: User.index_name,
    body: {
      suggest: {
        text: "f",
        completion: {
          field: "suggest_name",
          context: {
            is_logged_in: false
          }
        }
     }
  })
```

```
> {"suggest":{"text":"f","completion":{"field":"suggest_name","context":{"is_logged_in":false}}}}
< {"_shards":{"total":5,"successful":0,"failed":5,"failures":[{"shard":0,"index":"dev_users","status":"INTERNAL_SERVER_ERROR","reason":{"type":"exception","reason":"failed to execute suggest","caused_by":{"type":"illegal_argument_exception","reason":"suggester [completion] doesn't expect any context"}}}]}}
[500] {"_shards":{"total":5,"successful":0,"failed":5,"failures":[{"shard":0,"index":"dev_users","status":"INTERNAL_SERVER_ERROR","reason":{"type":"exception","reason":"failed to execute suggest","caused_by":{"type":"illegal_argument_exception","reason":"suggester [completion] doesn't expect any context"}}}]}}
Elasticsearch::Transport::Transport::Errors::InternalServerError: [500] {"_shards":{"total":5,"successful":0,"failed":5,"failures":[{"shard":0,"index":"dev_users","status":"INTERNAL_SERVER_ERROR","reason":{"type":"exception","reason":"failed to execute suggest","caused_by":{"type":"illegal_argument_exception","reason":"suggester [completion] doesn't expect any context"}}}]}}
```

**Comment by bublik** [comment]
latest versions has been changed, and context is removed 
https://www.elastic.co/guide/en/elasticsearch/reference/5.2/search-suggesters-completion.html

**Comment by arturtr** [comment]
@bublik what about this?
https://www.elastic.co/guide/en/elasticsearch/reference/current/suggester-context.html

**Comment by yozzz** [comment]
@karmi can you provide some information about using context suggestions?

**Comment by murat** [comment]
@arturtr is right, suggestion API is available with the `contexts` in the latest version, we can use completion suggestion API like followings:

```ruby
class Model < ActiveRecord::Base
    include Elasticsearch::Model

    settings index: { number_of_shards: 1 } do
        mappings dynamic: "true" do
            indexes :name, type: "text" do
                indexes :keyword, type: "keyword"
                indexes :suggest, type: "completion"
            end
        end
    end
end
```

and

```ruby
suggestions = Model.search(suggest: {
    suggestion: {
        prefix: "test",
        completion: {
            field: "name.suggest",
            size: 10
        }
    }
}).results.as_json.map { |r| r["suggest"]["suggestion"][0]["options"].map { |opt| opt["_source"] } }.flatten
```

however, I could not define the `contexts` in the Model. is there a syntax for using the `indexes` keyword with `context` option?

**Comment by estolfo** [comment]
Hi @murat Would you mind showing an example of the request you'd like to make in Ruby or just the raw document so I'm clear on what you're are asking about? Thanks!

**Comment by murat** [comment]
Hi @estolfo I would like to set up my index for use the context suggester [like here.](https://www.elastic.co/guide/en/elasticsearch/reference/current/suggester-context.html) But I don't know how to define my contexts.

**Comment by estolfo** [comment]
@murat Have you resolved this?

**Comment by murat** [comment]
Hi @estolfo I resolved that with `match` filter. Thanks..

**Comment by estolfo** [comment]
ok great. I'll close this then.

**Comment by msojka** [comment]
Has the support for `contexts` been added?

**Comment by lucasklaassen** [comment]
> I resolved that with match filter. Thanks..

@murat can you explain what you mean by this? 

We are trying to use context suggestions and need to define this within our mapping but it doesn't appear that the elasticsearch-model gem supports nested values for mappings besides for `nested` or `object` types. See here: 
https://github.com/elastic/elasticsearch-rails/blob/main/elasticsearch-model/lib/elasticsearch/model/indexing.rb#L57

Trying to [recreate what the docs show](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/suggester-context.html):

```
"mappings": {
        "_doc" : {
            "properties" : {
                "suggest" : {
                    "type" : "completion",
                    "contexts": [
                        { 
                            "name": "place_type",
                            "type": "category"
                        },
                        { 
                            "name": "location",
                            "type": "geo",
                            "precision": 4
                        }
                    ]
                }
            }
        }
    }
 ```
 
Where `contexts` is an array of values under the `suggest` object.

Is there a way we can override the `mappings` method and just return the mappings raw value maybe?

**Comment by BeubeuCode** [comment]
Just in any case another developer comes by this issue, I fixed it using the `dynamic_templates` argument to the mapping :
```ruby
        dynamic_templates = [{
          suggest: {
            type: completion,
            contexts: [
              {
                name: 'ig',
                type: 'category',
                path: 'ig'
              }
            ]
          }
        }]
