### ISSUE TITLE
ActiveRecord / Arel 3 failures

### ISSUE THREAD

**Issue by karmi** [elastic/elasticsearch-rails#661]
ActiveRecord 3 integration tests are failing due to Arel error: `Cannot visit Integer (TypeError)`.

This short script replicates the error:

```ruby
gem 'arel', '3.0.2'
gem 'activerecord', '3.2.22.5'

# gem 'arel', '6.0.4'
# gem 'activerecord', '4.2.7.1'

require 'logger'
require 'active_record'

ActiveRecord::Base.establish_connection( :adapter => 'sqlite3', :database => ":memory:" ) unless ActiveRecord::Base.connected?

ActiveRecord::Schema.define(version: 1) do
  create_table :posts do |t|
    t.string     :title
  end
end

ActiveRecord::Base.logger = Logger.new(STDERR)

class Post < ActiveRecord::Base
end

puts "ActiveRecord [#{ActiveRecord::VERSION::STRING}]"

Post.create(title: 'Test')
# => #<Post id: 1, title: "Test">

puts '> Post.find_in_batches { |b| p b }', ''

results = Post.find_in_batches { |b| p b }
puts results

# => TypeError: Cannot visit Integer
require 'pry'; binding.pry;
```

Since Rails 3 is [no longer supported](http://rubyonrails.org/maintenance/), we should probably remove the support and the corresponding Gemfile.

**Comment by mangeshdevare** [comment]
Getting same problem when updating a model.. Is there any way around

**Comment by mangeshdevare** [comment]
hi @karmi , I am currently working on a program, but due to this error I am stuck there, Is there aany way around for different version of gem or anything?

**Comment by estolfo** [comment]
This error was due to incompatible versions of Ruby and Rails. Please see this [Stackoverflow post](https://stackoverflow.com/questions/44053672/simple-rails-app-error-cannot-visit-integer).
