### ISSUE TITLE
How to prevent some attributes to be stored in ES

### ISSUE THREAD

**Issue by phlegx** [elastic/elasticsearch-rails#662]
Hi!

I use **ES v5.1**, **elasticsearch-rails** and **elasticsearch-model** gem **v0.1.9**. How can I prevent some ActiveRecord attributes to be stored in ES in my mapping configuration?

I have tried `enabled: false` and `index: false` but without success. I don't want to store `created_at` and `updated_at` in ES.

So, how should my mapping look like?

```ruby
settings do
    mappings dynamic: false do
      indexes :created_at, enabled: false
      indexes :updated_at, enabled: false
      indexes :locale, type: :keyword
      ...
    end
end
```

**Comment by MaxDBN** [comment]
I think what you're looking for is the as_indexed_json method, here's an example:

```
def as_indexed_json(options = nil)
    self.as_json( only: [ :created_at, :update_at, :locale )
end
```

**Comment by phlegx** [comment]
Thx! :+1: :smile:
