### ISSUE TITLE
How to set enabled: false to field

### ISSUE THREAD

**Issue by phlegx** [elastic/elasticsearch-rails#663]
Hi!

I use **ES v5.1**, **elasticsearch-rails** and **elasticsearch-model** gem **v0.1.9**. How can I set `enabled: false` to a field in my mapping configuration like described [here](https://www.elastic.co/guide/en/elasticsearch/reference/5.1/enabled.html)?

https://www.elastic.co/guide/en/elasticsearch/reference/5.1/enabled.html

**Comment by arunn** [comment]
I don't know if you still need this information. But the following way should work for the `enabled: false` thing.

      settings do

         mappings do

              indexes :stored_unindexed_data, enabled: false, type: "object"

         end

     end

**Comment by estolfo** [comment]
Closing as the last comment shows the solution.
