### ISSUE TITLE
elasticsearch-ruby downgraded from 5.0.1 to 1.1.2

### ISSUE THREAD

**Issue by sailman** [elastic/elasticsearch-rails#665]
Elasticsearch: 5.1.1
rails: 5.0.1
elasticsearch-rails: head

-  s.add_dependency "elasticsearch",       '> 0.4'
 +  s.add_dependency "elasticsearch",       '~> 1.1'

After this commit these gems was downgraded:

elasticsearch-api 1.1.2 (was 5.0.1)
elasticsearch 1.1.2 (was 5.0.1)
elasticsearch-transport 1.1.2 (was 5.0.1)

Readme says elasticsearch-ruby 1.1 gem is compatible only Ealsticsearch 1.x.
How can i use this gem with Ealsticsearch 5.x?

**Comment by karmi** [comment]
I've recently did some major re-shuffling of versions and fought with dependency hell on Travis, so here might be some side effect.

Can you post more details, as the relevant portion of your Gemfile (or the whole Gemfile) and what change resulted in the problem?

**Comment by sailman** [comment]
gemfile:
gem 'elasticsearch-model', git: 'https://github.com/elasticsearch/elasticsearch-rails.git'
gem 'elasticsearch-rails', git: 'https://github.com/elasticsearch/elasticsearch-rails.git'

I just ran bundle update.

This commit results the change:
https://github.com/elastic/elasticsearch-rails/commit/db2cd1cccecea678457f90142c0d00240799fb19

```
-s.add_dependency "elasticsearch", '> 0.4'
+s.add_dependency "elasticsearch", '~> 1.1'
```

Before elasticsearch was resolved 5.0.1 (because of: '> 0.4')
Now elasticsearch is resolved: 1.1.2 (beacouse of:  '~> 1.1')

Why is this dependency change?

**Comment by karmi** [comment]
Ah, right, thanks for the details, now I remember.

Yes, this is (unfortunately) expected based on the commit. I'll go and relax the requirement, there's (unfortunately) not a better fix at the moment.

Regarding the reason for the change, it was done in the middle of Travis fixing, so my line of thinking probably went along something like "the Rails integration hasn't been properly upgraded in all corners for Elasticsearch 5.x, so let's pin it to 1.x lineage". Not my brightest moment I think :)

**Comment by karmi** [comment]
I've just pushed commits with the relaxed dependency specification, can you please check?

**Comment by sailman** [comment]
Thanx, now installs latest elasticsearch-ruby gem.

**Comment by alepore** [comment]
@karmi it's normal that `elasticsearch-model` 2.x depends on `elasticsearch` 1.x? https://github.com/elastic/elasticsearch-rails/blob/2.x/elasticsearch-model/elasticsearch-model.gemspec#L26

**Comment by karmi** [comment]
@alepore, it isn't :) There's a PR at https://github.com/elastic/elasticsearch-rails/pull/702 which I'm gonna merge soon. These are some unfortunate side effects of making the support matrix a bit predictable in both the Ruby client and Rails integration...
