### ISSUE TITLE
update_document doesn't work as it should while being called from a callback

### ISSUE THREAD

**Issue by MaxDBN** [elastic/elasticsearch-rails#669]
- I have a model that is being updated several times within a running job, after being created.
- Indexing after creation is working as it should, I can see the document in Elasticsearch.
- The problem is that when the document should be updated, it only updates certain attributes. 
- If I execute the `__elasticsearch__.update_document `method from the console, it works as it should and all the attributes are updated.
- Tried using `include Elasticsearch::Model::Callbacks`, as well as custom callbacks.

You can see the settings I use in my model down below.
**best_price, first_offer_date, last_offer_date** are not updated from the callback.

I tried adding them to the mapping, but it had no difference.

**EDIT:** What did work is replacing  `__elasticsearch__.update_document` for `__elasticsearch__.index_document refresh: true`
The question is, **will it impact Elasticsearch perfomance or has any other issue I should be worried about?**

```
settings index: { number_of_shards: 2 } do
    mapping dynamic: false do
      indexes :user_id, type: :integer
      indexes :initial_price, type: :float
      indexes :saving_amount, type: :float
      indexes :distance, type: :string
      indexes :departure_datetime, type: :date
      indexes :created_at, type: :date
      indexes :origin_station_id, type: :integer
      indexes :destination_station_id, type: :integer
    end
  end

  def as_indexed_json(options = nil)
    self.as_json(
      only: [
        :id,
        :user_id,
        :initial_price,
        :saving_amount,
        :departure_datetime,
        :created_at,
        :status
      ],
      methods: [
        :best_price,
        :first_offer_date,
        :last_offer_date
      ],
      include: [
        :user,
        :origin_station,
        :destination_station,
        :last_report,
        :last_offer
      ]
    )
  end
```

This is my concern:

```
after_commit on: [:create] do
    __elasticsearch__.index_document
 end

after_commit on: [:update] do
    __elasticsearch__.update_document
end

 after_commit on: [:destroy] do
     __elasticsearch__.delete_document
end
```

I stumbled upon these old issues but the suggestions there help me.

- https://github.com/elastic/elasticsearch-rails/issues/499 
- https://github.com/elastic/elasticsearch-rails/issues/232

**Comment by faliev** [comment]
Any updates on this?

**Comment by pmaksimenko** [comment]
@faliev if your application has STI try to add
```
index_name "your_index_name"
document_type 'you_model_name'
```
to all your STI models.

**Comment by faliev** [comment]
I ended up doing it myself with callbacks with after_commit hook, but that was for older gem version. Thank you!
