### ISSUE TITLE
OO structure is really weird

### ISSUE THREAD

**Issue by Overbryd** [elastic/elasticsearch-rails#670]
> Please take this as criticism, just don't take it personally.

The class structure chosen for `Elasticsearch::Persistence::Repository` is more than weird. While it seems to allow for certain niceties like `Elasticsearch::Persistence::Repository.new do ... end` it certainly breaks any idiomatic assumption on how Ruby works.

My main critique is that this yields highly unexpected behaviour.

For example, I am trying to do create a `class FooRepository < BaseRepository` class structure, to model my repositories.

This inherently breaks, since this "Gateway" construction (you could have used standard Ruby OO tools) only ever refers to "added" methods where it was included. This breaks the complete method lookup/inheritance chain Ruby is providing.

The culprit can be found here: https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/lib/elasticsearch/persistence/repository.rb#L59

I think there is no way around this, since this gem has been released to the wild.

If there are any plans on changing this, you could save me from a fork and maybe provide the chance to rework this into a sane structure. I am willing to help. I prefer a simple `include ...` and extend into existing classes rather than reinventing a quirky delegation pattern with this "Gateway" thing.

**Comment by karmi** [comment]
Hi Lukas, thanks for the critique!

I agree that some of the constructs of the `Repository` implementation are quite uncommon, and it's certainly maybe "too much" acrobatics at times...

However, the motivation is exactly the thing you hint at: to allow a lot of flexibility when it comes to [creating a custom class](https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-persistence#a-custom-class) in user code, either by the "configuration via block" pattern, or via the "model mixin" pattern. So far, I've been happy with the look-and-feel of the usage, eg. in the [example applications](https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-persistence/examples).

You're correct that it has not been designed with the standard class inheritance pattern in mind, and I guess there may be certain spots where it breaks. Nonetheless, when quickly fooling around with it now inside a `pry` session, it seems to behave mostly well (defining a repository class, storing documents, ...), so maybe with a bit of refactoring, it can be smoothed out.

But, most importantly, if you have a concrete usage or requirement in mind, where the library stands in your way, do share it here (or in another issue), and I'll try to assist you, either by finding a way of doing that with the current implementation, or changing the library, if time allows. In other words: I usually need a working (or broken) Ruby code to be able to wrap my mind around it and find a solution.

**Comment by karmi** [comment]
I forgot to add that any refactoring which would make the design/structure more "OO", and which would _not_ prevent the current usage patterns :), is highly appreciated and welcomed!

**Comment by Overbryd** [comment]
I find some beauty in separating different Persistence/DB-Layers from the main Model code.
So in order to support this on my application I wrote the following "Base" class.
I incorporated the Singleton idea. The only special code is that I infer the `class_name` from the repository class name. That can be removed for a more generalised implementation.

If you think this would represent a valid way, I can imagine this could replace the Gateway construct.
This implementation below incorporates some overrides that I found directly useful for my own application.

For me the convenience lies within having a base class that can hold a base configuration for all its subclasses. In the following example, I am making use of that when looking up a `client`.

```ruby
  def client(setter = nil)
    @client = setter if setter
    @client || self.class.superclass.respond_to?(:client) ? self.class.superclass.client : nil
  end
```

This could be generalised into something that makes the attributes of these singletons configurable, yet they can lookup missing configuration pieces from their ancestors.

Here is the code I got so far:

```ruby
# Configuring it
BaseRepository.client = Elasticsearch::Client.new('http://localhost:9200')

# Subclassing other repositories
class ProductRepository < BaseRepository
  settings do
    mapping(dynamic: false) do
      indexes :name
      indexes :description, analyzer: 'english'
    end
  end

  # now you can simply override anything inherited from BaseRepository
  def serialize(obj)
    custom_code || super
  end
end

# Using these singleton repositories
Product.find_each do |product|
  ProductRepository.save(product)
end

ProductRepository.search('...')

# Overriding specific configuration like client stays within the singleton
ProductRepository.client = Elasticsearch::Client.new('http://other-host:9200')
BaseRepository.client != ProductRepository.client
# true
```

```ruby
# app/repositories/base_repository.rb

class BaseRepository
  include Singleton

  class << self
    def respond_to_missing?(method, include_private = false)
      super || instance.respond_to?(method)
    end

    def method_missing(method, *args)
      instance.send(method, *args)
    end
  end

  # include Elasticsearch::Persistence::Repository::Client
  include Elasticsearch::Persistence::Repository::Naming
  include Elasticsearch::Model::Indexing::ClassMethods
  # include Elasticsearch::Persistence::Repository::Serialize
  include Elasticsearch::Persistence::Repository::Store
  include Elasticsearch::Persistence::Repository::Find
  include Elasticsearch::Persistence::Repository::Search

  def class_name
    self.class.name.sub(/Repository$/, '')
  end

  # @override Elasticsearch::Persistence::Repository::Naming#klass
  def klass(setter = nil)
    @klass = setter || @klass || class_name.constantize
  end

  # @override Elasticsearch::Persistence::Repository::Naming#index_name
  def index_name(setter = nil)
    @index_name = setter || @index_name || class_name.underscore.gsub(/\//, '-')
  end

  def client(setter = nil)
    @client = setter if setter
    @client || self.class.superclass.respond_to?(:client) ? self.class.superclass.client : nil
  end

  def client=(setter)
    @client = setter
    @client
  end

  def serialize(object)
    object.kind_of?(klass) ? object.as_json : object.to_hash
  end

  def deserialize(document)
    deserialize_all([document]).first
  end

  def deserialize_all(documents)
    klass.where(id: documents.map { |document| document['_id'] })
  end

  # @override Elasticsearch::Persistence::Repository::Find#__find_many
  def __find_many(ids, options={})
    type = document_type || (klass ? __get_type_from_class(klass) : '_all')
    options = { index: index_name, type: type, body: { ids: ids } }.merge(options)
    documents = client.mget(options)

    deserialize_all(documents.select { |document| document['found'] })
  end
end

```

**Comment by estolfo** [comment]
I've refactored the `elasticsearch-persistence` gem with `Elasticsearch::Persistence::Repository` and `Elasticsearch::Persistence::Repository::DSL` as mixins. 6.0.0.pre versions of the `elasticsearch-rails`, `elasticsearch-model`, and `elasticsearch-persistence` gems are now available for testing. Please see the [readme](https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-persistence#usage) for documentation and use.

**Comment by estolfo** [comment]
I'm going to close this as `elasticsearch-persistence` 6.0 has been available for a few weeks and it resolves the mentioned OO structure issues. Thanks!
