### ISSUE TITLE
does it support :fields parameter?

### ISSUE THREAD

**Issue by guilhermemaranhao** [elastic/elasticsearch-rails#672]
Hi everyone,

I'm using ES 5.2.

I have a text field that contains a :fields parameter to map raw separated field for aggregation purpose.
I used the Faraday client :index method to perform the indexing, but when I search for a document, the field.raw aggregation bucket is empty.

Here is my mapping:
```
"my_type" : {
      "properties" : {
        "some_field" : {"type" : "integer"},
        "array_field": {"type": "text", "analyzer": "collection_analyzer", "fields": {"raw": {"type": "keyword"}}}
      }
    }
```

And my aggregation clause is:
```
:aggs=>
{:some_field_agg=>
{:terms=>{:field=>"some_field"}}, 
:array_field_agg=>{:terms=>{:field=>"array_field.raw"}}}
```

Have I missed something?

Is anything wrong with my mapping, my aggregation clause or it hadn't been indexed due to gem doesn't support this parameter?

Thanks,

Guilherme

**Comment by guilhermemaranhao** [comment]
My mistake! Everything is allright!

Thanks

**Comment by key88sf** [comment]
@guilhermemaranhao How about closing this issue?

**Comment by guilhermemaranhao** [comment]
Sure!

Sorry.
