### ISSUE TITLE
Querying Association Trouble?

### ISSUE THREAD

**Issue by taylor-a-barnette** [elastic/elasticsearch-rails#674]
Hey... I'm trying to query a has_many association of model Post called PostSection and have run into an issue I can't yet work around. The following code works fine locally on ES -v 1.4.4, but it doesn't run on Heroku, using Bonsai, on -v 2.4. However I can't verify that's the root cause, it's just the last remaining difference.

Post model:

    settings index: { number_of_shards: 1, number_of_replicas: 0 } do
      mapping do
        
        indexes :business_id, type: "long"
        indexes :content_category_ids, type: "long"
        indexes :content_tag_ids, type: "long"
        indexes :created_at, type: "date", format: "dateOptionalTime"
        indexes :facebook_id, type: "string"
        indexes :id, type: "long"
        indexes :meta_description, type: "string"
        indexes :published_on, type: "date", format: "dateOptionalTime"
        indexes :published_status, type: "boolean"
        indexes :slug, type: "string"
        indexes :sorting_date, type: "date", format: "dateOptionalTime"
        indexes :title, type: "string"
        indexes :updated_at, type: "date", format: "dateOptionalTime"

        indexes :post_sections do
          indexes :content, type: "string"
          indexes :heading, type: "string"
        end
      end
    end
  def as_indexed_json(options = {})
    as_json(
      methods: %i[content_category_ids content_tag_ids sorting_date],
      include: { post_sections: {only: [:content, :heading]} }
    )
  end
Here's the query I'm running:

      dsl = { }
      dsl[:query] = {
        query_string: {
          fields: %w[title^2 description content heading],
          query: "foo",
        },
      }

Elasticsearch::Model.search(dsl, Post)
Bonsai presents the following for the mapping:

{
  "posts" : {
    "mappings" : {
      "post" : {
        "properties" : {
          "business_id" : {
            "type" : "long"
          },
          "content_category_ids" : {
            "type" : "long"
          },
          "content_tag_ids" : {
            "type" : "long"
          },
          "created_at" : {
            "type" : "date",
            "format" : "dateOptionalTime"
          },
          "facebook_id" : {
            "type" : "string"
          },
          "id" : {
            "type" : "long"
          },
          "meta_description" : {
            "type" : "string"
          },
          "post_sections" : {
            "properties" : {
              "content" : {
                "type" : "string"
              },
              "heading" : {
                "type" : "string"
              }
            }
          },
          "published_on" : {
            "type" : "date",
            "format" : "dateOptionalTime"
          },
          "published_status" : {
            "type" : "boolean"
          },
          "slug" : {
            "type" : "string"
          },
          "sorting_date" : {
            "type" : "date",
            "format" : "dateOptionalTime"
          },
          "title" : {
            "type" : "string"
          },
          "updated_at" : {
            "type" : "date",
            "format" : "dateOptionalTime"
          }
        }
      }
    }
  }
}
I've tried modifying the query several ways based on the most recent documentation here, because I don't think it's right, but nothing I've tried works. I believe I'm missing something (probably very) obvious after being in the weeds a while with this issue (there were other problems with this code), but I can't determine what, beyond identifying the query as the root cause.

Thanks!

**Comment by estolfo** [comment]
Closing as this relates to the deprecated and removed `ActiveRecord` pattern.
