### ISSUE TITLE
How to set default dynamic string mappings in Elasticsearch::Persistence::Model 

### ISSUE THREAD

**Issue by phlegx** [elastic/elasticsearch-rails#676]
I have a ruby class `MyIndex` with `include Elasticsearch::Persistence::Model`. How can I configure the index in my class like explained here: 

https://www.elastic.co/guide/en/elasticsearch/reference/master/tune-for-disk-usage.html#_don_8217_t_use_default_dynamic_string_mappings

```
PUT index
{
  "mappings": {
    "type": {
      "dynamic_templates": [
        {
          "strings": {
            "match_mapping_type": "string",
            "mapping": {
              "type": "keyword"
            }
          }
        }
      ]
    }
  }
}
```

**Comment by phlegx** [comment]
Found a solution here: https://github.com/elastic/elasticsearch-rails/issues/436#issuecomment-264973387

```ruby
settings index: { ... } do
    mapping dynamic_templates: [
      {
        strings: {
          match_mapping_type: :string,
          mapping: {
            type: :keyword
          }
        }
      }
    ]
  end
```

**Comment by estolfo** [comment]
Closing as the last comment shows a solution and the `ActiveRecord` pattern has been deprecated/removed.
