### ISSUE TITLE
active_record_associations_parent_child test is not working

### ISSUE THREAD

**Issue by TakaakiFuruse** [elastic/elasticsearch-rails#677]
Hi.
I just find out that elasticsearch-models's active_record_associations_parent_child.rb test is not loaded by running be rake test:run_integration or test:all command.

It's just because the file lacks _test.rb at the end.
I think it's better to rename the file since, the elasticsearch-model/Rakefile only reads test.rb files.

```rb
  Rake::TestTask.new(:run_integration) do |test|
    test.libs << 'lib' << 'test'
    test.test_files = FileList["test/integration/**/*_test.rb"]   # => should be *.rb or something
    test.verbose = false
    test.warning = false
  end
```

Also, if you run active_record_associations_parent_child.rb it gives you an error which says

```rb
 Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Mapping definition for [_parent] has unsupported parameters:  [required : true]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [answer]: Mapping definition for [_parent] has unsupported parameters:  [required : true]","caused_by":{"type":"mapper_parsing_exception","reason":"Mapping definition for [_parent] has unsupported parameters:  [required : true]"}},"status":400}

```

so,

```rb
  mapping _parent: { type: 'question', required: true } do  # =>  required: true  should be removed
    indexes :text
    indexes :author
  end
```

I have just removed required: true  and passed all the test.

**Comment by karmi** [comment]
Hi, thanks for the ping!, this has been indeed an omission in the filename -- I've fixed that.

The configuration for making the routing required (which I think is beneficial in this case) [has been changed](https://www.elastic.co/guide/en/elasticsearch/reference/5.x/mapping-routing-field.html), so I've fixed that as well.

Thanks again!
