### ISSUE TITLE
Elasticsearch::Model does not send routing when indexing

### ISSUE THREAD

**Issue by aldesantis** [elastic/elasticsearch-rails#685]
I have the following two models in my application:

```ruby
class Category < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  index_name 'blog'
  document_type 'category'
end
```

```ruby
class Article < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  index_name 'blog'
  document_type 'article'

  mapping _parent: { type: 'category' } do
  end
end
```

I am creating my index with this `IndexManager` class:

```ruby
class IndexManager
  class << self
    def create_index(options = {})
      client     = Category.__elasticsearch__.client
      index_name = Category.index_name

      client.indices.delete index: index_name rescue nil if options[:force]

      settings = Category.settings.to_hash.merge(Article.settings.to_hash)
      mappings = Category.mappings.to_hash.merge(Article.mappings.to_hash)

      client.indices.create(
        index: index_name,
        body: {
          settings: settings.to_hash,
          mappings: mappings.to_hash
        }
      )
    end
  end
end
```

But when I create an article, I get a "routing is needed" error. It turned out that elasticsearch-model wasn't sending neither the parent nor the routing when indexing my document. The only was to fix the issue was to define the callbacks myself:

```ruby
class Article < ApplicationRecord
  include Elasticsearch::Model

  index_name 'blog'
  document_type 'article'

  mapping _parent: { type: 'category' } do
  end

  after_commit lambda { __elasticsearch__.index_document(routing: category_id, parent: category_id) }, on: :create
  after_commit lambda { __elasticsearch__.update_document(routing: category_id, parent: category_id) }, on: :update
  after_commit lambda { __elasticsearch__.delete_document(routing: category_id, parent: category_id) }, on: :destroy
end
```

Is this expected behavior, is it a bug or am I just doing something wrong?

**Comment by karmi** [comment]
Yes, this is expected -- the default callbacks will not include the `parent` parameter in the indexing call. In fact, the [integration test](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/test/integration/active_record_associations_parent_child_test.rb#L39-L41) for a parent:child relationship has exactly the same code as you have in your example. (Note: Sending the `parent` should be enough.)

As a side note, the "automatic callbacks module" is really only a starting point, for any slightly complex application, defining custom callbacks is appropriate. (Also, they could be done in the background with eg. _Sidekiq_.)

Actually, I'm more and more considering removing the automatic callbacks, so people don't rely on them, and just copy&paste the additional three lines of Ruby in their model configuration :)

**Comment by karmi** [comment]
Hi, I see your 👍 , but don't know if the issue can be closed then? :)

**Comment by alessandro1997** [comment]
@karmi I thought this was a bug. Since it's expected behavior, I guess it can be closed. It's just a little counterintuitive, so maybe it should be documented somewhere (unless it's documented already and I missed it)!

**Comment by karmi** [comment]
Well, I strongly consider removing the automatic callbacks for the reasons I've mentioned. There's the [integration test](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/test/integration/active_record_associations_parent_child_test.rb#L39-L41) I've linked, and I consider the integration tests part of the documentation, but maybe we should advertise them more in the README...

I'll keep this open, then, and close it if/when I get to the automatic callbacks module removal, so there's some kind of trail to follow.
