### ISSUE TITLE
Disable _all for type

### ISSUE THREAD

**Issue by baileyspace** [elastic/elasticsearch-rails#687]
I'm trying to disable _all as outlined [here in the ES docs](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/mapping-all-field.html#disabling-all-field) . The following looks right to me but isn't being implemented when I create the index: 
 
```
mappings dynamic: 'false', _all: {'enabled' => false} do
    ...
end
```

Mappings as json: 

```
pry(main)> Item.mappings.to_json
=> "{\"item\":{\"dynamic\":\"false\",\"_all\":{\"enabled\":false},\"properties\":{ ... }}}"
```

**Comment by baileyspace** [comment]
Looks like I was mistaken. This seems to be working now.

**Comment by karmi** [comment]
Hi, what was the correct syntax? Can you leave it here for the Google visitors? :) Thanks!

**Comment by baileyspace** [comment]
Sure thing, the syntax in my original post worked:

```
mappings dynamic: 'false', _all: {'enabled' => false} do
   ...
end
```
