### ISSUE TITLE
Last Realse of elasticsearch-rails

### ISSUE THREAD

**Issue by macartur** [elastic/elasticsearch-rails#691]
I am working to pack the 'elasticsearch-rails' repository to debian, but the last tag is  'dischord.yml' and this is different of previous version. I want to know if this last tag is right ?

**Comment by karmi** [comment]
Hi, I've abused the "Releases" feature of the repository to store a file with data for the [example application](https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-persistence/examples/music).

So, you will have to filter the tags for the correct format, something like `/v\d+/`. I'm not familiar with the Debian packaging processes, but maybe it's better to use the versions released to Rubygems for that?

**Comment by estolfo** [comment]
Closing this as it's out-of-date. Please reopen if you still have questions on this issue.
