### ISSUE TITLE
'ArgumentError: `type` is missing' when moving inclusion of module to base class.

### ISSUE THREAD

**Issue by ttrmw** [elastic/elasticsearch-rails#694]
Hey,

I wanted to define a base class that includes `ElasticsearchPersistence::Model`, ie:

```
class ElasticRecord
  include Elasticsearch::Persistence::Model
end

class MyModel < ElasticRecord; end
```

however, as soon as I move the inclusion from `MyModel` to `ElasticRecord`, I get:

```
ArgumentError: `type` is missing
	from /home/thomas/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/elasticsearch-model-0.1.9/lib/elasticsearch/model/indexing.rb:43:in `initialize'
	from /home/thomas/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/elasticsearch-model-0.1.9/lib/elasticsearch/model/indexing.rb:136:in `new'
	from /home/thomas/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/elasticsearch-model-0.1.9/lib/elasticsearch/model/indexing.rb:136:in `mapping'
	from /home/thomas/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/elasticsearch-persistence-0.1.9/lib/elasticsearch/persistence/model.rb:54:in `attribute'
	from /home/thomas/mammoth/vcs/app/models/my_model.rb:2:in `<class:RawResult>'
	from /home/thomas/mammoth/vcs/app/models/my_model.rb:1:in `<top (required)>'
	from /home/thomas/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:477:in `load'
	.....
```

when I try to instantiate `MyModel`. Any pointers?

**Comment by karmi** [comment]
I don't get this error when using current `master` of "elasticsearch-model" and "elasticsearch-persistence", but I do get another one, when I do `MyModel.new`: "undefined method `set' for nil:NilClass".

When you're using inheritance like this, the workaround is to `include` the model also in the child class:

```ruby
class MyModel < ElasticRecord
  include Elasticsearch::Persistence::Model
end
```

Can you try it out?

**Comment by ttrmw** [comment]
Sure, that works fine. I was hoping I might be able to include from the base class only but I see that's not possible. Thanks anyway!

**Comment by karmi** [comment]
This is probably the same problem reported in #670, and it's certainly we should fix, even though the workaround is that simple.
