### ISSUE TITLE
Approach to schemaless models (or attributes?)

### ISSUE THREAD

**Issue by ttrmw** [elastic/elasticsearch-rails#695]
So say I'm trying to associate some ES documents with my normal db backed models in Rails. I'm using the ActiveRecord pattern, and define `attribute :model_id, Integer` on my ES backed model. Now, I want to store basically an arbitrary JSON document for the rest of the model's attributes, making it kinda schemaless.

I've tried adding `attribute :schemaless_stuff, Hash`, which allows me to store arbitrary stuff. Good start. But then if I try searching on it, that fails:

```
irb(main):006:0> ESModel.create(model_id: 433, schemaless_stuff: {foo: "bar"})
=> #<ESModel {created_at: 2017-04-05 16:34:39 UTC, updated_at: 2017-04-05 16:34:39 UTC, model_id: 433, schemaless_stuff: {foo: "bar"}, id: "AVs-984XamuIDMR5Mqcu"}>

irb(main):007:0> ESModel.search({ query: { match: { schemaless_stuff: { foo: "bar" } } } })
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"parsing_exception","reason":"[match] query does not support [foo]","line":1,"col":37}],"type":"parsing_exception","reason":"[match] query does not support [foo]","line":1,"col":37},"status":400}
```

Leading me to suspect I'm going wrong somewhere. I'm an ES noob so that may also be the problem :grin:

**Comment by karmi** [comment]
@ttrmw, it's a good start indeed! :) However, when you use those fields in the `match` query, you have to use `schemaless_stuff.foo` notation -- can you try it?

**Comment by ttrmw** [comment]
Oh! So like `{"schemaless_stuff.foo": "bar"}`"?

**Comment by karmi** [comment]
Yes, something like

```
ESModel.search({ query: { match: { 'schemaless_stuff.foo' =>"bar" } } })
```

But I'm writing that from memory, try it and ping me if you'll get into trouble.

**Comment by ttrmw** [comment]
Great, will do! 

Relatedly enough that it doesn't feel worth opening a new issue for... Using the AR implementation, is there a way to actually just map an attribute as JSON? I'm guessing the mapping option would take 'json' as a value, but I don't think virtus will support it?

**Comment by karmi** [comment]
Feel free to open issues in the repository, we use it for general questions as well. For the use case you mention, can you provide some kind of context, ideally with some code? If "AR implementation" means the _ActiveRecord_ pattern for `elasticsearch-persistence`, I advice against it, in favour of the [_Repository_](https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-persistence#the-repository-pattern) pattern.

**Comment by ttrmw** [comment]
Sorry, yeah - the ActiveRecord pattern implementation. It seems a little more limiting on the face of it than the repository pattern implementation, but naturally our team is more familiar with AR style persistence, so this felt like a good idea.

Basically I'm looking to store arbitrary JSON and join it to our RDBMS backed models, then query on the JSON with ES. The way I was looking at doing that was by mapping an `rdbms_backed_model_id` as int, then `everything_else` as JSON.

**Comment by karmi** [comment]
@ttrmw, all right, makese sense. I'd really advice against the AR pattern, the implementation in `elasticsearch-rails` is inconsistent and the pattern itself too limiting. You can always work with a thin wrapper eg. based on `Hashie::Mash` with the Repository pattern.

I think we should close this issue then, and you can open new issues for specific problems?

**Comment by ttrmw** [comment]
sure, thanks!
