### ISSUE TITLE
Include aggregations when rendering json on elasticsearch model

### ISSUE THREAD

**Issue by zachdb86** [elastic/elasticsearch-rails#698]
How can I include aggregations or other response data when rendering an elasticsearch response object to json?  Right now I am only getting a list of results back.

In my model I have this method:
```
def self.list(id)
    @search_definition = {}
    @search_definition[:query] = {
      bool: {
        must: {
          term: {
            'channel_id.keyword': id
          }
        }
      }
    }
    @search_definition[:aggs] = {
      avg_views: {
        avg: {
          field: "like_count"
        }
      }
    }
    __elasticsearch__.search(@search_definition)
end 
```
And In my controller I have:
`render json: Post.list('abcd')`

But the json response from rails does not include my aggregations.

**Comment by karmi** [comment]
Hi, you have to use the `#aggregations` accessor, see the example here in the integration tests: https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/test/integration/active_record_basic_test.rb#L229-L246

More examples are available in the example application:

* https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-rails/lib/rails/templates/searchable.dsl.rb
* https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-rails/lib/rails/templates/index.html.dsl.erb#L71

**Comment by zachdb86** [comment]
I have no problem accessing aggregations in my views, this is strictly an issue when I want to render the elasticsearch response as json rather than rendering an html view.

**Comment by karmi** [comment]
Right, that's correct, Rails will probably call `#to_a` on the object, and that will only return `#records`, or `#results`. Closing the issue then?

**Comment by estolfo** [comment]
I'm going to close this issue because the user has indicated it is resolved.
