### ISSUE TITLE
failed to find geo_point field only when i use one index!

### ISSUE THREAD

**Issue by christianonrails** [elastic/elasticsearch-rails#699]
Hi there,

I came across a really strange issue. I've got two repos User and Request. 

```
class UserRepo
  include Elasticsearch::Persistence::Repository

  def initialize(options={})
    index ES_INDEX_USER_REQUEST
    client ES_CLIENT
  end

  klass User

  mapping do
    indexes :id, type: 'string', index: 'not_analyzed'
    indexes :last_active_at, type: 'date'
    indexes :carpooled_with, type: 'string', index: 'not_analyzed'
    indexes :location_home, type: 'geo_point'
    indexes :location_work, type: 'geo_point'
    indexes :bounding_box, type: 'geo_shape'
  end
end
```

```
class RequestRepository
  include Elasticsearch::Persistence::Repository

  def initialize(options={})
    index ES_INDEX_USER_REQUEST
    client ES_CLIENT
  end

  klass Request

  mapping _parent: { type: 'user' } do
  end

  mapping do
    indexes :pax_id, type: 'string', index: 'not_analyzed'
    indexes :scheduled_at, type: 'date'
    indexes :declined, type: 'string', index: 'not_analyzed'
    indexes :commute_to_home_or_work, type: 'string', index: 'not_analyzed'
    indexes :status, type: 'string', index: 'not_analyzed'
  end
end
```

Since it is a parent/child relationship I had to use the same index. And there is the problem. Since both types using the same index I get this error when I do this search:

```
Elasticsearch::Transport::Transport::Errors::BadRequest:
       [400] {"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to find geo_point field [location_home]","index_uuid":"bQrwGxmMSf2QO9VcGAugZg","index":"matching-service_user_request_test"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"matching-service_user_request_test","node":"8VYhh312QZeJ67u8_0Yztw","reason":{"type":"query_shard_exception","reason":"failed to find geo_point field [location_home]","index_uuid":"bQrwGxmMSf2QO9VcGAugZg","index":"matching-service_user_request_test"}}],"caused_by":{"type":"query_shard_exception","reason":"failed to find geo_point field [location_home]","index_uuid":"bQrwGxmMSf2QO9VcGAugZg","index":"matching-service_user_request_test"}},"status":400}
```

Just in case you like to see the search:

```
ES_REPO_USER.search(
         query: {
            bool: {
              filter: {
                bool: {
                  must: [
                    {
                      geo_polygon: {
                        location_home: {
                          points: [
                            { lat: bounding_points[:pointa][:lat], lon: bounding_points[:pointa][:lon] },
                            { lat: bounding_points[:pointb][:lat], lon: bounding_points[:pointb][:lon] },
                            { lat: bounding_points[:pointc][:lat], lon: bounding_points[:pointc][:lon] },
                            { lat: bounding_points[:pointd][:lat], lon: bounding_points[:pointd][:lon] },
                            { lat: bounding_points[:pointa][:lat], lon: bounding_points[:pointa][:lon] }
                          ]
                        }
                      }
                    }
                  ]
                }
              }
            }
          })
```

If I change the index back, so every type has their own index, then everything is fine again, but then I can't do a parent search, which I need in another place.

Anyone an idea?

**Comment by christianonrails** [comment]
I foun

**Comment by karmi** [comment]
@christianonrails, any info about how did you solve it?

**Comment by christianonrails** [comment]
not solved, i switched now to the model pattern. not sure how you would do it in repository pattern though

**Comment by karmi** [comment]
Interesting point, I can't see how the _ActiveRecord_ pattern makes this easier on the ES level... But in any case, I plan to remove this pattern in the next major release, and leave the _Repository_ pattern only.

**Comment by christianonrails** [comment]
I switched now to the activerecord pattern and i'm quite happy with that. anyway, i found out that the problem was simply the mapping. once you have a parent child relationship, you have to merge both models and create the index just once. before i created the index for both models individually even they share the same index and this causes problems. so nothing really wrong with the repository pattern.

**Comment by karmi** [comment]
Yes, indeed, you have to write some kind of `IndexManager` to merge all the settings/mappings, and create the index. Glad it's working!

**Comment by christianonrails** [comment]
yeah thats what i did now. any reasons why activerecord pattern gets removed? probably you just wanna maintain one approach?

**Comment by karmi** [comment]
There are numerous problems with that pattern, some coming from the "impedance mismatch" between the semantics of _ActiveRecord_ for relational databases, some coming from incomplete implementation. It was an attractive thing to do, since you can hook such a class so easily into Rails. But in reality, it's really too tight coupling between the "persistence" logic and the "business" logic, leads to strange behaviours, and it can be said promotes bad practices... And of course, maintaining just one approach is much less time-consuming than two...
