### ISSUE TITLE
Urls in as_indexed_json method in model

### ISSUE THREAD

**Issue by zauzaj** [elastic/elasticsearch-rails#707]
I have as_indexed_json method in my model, where I include all fields/methods for that model I need: 

```
 def as_indexed_json(options = {})
    self.as_json({
      only: [:id],
      methods: [
        :type, :path, :priority, :url, :title, :sub_title, :pro_pricings, :pricing_title,
        :specialty_ids, :convention_type_name, :coordinates, :next_availability_in_days,
        :indexed_geographical_area_id, :img, :searchable
      ]
   end
end
```
As you can see there are methods `path`&`url` which are actually from decorator, and they used to generate object urls. 

```
      def path
        self.decorator.path
      end
```

I know this is not good practice, but that was only way to do it! Now I want to refactor it and to move decorator from model, but not sure what would be the best way to do it ? Maybe to include RouteHelper into model and generate paths ? 

Thanks.

**Comment by estolfo** [comment]
Closing as this issue is out-of-date. Please reopen if the question is still relevant.
