### ISSUE TITLE
[Feature(?)] No bang (!) methods for create/save on elasticsearch models

### ISSUE THREAD

**Issue by BenTalagan** [elastic/elasticsearch-rails#713]
Hi, a small difference between classical ActiveRecord models and elasticsearch models is that elasticsearch ones come without bang methods (which would raise exceptions on validation failure) :

```ruby
class TestRecord
  include Elasticsearch::Persistence::Model
end

tr = TestRecord.new
 => #<TestRecord {created_at: 2017-05-18 16:13:39 UTC, updated_at: 2017-05-18 16:13:39 UTC, id: nil}> 
 
tr.save
 => {"_index"=>"test_records", "_type"=>"test_record", "_id"=>"AVwcVhPsYFwWlYjHgUA6", "_version"=>1, "result"=>"created", "_shards"=>{"total"=>2, "successful"=>1, "failed"=>0}, "created"=>true} 

tr.save!

NoMethodError: undefined method `save!' for #<TestRecord:0x007f8b999b4b38>
Did you mean?  save
	from (irb):10
```

Is it a choice of design or a missing feature? 

Thanks for this awesome gem.

**Comment by estolfo** [comment]
Hi @BenTalagan, we have plans to deprecate the ActiveRecord pattern (`Elasticsearch::Persistence::Model`) in the next major version, 6.0.
I recommend checking out the [Repository pattern](https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-persistence#the-repository-pattern) in the `Elasticsearch::Persistence` gem, as we will focus our future development efforts there.
If you don't mind, I'd like to close this issue as it's unlikely we will work on it. Thanks for your understanding.

**Comment by BenTalagan** [comment]
Sure! I approve that orientation since the conceptual bridge between AR and elastic search has its limits. Good luck!

**Comment by estolfo** [comment]
@BenTalagan I couldn't have said it better myself =)
