### ISSUE TITLE
How to connect AWS Elasticsearch?

### ISSUE THREAD

**Issue by hanhdt** [elastic/elasticsearch-rails#716]
I want to use AWS Elasticsearch service.
But I'm not sure that my config in the initializers folder work: 

```
config = {
    hosts: {host: 'search-coubic-xxxxxxxxxxxxxxxxx.aws-region.es.amazonaws.com', port: '80'},
    transport_options: {
        request: { timeout: 5 }
    }
}

Elasticsearch::Model.client = Elasticsearch::Client.new(config)
```

Anyone can help me review?

**Comment by erdemgezer** [comment]
@hanhdt have you found anything useful about this?

**Comment by hanhdt** [comment]
Yes, it works for me with AWS Elasticsearch.

Please refer to the elasticsearch-transport library documentation for all the configuration options,

Thanks.

**Comment by erdemgezer** [comment]
@hanhdt thanks!

**Comment by Startouf** [comment]
-> https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-request-signing.html#es-request-signing-ruby
