### ISSUE TITLE
Geo_point does not get update, but works on create.

### ISSUE THREAD

**Issue by keferboeck** [elastic/elasticsearch-rails#724]
Hi, I opened this issue today:

[https://stackoverflow.com/questions/44631151/elasticsearch-rails-elasticsearch-5-4-geopoint-not-updating](https://stackoverflow.com/questions/44631151/elasticsearch-rails-elasticsearch-5-4-geopoint-not-updating)

I run a few more tests in the console, just to confirm the issue is not with my code. Everything gets updated and works as expected. The problem is that geo_code does not ever get updated on updates.

**Comment by Meekohi** [comment]
I think this is related to https://github.com/elastic/elasticsearch-rails/pull/182 (trying to understand how this works exactly myself...)

**Comment by eduzera** [comment]
@keferboeck i had the same situation

so i found one possible solution: The idea is after you update with `save` or `update_attributes` method, force index again, like:

```ruby
model_object.__elasticsearch__.index_document
```

**Comment by Meekohi** [comment]
@eduzera indeed, my own solution is to add this as a callback after any update:

```
  after_commit on: [:update] do
    __elasticsearch__.index_document
  end
```

so it re-indexes the entire object. Ideally we would have a solution like proposed in #182 that handles "partial updates" correctly even for derived attributes.
