### ISSUE TITLE
Query string on multiple indexes with fields by index

### ISSUE THREAD

**Issue by victor-cruz** [elastic/elasticsearch-rails#725]
Hi all!

Wanted to check if is possible to do a query string search (or multi match search) on multiple indexes but specifying on which field of each index to search. Let me explain with a sample:

```ruby
class User
  mapping do
    indexes :name
    indexes :description
  end
end

class Animal
  mapping do
    indexes :name
    indexes :description
  end
end

# Wanted to search on users (name) and animals (description, no name) and boost user's names:
Elasticsearch::Model.search({query: {query_string: {query: 'John', fields: ['user.name^2', 'animal.description']}}}, [User, Animal]) # This search does not work, no results
Elasticsearch::Model.search({query: {query_string: {query: 'John', fields: ['name^2', 'description']}}}, [User, Animal]) # This search works, but is also searching on user's description and animal's names
```

I'm upgrading from ElasticSearch 1.7 to 5.4. Query with fields ```['user.name^2', 'animal.description']``` works on 1.7 but not working on 5.4.

Thanks in advance!

**Comment by henrikholm89** [comment]
@victor-cruz You managed to fix this problem?

And btw, is it only behaving this way when you upgraded the ES cluster from 2.x to 5.x, or also if you are only upgrading the elasticsearch gem 5.x, while still using an ES 2.x cluster?

**Comment by victor-cruz** [comment]
@henrikholm89 not solved yet. I've upgraded both ES cluster and gem, because if I'm not wrong elasticsearch gem 5.x requires ES cluster 5.x in terms of compatibility.

**Comment by andrba** [comment]
Looks like type prefixes are removed since ES v2.0: https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking_20_mapping_changes.html#_type_name_prefix_removed

**Comment by estolfo** [comment]
Hi @victor-cruz 
Have you resolved this? Let me know if I can close this issue.
Thanks

**Comment by estolfo** [comment]
Hi @victor-cruz I'm going to close this issue. Please open a new one if you have further questions. Thanks
