### ISSUE TITLE
[Persistence] No updated_at or created_at added to mapping of nested objects

### ISSUE THREAD

**Issue by twigbranch** [elastic/elasticsearch-rails#726]
Elasticsearch-rails persistence adds updated_at and created_at timestamps to the mappings of a model.  It appears it does not add them to the mappings of nested objects in a given model, though it does add them as virtus attributes to the nested objects -- shouldn't it add them to the mappings, as well?

**Comment by estolfo** [comment]
Hi @twigbranch 
We are deprecating the ActiveRecord persistence pattern in favor of the Repository pattern. It's unlikely we'll make any changes to address your issue. That said, do you mind if we close this? 
Thanks

**Comment by estolfo** [comment]
Hi @twigbranch, I'm going to close this issue. Please open a new one if you have further questions.
