### ISSUE TITLE
stack level too deep with inheritance_enabled when acessing __elasticsearch__.index_name

### ISSUE THREAD

**Issue by quorak** [elastic/elasticsearch-rails#729]
hey there,

thanks for the great gem.
just followed your docs and came across the folowwing issue when working with inheritance in my rails models.
With the default settings
```Ticket::EmailTicket.__elasticsearch__.index_name```
return me the correct index name `ticket-email_tickets` but when ```Elasticsearch::Model.settings[:inheritance_enabled] = true``` 
I get a 
> SystemStackError: stack level too deep
	from /usr/local/lib/ruby/2.0.0/irb/workspace.rb:86

when accessing the index_name. Obviously also for all methods using the index_name

I have very easy inheritance: `Ticket::Ticket` is the superclass of `Ticket::EmailTicket` and also includes the `Elasticsearch::Model`

I would expect `Ticket::EmailTicket.__elasticsearch__.index_name` to return `ticket-tickets`

I'm running on ruby 2.0 and rails 3.2. maybe the modules in my models make this problem.
Happy about any advice.

best

**Comment by karmi** [comment]
@blevine , thanks for posting the workaround. 

I've seen including the module again in the child classes to fix it as well. Sorry for the silence here, we're scheduling some effort to focus on the `elasticsearch-rails` group of gems again soon.

**Comment by emilong** [comment]
Another workaround option that's working for me:

```ruby
class Subclass < Superclass
  __elasticsearch__.index_name = Superclass.__elasticsearch__.index_name
end
```

Would love to get this resolved with the configuration option though. :smile:

**Comment by whitelancer** [comment]
Just wanted to report that I'm having this same issue.  It seems like this code should work, but I think it must be choking on the part where it compares ancestors to self?  Not entirely sure.
```
> Author.__elasticsearch__.send :implicit, :index_name
> "authors"
> NestedAuthor.__elasticsearch__.send :implicit, :index_name
> SystemStackError: stack level too deep
        from (irb):92
```
```def implicit(prop)
            value = nil

            if Elasticsearch::Model.settings[:inheritance_enabled]
              self.ancestors.each do |klass|
                next if klass == self
                break if value = klass.respond_to?(prop) && klass.send(prop)
              end
            end

            value || self.send("default_#{prop}")
end```

I haven't had a ton of time to dig into this, but it seems that `self` here is not correct.  
```
irb(main):095:0> NestedAuthor.__elasticsearch__.ancestors.each {|klass| puts "klass: #{klass}; self: #{self}; ==? #{klass == self}" }
klass: NestedAuthor; self: main; ==? false
```
And that's what drives this into an infinite loop.

**Comment by estolfo** [comment]
Fixed by https://github.com/elastic/elasticsearch-rails/pull/887
