### ISSUE TITLE
Ingest pipeline examples!

### ISSUE THREAD

**Issue by twigbranch** [elastic/elasticsearch-rails#730]
Are there any examples showing creation of an ingest pipeline?

**Comment by karmi** [comment]
Not at the moment, but I think those would probably go to the https://github.com/elastic/elasticsearch-ruby first, in this repo, it would have to be somehow Rails specific...

**Comment by estolfo** [comment]
Hi @twigbranch 
Do you mind if we close this issue or do you have further questions?

**Comment by estolfo** [comment]
Hi @twigbranch I'm going to close this issue. Please open a new one if you have further questions. Thanks!
