### ISSUE TITLE
Synonyms not working

### ISSUE THREAD

**Issue by cannonmoyer** [elastic/elasticsearch-rails#734]
I need to set a synonym for my product name field (eventually several of my fields) that allows the user to see the same search results if they type in "roller" or "wheel". I've been working on the code below all day and cannot get this to work. The search does return results when I search for "roller" (because I have products named "roller", but returns no results when I search for "wheel". I haven't received any errors either. I have no idea what to do at this point. Any help would be appreciated. I've re-indexed probably 20 times. 

Here is the search method in my controller

    @products = Product.search(
          query: { 
              query_string: {
              
               fields: ['name', '_all'],
                query: "#{params[:q]} AND status:\"Viewable On Website & Backend\""
                }
            }
          ).page(page).per(25)

My settings:

    settings index: { number_of_shards: 1 },
		analysis: {
      filter: {
        synonym: {
          type: "synonym",
          ignore_case: true,
          synonyms:[
            "wheel,roller"
          ]
        }
      },
      analyzer: {
        synonym: {
          tokenizer: "whitespace",
          filter: ["synonym", "lowercase", "stop", "snowball"]
        }
      }
    } do
	  mappings dynamic: 'false' do
	    indexes :name, analyzer: 'synonym'
	    indexes :status, analyzer: 'english'
	    #indexes :description, analyzer: 'english' 
	    indexes :part_number, analyzer: 'english'
	    indexes :text, analyzer: 'english'
	    indexes :normal_model, type: 'nested' do
	      indexes :name, analyzer: 'english'
	      indexes :number, analyzer: 'english'
	      indexes :machine_type, analyzer: 'english'
	     
	      indexes :normal_brand, type: 'nested' do
	    	indexes :name, analyzer: 'english'
	      end
	    end
	  end
	end

My indexed_as_json method:

    def as_indexed_json(options={})
	    as_json(
	    	only: [:name, :description, :part_number, :url_key, :image, :price, :shipping, :warranty, :eta, :status, :sku],
	        include: { 
            	normal_model: { only: [:name, :number, :machine_type],
            		include: { 
            			normal_brand: { only: :name}
            		}
            	}
            }
	    )
	 end

**Comment by karmi** [comment]
The `synonym` analyzer is set only for the name field, can you use the "Match" or "Multi Match" query instead of the "Query String" query — the latter should be avoided in general?

Also, are you familiar with the ["Analyze"](http://www.rubydoc.info/gems/elasticsearch-api/Elasticsearch/API/Indices/Actions#analyze-instance_method) API? It should allow you to debug the analysis process much faster then re-indexing and running queries.

Also, are you 100% sure that your index has the correct mapping, ie. the mapping from the model is applied? (There's the `create_index force: true` method for that.)

**Comment by cannonmoyer** [comment]
Thanks for the help. I changed the query_string to multi_match and everything started working as expected.  Thanks again!
