### ISSUE TITLE
ArgumentError: comparison of NilClass with 7 failed

### ISSUE THREAD

**Issue by Hirurg103** [elastic/elasticsearch-rails#735]
Environment:
elasticsearch: v1.6.2
gem elasticsearch-rails: d6e534c7b3ae
rails: 4.2.1

Backtrace:
```
[GEM HOME]/bundler/gems/elasticsearch-rails-d6e534c7b3ae/elasticsearch-model/lib/elasticsearch/model/adapters/active_record.rb:28 in sort_by
[GEM HOME]/bundler/gems/elasticsearch-rails-d6e534c7b3ae/elasticsearch-model/lib/elasticsearch/model/adapters/active_record.rb:28 in block (2 levels) in records
/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:46 in map
[APP TRACE]
```

Steps to reproduce:
1. Add `sleep 10` in elasticsearch-model/lib/elasticsearch/model/adapters/active_record.rb:17 to make the following steps more stable
2. Perform search `records = Model.search(criteria).records.records`
3. Create new record matching the search criteria
4. Wait until `sleep 10` is running
=>
 	from [GEM HOME]/bundler/gems/elasticsearch-rails-d6e534c7b3ae/elasticsearch-model/lib/elasticsearch/model/adapters/active_record.rb:29:in `sort_by'
	from [GEM HOME]/bundler/gems/elasticsearch-rails-d6e534c7b3ae/elasticsearch-model/lib/elasticsearch/model/adapters/active_record.rb:29:in `block (2 levels) in records'
	from [GEM HOME]/gems/activerecord-4.2.1/lib/active_record/relation.rb:629:in `inspect'

I think this happens because `sql_records` and `response.response['hits']['hits']` have different IDs because we make two **separate** calls to the ES for the results:

`sql_records = klass.where(klass.primary_key => ids) # <--- first call`
`sql_records.instance_exec(response.response['hits']['hits']) do ... # <--- second call`

I paste the code for clarity below:

```
 # lib/elasticsearch/model/adapters/active_record.rb
module Records
  # Returns an `ActiveRecord::Relation` instance
  #
  def records
    sql_records = klass.where(klass.primary_key => ids)

    # Re-order records based on the order from Elasticsearch hits
    # by redefining `to_a`, unless the user has called `order()`
    #
sleep 10
    sql_records.instance_exec(response.response['hits']['hits']) do |hits|
      define_singleton_method :to_a do
        if defined?(::ActiveRecord) && ::ActiveRecord::VERSION::MAJOR >= 4
          self.load
        else
          self.__send__(:exec_queries)
        end
        @records.sort_by { |record| hits.index { |hit| hit['_id'].to_s == record.id.to_s } }
      end
    end

    sql_records
  end
end
```
Maybe we can cache search.response to make sql_records consistent with ES response IDs?

**Comment by estolfo** [comment]
Closing this as it is out-of-date.
