### ISSUE TITLE
ERROR: Routing_missing_exception - Parent-Child Relationship

### ISSUE THREAD

**Issue by loganh0522** [elastic/elasticsearch-rails#736]
Hi, I have been trying to set up a parent-child relationship in ES for a while now and have thoroughly searched through issues, and documentation to set-up this relationship. I have referred to the [Integration Test](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/test/integration/active_record_associations_parent_child_test.rb), and this issue seems to be most similar [Issue 685](https://github.com/elastic/elasticsearch-rails/issues/685l), and I have not been able to figure it out. 

When I import my model I get this error: 

{"index":{"_index":"_development","_type":"candidate","_id":"62","status":400,"error":{"type":"routing_missing_exception","reason":"routing is required for [_development]/[candidate]/[62]","index":"_development"}}}

Here is my code for my model. 

`class Candidate < ActiveRecord::Base
      include Elasticsearch::Model
      include Elasticsearch::Model::Callbacks  
      index_name ["test", Rails.env].join('_') 

    mapping _parent: { type: 'company'}, _routing: { required: true } do
      indexes :id, type: 'integer'
      indexes :first_name, type: 'string'
      indexes :last_name, type: 'string'
      indexes :email, type: 'string'
      indexes :manually_created, type: 'boolean'
      indexes :full_name, type: "string"
      indexes :rating, type: "integer"
      indexes :created_at, type: "date"
    end

    after_commit lambda { __elasticsearch__.index_document(routing: company_id, parent: company_id) }, on: :create
    after_commit lambda { __elasticsearch__.update_document(routing: company_id, parent: company_id) }, on: :update
    after_commit lambda { __elasticsearch__.delete_document(routing: company_id, parent: company_id) }, on: :destroy
    end`

**Comment by estolfo** [comment]
Hi @loganh0522

Were you able to resolve this issue? We've updated the parent-child test [here](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/test/integration/active_record_associations_parent_child_test.rb) to work with Elasticsearch 6, for your reference.
Otherwise, I would suggest checking out: https://discuss.elastic.co/

**Comment by estolfo** [comment]
Hi @loganh0522, I'm going to close this issue. Please open a new one if you have further questions. Thanks
