### ISSUE TITLE
Randomizing Hosts vs round-robin

### ISSUE THREAD

**Issue by pathbox** [elastic/elasticsearch-rails#742]
Hi, 
    I read the document  http://www.rubydoc.info/gems/elasticsearch-transport, and I am confused about the Randomizing Hosts。 My Rails application does not config the `randomize_hosts: true`, so it use the default configuration `round-robin`, isn't right? I have five elasticsearch services, I check the newrelic external services, it shows that my Rails application accesses the five elasticsearch services averagely 
My Rails application use the Unicorn. 
So I want to konw the reason, and the different between Randomizing Hosts and round-robin

Thanks

**Comment by estolfo** [comment]
Hi @pathbox 

The default configuration is `round-robin`, and as you can see [here in the source code](https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-transport/lib/elasticsearch/transport/transport/connections/selector.rb#L51-L56), it will select each node from the list of nodes serially with each request. The other option,`randomize_hosts`, [will call `:choice` or `:sample` on the list of nodes](https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-transport/lib/elasticsearch/transport/transport/connections/selector.rb#L30-L40), depending on your Ruby version. In theory, you'll see an equal distribution of requests across the nodes with both configurations.

Does that answer your question?
Emily

**Comment by estolfo** [comment]
Great! I'm going to close this issue then.
