### ISSUE TITLE
elasticsearch/rails/lograge broke my custom lograge options

### ISSUE THREAD

**Issue by bolshakov** [elastic/elasticsearch-rails#749]
My application.rb file:

```rb
require 'elasticsearch/rails/lograge'

class Application < Rails::Application
  config.lograge.custom_options = lambda do |event|
     { params: event.payload[:params] }
  end
end
```

Since engine from `elasticsearch/rails/lograge` loads after my `application.rb`, it overrides `config.lograge.custom_options` and my configuration has no effect.

**Comment by estolfo** [comment]
@bolshakov Is this still an issue for you or can we close it?

**Comment by bolshakov** [comment]
@estolfo I tried to fix it here #750, but the build was broken in master. So PR wasn't merged.

**Comment by estolfo** [comment]
Thanks for the update, @bolshakov

**Comment by tagliala** [comment]
Hello, this is still an issue.  #750 should be merged and released. I understand that there have been issues with CLA but please consider as maintainers to fix
