### ISSUE TITLE
lib/rails/templates/01-basic.rb missing requirement

### ISSUE THREAD

**Issue by arcutright** [elastic/elasticsearch-rails#751]
I'm not sure what environment you're testing under, but I had to add a `require 'json'` to run this file since you were making use of the JSON gem.
Specifically, my runtime error was
```
$ rails new searchapp --skip --skip-bundle --template https://raw.github.com/elasticsearch/elasticsearch-rails/master/elasticsearch-rails/lib/rails/templates/01-basic.rb
...
apply  https://raw.github.com/elasticsearch/elasticsearch-rails/master/elasticsearch-rails/lib/rails/templates/01-basic.rb
https://raw.github.com/elasticsearch/elasticsearch-rails/master/elasticsearch-rails/lib/rails/templates/01-basic.rb:39:in `apply': uninitialized constant #<Class:#<Rails::Generators::AppGenerator:0x000000018973e8>>::JSON (NameError)
```

**Comment by psylone** [comment]
Here's a related [PR](https://github.com/elastic/elasticsearch-rails/pull/733).

**Comment by ravindra9278** [comment]
Getting same issue

**Comment by estolfo** [comment]
The require line was added in this commit https://github.com/elastic/elasticsearch-rails/commit/e1fc0e6df0b85d2eb65df1dec1459fc1da980dc8
so I will close this.
