### ISSUE TITLE
after_touch on nested model seems to trigger indexing before actual value is changed

### ISSUE THREAD

**Issue by mwoskowicz** [elastic/elasticsearch-rails#753]
```
Person.rb
	include Elasticsearch::Model
	include Elasticsearch::Model::Callbacks
	include ActiveModel::Dirty
	has_many :project_rows, dependent: :destroy
	after_touch lambda { __elasticsearch__.index_document }

        #mappings
        mappings dynamic: 'false' do
        indexes :project_rows, type: :nested do
	   indexes :stage, fields: {
	    default_analyzer: {
	    type: :string,
	    index: :analyzed,
	    analyzer: "keyword"
	 }
   }


ProjectRow.rb
	belongs_to :person, optional: true, touch: true


```
Let's say I can update _ProjectRow's stage_ value to three attributes = ["A,"B","C"].
If I update from A to B, still **A** is indexed. Then, if I update from B to C, **B is indexed**. From C to A, **C is indexed** etc.
It seems like the update takes place one iteration too late. Am I doing something wrong?

**Comment by mwoskowicz** [comment]
It turned out that after_touch _as_indexed_json_ was not changed, so I had to do person.reload, before doing person.update_document

**Comment by estolfo** [comment]
Closing this as it is out-of-date
