### ISSUE TITLE
Keep sort value in records

### ISSUE THREAD

**Issue by nicolas-besnard** [elastic/elasticsearch-rails#76]
Hi,

When using geo-spatial features of Elasticsearch, the "sort" value is very important, because it returns the distance between the query and the results. For instance :

```
      sort:  [{
            _geo_distance: { location: [48, 8], order: 'asc', unit: 'km' }
        }]
```

Is there a way to keep "sort" value in records model ? (User in my case).

Conf : Rails 4 and elasticsearch-model

Thanks.

**Comment by ctrlaltdylan** [comment]
@karmi is it possible to have `each_with_hit` return an instance of `Elasticsearch::Model::Response::Response` instead of an Array? This method is doing exactly what I need it to do without adding a script_field but returning an Array breaks all of the built in pagination awesomeness.
