### ISSUE TITLE
Failed to parse value [not_analyzed] as only [true] or [false] are allowed.

### ISSUE THREAD

**Issue by nrvakil** [elastic/elasticsearch-rails#761]
I get the following error:

```ruby
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Failed to parse mapping [note]: Could not convert [raw.index] to boolean"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [note]: Could not convert [raw.index] to boolean","caused_by":{"type":"illegal_argument_exception","reason":"Could not convert [raw.index] to boolean","caused_by":{"type":"illegal_argument_exception","reason":"Failed to parse value [not_analyzed] as only [true] or [false] are allowed."}}},"status":400}
```

Model: (ploymorphic)

```ruby
class Note < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  mappings dynamic: 'false' do
      indexes :noteable_type, type: 'text', index: :not_analyzed
  end
 
  # ...
end

Note.__elasticsearch__.create_index! force: true
```

Am am I doing something wrong? Or some syntax has changed again? Please help. Thanks.

**Comment by nilbus** [comment]
@nrvakil Yes, the syntax [changed in elasticsearch 5.0][1]. The `string` type has been replaced by the `text` (analyzed) and `keyword` (not analyzed) types. You're specifying the `text` type, but `keyword` is what you want for no analysis.

[1]: https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_mapping_changes.html#_literal_string_literal_fields_replaced_by_literal_text_literal_literal_keyword_literal_fields

```ruby
  mappings dynamic: 'false' do
    indexes :noteable_type, type: 'keyword'
  end
```

**Comment by nrvakil** [comment]
That did it. Thanks @nilbus .

**Comment by briansanchez** [comment]
I changed this "preserve_original": 1 to "preserve_original": "True" and worked


                "analysis": {
                    "filter": {
                        "email": {
                            "type": "pattern_capture",
                            "preserve_original": True,
                            "patterns": [
                                "([^@]+)",
                                "(\\p{L}+)",
                                "(\\d+)",
                                "@(.+)",
                                "([^-@]+)"
                            ]
                        }
                    },
                    "analyzer": {
                        "email": {
                            "tokenizer": "uax_url_email",
                            "filter": [
                                "email",
                                "lowercase",
                                "unique"
                            ]
                        }
                    }
                },
