### ISSUE TITLE
Geo point parameter ignore_malformed in v. 2.4.5 doesn't work.

### ISSUE THREAD

**Issue by Vandalisk** [elastic/elasticsearch-rails#765]
I've tried to use `ignore_malformed` parameter with geo_point in my project, but it couldn't work with `location: {}`
I even tried `lat_lon` parameter, as suggested [here](https://gist.github.com/hkorte/9936192) , but this couldn't work either. After some picking, one of the options `"location": null` worked for me. Is it worth repairing this issue?

**Comment by estolfo** [comment]
Hi @Vandalisk 
Have you been able to resolve your issue? If not, perhaps https://discuss.elastic.co/ would be a good resource for you.

**Comment by estolfo** [comment]
Hi @Vandalisk
I'm going to close this issue but feel free to open another one if you are still having trouble. Thanks
Emily
