### ISSUE TITLE
Virtus accounts for 45% of view rendering time for large result sets

### ISSUE THREAD

**Issue by bkazez** [elastic/elasticsearch-rails#767]
See attached performance analysis. Virtus seems to be adding a significant slowdown when processing a result set of 10k smallish documents. Note that the attached is just for rendering a single .erb.html template and does not include time spent querying es or even processing the results.

I am porting legacy code from PHP/MySQL and right now it performs much better on PHP/MySQL (~10x).

Eventually I will implement pagination using search_after, but I believe I will still have these issues. For heavy-duty use, do implementors need to simple use the client directly? I am just parsing array fields into a `<table>` and so do not require much fanciness on the part of the Rails library.

<img width="742" alt="screen shot 2017-12-30 at 22 21 17" src="https://user-images.githubusercontent.com/64005/34457666-d3a32cda-edaf-11e7-8e82-07c34b2e635f.png">

**Comment by nilbus** [comment]
solnic/virtus#287 discusses performance in Virtus, which is a little worse in Ruby 1.9, and a _lot_ worse when loading the `binding_of_caller` gem. I'm not sure if you're being affected by these or not, but that's worth looking into.

It is possible to use Virtus without the type coercer, but not [in `Elasticsearch::Persistence::Model`][1] without modifying the gem to use `Virtus.model(coerce: false)`.

[1]: https://github.com/elastic/elasticsearch-rails/blob/b5c01fd840ae069f8c7288450f1c39d65f3a4370/elasticsearch-persistence/lib/elasticsearch/persistence/model.rb#L34

**Comment by estolfo** [comment]
@bkazez @nilbus The ActiveRecord persistence pattern (`Elasticsearch::Persistence::Model`) has been deprecated and removed in version 6.0 of the elasticsearch-persistence gem so this issue is no longer relevant. If you don't mind, I'd like to close it.

**Comment by estolfo** [comment]
@bkazez I apologize, my mistake. I must have looked at the last comment and noticed that `Elasticsearch::Persistence::Model` was cited. Is there anything you think the `elasticsearch-persistence` gem can do about this or is the performance issue with the Virtus gem itself?

**Comment by bkazez** [comment]
Unfortunately I'm rather new to Rails and the only solution I had was to
remove Virtus entirely. Sorry I can't be of more help right now.

**Comment by estolfo** [comment]
@bkazez ok, I think the performance issue lies with Virtus, not with the elasticsearch-rails gems. If I'm mistaken, please let me know where you notice a bottleneck or if I can close this issue. Thanks!
