### ISSUE TITLE
Elasticsearch::Transport::Transport::Errors::NotFound 404

### ISSUE THREAD

**Issue by AntoninMarchardDev** [elastic/elasticsearch-rails#768]
There is already an issue https://github.com/elastic/elasticsearch-rails/issues/567, but the status is closed while no solution has been found. 
This error occur on `Model.destroy `. In my model I call : 

> 
>     include Elasticsearch::Model
>     include Elasticsearch::Model::Callbacks
> 
>     after_touch on: [:create, :update] do
>       __elasticsearch__.create_index! force: true
>       __elasticsearch__.index_document
>     end
> 
>     after_commit on: [:destroy] do
>       __elasticsearch__.delete_document ignore: 404
>     end

I try using custom callbacks, and using Model::Callbacks, but I still have this issue, in production using Bonsai/Heroku. I've launched : 

`sudo heroku run:detached rake environment elasticsearch:import:all FORCE=y --app <app_name>`

Any help will be appreciated !

**Comment by karmi** [comment]
Hi @AntoninMarchardDev, in the code you've posted, the index will be deleted and created each time you update a model, which is not what you want I guess — the `create_index!` call is suitable for some kind of bootstrapping Rake task, in integration tests, and so on.

So I understand from your description that the `delete_document` call results in a `404` error when you delete a record from the database. Did you try enabling logging — `...Client.new ... log: true` — and having a look at the calls? With the code you've posted, as soon as you create or update any model instance, the whole index is deleted, therefore, it's not surprising that _another_ record/document would not be found.

**Comment by AntoninMarchardDev** [comment]
Hi @karmi ! 
Thank you for the answer !
I was already calling `log: true`, but right now, I find this Stackoverflow post : 
https://stackoverflow.com/questions/35812742/rails-elasticsearch-bonsai-with-heroku-performance-issues

I try using same callback than the question, and it work well, using `begin..rescue `

**Comment by karmi** [comment]
Hello, I'm wondering why you think the Stackoverflow post is relevant? Again, make sure that you don't call `create_index! force: true` in the `after_touch` callback, or you'd effectively wipe out the entire index on every model change.

**Comment by estolfo** [comment]
Hi @andremm 
Have you been able to resolve this issue? As mentioned in the above comment, the `#create_index!` call [will delete and recreate the index](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model/indexing.rb#L222-L237), resulting in a 404 when you try to search for another document. Please let us know if you need further assistance with this issue.

**Comment by andremm** [comment]
@estolfo by any chance where you trying to reach out to @AntoninMarchardDev ?

**Comment by estolfo** [comment]
Sorry for the noise @andremm, your name was auto-completed.

**Comment by andremm** [comment]
No problem @estolfo :)

**Comment by estolfo** [comment]
Hi @AntoninMarchardDev
I'm going to close this issue but feel free to open another one if you are still having trouble. Thanks
Emily
