### ISSUE TITLE
Indexing input for Completion Suggesters

### ISSUE THREAD

**Issue by skukx** [elastic/elasticsearch-rails#772]
I currently have a similar mapping to https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/examples/activerecord_mapping_completion.rb#L20-L25.
```ruby
mapping do
    indexes :title, type: 'text' do
      indexes :keyword, type: 'keyword'
      indexes :suggest, type: 'completion'
    end
end
```

**My question is if there is a way to pass multiple inputs while indexing similar to:**
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-completion.html#indexing
```json
"suggest" : {
        "input": [ "Beatles", "The Beatles" ]
}
```

Something like:
```ruby
def as_indexed_json(_options = {})
  as_json().merge('title.suggest': { input: ['Beatles', 'The Beatles'] })
end
```

I understand I could probably get away with doing this by having a separate property called `title_suggest`. However it feels cleaner to have the completion field as part of the `title` property.

Thank you for the great work you do!

**Comment by victorhazbun** [comment]
Is this an issue? Please close.

**Comment by skukx** [comment]
I'll answer this question:
By mapping the `suggest` field as a field of the property, it is not possible to then pass the `input` array when indexing. It is better to create a new property such as `title_suggest`
