### ISSUE TITLE
Can't Retrieve Records from a Search when Using a Custom ID

### ISSUE THREAD

**Issue by roeltm** [elastic/elasticsearch-rails#774]
When using a custom field as the document id in elasticsearch the basic actions(create/update/delete) are fairly easy to change in the code, e.g.:
```
object.__elasticsearch__.delete_document id: object.custom_id
object.__elasticsearch__.update_document id: object.custom_id
object.__elasticsearch__.index_document id: object.custom_id
```

However, when searching and retrieving the `records`, it seems that the _id is always matched with the primary_key and this is not configurable:
https://github.com/elastic/elasticsearch-rails/blob/b6d485748c71a07d064ea2a46a6da82d64a04cd7/elasticsearch-model/lib/elasticsearch/model/adapters/active_record.rb#L22

https://github.com/elastic/elasticsearch-rails/blob/b6d485748c71a07d064ea2a46a6da82d64a04cd7/elasticsearch-model/lib/elasticsearch/model/response/records.rb#L36-L38

Should this be made configurable? And if so, which part should be configurable, the `primary_key` or the `_id`.

**Comment by m1neral** [comment]
+1

Need API to normalize `_id` before insertion in SQL.
Frequent case, when `_id`'s are `child:123`, `parent:123` etc

**Comment by spodlecki** [comment]
+1 here.

I've had to monkey patch around to make the gem work as expected, which is not optimal for obvious reasons. With ElasticSearch 6.x getting rid of multi-type indices, I've had to opt to do a "custom type field" to keep the number of shards down in our clusters. I first tried to keep IDs as-is, but problems quickly reared their heads when IDs started to conflict (e.g. updating the document would update a different document of the same ID, fetching by ID fetched all ID records, and so on). So I've made the `_id` field a custom value and the `type` field a constant `doc` value.

> note: ElasticSearch's recommendation of `_doc` type is an illegal format says 6.1.1

**Comment by estolfo** [comment]
@roeltm @m1neral @spodlecki 
I have opened [this PR](https://github.com/elastic/elasticsearch-rails/pull/828) as a proposed implementation of your request. Please take a look, try it out in your testing environments, and let me know what you think. Thanks!

**Comment by soranoba** [comment]
+1
What's the PR's status?
