### ISSUE TITLE
is there any way to remove extra fields from the ElasticSearch response?

### ISSUE THREAD

**Issue by ravindra9278** [elastic/elasticsearch-rails#781]
> Hi I am very new to the ElasticSearch and I am struggling to remove all extra fields from response getting from ElasticSearch. Please see below response:

```
"report": {
    "unique_users": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": [
        {
          "key": 1234,
          "doc_count": 2,
          "user_details": {
            "hits": {
              "total": 2,
              "max_score": 1.4E-45,
              "hits": [
                {
                  "_index": "orders-test",
                  "_type": "order",
                  "_id": "2",
                  "_score": 0.0,
                  "_source": {
                    "customer_email": "reba_dickens@blick.name",
                    "customer_phone": "476.824.4998 x498",
                    "customer_name": "Mohammed Abernathy"
                  }
                }
              ]
            }
          }
        },
        {
          "key": 5678,
          "doc_count": 1,
          "user_details": {
            "hits": {
              "total": 1,
              "max_score": 1.4E-45,
              "hits": [
                {
                  "_index": "orders-test",
                  "_type": "order",
                  "_id": "1",
                  "_score": 0.0,
                  "_source": {
                    "customer_email": "yolanda.batz@ruel.biz",
                    "customer_phone": "1-715-183-8343 x026",
                    "customer_name": "Richie Tillman II"
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
```

> 
Above you can see that there are some additional fields coming with the response like _index, _type, _score, max_score etc. I have followed ElasticSearch response_filtering guide to remove these fields but it was not working for me. I have also passed the filter_path parameter to the request 0.0.0.0:5000/v4/reports/user.json?filter_path=unique_users,unique_users.user_details.hits.hits._source but did not get any response. I am using below function to process the Elasticsearch query.

```
def query(options = {})

    aggregations = {}

    buckets = {}
    buckets_for_unique_users buckets, aggregations
    buckets_for_new_users buckets, aggregations
    buckets_for_high_rollers buckets, aggregations

    filters = []
    filters << time_filter(options)
    filters << restaurant_filter(options) if options[:restaurant_id]
    filters << channel_filter(options) if options[:channel_id]

    query = {
      query: { bool: { filter: filters } },
      aggregations: buckets
    }
    query
  end
```

> I have also used _source https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-source-filtering.html but it did not remove extra fields. Could anyone please let me know where I am doing wrong.

**Comment by estolfo** [comment]
Hi @ravindra9278 
Have you been able to resolve your issue? If not, perhaps https://discuss.elastic.co/ would be a good resource for you.

**Comment by estolfo** [comment]
Hi @ravindra9278
I'm going to close this issue but feel free to open another one if you are still having trouble. Thanks
Emily

**Comment by angusdavisadobe** [comment]
I would also like to be able to exclude (filter out) the  _index, _type and _id fields in hits results of an aggregation query. Not sure why this was closed. What is the solution?
