### ISSUE TITLE
Search returns no data, but with no errors also.

### ISSUE THREAD

**Issue by Yi3nz** [elastic/elasticsearch-rails#782]
Tried to implement the searchkick with elasticsearch,

Have no errors occurred but when the search button is clicked the table returns no data:
![1](https://user-images.githubusercontent.com/8803860/38273680-84cb3ebc-3784-11e8-9db3-56341b70595b.PNG)
Search
![2](https://user-images.githubusercontent.com/8803860/38273690-87fb532e-3784-11e8-8746-6da975dfb6ca.PNG)
While the server does response
![3](https://user-images.githubusercontent.com/8803860/38273695-8b58e4b4-3784-11e8-9b0b-b29ffb78d9c1.PNG)

Any suggestion is appreciated!

**Comment by estolfo** [comment]
Hi @Yi3nz 
Have you been able to resolve this issue? Please let us know if you still need assistance.
Emily

**Comment by estolfo** [comment]
Hi @Yi3nz
I'm going to close this issue but feel free to open another one if you are still having trouble. Thanks
Emily
