### ISSUE TITLE
`Model.import` not respecting `default_scope`

### ISSUE THREAD

**Issue by ctrlaltdylan** [elastic/elasticsearch-rails#784]
My model has a `default_scope` like this:

`  default_scope { where(status: 1).where.not(user: nil) }`

However, during searches Elasticsearch will return `response.records` that do not actually respect the scope:

```
$ pry(VehicleElasticSearchService)> response.records.to_a.first
RvshareRv Load (3.2ms)  SELECT `default_rvs`.* FROM `default_rvs` WHERE (`vehicles`.`user_id` IS NOT NULL) AND `vehicles`.`status` = 1 AND `vehicles`.`id` IN (1004787, 1005459, 1005571, 1005785, 1006249, 1006326, 1006389, 1006427, 1006650, 1006667, 1006708, 1006802, 1006839, 1006877, 1006931, 114106, 114107, 114111, 114112, 114119, 114122, 114123, 114124, 114650, 115314)
=> nil
```

I ran the query _without_ the `WHERE status = 1` and was able to retrieve the records, so that means that Elasticsearch imported records outside of the defined `default_scope`

It seems that during indexing (`Vehicle.import`), the `default_scope` is not being applied and these records somehow make it into the index.

How can we force Elasticsearch to respect the `default_scope` of a model? Or conditionally import records?

**Comment by estolfo** [comment]
@ctrlaltdylan Would [this change](https://github.com/elastic/elasticsearch-rails/pull/414/files#diff-c31364bbef3dfe92e6d34dce8d37775cR66) in a pull request fix the issue you're having?

**Comment by ctrlaltdylan** [comment]
@estolfo honestly I'm not sure, I haven't looked into the internals much of ElasticSearch, I just wanted to at least report the bug. I'm sure you know better than I if it'll fix the issue!

**Comment by ctrlaltdylan** [comment]
Also this bug was using the `mysql2` Rails db adapter, not mongo.

**Comment by estolfo** [comment]
ah, ok. Thanks for letting me know.

**Comment by estolfo** [comment]
@ctrlaltdylan I've opened [a pull request](https://github.com/elastic/elasticsearch-rails/pull/827) to address this. Please test it out and let me know if it works ok for you. Thanks!

**Comment by estolfo** [comment]
I'm going to close this issue as I've merged in the pull request https://github.com/elastic/elasticsearch-rails/pull/827 testing this issue and showing that the default scope is indeed applied to an import. Please comment or open a new issue if it's not resolved.
