### ISSUE TITLE
how to match the name

### ISSUE THREAD

**Issue by Thomastar** [elastic/elasticsearch-rails#788]
"match": {
              "product_name": {
                "query": "锐科机械 砂边机",
                "operator": "and"
              }
                
            }

data: 
id = 1 product_name = 锐科机械-直线-铣型砂边机-已利生产效率,适合合开复杂的直线曲子面型成沙光

the result
`{
  "took": 4,
  "timed_out": false,
  "_shards": {
    "total": 134,
    "successful": 134,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": null,
    "hits": []
  }
}`

tips: version : 5.4.2
Why? It is bug ?

**Comment by estolfo** [comment]
Hi @Thomastar 
My initial guess would be that you haven't properly defined the language analyzer.
I would also suggest you direct your question to https://discuss.elastic.co/
Please let us know if you were able to resolve this issue so we can close it or if we can help further.
Thanks

**Comment by estolfo** [comment]
Hi @Thomastar 
I'm going to close this issue but please open a new one if you have further questions or if you still need assistance on this one.
