### ISSUE TITLE
How to write multi-field mapping in elasticsearch-model?

### ISSUE THREAD

**Issue by jjyr** [elastic/elasticsearch-rails#79]
Hello, I notice `indexes` api is not 100% match to the api of elasticsearch according official document http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/most-fields.html#_multi_field_mapping

And I can't find how to write mutil fields in README & examples

The following is what I am trying now but it doesn't work.

``` ruby
mappings do
  indexes :nickname, analyzer: 'ik', fields: {en: {analyzer: 'english', type: "string"}}, type: "multi_field"
end
```

please help

**Comment by thedanielhanke** [comment]
news?

**Comment by jspizziri** [comment]
+1

It would be really nice if this were updated.

**Comment by skukx** [comment]
+1

**Comment by woniesong92** [comment]
multi_field is completely deprecated in ES 5.x
