### ISSUE TITLE
Unexpected search behaviour in test

### ISSUE THREAD

**Issue by ttrmw** [elastic/elasticsearch-rails#790]
Ruby 2.4.0/Rails 5.1.4/elasticsearch-model 0.1.9/Elasticsearch 5.3.0

I'm using elasticsearch-model, and manually indexing in my test.

My test looks a little like this:

```
 test 'it can be searched' do                                         
    VCR.use_cassette('this_test') do                                    
      model_instance = ModelName.create(value: 'reddit.com')
      ModelName.import(force: true)                                                   
                                                                                    
      result = ModelName.search('reddit.com').records.first   
                                                                                    
      assert_equal model_instance, result                                                  
    end                                                                             
  end
```

however, result comes back nil. If I put a debugger in after the assignment to result, and repeat `result = ModelName.search_with_elasticsearch('reddit.com').records.first`, the record is assigned as expected (!?).

If I add `ModelName.__elasticsearch__.refresh_index!` after the call to import, the record is assigned as expected.

However, neither approach works when run as part of the full test suite, `result` is still set to nil in this context. When the test is run in isolation, either approach works. 

I have tried disabling VCR & webmock and this has no affect. The VCR response recorded is as expected, the GET corresponding to the search is present and contains the correct result.

**Comment by karmi** [comment]
Hi, not sure about how VCR interferes with the test in general, if at all, but it is definitely needed to call the "Refresh" API in order to propagate the changes from your import — force first deletes the index — to the search.

It is strange if it works in isolation, but not as part of the whole test suite, since even if a`setup` somewhere would delete / re-create the index, the `import` and `refresh_index!` calls should make the change visible to the subsequent search...

**Comment by ttrmw** [comment]
This turned out to be my mistake, the VCR cassette was recorded with a specific ID, but of course the model created in test would not necessarily match, so whilst results were present, records couldn't be rehydrated from them.
