### ISSUE TITLE
How to get "sort" value from a searched document?

### ISSUE THREAD

**Issue by hokuma** [elastic/elasticsearch-rails#791]
I want to use `Search After` feature.
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-after.html

This feature requires the last searched document `sort` value in next search query, but there is no `sort` accessor in [Model](https://github.com/elastic/elasticsearch-rails/blob/5.x/elasticsearch-persistence/lib/elasticsearch/persistence/model/base.rb)

Is there a plan to add `sort` accessor to `Model` or is there any method to access `sort` value?

**Comment by karmi** [comment]
Hi @hokuma, when you get search results from `MyModel.search`, the `each_with_hit` method should give you access to the "raw" JSON hits from Elasticsearch, so you should be able to feed it into the `search` method, in order to use the "Search After" feature.

**Comment by estolfo** [comment]
Hi @hokuma 
Have you tried to use the raw JSON hits to get the sort value, as suggested in the comment above?
Please let us know if you were able to resolve this and we can close the issue.
Thanks
Emily

**Comment by estolfo** [comment]
Hi @hokuma 
I'm going to close this issue but feel free to open a new one if you have further questions.
Thanks!
