### ISSUE TITLE
Mappings are ignored in rails 5

### ISSUE THREAD

**Issue by IvRRimum** [elastic/elasticsearch-rails#793]
So I have been trying to make this work for few days now, nothing seems to work.

I have mappings defined in my model:
```
  settings do
    mappings dynamic: false do
      indexes :title, type: 'text'
      indexes :description, type: 'text'
      indexes :user, type: 'text' do
        indexes :name, type: 'text'
      end
    end
  end
```
But when I do:
```
Podcast.__elasticsearch__.delete_index! force: true 
Podcast.__elasticsearch__.create_index! force: true 
Podcast.__elasticsearch__.import force: true
```

and visit: `http://localhost:9200/podcasts/_search?pretty=true&q=*:*&size=1000`

I see all of the model data poured into the indexes(I need only title, description and user name).

What is the problem here?

**Comment by bysxiang** [comment]
在模型中定义一个as_indexed_json方法，

`def as_indexed_json(options = {})
    as_json(only: [:id, :parent_id, :name, :barcode])
  end`

**Comment by karmi** [comment]
Hi @IvRRimum, as @bysxiang suggests above, the `mappings` DSL only _sets up_ the fields in your index with proper types, analyzers, etc. When you need to filter the properties of your model to be indexed, you have to use `as_indexed_json` — have a look at this chapter in the README: https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-model#model-serialization

**Comment by estolfo** [comment]
Hi @IvRRimum 
Has using `as_indexed_json` achieved the functionality you were looking for?
If so, can we close this issue? If not, please let us know how we can help further.
Thanks
