### ISSUE TITLE
is_a? doesn't work as expected with multi-model search

### ISSUE THREAD

**Issue by ttrmw** [elastic/elasticsearch-rails#799]
Given a multi model search, the rehydrated records do not return true for `.is_a? RecordClassName` - inspection of `.class.object_id` and `RecordClassName.class.object_id` shows different values.

**Comment by estolfo** [comment]
@ttrmw Can you please provide a code example? That will make it easier for us to see where the problem is. Thanks

**Comment by estolfo** [comment]
@ttrmw Would it be possible to get a code example so we can help? Thanks

**Comment by ttrmw** [comment]
Ah apologies, I will put one together this week

**Comment by estolfo** [comment]
@ttrmw That would be most helpful, thanks!

**Comment by ttrmw** [comment]
in a weird turn I now can't repro this either in a SSCE or the affected applications! @victor-cruz, since you :+1:'d this, is there any chance you can reproduce? I'm baffled!

**Comment by estolfo** [comment]
@victor-cruz can you provide a code example? Thanks!
