### ISSUE TITLE
elasticsearch-model: one index, multiple models, multiple mappings 

### ISSUE THREAD

**Issue by rozumem** [elastic/elasticsearch-rails#80]
I have three models and each have their own mappings. All three models are stored in the same index.

If I do 

```
ModelOne.__elasticsearch__.create_index! force: true
```

then only ModelOne's mappings are returned when I call "GET my_index/_mapping"

Then if I do

```
ModelTwo.__elasticsearch__.create_index! force: true
```

then ModelOne's mappings are erased and "GET my_index/_mapping" only return ModelTwo's mappings.

Is there a way to create the index with all the models' mappings? Seems like this should be straightforward, but I am clearly missing something.

**Comment by chip-miller** [comment]
Thanks @ghilead - the rake task did the trick!

**Comment by nickrivadeneira** [comment]
I like the idea of @karmi's `IndexManager` class because it's testable. I've taken some of those ideas and built a small rake task that calls the index manager. Gist here for anyone that's interested:

https://gist.github.com/nickrivadeneira/e99fbf9beb82fed2f95eaf6964c97853
