### ISSUE TITLE
to_param incorrectly returns nil for an unpersisted object

### ISSUE THREAD

**Issue by jcoyne** [elastic/elasticsearch-rails#804]
On an ActiveRecord model (see `User` below), calling `to_param` on an unsaved object returns it's key.  This is part of `ActiveRecord::Integration` however on `Elasticsearch::Persistence::Model` calling `to_param` on an unsaved object returns nil.  It would be nice if `Elasticsearch::Persistence::Model` matched the behavior of `ActiveRecord::Integration`: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/integration.rb#L49-L52

```ruby
class Document
    include Elasticsearch::Persistence::Model
end

class User < ActiveRecord::Base
end


Document.new(id:'123').to_param
nil
> u.to_param
"123"
> User.new(id: '123').to_param
"123"
> Document.new(id:'123').method(:to_param).source_location
["/Users/jcoyne/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activemodel-5.2.0/lib/active_model/conversion.rb", 82]
> User.new(id:'123').method(:to_param).source_location
["/Users/jcoyne/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/integration.rb", 49]
```

**Comment by estolfo** [comment]
Hi @jcoyne 

I'm sorry you're running into this inconsistency between `ActiveRecord::Base` and `Elasticsearch::Persistence`'s implementation of the ActiveRecord pattern.

Typically, we would work to fix bugs in the elasticsearch gems but we have plans to deprecate the ActiveRecord pattern (`Elasticsearch::Persistence::Model`) in the next major version, 6.0.

I recommend checking out the [Repository pattern](https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-persistence#the-repository-pattern) in the `Elasticsearch::Persistence gem`, as we will focus our future development efforts there.

If you don't mind, I'd like to close this issue as it's unlikely we will work on it. Thanks for your understanding.
Emily

**Comment by estolfo** [comment]
Hi @jcoyne, I'm going to close this issue. Please open a new one if you have further questions. Thanks

**Comment by jcoyne** [comment]
I am using the repository pattern. But I’d still like the to_param to behave consistently in order to use the rails route helpers.

**Comment by estolfo** [comment]
Hi @jcoyne, in your example above, you've included the `Elasticsearch::Persistence::Model` module so can you please provide an example using the Repository pattern and what the expected behavior is? I'm reopening this issue so we can continue looking into it. Thanks!

**Comment by jcoyne** [comment]
Sure. I'm retrieving an object like this:

```ruby
repo = Elasticsearch::Persistence::Repository.new do
         klass Document
       end
@doc = repo.find(id)
```

Now, when I want to route to a controller to handle that document using the rails routing helpers I am doing:
```erb
  <%= link_to 'More info', @doc %>
```

In order to do that latter part, you need to include `Elasticsearch::Persistence::Model` on `Document` so that `Document` will respond to `to_param`, right?

**Comment by estolfo** [comment]
@jcoyne I just wanted to check in and see if you could define `#to_param` on the model?

**Comment by jcoyne** [comment]
Yeah, I can add all that ActiveModel stuff myself. Thanks for following up.
