### ISSUE TITLE
Pagy support

### ISSUE THREAD

**Issue by markivancho** [elastic/elasticsearch-rails#815]
Hello, thanks for a great gem. I'm just curious, are you going to add a support for a new pagination gem [Pagy](https://github.com/ddnexus/pagy)?

**Comment by estolfo** [comment]
Hi @markivancho, we aren't currently working on adding support but would welcome a pull request, if you'd like to open one.

**Comment by renshuki** [comment]
Hi @estolfo, @markivancho, 
I saw [Pagy](https://github.com/ddnexus/pagy) gem can manage *[Backend extras](https://github.com/ddnexus/pagy/#easy-to-extend)* which are modular extensions for compatibility with other gems. Then, I'm wondering if it's better to create a *Backend extra* in [Pagy](https://github.com/ddnexus/pagy) gem for elasticsearch-rails or implement this directly in elasticsearch-rails itself (like with [Kaminari](https://github.com/kaminari/kaminari) or [will_paginate](https://github.com/mislav/will_paginate)).

What do you think @estolfo?

**Comment by estolfo** [comment]
Related pull request: https://github.com/ddnexus/pagy/pull/96

**Comment by estolfo** [comment]
Great! Thanks so much @renshuki
