### ISSUE TITLE
I was worried about "Use default doc type: _doc"

### ISSUE THREAD

**Issue by Chiether** [elastic/elasticsearch-rails#818]
I was update gems. and I meet some trouble.
(tentatively, I write ```document_type "_doc"``` to ApplicationRecord, now)

$ bundle update
```
$ bundle list | grep elastic
  * elasticsearch (6.1.0)
  * elasticsearch-api (6.1.0)
  * elasticsearch-model (7.0.0 071fa96)
  * elasticsearch-rails (7.0.0 071fa96)
  * elasticsearch-transport (6.1.0)
```

$ bundle exec rails c
```
[app/models/member.rb]
class Member < ApplicationRecord
   include Elasticsearch::Model
end

Member.document_type => "member"
```

$ bundle exec rails s  (web-console)
```
>> Member.document_type
=> "_doc"
```

Sorry, I do not understand it deeply.
Is this behavior as expected?

Rails 5.2.0
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

probably linked to 4d056ed

**Comment by estolfo** [comment]
Hi @Chiether We have changed the default document type to "_doc", unless you override it with the `document_type` setting. The reason for this change is that the ability to have multiple types in a single index is deprecated and will be removed in Elasticsearch 7. Please see the documentation [here](https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html#_schedule_for_removal_of_mapping_types).

When you use these gems with Elasticsearch 6, you must explicitly specify the `document_type` on the model if you want it to be something other than `_doc`. Keep in mind that you won't have this option in the future when you use the gems with Elasticsearch 7.

For example:
```ruby
[app/models/member.rb]
class Member < ApplicationRecord
   include Elasticsearch::Model
   document_type 'member'
end

Member.document_type => "member"
```

**Comment by Chiether** [comment]
I understood background. May be I've confusion because branch[elastic:6.x].
Your example is match as I assumed. There is no problem. :)

Thanks @estolfo.

**Comment by estolfo** [comment]
Great, I'm glad this is resolved. Thanks!
