### ISSUE TITLE
keyword field is splited into two types

### ISSUE THREAD

**Issue by jinhucheung** [elastic/elasticsearch-rails#823]
Hi elastic,

Thanks for your AMAZING Project. 

I'm trying to define the following mappding.

```ruby
mappding do
   indexes  :lang_name,               type: :keyword
end
```

In prodution env, it defines the following lang_name field

```json
  "lang_name" : {
      "type" : "text",
       "fields" : {
           "keyword" : {
              "type" : "keyword",
               "ignore_above" : 256
            }
       }
   }
```

but In development env,  it defines the following

```json
  "lang_name" : {
      "type" : "keyword"
   }
```

How can I make sure that they are consistent?

Versions:

+ rails: 3.2.2

+ elasticsearch: 6.3.1

+ elasticsearch-model: 5.1.0

Thanks a lot

**Comment by estolfo** [comment]
Hi @jinhucheung did you just create the indexes or was the production index created before when the mapping was defined differently in your Ruby code? Are the versions of Elasticsearch the same in Production and Development?

**Comment by jinhucheung** [comment]
Hi @estolfo, 

thanks a lot for your reply

it is sad, the indexes has run on production, and elasticsearch is the same version in the development or production

but I did not find the above production mapping from git

Thanks

**Comment by estolfo** [comment]
@jinhucheung So have you found the reason for the difference?

**Comment by estolfo** [comment]
I'm going to close this issue. Please open a new one if you are still having trouble.
