### ISSUE TITLE
Example With Parent/Child Setup for ES 6

### ISSUE THREAD

**Issue by perkins2099** [elastic/elasticsearch-rails#849]
This may not be the right place for this but I'm struggling on putting together a Parent/Child (using the join field since the types were removed) relationship in the same index with two different mappings.  Could a comprehensive example be created to illustrate how to set it up using elasticsearch-rails?

Thank you

**Comment by estolfo** [comment]
Hi @perkins2099 
Sure, we can add an example. Please keep in mind though that using the join datatype with the `has_parent` query, or the `has_child` query adds significant overhead to query performance. That said, the join datatype can still be used. It is required to index the lineage of a parent in the same shard as a child so you must always route child documents using their parent id. If you persist parent and child documents in a single index, ensure that the routing values are taken into account when both saving and retrieving child documents.

In the meantime, before we are able to add an example, [this test](https://github.com/elastic/elasticsearch-rails/blob/e72e02ca3eefef1e6af673456ec28b90e0e5c873/elasticsearch-model/spec/elasticsearch/model/adapters/active_record/parent_child_spec.rb) that uses [this module](https://github.com/elastic/elasticsearch-rails/blob/e72e02ca3eefef1e6af673456ec28b90e0e5c873/elasticsearch-model/spec/support/app/parent_and_child_searchable.rb) might be useful to you.

**Comment by estolfo** [comment]
@perkins2099 Did the resources mentioned above help?

**Comment by perkins2099** [comment]
I've reviewed the document but its a bit cryptic for me.  Was hoping for a dead simple example. :)  I dont know if it would help someone else but I've decided to go another direction away from the parent join.  So perhaps we can close this issue?

**Comment by estolfo** [comment]
@perki Sorry the resources didn't help. 
I would encourage you to represent your objects without using the join data type and am glad to hear you've gone in another direction. We can close this issue but feel free to open a new one if you have further questions.

**Comment by chrisharrisonkiwi** [comment]
I for one would have liked this to have resolved in a "documentation updated with better/multiple examples" result rather than: "Requester went in another direction so closing".

@perkins2099 Can you give us any details on the direction you took with this? I'm desperately struggling to find a decent example of a parent/child like setup without using joins.
