### ISSUE TITLE
Can't generate rails task after installing es-rails

### ISSUE THREAD

**Issue by hiracky16** [elastic/elasticsearch-rails#851]
Hi.
I installed es-rails into my application running docker.
After installing, I executed the following command. However, I couldn't.

```
$ docker-compose run web rails g task elasticsearch
Starting research_app_db_1 ... done
The git source https://github.com/elastic/elasticsearch-rails.git is not yet checked out. Please run `bundleinstall` before trying to start your application
``` 

I tried `docker-compose run web bundle install` again but I can't do it yet.
Please tell me the way to resolve this problem.

**Comment by estolfo** [comment]
@hiracky16 What are you trying to accomplish with the command?

**Comment by hiracky16** [comment]
@estolfo Thank you reply Emily.
I hope to make a Rake task to index into ElasticSearch.
When I try to generate task, this problem is happened.

**Comment by estolfo** [comment]
@hiracky16 Are you trying to import your models as outlined [here](https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-rails#rake-tasks) ?

**Comment by hiracky16** [comment]
@estolfo 
Thank you for telling me the way to resolve this problem!
I can generate task 👍

**Comment by estolfo** [comment]
Great, I'm glad you've resolved it!
