### ISSUE TITLE
Elasticsearch::Persistence::Repository#index_exists? silently drops arguments

### ISSUE THREAD

**Issue by fnordfish** [elastic/elasticsearch-rails#852]
I was just upgrading and ran into an issues when trying to use `my_repository.index_exists?(index: "my_index_name")`

In https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/lib/elasticsearch/persistence/repository.rb#L213-L215

While I can still pass in an explicit `:index`, all arguments are ignored and the repositories index_name is used instead.

This is a bit surprising, I would expect the method to either use the passed in argument or raise an ArgumentError if passing an index name is not desired.

**Comment by estolfo** [comment]
Hi @fnordfish Thanks for reporting this! I've opened a pull request to fix it [here](https://github.com/elastic/elasticsearch-rails/pull/853)
Can you try it out in your testing environment and let me know if it resolves the issue for you? Thanks!

**Comment by estolfo** [comment]
I'm going to close this as a fix was merged. See above for pull request reference.
