### ISSUE TITLE
ActiveRecord migration example/help for 6.x gem

### ISSUE THREAD

**Issue by loren** [elastic/elasticsearch-rails#854]
I understand that the 6.x version of this gem has [deprecated the ActiveRecord pattern](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/README.md#the-activerecord-pattern). I have code that looks like [this example](https://github.com/elastic/elasticsearch-rails/commit/31510278e06d1c00d213f695640d9e4efdfaaab5) that I'm trying to migrate to the recent gem.

I'm looking for an example of what this code would look like to preserve the functionality while using the new gem. I've looked in the [examples directory](https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-model/examples), but I don't see anything that covers everything. And these examples assume that I'm using some sort of underlying DB to define a schema via ActiveRecord, but I'm not doing that.

I get the sense that I'm now supposed to include the `virtus` gem myself to handle attributes, but how would I migrate the `validates` functionality?

**Comment by estolfo** [comment]
Hi @loren Thanks for your question. I've published a [blog post](https://www.elastic.co/blog/activerecord-to-repository-changing-persistence-patterns-with-the-elasticsearch-rails-gem) on this subject and have migrated one of the example apps to use the Repository pattern. You will find links to it in the blog post but [here](https://github.com/elastic/rails-app-music) is the repo itself. Let me know if I can help further!

**Comment by loren** [comment]
Oh wow, I somehow totally missed that blog post! My apologies. I'll close this out.
