### ISSUE TITLE
[PERSISTENCE] no find_each or find_in_batches method for the Repository pattern

### ISSUE THREAD

**Issue by jogaco** [elastic/elasticsearch-rails#856]
I am migrating my app from the deprecated ActiveRecord pattern to the Repository pattern.

I could not find any equivalent to `find_each` in the Repository pattern.
The only thing I found is some code to do something similar in #693 

Am I missing anything?

**Comment by estolfo** [comment]
@jogaco What functionality would you want in a `find_each` method that is not supported via the `find` method on a repository?

**Comment by estolfo** [comment]
Closing because no response.
