### ISSUE TITLE
Document mapping type name can't start with '_', found: [_suggest]"}

### ISSUE THREAD

**Issue by armhold** [elastic/elasticsearch-rails#858]
Hi, thanks for creating this library!

I'm having trouble getting autocomplete/suggest to work, almost certainly user error on my part.

I'm following the example in [activerecord_mapping_completion.rb](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/examples/activerecord_mapping_completion.rb).  But the elasticsearch server (6.4.2) doesn't seem to like mappings with names starting with underscore:

```
Error:
BookTest#test_autocomplete:
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"invalid_type_name_exception","reason":"Document mapping type name can't start with '_', found: [_suggest]"}],"type":"invalid_type_name_exception","reason":"Document mapping type name can't start with '_', found: [_suggest]"},"status":400}
    app/models/book.rb:96:in `autocomplete'
    test/models/book_test.rb:26:in `block in <class:BookTest>'
```

My mapping definition looks like the following:

```
  mapping do
    indexes :name, type: 'text' do
      indexes :suggest, type: 'completion'
    end

    indexes :id, type: 'long'
    indexes :user_id, type: 'long'
    indexes :url, type: 'text'
  end
```
Which results in:
```
{
  "books-test" : {
    "mappings" : {
      "book" : {
        "properties" : {
          "created_at" : {
            "type" : "date"
          },
          "id" : {
            "type" : "long"
          },
          "name" : {
            "type" : "text",
            "fields" : {
              "suggest" : {
                "type" : "completion",
                "analyzer" : "simple",
                "preserve_separators" : true,
                "preserve_position_increments" : true,
                "max_input_length" : 50
              }
            }
          },
          "updated_at" : {
            "type" : "date"
          },
          "url" : {
            "type" : "text"
          },
          "user_id" : {
            "type" : "long"
          }
        }
      }
    }
  }
}
```

Any idea what I might be doing wrong?

**Comment by estolfo** [comment]
Hi @armhold Would you mind sharing the code that leads to the error? I.e. the code surrounding `test/models/book_test.rb:26` and the code in the method `BookTest#test_autocomplete`.
Thanks!

**Comment by armhold** [comment]
Hi @estolfo thanks for your help.

In an effort to eliminate errors on my part, I'm now running the [article example](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/examples/activerecord_mapping_completion.rb) directly (I had to re-tool my project a bit and add libs+gems for sqlite3 and 'ansi' that the example uses). My only change to that file is to pass in the url for elasticsearch like:

```
Article.__elasticsearch__.client = Elasticsearch::Client.new url: 'elasticsearch:9200', log: true
```

and I am still getting a similar error:

```
2018-11-07 13:47:46 +0000: POST http://elasticsearch:9200/articles/_suggest [status:400, request:0.011s, query:N/A]
2018-11-07 13:47:46 +0000: > {"articles":{"text":"foo","completion":{"field":"title.suggest"}}}
2018-11-07 13:47:46 +0000: < {"error":{"root_cause":[{"type":"invalid_type_name_exception","reason":"Document mapping type name can't start with '_', found: [_suggest]"}],"type":"invalid_type_name_exception","reason":"Document mapping type name can't start with '_', found: [_suggest]"},"status":400}
2018-11-07 13:47:46 +0000: [400] {"error":{"root_cause":[{"type":"invalid_type_name_exception","reason":"Document mapping type name can't start with '_', found: [_suggest]"}],"type":"invalid_type_name_exception","reason":"Document mapping type name can't start with '_', found: [_suggest]"},"status":400}
Traceback (most recent call last):
	5: from app/models/article.rb:53:in `<main>'
	4: from /usr/local/bundle/gems/elasticsearch-api-6.1.0/lib/elasticsearch/api/actions/suggest.rb:42:in `suggest'
	3: from /usr/local/bundle/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/client.rb:131:in `perform_request'
	2: from /usr/local/bundle/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
	1: from /usr/local/bundle/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:323:in `perform_request'
/usr/local/bundle/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:205:in `__raise_transport_error': [400] {"error":{"root_cause":[{"type":"invalid_type_name_exception","reason":"Document mapping type name can't start with '_', found: [_suggest]"}],"type":"invalid_type_name_exception","reason":"Document mapping type name can't start with '_', found: [_suggest]"},"status":400} (Elasticsearch::Transport::Transport::Errors::BadRequest)
```

At this point I tend to suspect a mismatch between the elasticsearch server (6.4.2) and the gems I am specifying. `bundle install` is showing me the following:

```
Using elasticsearch-api 6.1.0
Using elasticsearch-transport 6.1.0
Using elasticsearch 6.1.0
Using elasticsearch-model 6.0.0
Using elasticsearch-rails 6.0.0
```

Is this a compatible configuration (there are apparently no released 6.1.x gems for -model and -rails)?

If it's helpful, I can carve out my project into a minimal rails project, Gemfile, Dockerfile, etc.  Thanks again for your time on this.

**Comment by estolfo** [comment]
Hi @armhold 
As per this issue https://github.com/elastic/elasticsearch/pull/20305, the separate `_suggest` endpoint has been deprecated. I would recommend using `search` instead and sending the suggest criteria in the body. I will update the example you referenced to reflect this deprecation. Let me know if that makes sense.
Please see this documentation for how to construct the `search` query to retrieve suggestions: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html

**Comment by armhold** [comment]
Thank you @estolfo, I see what I need to do now.

Shouldn't the [suggest method](https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-api/lib/elasticsearch/api/actions/suggest.rb#L31) also be updated to reflect this deprecation? My initial problem was in calling that code, getting a similar error. Thank you.

**Comment by estolfo** [comment]
Hi @armhold 
I've added a deprecation tag to the documentation in this commit: https://github.com/elastic/elasticsearch-ruby/commit/34d4633e3513f383b227f64a5a0b0dc049308ddb
I will leave the method as-is, in case the gem is being used with an older version of elasticsearch.
If everything is sorted on your end, may I close this issue? Thanks!

**Comment by armhold** [comment]
Closing, thank you @estolfo !

**Comment by estolfo** [comment]
my pleasure @armhold !
