### ISSUE TITLE
Retrieving 'took' time results in extra queries and latency

### ISSUE THREAD

**Issue by mrmason** [elastic/elasticsearch-rails#859]
We recently upgraded a small service from elastic 2.3 to elastic 6.

Using the same code we've been using for a while resulted in a large increase in latency for the query ( not inside elastic, but from rendering the results ).

After some investigation the problem seems to be with the 'took' method on results... so we were using code like this:

```
r = __elasticsearch__.search(query)
return r.took
```
This image shows the latency spike:
![image](https://user-images.githubusercontent.com/93157/48187093-ff3eab80-e331-11e8-9908-20052770ea10.png)

This image shows the difference in queries ( it gets lower after we fixed the problem ):
![image](https://user-images.githubusercontent.com/93157/48187204-46c53780-e332-11e8-965d-4dcc3c5e3cc0.png)

After we changed the code to
```
r = __elasticsearch__.search(query)
return r.response.took
```

things returned to normal.

I couldn't find anything in the documentation to explain this change in behaviour but I may have missed it - is it intentional that an extra request would be made on `took` but not on `response.took` ?

**Comment by estolfo** [comment]
Hi @mrmason I have an idea as to why you would notice a performance decrease but I'd like to confirm which versions of the elasticsearch gems you've upgraded from. Can you tell me what version you were using before and what version you are using now?

In addition, was the code that showed a decrease in performance exactly what you've provided or have you simplified it for the issue? 
Thanks!

**Comment by mrmason** [comment]
Looking through the old code, we seemed to be using
```
gem 'elasticsearch-model', '~> 5.0.1'
gem 'elasticsearch-rails', '~> 5.0.1'
```
which paired up to an ES server running `2.4.0`.

We've upgraded to 
```
gem 'elasticsearch-model', '~> 6.0'
gem 'elasticsearch-rails', '~> 6.0'
```

which has resulted in

```
    elasticsearch (6.1.0)
      elasticsearch-api (= 6.1.0)
      elasticsearch-transport (= 6.1.0)
    elasticsearch-api (6.1.0)
      multi_json
    elasticsearch-model (6.0.0)
      activesupport (> 3)
      elasticsearch (> 1)
      hashie
    elasticsearch-rails (6.0.0)
    elasticsearch-transport (6.1.0)
```

I have simplified the code but not by much, the real code goes through the results and creates a new array so something more like

```
r = __elasticsearch__.search(query)
results = []
r.results.each do |res|
 results << { res.name }
end

return {
  "query": query,
  "took": r.took,
  "results": results
}
```

We debugged everything and the slowdown and extra query(ies?) were caused by `r.took`

**Comment by estolfo** [comment]
Hi @mrmason Thank you for that information. I believe the reason you are seeing a difference is because of a change in 6.0 where the `raw_response` of the request was cached in addition to the wrapped response. In the 6.0 release, some methods on the response object erroneously weren't use the cached response.
There is a change in master and the 6.x branch to fix this. Would you mind trying the 6.x branch of the gem in your testing environment and letting me know if the issue is resolved? Thanks!

**Comment by estolfo** [comment]
Closing because of lack of response.
