### ISSUE TITLE
Document didnt updated into elasticsearch when we run `index.save(doc)`

### ISSUE THREAD

**Issue by OpakAlex** [elastic/elasticsearch-rails#863]
My issue, that ES return old version for document, which was updated via rails.
My quersion: Can i pass params to `https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/lib/elasticsearch/persistence/repository/store.rb#L37`
params like: `refresh=wait_for` ?

**Comment by estolfo** [comment]
@OpakAlex Yes, you can pass options for the request like this:
```ruby
repository.save({ a: 1 }, refresh: 'wait_for')
```

Let me know if that works for you.

**Comment by OpakAlex** [comment]
ok, thanks, i will try ;)

**Comment by estolfo** [comment]
@OpakAlex Did you get a chance to try that out?

**Comment by OpakAlex** [comment]
thanks @estolfo .Looks like works. I will monitor it. Thanks
