### ISSUE TITLE
How to use update_by_query elasticsearch API

### ISSUE THREAD

**Issue by RajarshiWebonise** [elastic/elasticsearch-rails#867]
I have gone through the docs but couldn't find a method that queries via `update_by_query`.
Is this API supported in this gem?

**Comment by shunta27** [comment]
I also want to use,
Feeling that it has not been implemented yet?

**Comment by estolfo** [comment]
Hi @RajarshiWebonise and @shunta27 are you using `elasticsearch-model`? If so, you can access the client to Elasticsearch via the `__elasticsearch__` method and call `update_by_query` on it. See [here](https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-model#the-__elasticsearch__-proxy) for more info. Let me know if that helps, thanks!

**Comment by estolfo** [comment]
Closing because no response.

**Comment by shunta27** [comment]
@ESamir thanks.
