### ISSUE TITLE
as_indexed_json and polymorphic associations

### ISSUE THREAD

**Issue by webattitude** [elastic/elasticsearch-rails#870]
How to make _include_ optional in #as_indexed_json dsl ?
I have to index a Selection model that has_many SelectionItems. These items have one polymorphic Resource (ie some Resources may not have artists association...).

Here is my #as_indexed_json definition : 
```
    def as_indexed_json(options={})
        as_json {
              methods: [:moods, :genres, :opened, :shared, :rating, :likes_count, :favorites_count],
              include: {
                user: {
                  only: [:id, :name, :email],
                  include: { station: {only: [:name, :id], methods: [:dpt]} }
                },
                selection_items: {
                  include: {
                    resource: {
                      include: {
                        artists: {
                          only: [:id, :name]
                        },
                        random_tracks: {
                          except: [:available_territories, :high_bitrate, :low_bitrate],
                          methods: [:moods, :moods_with_score],
                          include: {
                            album: { include: { artists: {only: [:id, :name]} }},
                            artists: {only: [:id, :name]},
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
    end
```

When SelectionItem has uncommon resource (ie with no artists association), it raises a no method error.

**Comment by estolfo** [comment]
@webattitude Do you still have this question? If so, have you tried putting the logic in the definition of how a `SelectionItem` is converted to `json`?

**Comment by webattitude** [comment]
> @webattitude Do you still have this question? If so, have you tried putting the logic in the definition of how a `SelectionItem` is converted to `json`?

Ok thx, I'll try this.

**Comment by webattitude** [comment]
OK thx, I eventually managed to serialize as expected...
