### ISSUE TITLE
Kaminari pagination: no implicit conversion of Integer into Hash

### ISSUE THREAD

**Issue by skukx** [elastic/elasticsearch-rails#876]
Gem: `elasticsearch-model` version `6.0`
Cluster: Elasticsearch 7.0

The kaminari pagination is causing an error when calling `next_page`

```ruby
resp = Model.__elasticsearch__.search query: { match_all: {} }
resp.page(1).per(2).next_page
#=> TypeError: no implicit conversion of Integer into Hash

resp.total_count
#=> #<Elasticsearch::Model::HashWrapper relation="gte" value=10000> 
```

Trace:
```
vendor/bundle/ruby/2.4.0/gems/kaminari-core-1.1.1/lib/kaminari/models/page_scope_methods.rb:36:in `<'
vendor/bundle/ruby/2.4.0/gems/kaminari-core-1.1.1/lib/kaminari/models/page_scope_methods.rb:36:in `total_pages'
vendor/bundle/ruby/2.4.0/gems/kaminari-core-1.1.1/lib/kaminari/models/page_scope_methods.rb:77:in `last_page?'
vendor/bundle/ruby/2.4.0/gems/kaminari-core-1.1.1/lib/kaminari/models/page_scope_methods.rb:62:in `next_page'
```

This is probably due to the breaking change in `hits`. See: https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#_literal_hits_total_literal_is_now_an_object_in_the_search_response

**Comment by estolfo** [comment]
Hi @skukx, thanks for opening this issue. We are currently working on 7.0 support and we'll be sure to fix this issue. I'll have an update soon, thanks for your patience!

**Comment by skukx** [comment]
Thanks @estolfo! I doubt many other people are having this issue but just in case anyone is, you can do a quick patch like below.

```ruby
Elasticsearch::Model::Response::Pagination::Kaminari.module_eval do
  def total_count
    results.total.try(:value) || results.total
  end
end
```

**Comment by skukx** [comment]
Linking the Pull Request for 7.0 support:
https://github.com/elastic/elasticsearch-rails/pull/875

**Comment by estolfo** [comment]
Hi @skukx I believe I've already handled this in the following commit https://github.com/elastic/elasticsearch-rails/commit/9c40f630e1b549f0b7889fe33dcd826b485af6fc
Would you mind trying master in your testing environment to see if it does indeed fix the issue? Thanks

**Comment by skukx** [comment]
@estolfo Yes! that does the trick. Thank you for pointing that out! Would you like me to close this issue?

**Comment by estolfo** [comment]
@skukx Thanks for testing the change and confirming it resolves the issue. A pre version of the gem will be available soon. I'll close the issue, thanks again!
