### ISSUE TITLE
Missing note about precondition for the command to generate example Rails application

### ISSUE THREAD

**Issue by yamashun** [elastic/elasticsearch-rails#878]
## Steps to reproduce
1. prepare an environment without running Elasticsearch at http://localhost:9200.
2. proceed as described in the "Usage" section of the README.
3.  try to start the sample application with the following command.

```
rails new searchapp --skip --skip-bundle --template https://raw.github.com/elasticsearch/elasticsearch-rails/master/elasticsearch-rails/lib/rails/templates/01-basic.rb
```

## Actual result
The following error occurs.
```
ERROR    Cannot connect to Elasticsearch on <http://localhost:9200>

                The application requires an Elasticsearch cluster running, but no cluster has been found on <http://localhost:9200>.
                The easiest way of launching Elasticsearch is by running it with Docker (https://www.docker.com/get-docker):

                docker run --name elasticsearch-rails-searchapp --publish 9200:9200 --env "discovery.type=single-node" --env "cluster.name=elasticsearch-rails" --env "cluster.routing.allocation.disk.threshold_enabled=false" --rm docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.0
```

## Expected result
Successfully proceeded with no error.

## Proposal
I propose that note in the README ahead of time that Elasticsearch needs to be running on http://localhost:9200.
I'm trying to send a pull request to do that.

**Comment by estolfo** [comment]
@yamashun Have you opened a pull request for this, as you mentioned you might?

**Comment by estolfo** [comment]
Closing because no response.
