### ISSUE TITLE
Scroll API confusion

### ISSUE THREAD

**Issue by philsmy** [elastic/elasticsearch-rails#882]
It seems that the calls to the scroll API exist OUTSIDE the regular use of elasticsearch-model.

I would have thought that I could call something like

```MyModel.search scroll: '1m', ...```

but instead it seems I have to create a new client and call the index directly. That seems to be a dangerous duplication of code, as it looks like I can't even use the client definition that I make in my initializer.

Am I misunderstanding? Or do we really need to do something like this in our model:

```client = Elasticssearch::Client.new    
result = client.search index: 'model_index',
scroll: '1m', body: { query: { match: { tenant_id: 3196 } }, sort: '_id' }
```

Should we create a method on the model for this?

**Comment by estolfo** [comment]
@philsmy Are you getting an error when you try to do the following:
`MyModel.search scroll: '1m', ...` ?
You can always access the client that the model uses by calling `__elasticsearch__` on the model. So you can call the search method directly with the `scroll` option if you want on the client returned from `MyModel.__elasticsearch__`
Let me know if that makes sense.

**Comment by estolfo** [comment]
Closing because no response.
