### ISSUE TITLE
Pagination via will_paginate not working

### ISSUE THREAD

**Issue by bholzer** [elastic/elasticsearch-rails#884]
I am trying to call `.page(2)` on a response and getting strange behavior.

```ruby
res = Profile.search(...)
=> #<Elasticsearch::Model::Response::Response:0x00007ff42ec0ce78
 @klass=[PROXY] Profile ...,
 @search=
  #<Elasticsearch::Model::Searching::SearchRequest:0x00007ff42ec31c50
   @definition=
    {:index=>"profiles",
     :type=>"_doc",
     :body=>
      {:query=>{:bool=>{:should=>[{:multi_match=>{:query=>"hip", :fields=>["user.name", :plan_name]}}], :must=>[{:match=>{:"user.name"=>"Test"}}]}},
       :size=>15,
       :from=>0}},
   @klass=[PROXY] Profile ...,
   @options={}>>

res.page(2)

=> #<Elasticsearch::Model::Response::Response:0x00007ff42ec0ce78
 @klass=[PROXY] Profile ...,
 @search=
  #<Elasticsearch::Model::Searching::SearchRequest:0x00007ff42ec31c50
   @definition=
    {:index=>"profiles",
     :type=>"_doc",
     :body=>
      {:query=>{:bool=>{:should=>[{:multi_match=>{:query=>"hip", :fields=>["user.name", :plan_name]}}], :must=>[{:match=>{:"user.name"=>"Test"}}]}},
       :size=>15,
       :from=>0},
      :size=>30,
      :from=>30},
   @klass=[PROXY] Profile ...,
   @options={}>>
=> 
```

It appears the `size` and `from` are being set on the wrapper `@definition` object, not the query body. Since they are being set in the wrong place, I am receiving the first page every time.

I noticed the documentation about load order, and I definitely have will_paginate above all ES gems.

**Comment by estolfo** [comment]
@bholzer Is this still an issue? If so, would you mind showing an example so I can reproduce this? Thanks

**Comment by estolfo** [comment]
Closing because no response.

**Comment by bholzer** [comment]
Sorry @estolfo, was on vacation. How would you like this presented, should I create a small app showing this behavior?

**Comment by estolfo** [comment]
@bholzer Would you mind showing a model definition, then some sample code inserting documents and then fetching documents showing the first page is always returned? Thanks

**Comment by kevinjalbert** [comment]
In using `elasticsearch-rails` for pagination, I've hit this issue as well with the `will_paginate` gem for pagination. I did discover some interesting behaviour though that I wanted to share.

First, I'm using `Feature` which has the `include Elasticsearch::Model` in it. For this demonstrate I'm also going to use the _raw_ `__elasticsearch__` for searching:

```
> Feature.__elasticsearch__.search('*', size: 10).page(1).records.map(&:id)
=> [3, 7, 8, 9, 12, 14, 16, 17, 19, 20]

> Feature.__elasticsearch__.search('*', size: 10).page(2).records.map(&:id)
=> [22, 23, 26, 27, 30, 31, 34, 35, 37, 38]
```

The above looks good! We're getting different records with different pages specified.

Now, lets look at how I _originally_ intended to use the pagination:

```
> results = Feature.__elasticsearch__.search('*', size: 10)
=> #<Elasticsearch::Model::Response::Response:0x00007fdca3e10190
 @klass=[PROXY] Feature(...),
 @search=
  #<Elasticsearch::Model::Searching::SearchRequest:0x00007fdca3e10320
   @definition={:index=>"features", :type=>"_doc", :q=>"*", :size=>10},
   @klass=[PROXY] Feature(...),
   @options={:size=>10}>>

> results.page(1).records.map(&:id)
=> [3, 7, 8, 9, 12, 14, 16, 17, 19, 20]

> results.page(2).records.map(&:id)
=> [3, 7, 8, 9, 12, 14, 16, 17, 19, 20]
```

This is interesting behaviour 🤔, and matches what @bholzer had demonstrated in this issue. It seems that **additional paginating off of a search response doesn't work as expected and that the results does not change after the first `page`**.

@bholzer @estolfo Is this something you could confirm/reproduce on your end?
