### ISSUE TITLE
High-level API for msearch

### ISSUE THREAD

**Issue by liamwhite** [elastic/elasticsearch-rails#885]
I currently [maintain a gem](https://github.com/liamwhite/model-msearch/blob/master/lib/model-msearch.rb) that monkey-patches the `Elasticsearch::Model` module to add a method to perform an `_msearch` request to Elasticsearch.

It can be used like this:
```rb
  @image_search, @top_scoring_search = Elasticsearch::Model.msearch! [
    Image.search(filter: { term: { tags: 'some tag' } }, sort: { created_at: :desc }),
    Image.search(filter: { range: { created_at: { gte: 'now-3d' } } }, sort: { score: :desc })
  ]
  @images = @image_search.records
  @top_scoring = @top_scoring_search.records
```

Since it doesn't appear that this functionality has been added in any form to `elasticsearch-model` since I first wrote it 3 years ago, I would like to request here that this, or functionally similar code, be added to elasticsearch-model.

---

In case it's relevant, I have already signed the Elastic community CLA. If you need anything else from me, let me know.

**Comment by shlima** [comment]
Any updates?

**Comment by picandocodigo** [comment]
Hi @liamwhite, this is great. If you want to open a Pull Request with this functionality, I'd be happy to review it. We do have some things on the roadmap for `msearch` and other functions, but it'll also be cool if you open a Pull Request with this code :+1:
