### ISSUE TITLE
How to create a mapping with join type?

### ISSUE THREAD

**Issue by kaibadash** [elastic/elasticsearch-rails#908]
I'd like to use [Join datatype](https://www.elastic.co/guide/en/elasticsearch/reference/current/parent-join.html).

I tried like as below.

```ruby
settings index: {number_of_shards: 1, max_result_window: 10000000, } do
  mappings dynamic: 'false' do
    indexes :my_join_field, type: "join" do
      indexes :relation, { "question" => "answer" }
    end
```

I got error.

```json
{"type":"mapper_parsing_exception","reason":"Mapping definition for [my_join_field] has unsupported parameters:  [fields : {relation={question=answer, type=text}}]"}}
```

How can I resolve that?

**Comment by runephilosof** [comment]
You can see an example of how it can be done in https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/spec/support/app/parent_and_child_searchable.rb and https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/spec/elasticsearch/model/adapters/active_record/parent_child_spec.rb

**Comment by kaibadash** [comment]
Thank you!
