### ISSUE TITLE
Broken link in the README

### ISSUE THREAD

**Issue by Duuun** [elastic/elasticsearch-rails#925]
Hello.Thank you so much for all your help.

The link to the following image seems to be broken in the README, can you please check it?

![スクリーンショット 2020-03-22 224029](https://user-images.githubusercontent.com/30006245/77251073-87a3bf00-6c8f-11ea-9b01-8d509075d22f.png)

**Comment by picandocodigo** [comment]
Thanks for reporting this @Duuun, will fix asap!
