### ISSUE TITLE
Elasticsearch::Transport::Transport::Errors::BadRequest. where i need to set type??

### ISSUE THREAD

**Issue by ronakabhattrz** [elastic/elasticsearch-rails#933]
Elasticsearch::Transport::Transport::Errors::BadRequest ([400] {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: type is missing

I am using 

> gem 'elasticsearch-model', github: 'elastic/elasticsearch-rails', branch: 'master'
> gem 'elasticsearch-rails', github: 'elastic/elasticsearch-rails', branch: 'master'

**VERSION**

```
elasticsearch-model (7.0.0)
      activesupport (> 3)
      elasticsearch (> 1)
      hashie
    elasticsearch-rails (7.0.0)
```

**Comment by picandocodigo** [comment]
Hi @ronakabhattrz, thanks for reporting this issue. What code are you running when you see this error?

**Comment by ronakabhattrz** [comment]
I got this error when i set index threw rails console

**Comment by key88sf** [comment]
@picandocodigo Related issue -- looks like the latest Faraday gem has renamed errors. So
`host_unreachable_exceptions` may need to use `Faraday:: ConnectionFailed` instead of `Faraday::Error:: ConnectionFailed`
