### ISSUE TITLE
2nd example template

### ISSUE THREAD

**Issue by engineer-plus-plus** [elastic/elasticsearch-rails#940]
When I execute the command to create the second rails example template,  I get following error
```
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Rejecting mapping update to [articles] as the final mapping would have more than 1 type: [_doc, properties]"}],"type":"illegal_argument_exception","reason":"Rejecting mapping update to [articles] as the final mapping would have more than 1 type: [_doc, properties]"},"status":400}
```

I'm using ES 6.4, ruby 2.6.5p114 ,Rails 6.0.3, macos 10.14

**Comment by picandocodigo** [comment]
Looking into this...

**Comment by engineer-plus-plus** [comment]
I can run all 3 templates now.  I'm not sure if something changed on your end or mine.  But this issue can be closed.

**Comment by picandocodigo** [comment]
@engineer-plus-plus thanks for reporting back! I think this potentially had to do with using an older Elasticsearch version with the latest client? But once the first template was working, the rest should work too. Thanks again!
