### ISSUE TITLE
Template Issues

### ISSUE THREAD

**Issue by engineer-plus-plus** [elastic/elasticsearch-rails#942]
I'm not sure if you changes something in the last 2 days.  But I can't generate any of the 3 templates due to various errors.  The all blow up.  I'm pretty sure I didn't do anything to my env to change from them all ok to this.  I can go over the errors, if you wawnt.  But. here, I'd like to make a few general points about the templates.

1. They are super useful for learning -- once the apps are generated.  Thanks for having and supporting them.
2. They are really fickle.  They build not reliably
3. The fact that in order to build the third one, the two previous have to be built makes it even more wonky, without adding any educational value

Consequently,

4. why not just create git repos for these example apps?  I think it would make it much easier for you to maintain too.  What do you think?

**Comment by picandocodigo** [comment]
@engineer-plus-plus There weren't any changes recently that could affect the templates. I just double checked and ran them from scratch locally and they are working ok for me, but let me know which errors you encountered if possible.

I do think we can improve the docs a bit to specify having Elasticserch and Redis running for the third template and other details. What you mention is a very good point, we've been having conversations about improving docs and examples, so I'll run this with the team and get back to you on how we go on with this. Thank you very much!
