### ISSUE TITLE
warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

### ISSUE THREAD

**Issue by bk-az** [elastic/elasticsearch-rails#948]
When you call the import method:

`../.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/elasticsearch-model-7.1.0/lib/elasticsearch/model/adapters/active_record.rb:105:`
warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

`../.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/querying.rb:21:`
warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

`../.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/relation/batches.rb:126:`
warning: The called method `find_in_batches' is defined here

Gemfile:
`rails (6.0.3.2)`
`elasticsearch-model (7.1.0)`

**Comment by picandocodigo** [comment]
Hi @bk-az, this was fixed on release `7.1.1` of the gem. If you update from `7.1.0`, the warning should go away.

Let me know if you have any further issues,
Thanks!

**Comment by bk-az** [comment]
Verified, thanks.
