### ISSUE TITLE
Ruby 2.7 deprecation in 6.x version

### ISSUE THREAD

**Issue by edariedl** [elastic/elasticsearch-rails#951]
Hey, would it be possible to fix ruby 2.7 deprecation also in 6.x version of the gem?

https://github.com/elastic/elasticsearch-rails/blob/6.x/elasticsearch-model/lib/elasticsearch/model/adapters/active_record.rb#L88

Line should look like this.

```ruby
scope.find_in_batches(**options) do |batch|
```

It is already fixed in 7.x version, unfortunately not in 6.x.

Thanks!

**Comment by picandocodigo** [comment]
Hi @edariedl,
Thanks for reporting this. I just published version 6.1.1 which includes this fix!
Check it out and let me know if there's any other issues.

Cheers!

**Comment by edariedl** [comment]
Awesome! Thanks
