### ISSUE TITLE
Client generation bad uri

### ISSUE THREAD

**Issue by antarr** [elastic/elasticsearch-rails#965]
I'm trying to start the client in production but it is generating a URI with the port on it twice.

***config/initializer/elasticsearch.rb***
```ruby
CLOUD_ID = ENV['ELASTIC_CLOUD_ID']
USERNAME = ENV['ELASTIC_USERNAME']
PASSWORD = ENV['ELASTIC_PASSWORD']
Elasticsearch::Client.new(cloud_id: CLOUD_ID,  user: USERNAME,  password:  PASSWORD) if Rails.env.production?
```

***error in when deploying***
```bash
rake stdout: rake aborted!
URI::InvalidURIError: bad URI(is not URI?): "https://myusername:mypassword@dc6160...2df11690baea.eastus2.azure.elastic-cloud.com:9243:9243"
```

**Comment by picandocodigo** [comment]
Hi @antarr, thanks for reporting this. Which version of the client are you using?

**Comment by antarr** [comment]
> Hi @antarr, thanks for reporting this. Which version of the client are you using?

7..1.1

**Comment by picandocodigo** [comment]
Ah, sorry got the repos mixed up. What's triggering the error is `elasticsearch-ruby`. I tried to reproduce the error with the latest versions of the client and it seems to be working fine. Can you check your Gemfile.lock file and let me know which version of `elasticsearch-transport` is being used please? Thanks!

**Comment by antarr** [comment]
@picandocodigo 

```ruby
elastic-apm (3.10.1)
      concurrent-ruby (~> 1.0)
      http (>= 3.0)
    elasticsearch (7.9.0)
      elasticsearch-api (= 7.9.0)
      elasticsearch-transport (= 7.9.0)
    elasticsearch-api (7.9.0)
      multi_json
    elasticsearch-model (7.1.1)
      activesupport (> 3)
      elasticsearch (> 1)
      hashie
    elasticsearch-rails (7.1.1)
    elasticsearch-transport (7.9.0)
      faraday (~> 1)
      multi_json
```

**Comment by picandocodigo** [comment]
@antarr Since this issue is on `elasticsearch-transport`, I'm following up on that issue [here](https://github.com/elastic/elasticsearch-ruby/issues/1081). I'm already working on a fix for it :+1:
