### ISSUE TITLE
Error while generating the simple app in README

### ISSUE THREAD

**Issue by kerolloz** [elastic/elasticsearch-rails#984]
running the following command gives an error 

```bash
rails new searchapp --skip --skip-bundle --template https://raw.github.com/elasticsearch/elasticsearch-rails/master/elasticsearch-rails/lib/rails/templates/01-basic.rb
```

![image](https://user-images.githubusercontent.com/36763164/109647089-995d3a00-7b61-11eb-9c14-4ec010d1f363.png)

```
Bundler could not find compatible versions for gem "elasticsearch":
  In Gemfile:
    elasticsearch

    elasticsearch-model was resolved to 7.1.0, which depends on
      elasticsearch (~> 7)
```

----

```bash
$ rails --version
Rails 6.0.3.5
```

**Comment by akiko-pusu** [comment]
Hi, I saw the same situation and just tried to create the pull request.
(I withdrew it for some reason but I think this was effective. Hope this would be any help.)

**Comment by picandocodigo** [comment]
@akiko-pusu thank you very much for the the fix! I couldn't merge your PR since it was closed, but I've added the fix now.
