### ISSUE TITLE
Result order is not preserved with records adapters (Mongoid in my case).

### ISSUE THREAD

**Issue by dwkoogt** [elastic/elasticsearch-rails#99]
Hi.
Let say i have two records and I'm running a query such that the order of the resulting records are reversed. I'm running a simple function score query and I can see that record #2 has higher score than record #1 (in response.response). But when I get the records, the result order is back to natural order. I tried to show the records' scores with each_with_hit function and saw that the scores are switched. I looked into the code and saw two problems. In the adapter code, it's using $in query for array of ids. I believe mongo returns results in natural order unless sort is defined. It will not return the results with the ids' array order. Then in the records class, this db result ( #1, #2) is zipped with elasticsearch result (#2, #1). Hence the scores get switched.

fyi
https://jira.mongodb.org/browse/SERVER-7528

**Comment by Naomarik** [comment]
This just tripped me up a bit until I found this. Mongoid does not seem to care about the order of the IDs passed into its `in` query. 

Might want to update the documentation here: https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-model#search-results-as-database-records to be explicit that you should call to_a to preserve the sort order for mongoid.
